### ISSUE TITLE
Add possibility to select multiple data points

### ISSUE THREAD

**Issue by gvozditskiy** [imaNNeoFighT/fl_chart#10]

**Comment by imaNNeoFighT** [comment]
May I ask you explain more about it?

**Comment by gvozditskiy** [comment]
@imaNNeoFighT if i touch some point of the chart, it should highlight somehow. And it will be nice if it will be possible to make multiple selections on the same chart.

![selection 2019-06-07 09_26_29](https://user-images.githubusercontent.com/16043598/59085158-5e838f00-8906-11e9-8cea-e476bf50bf04.gif)

**Comment by imaNNeoFighT** [comment]
currently, we haven't any interaction on the Chart,
and Interactivity is the first goal on the [RoadMap](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/roadmap.md), 
we can't have this directly, then firstly we should implement simple interaction, then you can raise your issue again.
