### ISSUE TITLE
Flutter 3.0

### ISSUE THREAD

**Issue by Sesa1988** [imaNNeoFighT/fl_chart#1003]
Hi,

looks like the flutter API changed for null safety on WidgetBindings

`/C:/devtools/flutter/.pub-cache/hosted/pub.dartlang.org/fl_chart-0.36.4/lib/src/chart/pie_chart/pie_chart.dart(38,20): warning GBC99161D: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null. [C:\Solutions\Flutter\cryptowulf\build\windows\flutter\flutter_assemble.vcxproj]`

**Comment by Faiizii** [comment]
This warning is already resolved and will be available in the next release version of lib.

**Comment by imaNNeoFighT** [comment]
Yes. It has just landed in the stable branch.
Check it out in [0.50.3](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.50.3)
