### ISSUE TITLE
App crashing: Method 'addPostFrameCallback' can not be called on 'WidgetsBinding?' 

### ISSUE THREAD

**Issue by iyar-avital** [imaNNeoFighT/fl_chart#1013]
![image](https://user-images.githubusercontent.com/57311417/168528468-8495f413-768c-46c6-9568-47c3f820ba37.png)

../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/fl_chart-0.50.5/lib/src/chart/pie_chart/pie_chart.dart:42:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {
                            ^^^^^^^^^^^^^^^^^^^^

I am using flutter 2.8.1 and can not upgrade anytime soon due to company policy.

There is a solution?

**Comment by proczak1** [comment]
Same issue for me

**Comment by agoldm** [comment]
Same here

**Comment by agoldm** [comment]
@imaNNeoFighT @iyar-avital @proczak1

**Comment by imujtaba8488** [comment]
Fixed and sent a PR to the author -- seems like a backward compatibility issue.

**Comment by iyar-avital** [comment]
> Fixed and filed a PR -- seems like a Flutter framework backward compatibility issue.

Thanks a lot

**Comment by imaNNeoFighT** [comment]
Guys you need to upgrade your Flutter version to 3

**Comment by imaNNeoFighT** [comment]
If you can't upgrade your Flutter, then you should use our previous release.
Does it make sense?

**Comment by iyar-avital** [comment]
> If you can't upgrade your Flutter, then you should use our previous release. Does it make sense?

I used version 0.50.1 for two weeks and everything worked. Two days ago the error appeared. 
I **have not** updated the version, as I can't update flutter to version 3.

**Comment by imaNNeoFighT** [comment]
Fixed in [0.50.6](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.50.6) Please check it out.
