### ISSUE TITLE
Reduce time process of getTitlesWidget 

### ISSUE THREAD

**Issue by JosueGauthier** [imaNNeoFighT/fl_chart#1015]
Hello to all, 

I'm starting to use your package to plot a yearly sales graph for my school association via a LineChart, 

For the bottom X axis I want to place only some points along the axis using: getTitlesWidget except that the process is very long because it compares each value to my map. 

Is there a way to reduce this computation time? 

I can't find anything on internet. 
Thank you ! 

```
for (var i = 0; i < linspace.length; i++) {
int lin = linspace[i].toInt();
DateTime date = DateTime.fromMillisecondsSinceEpoch(lin * 100000);
var format = DateFormat('dd-MM');
var dateString = format.format(date);
datetimeMap[linspace[i]] = dateString;
}
```

```
Widget bottomTitleWidgets(double value, TitleMeta meta) {
  const style = TextStyle(
    color: Color(0xff68737d),
    fontWeight: FontWeight.bold,
    fontSize: 16,
  );

  Widget text = Text('', style: style);

  if (datetimeMap.containsKey(value)) {
    text = Text(datetimeMap[value], style: style);
  }

  return Padding(child: text, padding: const EdgeInsets.only(top: 8.0));
}
```

**Comment by imaNNeoFighT** [comment]
Checking the existence of a value on a Map is O(1).
So there's nothing to be worried about. What is the problem with that?
