### ISSUE TITLE
New version 0.50.5 on Flutter 2.10.x version error

### ISSUE THREAD

**Issue by josercc** [imaNNeoFighT/fl_chart#1016]
warning: Flutter archive not built in Release mode. Ensure FLUTTER_BUILD_MODE is set to release or run "flutter build ios --release", then re-run Archive from Xcode.../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/fl_chart-0.50.5/lib/src/chart/pie_chart/pie_chart.dart:42:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
     - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    Try calling using ?. instead.
        WidgetsBinding.instance.addPostFrameCallback((_) {
                                ^^^^^^^^^^^^^^^^^^^^
    Failed to package /Users/jenkins/.jenkins/workspace/ordering_ios.

**Comment by josercc** [comment]
test 0.50.1 can build ok

**Comment by imaNNeoFighT** [comment]
Fixed in [0.50.6](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.50.6) Please check it out.

**Comment by josercc** [comment]
@imaNNeoFighT Yes, version 0.50.6 has fixed the error report. Thank you for releasing the new version in time
