### ISSUE TITLE
LineChart with ListView

### ISSUE THREAD

**Issue by TheHypnoo** [imaNNeoFighT/fl_chart#1019]
Hi all, I am trying to add a LineChart in a ListView so that it paints more than 1. But I do not get it in any way, I do not know if it is not possible or something.

Since it gives me error of sizes....

Could someone give me an example if it is possible?

Flutter version 3.0.0
FlChart version latest

**Comment by AkshaySiddannavar** [comment]
Could you please post the important part of error you're facing so that we can understand exactly what issue it is?

**Comment by TheHypnoo** [comment]
@AkshaySiddannavar In this case I realized that the problem is that there was no way to use a Flexible or Expanded, but adding a fixed size. Is there any way to use it with Flexible/Expanded? 

https://pastebin.com/zTTJ8fZt

**Comment by AkshaySiddannavar** [comment]
Not sure about that, I actually thought your error might be something like `'package:flutter/src/rendering/box.dart': Failed assertion: line 1982 pos 12: 'hasSize'`. 
For that I found a SOF link : https://stackoverflow.com/questions/71517122/flutterlistview-hassize?noredirect=1&lq=1 
Thought maybe this could help you.
