### ISSUE TITLE
Line Chart out of Bound for the proper value

### ISSUE THREAD

**Issue by IMHitesh** [imaNNeoFighT/fl_chart#1024]
![Simulator Screen Shot - iPhone 12 Pro - 2022-05-22 at 23 42 17](https://user-images.githubusercontent.com/33254089/169709662-22814d3c-dd23-4015-8cde-e7fd64121675.png)

Generate spot using the below method:

```
List<FlSpot> genrateRandomSpots(int maxValue, int numberOfRecord) {
    List<FlSpot> arrSpots = [];
    for (var index = 0; index < numberOfRecord + 1; index++) {
      final randomNumber = Random().nextDouble() * maxValue;
      print(randomNumber);
      arrSpots.add(FlSpot(index.toDouble(), randomNumber));
    }
    return arrSpots;
  }
```

Happen with git source code.

Please help me

**Comment by RobinJespersen** [comment]
did u try to use FlClipData.all() ?
u can also set the LineChartBarData preventCurveOverShooting to true

**Comment by IMHitesh** [comment]
Yes, i have fixed the issue using this `preventCurveOverShooting`.
