### ISSUE TITLE
Bar Chart - is it possible to have minus values

### ISSUE THREAD

**Issue by atreeon** [imaNNeoFighT/fl_chart#103]
I'm looking to show minus values, is this type of chart possible?

![Screenshot 2019-11-10 at 16 57 53](https://user-images.githubusercontent.com/4139336/68547626-91f9a680-03db-11ea-960d-acfb4da272ff.png)

**Comment by imaNNeoFighT** [comment]
Hi, currently we do not support the negative values.
Let this issue open, and if it takes some thumbs up by the people,  I will resolve it in a high priority way.

**Comment by atreeon** [comment]
ok, great thank you.  I wondered whether I could kind of do a hack with a stacked chart

**Comment by imaNNeoFighT** [comment]
Also, you can use normal BarChart and shift your y variables and show titles with '-' to achieve that.
Stay tuned ;)

**Comment by atreeon** [comment]
ok, I'm a bit lost by that tbh!  If you can write another couple of lines really quickly I might be able to figure it out (otherwise I will be patient :-)

I've tried syncfusion and the google charts but can't achieve what I want but maybe with this it might be possible.  Thank you

**Comment by imaNNeoFighT** [comment]
Apologize, there is no way at the moment, but I will implement it ASAP.
Stay tuned!

**Comment by tasaquino** [comment]
I opened an issue with the same purpose before  [Issue](https://github.com/imaNNeoFighT/fl_chart/issues/98) . I could add negative values and bars. But is not possible to control the touch on them. For now I am trying to create a custom implementation to achieve that.

**Comment by imaNNeoFighT** [comment]
I appreciate your PRs,
clone the source code and try to add this feature,
It helps me a lot.
Thanks!

**Comment by imaNNeoFighT** [comment]
Implemented support for negative values for the BarChart, in [0.9.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.9.0)
Check it out:

##### Sample 5 ([Source Code](/example/lib/bar_chart/samples/bar_chart_sample5.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_5.png" width="300" >

**Comment by jlubeck** [comment]
Awesome! Minor note, clicking on that Source Code link returns a 404 error

**Comment by imaNNeoFighT** [comment]
You're welcome,
Link has just been fixed,
thank you!
