### ISSUE TITLE
Bar chart - is it possible to have stacked values?

### ISSUE THREAD

**Issue by atreeon** [imaNNeoFighT/fl_chart#104]
Is it possible to create something like below?  Stacked charts I think they are called.

![Screenshot 2019-11-10 at 17 09 20](https://user-images.githubusercontent.com/4139336/68547738-e18ca200-03dc-11ea-8974-cd3f33475218.png)

**Comment by imaNNeoFighT** [comment]
Hi, unfortunately, it is impossible at the moment.
We will implement it ASAP.
Stay tuned!

**Comment by kw2019ltd** [comment]
also if can be horizontal stacked like below
https://google.github.io/charts/flutter/example/bar_charts/stacked_horizontal

**Comment by imaNNeoFighT** [comment]
Hey guys, 
I've just implemented the stacked bar chart in [0.4.2](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.4.2) , using [BarChartRodStackItem](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#BarChartRodStackItem) in our `BarChart'.
check out the samples:

##### Sample 4 ([Source Code](/example/lib/bar_chart/samples/bar_chart_sample4.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_4.png" width="300" >

##### Sample 5 ([Source Code](/example/lib/bar_chart/samples/bar_chart_sample5.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_5.png" width="300" >

**Comment by imaNNeoFighT** [comment]
@kw2019ltd 
Unfortunately, we do not support horizontal bar charts.
Make another issue to follow it up.

**Comment by bebopinbebop** [comment]
I use a Transform.rotate widget to rotate the chart:

Transform.rotate(
                  angle: 3.14 / 2,
                  child: BarChart(
                    isPlaying ? randomData() : mainBarData(),
                    swapAnimationDuration: animDuration,
                  ),
                )
