### ISSUE TITLE
PieChart and HTML renderer NotImplemented Exception

### ISSUE THREAD

**Issue by Sesa1988** [imaNNeoFighT/fl_chart#1045]
** Don't make a duplicate issue.
I found similar issues but this exact one probably.

**Describe the bug**
- Add a pie chart with any data
- Start flutter web with html renderer (its working with canvas or on mobile/desktop)
- Navigate to chart

**To Reproduce**
I will do it if needed.

**Screenshots**
If applicable, add screenshots, or videoshots to help explain your problem.

**Versions**
 - Fl_chart: 0.51.0
 - Flutter: 

**Exception**
`══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following UnimplementedError was thrown during paint():
UnimplementedError
The relevant error-causing widget was:
  PieChart
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
lib/ui/path.dart 72:5                                                         combine
packages/fl_chart/src/chart/pie_chart/pie_chart_painter.dart 164:26           generateSectionPath
packages/fl_chart/src/chart/pie_chart/pie_chart_painter.dart 99:25            drawSections
packages/fl_chart/src/chart/pie_chart/pie_chart_painter.dart 47:5             paint
packages/fl_chart/src/chart/pie_chart/pie_chart_renderer.dart 139:13          paint
packages/flutter/src/rendering/object.dart 2477:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 187:12                             paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                          paint
packages/flutter/src/rendering/object.dart 2477:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 187:12                             paintChild
packages/flutter/src/rendering/box.dart 2844:14                               defaultPaint
packages/flutter/src/rendering/stack.dart 611:5                               paintStack
packages/flutter/src/rendering/stack.dart 627:7                               paint
packages/flutter/src/rendering/object.dart 2477:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 187:12                             paintChild
packages/flutter/src/rendering/shifted_box.dart 79:14                         paint
packages/flutter/src/rendering/object.dart 2477:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 187:12                             paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                          paint
packages/flutter/src/rendering/object.dart 2477:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 187:12                             paintChild
packages/flutter/src/rendering/sliver.dart 1774:14                            paint
packages/flutter/src/rendering/object.dart 2477:7                             [_paintWithContext]`

**Comment by imaNNeoFighT** [comment]
Dup of #955
