### ISSUE TITLE
如何实现网状雷达图?RadarChart (spider web chart)

### ISSUE THREAD

**Issue by codertiany** [imaNNeoFighT/fl_chart#1047]
** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.

**Describe the bug**

**To Reproduce**
Provide us a completely reproducible code (contains the main function) in a `main.dart` file, it helps us to find the bug immediately.

**Screenshots**
If applicable, add screenshots, or videoshots to help explain your problem.

**Versions**
 - which version of the Flutter are you using?
 - which version of the FlChart are you using?

**Comment by codertiany** [comment]
https://camo.githubusercontent.com/5bc3f6ca916ccb0933610921fbab438a48f164638cd87e8f0823d5255790f6b8/68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d50416e64726f696443686172742f6d61737465722f73637265656e73686f74732f726164617263686172742e706e67

**Comment by codertiany** [comment]
Hello, how can I achieve the effect similar to the above radar chart?

**Comment by FlorianArnould** [comment]
Hello, this could help #1052

**Comment by codertiany** [comment]
> Hello, this could help #1052

Thanks,The effect is quite good.

**Comment by imaNNeoFighT** [comment]
@codertiany If your issue is solved, feel free to close it.

**Comment by imaNNeoFighT** [comment]
This feature has just been added in [0.55.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.55.0)/

**Comment by codertiany** [comment]
> This feature has just been added in [0.55.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.55.0)

Thanks
