### ISSUE TITLE
Bar Chart - an option to align title, currently the texts are overlapping

### ISSUE THREAD

**Issue by atreeon** [imaNNeoFighT/fl_chart#105]
With many bars the titles overlap.  If we could show the titles vertically that would be great.  As a suggestion they could go on top of the bars.

<img width="323" alt="Screenshot 2019-11-10 at 20 17 28" src="https://user-images.githubusercontent.com/4139336/68550063-4e149a80-03f7-11ea-933f-73b67afb8226.png">

**Comment by imaNNeoFighT** [comment]
Currently, we support showing them at the top of each bar, [check it out](https://github.com/imaNNeoFighT/fl_chart/issues/84),
and about the vertical titles, there is an open [issue](https://github.com/imaNNeoFighT/fl_chart/issues/75), follow it up.
If this answer satisfied you, feel free to close it.
Thanks!

**Comment by atreeon** [comment]
Actually, I couldn't get the title on top so I added to the source

**Comment by atreeon** [comment]
It mostly works but when the bars are the same height and narrow then I still get overlapping.  It could be useful to have a staggered option where the title is not directly above the bar but cascading from top to bottom so there is a real minimal chance of overlapping (although I guess the align text will help with this anyway)

<img width="112" alt="Screenshot 2019-11-10 at 23 13 06" src="https://user-images.githubusercontent.com/4139336/68552511-ba02fd00-040f-11ea-969b-2f5cf0258c23.png">

**Comment by imaNNeoFighT** [comment]
Your use cases are so unique :)
btw let it be open,
we can consider it in the future.

**Comment by atreeon** [comment]
As a small work around what I did was order the bars based on how different the values are.  I get a bit of an up and down result but much less overlapping.
<img width="319" alt="Screenshot 2019-11-12 at 07 47 48" src="https://user-images.githubusercontent.com/4139336/68652163-c7f47300-0520-11ea-8756-65ff153bdffd.png">

**Comment by imaNNeoFighT** [comment]
I'm going to close this issue, do you have any request or suggestion except the vertical titles?

**Comment by atreeon** [comment]
No probs
