### ISSUE TITLE
Throws exception when bar chart data is empty.

### ISSUE THREAD

**Issue by panda-p1** [imaNNeoFighT/fl_chart#1050]
Hi, I would like to show empty bar chart when there is no data, how can I do that?
When I try to pass empty array as argument to barGroups it throws exception: 

'package:fl_chart/src/extensions/bar_chart_data_extension.dart': Failed assertion: line 5 pos 12: 'barGroups.isNotEmpty': is not true.

Could you please help me with that?

Versions:  
1) Flutter 3.0.1
2) fl_chart 0.51.0

Thank you for this awesome package!

**Comment by m-gavrilovic** [comment]
Had the same problem with empty data and I tried providing empty list , but it didn't work.
For me the solution was: BarChartGroupData (barGroups) is null-able . So you can just say : 

barGroups: data.isNotEmpty ? chartLines : null
