### ISSUE TITLE
Bar Chart - negative values go above

### ISSUE THREAD

**Issue by atreeon** [imaNNeoFighT/fl_chart#106]
I set the width of my bars.  Some of the bars are shown correctly as negative values going below the 0 line but others, even though they have and display a negative value, show above the 0 line.  If I reduce the width of the bars sometimes they behave correctly.  Any ideas?  

<img width="239" alt="Screenshot 2019-11-11 at 02 35 41" src="https://user-images.githubusercontent.com/4139336/68556962-3a375b80-042c-11ea-8ab7-17037d7d1d6c.png">

<img width="159" alt="Screenshot 2019-11-11 at 02 40 15" src="https://user-images.githubusercontent.com/4139336/68557081-9e5a1f80-042c-11ea-9216-190b96e7862d.png">

(and thank you again for the package, I like the way it is customisable, really good and the only one I could find that does most of what I want to do!)

**Comment by imaNNeoFighT** [comment]
Do you have rounded corners with 0 radius?

**Comment by imaNNeoFighT** [comment]
Pleasure that it fits your usage

**Comment by imaNNeoFighT** [comment]
> Do you have rounded corners with 0 radius?

?

**Comment by atreeon** [comment]
Hello, you mean corners on the card like you have in the samples?  I've tried with and without actually and unfortunately it doesn't make a difference to the negative values showing above the line.
```
    return Card(
      elevation: 0,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
```

_sorry I was away from my computer all yesterday._

**Comment by imaNNeoFighT** [comment]
No,
do you set `isRounded` true, in your [BarChartRodData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#barchartroddata)?

**Comment by atreeon** [comment]
I have it set to false but if I do set it to true then the negative values don't look very accurate.
<img width="322" alt="Screenshot 2019-11-12 at 09 21 41" src="https://user-images.githubusercontent.com/4139336/68658747-f0cf3500-052d-11ea-8b44-224961863f12.png">

**Comment by imaNNeoFighT** [comment]
Let it be false, can you please provide me a code to reproduce it?

**Comment by atreeon** [comment]
All it requires is the width to be different for different bars

**Comment by imaNNeoFighT** [comment]
I need to a reproducible code, please make it, I don't have time to write the reproducible code,
write your scenario and put it here (including the main function), then I can copy-paste and run it, instead of writing them.
Regards!

**Comment by imaNNeoFighT** [comment]
Implemented support for negative values for the BarChart, in [0.9.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.9.0)
Check it out:

##### Sample 5 ([Source Code](/example/lib/bar_chart/samples/bar_chart_sample5.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_5.png" width="300" >

**Comment by mkprogrammer15** [comment]
Hello! Is there a solution to display negative values with a different color in line chart?
