### ISSUE TITLE
Selection line

### ISSUE THREAD

**Issue by mohamed-adly** [imaNNeoFighT/fl_chart#1063]
is there is a way to customize selection line?
like color or make it dotted

**Comment by imaNNeoFighT** [comment]
I didn't understand what you wanted.
Can you explain it more clearly?

**Comment by mohamed-adly** [comment]
![image](https://user-images.githubusercontent.com/57298072/174354911-ed27ea4d-080e-4a47-8718-97bba44491b8.png)
the line that appears when you hover on the chart
how to customize it in terms of color thickness the tip of it and so on
Thank you

**Comment by imaNNeoFighT** [comment]
Please checkout our sample:

##### LineChartSample 3 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample3.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_3.gif" width="300" >
