### ISSUE TITLE
Pie chart is not appear in mobile web browser.

### ISSUE THREAD

**Issue by SumeetMourya** [imaNNeoFighT/fl_chart#1071]
**Description of the bug**
I have some issue for Pie chart, on **desktop web browser** everything is fine.
but on the **mobile device web browser**, the **Pie chart** is not appear on the UI.

This is only for the **Pie chart**, when I use another type of chart like **RadarChart** then it working. Please check the screenshots  

I cannot debug with dart tools to check for the hierarchy of widget tree, because this issue on mobile device web browser.

**To Reproduce**
Add the Pie chart to the UI, and build for the web and either deploy on local host or remote server, then run it on **Mobile Device web browser**

**Screenshots**

**Radar chart on mobile web browser**

<img width="220" alt="Screenshot 2022-06-24 at 08 12 43" src="https://user-images.githubusercontent.com/6266232/175482472-a3779aec-7e71-4d33-92be-feaec0afd065.png">

**Radar chart on desktop web browser**

<img width="500" alt="Screenshot 2022-06-24 at 08 12 43" src="https://user-images.githubusercontent.com/6266232/175482231-e5d307f5-ce97-401c-8cc9-0bfd56face4b.png">

**Pie chart on mobile web browser**

<img width="220" alt="Screenshot 2022-06-24 at 08 12 43" src="https://user-images.githubusercontent.com/6266232/175482853-8c7b9664-f550-42ac-a017-c2fe269b24c8.png">

**Pie chart on desktop web browser**
<img width="500" alt="Screenshot 2022-06-24 at 08 16 46" src="https://user-images.githubusercontent.com/6266232/175482928-6587e173-f0bf-47dc-9d6a-93c7e6f599d7.png">

**Versions**
 - Flutter: 3.0.2
 - fl_chart: 0.55.0

**Comment by imaNNeoFighT** [comment]
It's a Flutter related bug. Follow this thread: #955
