### ISSUE TITLE
FlSpot decimal digit Display 

### ISSUE THREAD

**Issue by AnkushCodes** [imaNNeoFighT/fl_chart#1073]
My use case is to show Digit and upto four decimals

eg. On **FLSpot**  if value is **93.0012** its will show correct **93.0012**

but when value is **93.1300** it shows on graph **93.13** after clicking on graph

_expected value is is 93.1300_

**Comment by RobinJespersen** [comment]
Use darts build in [toStringAsFixed()](https://api.dart.dev/stable/2.17.5/dart-core/num/toStringAsFixed.html) method to convert it to a string.

**Comment by imaNNeoFighT** [comment]
@RobinJespersen is correct.
You can customize the showing text using [toStringAsFixes()](https://api.dart.dev/stable/2.17.5/dart-core/num/toStringAsFixed.html)
