### ISSUE TITLE
RadarChart titlePositionPercentageOffset is uneven across titles in version 0.55.0

### ISSUE THREAD

**Issue by ateich** [imaNNeoFighT/fl_chart#1074]
**Describe the bug**
In RadarChart when titlePositionPercentageOffset is used, titles are displayed at an uneven distance from the chart

This occurs in version 0.55.0, but not 0.51.0

**To Reproduce**
```
import 'dart:math';

import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: UsageRadarChart(),
        ),
      ),
    );
  }
}

class UsageRadarChart extends StatelessWidget {
  const UsageRadarChart({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final random = Random();
    final dataValuesPerHour = List.generate(24, (index) => random.nextInt(10));
    return SizedBox(
      width: 300,
      height: 300,
      child: RadarChart(
        RadarChartData(
          titlePositionPercentageOffset: 0.2,
          getTitle: (int index, double angle) {
            return RadarChartTitle(text: 'A', angle: angle);
          },
          dataSets: [
            RadarDataSet(
              dataEntries: List.generate(
                dataValuesPerHour.length,
                    (index) => RadarEntry(value: dataValuesPerHour[index].toDouble()),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

**Screenshots**
Expected Behavior (version 0.51.0)            |  Actual Behavior (version 0.55.0)
:-------------------------:|:-------------------------:
<img width="271" alt="Expected" src="https://user-images.githubusercontent.com/4775201/176349488-dfb5f821-17f7-4bbc-a72b-53474676c8c6.png">  | <img width="277" alt="Actual" src="https://user-images.githubusercontent.com/4775201/176349487-7e3d771c-0110-482b-841a-6b31ca359498.png">
All titles are evenly distanced from the chart | The titles at the top and the bottom are closer to the chart than the titles on the sides

**Versions**
 - which version of the Flutter are you using?
 ```
 flutter --version
Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (7 weeks ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2
```
 - which version of the FlChart are you using?
```
fl_chart: ^0.55.0
```

**Cause**
Line 221 of radar_chart_painter.dart should be `radius * threshold` not `radius + threshold`
```
sin(angle) * (radius * threshold + (_titleTextPaint.height / 2));
```

https://github.com/imaNNeoFighT/fl_chart/blob/7c4af2f334d7e195c7c74aa7b465a99635e3f0db/lib/src/chart/radar_chart/radar_chart_painter.dart#L218-L221

**Comment by imaNNeoFighT** [comment]
Fixed in [0.55.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.55.1). Check it out!
