### ISSUE TITLE
LineChart horizontal scroll support?

### ISSUE THREAD

**Issue by codertiany** [imaNNeoFighT/fl_chart#1077]
hi，@imaN_Khoshabi
Line chart support horizontal scrolling?

![image](https://user-images.githubusercontent.com/11660271/176818666-8e94a591-9baa-4491-b31a-17054a11990c.png)

**Comment by martinkong0806** [comment]
The horizontal scroll is not implemented inside the package, but instead wrapped with a GestureDetector that will listen to the drag response, and rerender the graph accordingly.

**Comment by imaNNeoFighT** [comment]
Follow #71
