### ISSUE TITLE
Curved goes to negative

### ISSUE THREAD

**Issue by BLACKCAT25896** [imaNNeoFighT/fl_chart#1080]
When Data goes too high and curved set true it goes under the bottom line
<img width="424" alt="Screenshot 2022-07-03 at 7 08 49 PM" src="https://user-images.githubusercontent.com/18536121/177041290-6dc7086b-9f6e-4876-8162-7b5ae204d025.png">
.

**Comment by RobinJespersen** [comment]
https://github.com/imaNNeoFighT/fl_chart/issues/1024#issuecomment-1186562047
