### ISSUE TITLE
convert last version

### ISSUE THREAD

**Issue by SouMeiApp** [imaNNeoFighT/fl_chart#1083]
I need to convert the following code and I didn't understand directly how to convert the following parameters:

getTextStyles
margin
getTitles

follow code:

 leftTitles: AxisTitles(
                          sideTitles: SideTitles(
                            showTitles: true,
                            getTextStyles: (value, _) => const TextStyle(
                              color: Color(0xff7589a2),
                              fontWeight: FontWeight.bold,
                              fontSize: 14,
                            ),
                            margin: 32,
                            reservedSize: 14,
                            getTitles: (value) {
                              if (value % 50 == 0) {
                                return value.toString();
                              }
                              return '';
                            },
                          ),
                        ),

**Comment by imaNNeoFighT** [comment]
Follow our guidelines [here](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/migration_guides/INDEX.md)
