### ISSUE TITLE
No border on pie chart with a single section

### ISSUE THREAD

**Issue by mentoc3000** [imaNNeoFighT/fl_chart#1089]
**Describe the bug**
Border is not shown on pie charts that have only one section.

**To Reproduce**
<details>
  <summary>Code that produces image below</summary>
  
```dart
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: PieChartSample(),
      ),
    );
  }
}

class PieChartSample extends StatelessWidget {
  const PieChartSample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Card(
            child: SizedBox(
              height: 200,
              width: 200,
              child: PieChart(
                PieChartData(sections: showingSections(4)),
              ),
            ),
          ),
          Card(
            child: SizedBox(
              height: 200,
              width: 200,
              child: PieChart(
                PieChartData(sections: showingSections(1)),
              ),
            ),
          ),
        ],
      ),
    );
  }

  List<PieChartSectionData> showingSections(int count) {
    final sections = [
      PieChartSectionData(value: 40, borderSide: const BorderSide()),
      PieChartSectionData(value: 30, borderSide: const BorderSide()),
      PieChartSectionData(value: 15, borderSide: const BorderSide()),
      PieChartSectionData(value: 15, borderSide: const BorderSide()),
    ];
    return sections.take(count).toList();
  }
}
```

</details>

**Screenshots**
<img width="360" alt="Screenshot_1657248194" src="https://user-images.githubusercontent.com/19390380/177906742-12c4e744-9508-4ec7-9a84-dfbe809f4ee2.png">

**Versions**
 - which version of the Flutter are you using? 3.0.1
 - which version of the FlChart are you using? 0.55.0

**Comment by imaNNeoFighT** [comment]
Fixed in [0.55.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.55.1). Check it out!

**Comment by mentoc3000** [comment]
Thanks for addressing this @imaNNeoFighT! I see the border on the outside now, but shouldn't there also be a border on the inside to be consistent with the multi-section design?

<img width="360" alt="Screenshot_1659701060" src="https://user-images.githubusercontent.com/19390380/183073967-d19a70e8-7c48-4be6-a071-e5da4aaf8d63.png">

**Comment by imaNNeoFighT** [comment]
Oh sorry. I missed that. I will fix it ASAP.

**Comment by imaNNeoFighT** [comment]
It has landed on the master branch just now.
You can try it out using the below code until we bump the version up.
```
dependencies:

  fl_chart:
    git:
      url: git@github.com:imaNNeoFighT/fl_chart.git
      ref: master
```

**Comment by mentoc3000** [comment]
Looks great!!

<img width="360" alt="Screenshot_1659797988" src="https://user-images.githubusercontent.com/19390380/183254558-63b6d068-f7cf-4eb6-8d8a-6e4e6bc02fdb.png">
