### ISSUE TITLE
Hide or customize horizontal line displaying on maxY and minimum value using getDrawingHorizontalLine

### ISSUE THREAD

**Issue by basnetjiten** [imaNNeoFighT/fl_chart#1095]
Currently I can use below to show horizontal grid line,

      gridData: FlGridData(
                        getDrawingHorizontalLine: (value) => FlLine(
                          color: AppColors.greenColor,
                          strokeWidth: 0.4,
                          dashArray: [8, 4],
                        ),

![Screen Shot 2022-07-15 at 14 25 37](https://user-images.githubusercontent.com/45201707/179187538-3f0438e3-8d5e-412a-b436-f9995b6c9792.png)

                      

I want to use gridline as customization for line that appears on maxY and minY or remove it.

**Comment by imaNNeoFighT** [comment]
You need to use `borderData` instead of `gridData` to modify lines around the chart.

**Comment by basnetjiten** [comment]
@imaNNeoFighT borderData is not available for BarChart.

**Comment by basnetjiten** [comment]
@imaNNeoFighT I have used  borderData and  customize the dash with dashArray. Is there a way I can do the same with a line that displays for maxY and minY? It is just a thick grey line for now.

**Comment by prateek601** [comment]
Any updates here. I also want a feature by which we can customize the line on the maxY and minY

**Comment by imaNNeo** [comment]
Can you provide me a simple reproducible code?

**Comment by d3xt3r2909** [comment]
The issue is that if you specify maxY (that is not inside range of dataset) the top line inside grid will not render because it doesn't reach at all maxY value (it goes until max value which is provided in data). Because of that people are using top and bottom labels (which I didn't found a way to be dashed since flutter is not supporting this feature)

**Comment by kimwest00** [comment]
> Any updates here. I also want a feature by which we can customize the line on the maxY and minY. Why this issues is closed? This needs to be reopen.
I agree with this

**Comment by kimwest00** [comment]
> Any updates here. I also want a feature by which we can customize the line on the maxY and minY. Why this issues is closed? This needs to be reopen.

I agree with this;)
I have to use both gridData, borderData to set maxY,minY gridLine like below code 
```
FlGridData get gridData => FlGridData(
      show: true,
      drawVerticalLine: false,
      checkToShowHorizontalLine: (value) {
       // set temporary value; in real logic, i set maxValue of data
        int maxValue = 60;
        var grids = [0, maxValue ~/ 3, maxValue * 2 ~/ 3, maxValue];
        return grids.contains(value);
      },
      getDrawingHorizontalLine: (value) {
        return FlLine(
          color: c313131,
          strokeWidth: 1,
        );
      },
    );
// remove this code, don't draw gridData for maxY,minY value
FlBorderData get borderData => FlBorderData(
      show: true,
      border: Border.symmetric(
        horizontal: BorderSide(
          color: c313131,
          width: 1,
        ),
      ),
    );
```
If I didn't add borderData code, `getDrawingHorizontalLine` method can't provide gridLine for maxY, minY value.
Therefore, I think that development can be more convenient if the`getDrawingHorizontalLine` method is expanded for maxY and minY values
