### ISSUE TITLE
Add average line and data point lines to line chart

### ISSUE THREAD

**Issue by agustka** [imaNNeoFighT/fl_chart#11]
Add additional line definition options for line chart that would include an average line and data points lines. Data point lines are lines that go from the label up to the chart line.

![chart](https://user-images.githubusercontent.com/15977764/59094165-1b74ec00-8905-11e9-850b-af89a7c4fb00.png)

**Comment by imaNNeoFighT** [comment]
added on [0.0.7](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.0.7), check this sample:

[<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_3.png" width="300" >](https://github.com/imaNNeoFighT/fl_chart/blob/feature/extra-lines/example/lib/line_chart/samples/line_chart_sample3.dart)

dashed lines and dotted lines not supported yet, 
but I will add it ASAP.
