### ISSUE TITLE
How can we avoid the overlap of the ordinate?  

### ISSUE THREAD

**Issue by redDwarf03** [imaNNeoFighT/fl_chart#1119]
Hello

i have a chart and sometimes, the ordonate overlaps the min or/and the max value
![Capture d’écran 2022-08-15 à 01 30 10](https://user-images.githubusercontent.com/68340133/184558960-e1bb208d-e8eb-4ea8-bc3d-c9c78faad758.png)
Can this be avoided?

Thx

**Comment by absar** [comment]
Since in this axis the maximum value is not so important to show, you can workaround it by hiding the max title using `getTitlesWidget` e.g.:

``` dart
rightTitles: AxisTitles(
  sideTitles: SideTitles(
    getTitlesWidget: (value, meta) {
      final axisTitle = value == meta.max ? const SizedBox.shrink() : Text(value.toString());
      return SideTitleWidget(axisSide: meta.axisSide, child: axisTitle);
    },
  ),
)
```

**Comment by redDwarf03** [comment]
Thx. I take this solution.

**Comment by peterwvj** [comment]
> Since in this axis the maximum value is not so important to show, you can workaround it by hiding the max title using `getTitlesWidget` e.g.:
> 
> ```dart
> rightTitles: AxisTitles(
>   sideTitles: SideTitles(
>     getTitlesWidget: (value, meta) {
>       final axisTitle = value == meta.max ? const SizedBox.shrink() : Text(value.toString());
>       return SideTitleWidget(axisSide: meta.axisSide, child: axisTitle);
>     },
>   ),
> )
> ```

I found that using `Text(meta.formattedValue)` instead of `Text(value.toString())` worked better for my case due to the precision of the `value` (a doube) which did not produce the formatting I wanted. As an example, `(2.0 - 1.9).toString()` returns `0.10000000000000009`.
