### ISSUE TITLE
How to change tooltip background color and text style?

### ISSUE THREAD

**Issue by Govindbetterlives** [imaNNeoFighT/fl_chart#1129]
Hi, 
Can we change tooltip background color and text style?

**Comment by Omegaviv** [comment]
Hey @Govindbetterlives  yes we can change tooltip background color and text style,

in LineTouchData there is one function called getToolTips item, here you can define a custom function to change text style of tooltip, here is an example 

`getTooltipItems: (List<LineBarSpot> touchedSpots) {
            return touchedSpots.map((LineBarSpot touchedSpot) {
              final textStyle = TextStyle(
                color: touchedSpot.bar.gradient?.colors.first ??
                    touchedSpot.bar.color ??
                    Colors.blueGrey,
                fontWeight: FontWeight.bold,
                fontSize: 27,
              );
              return LineTooltipItem(touchedSpot.y.toString(), textStyle);
            }).toList();
          }`
