### ISSUE TITLE
Add Line Support for Bar Chart like a Combo Chart

### ISSUE THREAD

**Issue by marmagno** [imaNNeoFighT/fl_chart#1140]
Hi, this is my first time creating an issue/feature request so kindly bear with me. 😅 

**Context**
We have a feature in our company project that wants to have a stackable bar chart along with a line but unfortunately, current `BarChart` does not have yet support to render simple lines like how `LineChart` does them. 

Kinda something like this: 
![image](https://user-images.githubusercontent.com/15721307/188637163-a5afdc9d-beaf-45b3-9699-9310c64b179e.png)

It would be wonderful if we could have an added feature/enhancement for that. 

So I tried to forked the project and implemented a simple line like how the `LineChart` does but I don't know if it is by far the best solution. Tho local testing seems it worked, I just need to add unit testing for that. 

**Suggested Solution**
What I did was the ff:
- move the `barPaint` instance from the `LineChartPaint` class to `AxisChartPaint` class as well as the methods needed to draw the lines. (i.e. drawBarLine, generateBarPath, etc. )
- move the `LineChartBarData` from `LineChartData` to `AxisChartData` to be able to use globally.
- then call the `drawLine` method in BarChart for every lineBarsData

Here is the link for the forked sample branch: [Line Chart support for Bar Chart](https://github.com/marmagno/fl_chart/tree/feature/bar_chart_lines)

**Expected Result**
Expected result usage could be like this, an added property in the `BarChart` for `LineChartBarData` list to render some simple lines. Ideally it would be awesome if it behaves like how it is in the line chart with the added area bars and touch interaction but for now we just need this.

```
return BarChart(
      BarChartData(
        ...
        lineBarsData: [
             LineChartBarData(
              spots: _generateSpots(chartBarData.dataPoints),
              barWidth: chartBarData.barWidth,
              color: chartBarData.solidColor,
              isCurved: chartBarData.isCurved,
              preventCurveOverShooting: chartBarData.preventCurveOverShooting,
              dotData: FlDotData(show: false),
              isStepLineChart: chartBarData.isStepLineChart,
            ),
          )
        ],
      ),

      /// set to: no animation
      swapAnimationDuration: Duration(),
    );
```

Looking forward for your response and great works as always for creating this awesome package. 💪

**Comment by imaNNeoFighT** [comment]
Hi. Thanks for creating this issue and sharing your experience.
We already have an open issue. You can follow it here: #764. Don't forget to thumb it up.
Also, I appreciate it if you write your experience there.
