### ISSUE TITLE
Bar Chart - horizontal line between positive and negative?

### ISSUE THREAD

**Issue by fennelhans** [imaNNeoFighT/fl_chart#1145]
How can I draw a horizontal line at y = 0?

![image](https://user-images.githubusercontent.com/98828887/189997666-d976f2b2-2b50-4d71-afdd-d9f1f6b9208b.png)

**Comment by imaNNeoFighT** [comment]
You can use `BarChartData.gridData` to draw lines behind bars.

**Comment by imaNNeoFighT** [comment]
Check our BarChartSample5:

[Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample5.dart)
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_5.gif" width="300" >
