### ISSUE TITLE
How to add  Image of value on the bar chart top?

### ISSUE THREAD

**Issue by Kimsoer** [imaNNeoFighT/fl_chart#1158]
Thank for your great library! 
I want add image like this, but I found out that topTitles seems to doesn't work on bar chart .
Would you please give me some tips ?

[https://i.stack.imgur.com/gaXTU.png](url)

**Comment by imaNNeoFighT** [comment]
You're welcome.
Unfortunately, there is no feature to do that. You can use font icons to draw icons in the tooltip.
BTW there is an open issue that we are talking about having widgets in our tooltip.
Please follow that issue.
#72
