### ISSUE TITLE
error touching chart

### ISSUE THREAD

**Issue by erasmojcjr** [imaNNeoFighT/fl_chart#116]
I/ViewRootImpl(19863): finishMotionEvent: handled = true stage=10: View Post IME stage,inputElapseTime=16 eventTime = 272585428 downTime = 272585428 title= br.com.areco.mobsales/br.com.areco.mobsales.MainActivity
E/flutter (19863): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (19863): Receiver: null
E/flutter (19863): Tried calling: [](0)
E/flutter (19863): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (19863): #1      PieChartPainter._getTouchedDetails (package:fl_chart/src/chart/pie_chart/pie_chart_painter.dart:197:42)
E/flutter (19863): #2      PieChartPainter.handleTouch (package:fl_chart/src/chart/pie_chart/pie_chart_painter.dart:170:12)
E/flutter (19863): #3      PieChartState.build.<anonymous closure> (package:fl_chart/src/chart/pie_chart/pie_chart.dart:62:28)
E/flutter (19863): <asynchronous suspension>
E/flutter (19863): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (19863): #5      DragGestureRecognizer._checkCancel (package:flutter/src/gestures/monodrag.dart:431:7)
E/flutter (19863): #6      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:340:9)
E/flutter (19863): #7      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:324:9)
E/flutter (19863): #8      DragGestureRecognizer.rejectGesture (package:flutter/src/gestures/monodrag.dart:328:5)
E/flutter (19863): #9      GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:261:24)
E/flutter (19863): #10     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:222:9)
E/flutter (19863): #11     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:52:12)
E/flutter (19863): #12     OneSequenceGestureRecognizer.resolve (package:flutter/src/gestures/recognizer.dart:255:13)
E/flutter (19863): #13     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:278:11)
E/flutter (19863): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (19863): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (19863): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (19863): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (19863): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (19863): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (19863): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (19863): #21     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (19863): #22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (19863): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (19863): #24     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (19863): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
E/flutter (19863):

**Comment by imaNNeoFighT** [comment]
Any description?

**Comment by imaNNeoFighT** [comment]
Hello?
