### ISSUE TITLE
Can you insert a Title Text or Widget inside the centre space of a pie chart?

### ISSUE THREAD

**Issue by fritz-playmaker** [imaNNeoFighT/fl_chart#1174]

**Comment by WilliamTekno** [comment]
Yes, you just need encapsulate you pie chart on  Stack() an put a Text() after AspectRatio().

`Stack(
            alignment: Alignment.center,
            children: [
              AspectRatio(
                aspectRatio: 1,
                child: PieChart(
                  PieChartData(
                    sectionsSpace: 5,
                    centerSpaceRadius: 120,
                    sections: loadCarteira(),
                    pieTouchData: PieTouchData(
                      touchCallback: (FlTouchEvent touch, PieTouchResponse? response) => setState(() {
                        index = response?.touchedSection?.touchedSectionIndex ?? 0;
                        setGraficoDados(index);
                      }),
                    ),
                  ),
                ),
              ),
              Column(
                children: [
                  Text(
                    graficoLabel,
                    style: const TextStyle(
                      fontSize: 20,
                      color: Colors.teal,
                    ),
                  ),
                  Text(
                    real.format(graficoValor),
                    style: const TextStyle(
                      fontSize: 28,
                    ),
                  ),
                ],
              ),
            ],
          );`

**Comment by imaNNeoFighT** [comment]
Yes, @WilliamTekno's answer is correct.
There is no build-in option to do that at the moment. And I think it is a very specific need that can be solved with the Stack solution.

Thank you

**Comment by JasonYinH** [comment]
Stack(
              alignment: Alignment.center,
              children: [
                AspectRatio(
                  aspectRatio: 1,
                  child: PieChart(
                    PieChartData(
                      pieTouchData: PieTouchData(
                        touchCallback: (FlTouchEvent event, pieTouchResponse) {
                          setState(() {
                            if (!event.isInterestedForInteractions ||
                                pieTouchResponse == null ||
                                pieTouchResponse.touchedSection == null) {
                              touchedIndex = -1;
                              return;
                            }
                            touchedIndex = pieTouchResponse
                                .touchedSection!.touchedSectionIndex;
                          });
                        },
                      ),
                      borderData: FlBorderData(
                        show: false,
                      ),
                      sectionsSpace: 0,
                      centerSpaceRadius: 50,
                      sections: showingSections(),
                    ),
                  ),
                ),
                const Text(
                  "中心标题",
                  style: TextStyle(
                    fontSize: 20,
                    color: Color(0xffffffff),
                  ),
                ),

**Comment by Shuhrat-java** [comment]
Stack is not working correctly
