### ISSUE TITLE
Can fl_chart render like this?

### ISSUE THREAD

**Issue by adrianvintu** [imaNNeoFighT/fl_chart#1176]
I am trying to achieve the design in this image, but fail to.
![fl_chart](https://user-images.githubusercontent.com/33379688/196541515-7d434898-10dd-4807-8950-4e7c716dc9bc.png)

The best is get is this
![fl_chart 2](https://user-images.githubusercontent.com/33379688/196541682-1c8357ff-6eb8-4299-b0e2-8aa6bf7e497a.png)

Is if possible in fl_chart to:
1. have the `leftTitles` render on top of the lines, instead of to the left of the line?
2. have empty circles as index indicators? I now use `getTouchedSpotIndicator` `FlDotCirclePainter` to set the white border, but if I set the `FlDotCirclePainter(color: Colors.transparent,` the bar line will show to the middle of the dot circle like here

![fl_chart 3](https://user-images.githubusercontent.com/33379688/196543178-7ff5dfc7-0045-40d8-82cd-e94f85f16396.png)

3. have the top/bottom line of the graph rendered as dots? it seems I can only render it as line or invisible via
```
borderData: FlBorderData(
        border: Border(
          bottom: BorderSide(
            color: Colors.yellow,
            width: 4.4,
            style: BorderStyle.none,
          ),
```
Related ticket: https://github.com/imaNNeoFighT/fl_chart/issues/1150

Thank you for your wonderful product which I already use in 2 projects. Wish you all the best!

**Comment by imaNNeoFighT** [comment]
Hi.
As you can pass a widget as a title, you leverage the power of flutter. Widgets.
You can wrap your [Text](https://api.flutter.dev/flutter/widgets/Text-class.html) widget (or any other widget) with [Transform.translate ](https://api.flutter.dev/flutter/widgets/Transform/Transform.translate.html) widget to move your text with an offset.

Check the below sample ([full code is here](https://gist.github.com/imaNNeoFighT/3db335be8502414b405c7177e4da7e29)):

![image](https://user-images.githubusercontent.com/7009300/212541451-2e50f02a-077f-4efa-b899-f208a18110bb.png)

**Comment by adrianvintu** [comment]
Thank you very much. I am assuming pints #2 and #3 are not doable thane, right?

**Comment by imaNNeoFighT** [comment]
What do you mean?

**Comment by adrianvintu** [comment]
There are 3 points to the ticket. I think you only answered the first one. Can you maybe reread the ticket text?

**Comment by imaNNeoFighT** [comment]
Aha I missed them.
2. You need to write your own Painter. (just read the `FlDotCirclePainter` to learn more about it)
3. Unfortunately you can't render as dots. You can only render them as dashed lines.

**Comment by adrianvintu** [comment]
Thank you very much!

Keep up the awesome work!

**Comment by imaNNeoFighT** [comment]
Thank you!
