### ISSUE TITLE
Line Chart: Always show tooltip and spot after a click

### ISSUE THREAD

**Issue by Nicolas-Bouvard** [imaNNeoFighT/fl_chart#118]
Hello ! I'm using your package for my lines charts.
I would like tooltip and spot to keep beeing displayed after a click and release on the chart.
Currently I didn't find any way to do so...

Thank you for your package, it's very cool !

Edit:
By clicking on the chart, the tooltip and spot keep beeing displayed.
Here, the package's tool tip and spot have been removed to put my own widget. The problem is that it was very long to create, it is not optimized, that's not really relliable and it don't follow chart's animations.

![SVID_20191127_163037_1](https://user-images.githubusercontent.com/47215972/69737239-575e7080-1134-11ea-8f19-949963c856f0.gif)

**Comment by imaNNeoFighT** [comment]
Hello, great to hear that, enjoy it :)
All charts have a built-in handled interaction, but you can implement your own interaction. 
In the [0.5.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.5.0) we've added `Velocity` to in [FlPanEnd](https://github.com/imaNNeoFighT/fl_chart/blob/feature/scatter-chart/repo_files/documentations/base_chart.md#fltouchinput) to determine the Tap event.
It means you can handle Tap events, and show/hide spots as you want.
We have a sample that handles tap to show or hide the tooltips in the [ScatterChart](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/scatter_chart.md), you can findout how to do that.
check it out:

##### Sample 2 ([Source Code](/example/lib/scatter_chart/samples/scatter_chart_sample2.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/scatter_chart/scatter_chart_sample_2.gif" width="300" >


Let me know if it does make sense to you.

**Comment by komputerboy** [comment]
How to make chart like that?
Have feature to group by yearly, monthly, and weekly?

**Comment by imaNNeoFighT** [comment]
I didn't get you.

**Comment by komputerboy** [comment]
> I didn't get you.

I mean how to make a feature to group chart data by yearly, monthly, and weekly?
so, when user clicks yearly, then the chart shows yearly data, and when weekly then the shart show weekly data.

**Comment by Nicolas-Bouvard** [comment]
> Hello, great to hear that, enjoy it :)
> All charts have a built-in handled interaction, but you can implement your own interaction.
> In the [0.5.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.5.0) we've added `Velocity` to in [FlPanEnd](https://github.com/imaNNeoFighT/fl_chart/blob/feature/scatter-chart/repo_files/documentations/base_chart.md#fltouchinput) to determine the Tap event.
> It means you can handle Tap events, and show/hide spots as you want.
> We have a sample that handles tap to show or hide the tooltips in the [ScatterChart](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/scatter_chart.md), you can findout how to do that.
> check it out:
> 
> ##### Sample 2 ([Source Code](/example/lib/scatter_chart/samples/scatter_chart_sample2.dart))
> <img alt="" width="300" src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/scatter_chart/scatter_chart_sample_2.gif">
> 
> Let me know if it does make sense to you.

After a few tests I didn't find any way to apply that to line charts.
I'm looking for a settings that allow us to keep displaying or not spot and tooltip.
Currently it doesn't seem to exist but it could be a cool enhancement =)

Anyway thanks for this package =)

**Comment by Nicolas-Bouvard** [comment]
> > I didn't get you.
> 
> I mean how to make a feature to group chart data by yearly, monthly, and weekly?
> so, when user clicks yearly, then the chart shows yearly data, and when weekly then the shart show weekly data.

That's not a package's feature. It's only a `setState()` which changes the list of FlSpots to show.

**Comment by imaNNeoFighT** [comment]
I will make a sample in the LineChart ASAP.

**Comment by GOGJIAN** [comment]
> I will make a sample in the LineChart ASAP.

where is the sample？I can't find it，please help me

**Comment by GOGJIAN** [comment]
> > I will make a sample in the LineChart ASAP.
> 
> where is the sample？I can't find it，please help me

and I use ```showingTooltipIndicators```  and handleBuiltInTouches: true,  because I need the line and dot

when I touch ,this work fine,but when I longpress or move finger, this tip will be removed

**Comment by GOGJIAN** [comment]
> > > I will make a sample in the LineChart ASAP.
> > 
> > 
> > where is the sample？I can't find it，please help me
> 
> I use `showingTooltipIndicators` and `handleBuiltInTouches: true`, because I need the line and dot
> 
> in this case ,when I touch ,this work fine,but when I longpress or move finger, this tip will be removed
> 
> OR I use `showingTooltipIndicators` and `handleBuiltInTouches: false` , but the `getTouchedSpotIndicator` params indicators always is `[]`

oh I sovled it, by `showingIndicators` ,alright，emmm ，this  not comfortable

**Comment by Sharkaboi** [comment]
Any way to do this with `LineChart` ? `showingIndicators ` seems to be for bar charts.

**Comment by masterwok** [comment]
@imaNNeoFighT is there a `LineChart` sample for persistent tool tips with `TouchedSpotIndicatorData` somewhere? I was able to get a persistent tool tip on tap working using your bar chart sample but I wasn't able to get the `TouchedSpotIndicatorData` to render on the graph (dot and dashed line) when `handleBuiltInTouches` was set to `false`. Any help would be greatly appreciated! Thank you.

**Comment by venomanse** [comment]
Hello, guys. Your help needed. I'm implementing single line bar chart with tooltips showed after click. And have issue after click first tooltip display correctly above the clicked dot. But the second one and others shows above clicked dot as list with previous. But I would like the tooltip to be shown on the dot that was selected only.

Here is video with the issue:
https://user-images.githubusercontent.com/64984018/208400705-7e441bfe-f8f0-4934-9dc9-2fc18c179515.mov

And here is a code: 
`import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart' as intl;

import '../assets.dart';

final List<String> _weekDays = List.generate(
  DateTime.daysPerWeek,
  (index) {
    final now = DateTime.now();
    final day = now.weekday % DateTime.daysPerWeek;
    final weekDay = now.add(Duration(days: DateTime.monday - day + index));

    return intl.DateFormat.E().format(weekDay);
  },
);

class ChartBuilder<T> extends StatefulWidget {
  const ChartBuilder({
    required this.items,
    required this.itemBuilder,
    required this.hintBuilder,
    super.key,
  });

  final List<T> items;

  /// Function that builds the item.
  final FlSpot Function(BuildContext context, T value) itemBuilder;

  /// Function that builds the hints.
  final List<LineTooltipItem> Function(BuildContext context, List<LineBarSpot>)
      hintBuilder;

  @override
  State<ChartBuilder<T>> createState() => _ChartBuilderState<T>();
}

class _ChartBuilderState<T> extends State<ChartBuilder<T>> {
  List<int> selectedSpots = [];

  @override
  Widget build(BuildContext context) {
    final leftTitles = AxisTitles(
      sideTitles: SideTitles(
        showTitles: false,
      ),
    );

    final rightTitles = AxisTitles(
      sideTitles: SideTitles(
        showTitles: false,
      ),
    );
    final topTitles = AxisTitles(
      sideTitles: SideTitles(
        showTitles: false,
      ),
    );

    final bottomTitles = AxisTitles(
      sideTitles: SideTitles(
        showTitles: true,
        getTitlesWidget: getTitles,
        reservedSize: 18,
        interval: 1,
      ),
    );

    const leftBorder = BorderSide(color: ColorName.neutral95, width: 3);

    const rightBorder = BorderSide(color: ColorName.neutral95, width: 3);

    final linesChartData = [
      LineChartBarData(
        color: ColorName.tertiary95,
        isCurved: true,
        curveSmoothness: 0.3,
        dotData: FlDotData(
          getDotPainter: (spot, percent, barData, index) => FlDotCirclePainter(
            radius: 5,
            color: ColorName.secondary90,
            strokeColor: ColorName.primary100,
            strokeWidth: 3,
          ),
        ),
        preventCurveOverShooting: true,
        preventCurveOvershootingThreshold: 1,
        spots: widget.items
            .map((item) => widget.itemBuilder(context, item))
            .toList(growable: false),
        barWidth: 2,
        showingIndicators: selectedSpots,
      ),
    ];

    return AspectRatio(
      aspectRatio: 2,
      child: Padding(
        padding: const EdgeInsets.all(6),
        child: LineChart(
          LineChartData(
            titlesData: FlTitlesData(
              topTitles: topTitles,
              leftTitles: leftTitles,
              rightTitles: rightTitles,
              bottomTitles: bottomTitles,
            ),
            minX: 1,
            maxX: 7,
            borderData: FlBorderData(
              border: const Border(
                left: leftBorder,
                right: rightBorder,
              ),
              show: true,
            ),
            gridData: FlGridData(
              drawHorizontalLine: false,
              getDrawingVerticalLine: (value) =>
                  FlLine(strokeWidth: 3, color: ColorName.neutral95),
              checkToShowVerticalLine: (value) => true,
              verticalInterval: 1,
            ),
            lineBarsData: linesChartData,
            showingTooltipIndicators: [
              ShowingTooltipIndicators(
                selectedSpots.map((e) {
                  final barData = linesChartData.first;

                  return LineBarSpot(
                    barData,
                    1,
                    barData.spots[e],
                  );
                }).toList(growable: false),
              ),
            ],
            lineTouchData: LineTouchData(
              enabled: true,
              handleBuiltInTouches: false,
              mouseCursorResolver: (touchEvent, response) =>
                  response == null || response.lineBarSpots == null
                      ? MouseCursor.defer
                      : SystemMouseCursors.click,
              touchCallback: _handleTouch,
              getTouchedSpotIndicator: (barData, spotIndexes) => spotIndexes
                  .map(
                    (e) => TouchedSpotIndicatorData(
                      FlLine(strokeWidth: 0),
                      FlDotData(
                        getDotPainter: (spot, percent, barData, index) =>
                            FlDotCirclePainter(
                          radius: 5,
                          color: ColorName.primary90,
                          strokeColor: ColorName.primary100,
                          strokeWidth: 3,
                        ),
                      ),
                    ),
                  )
                  .toList(growable: false),
              touchTooltipData: LineTouchTooltipData(
                fitInsideHorizontally: true,
                tooltipBgColor: ColorName.primary90,
                getTooltipItems: (touchedSpots) => widget
                    .hintBuilder(context, touchedSpots)
                    .toList(growable: false),
              ),
            ),
          ),
        ),
      ),
    );
  }

  void _handleTouch(FlTouchEvent touchEvent, LineTouchResponse? touchResponse) {
    if (touchResponse == null || touchResponse.lineBarSpots == null) {
      return;
    }
    if (touchEvent is FlTapUpEvent) {
      final touchedSpots = touchResponse.lineBarSpots!
          .map(
            (e) => e.spotIndex,
          )
          .toList(growable: false);

      setState(() {
        for (final element in touchedSpots) {
          if (selectedSpots.contains(element)) {
            selectedSpots.remove(element);
          } else {
            selectedSpots.add(element);
          }
        }
      });
    }
  }

  Widget getTitles(double value, TitleMeta meta) {
    const style = TextStyle(
      fontSize: 12,
    );

    return SideTitleWidget(
      axisSide: meta.axisSide,
      space: 4,
      child: Text(
        _weekDays[value.toInt() - 1],
        style: style,
      ),
    );
  }
}
`

**Comment by asinel** [comment]
@imaNNeo I think we should reopen this issue, it is still not possible to set touchedSpotIndicator on LineChart, when handleBuiltInTouches is false

**Comment by imaNNeo** [comment]
So I have updated our LineChartSample5 to implement a toggle to show/hide the tooltip in LineChart.

You can check it out live in our web app at https://app.flchart.dev
There is a link to source-code in the example (top right)

https://user-images.githubusercontent.com/7009300/232223355-2a580a17-8d63-4b0d-ad9d-39e59b538095.mov
