### ISSUE TITLE
When I use four charts in a screen, the performance is bad

### ISSUE THREAD

**Issue by Gavin-1991** [imaNNeoFighT/fl_chart#119]
Could you tell me some methods to optimize it. Each chart only have 7 group data.

**Comment by imaNNeoFighT** [comment]
Hi there,
could you please provide me a sample?

**Comment by Gavin-1991** [comment]
I found that If I use five charts in a screen and each chart enable LineTouchData, the scroll event often doesn't work and it load slowly.

**Comment by imaNNeoFighT** [comment]
We have some issues when your data is huge, please provide me your sample, I will help you.

**Comment by imaNNeoFighT** [comment]
Feel free to close this issue if you find out the problem.
Thanks!
