### ISSUE TITLE
When there is a lot of data, the touch display data spills out of the screen

### ISSUE THREAD

**Issue by helloworkcupid** [imaNNeoFighT/fl_chart#1193]
**Describe the bug**

**To Reproduce**
Provide us a completely reproducible code (contains the main function) in a `main.dart` file, it helps us to find the bug immediately.

      child: LineChart(
        LineChartData(
          lineBarsData: listLine,
          titlesData: titlesData1,
          minY: 0.0,
          baselineX: 0,
          baselineY: 0,
          clipData: FlClipData.none(),
        ),
      ),

FlTitlesData get titlesData1 => FlTitlesData(
        bottomTitles: AxisTitles(
          sideTitles: bottomTitles,
          // rotateAngle:5,
        ),
        rightTitles: AxisTitles(
          sideTitles: SideTitles(showTitles: false),
        ),
        topTitles: AxisTitles(
          sideTitles: SideTitles(showTitles: false),
        ),
        leftTitles:
            AxisTitles(
          drawBehindEverything: true,
          sideTitles: leftTitles(),
          axisNameSize: 1,
   
        ),
      );

  SideTitles get bottomTitles => SideTitles(
        showTitles: true,
        reservedSize: 32,
        // rotateAngle: 90,
        interval: 1,
        getTitlesWidget: bottomTitleWidgets,
      );

  SideTitles leftTitles() => SideTitles(
        getTitlesWidget: leftTitleWidgets,
        showTitles: true,
        interval: 1,
        reservedSize: 40,
      );

**Screenshots**
If applicable, add screenshots, or videoshots to help explain your problem.
When there is a lot of data, the touch display data spills out of the screen
How to make touch display data in the middle of the screen
**Versions**
 - which version of the Flutter are you using?
 - Flutter (Channel beta, 3.3.0-0.5.pre
 - which version of the FlChart are you using?
 -   fl_chart: ^0.55.1

![image](https://user-images.githubusercontent.com/25734405/208455236-6bb40430-d9a0-4b2e-b4ca-bc0fcd95a209.png)

**Comment by venomanse** [comment]
```
touchTooltipData: LineTouchTooltipData(
                fitInsideHorizontally: true,
                fitInsideVertically: true,

```

**Comment by helloworkcupid** [comment]
Thank you! my friends
