### ISSUE TITLE
Property rotateAngle was silently removed from SideTitles

### ISSUE THREAD

**Issue by JoshMart** [imaNNeoFighT/fl_chart#1203]
**Describe the bug**
[Release 0.6.0](https://pub.dev/packages/fl_chart/changelog#060) added a `rotateAngle` property to `SideTitles`. However it appears this has been removed sometime in later versions but the release notes don't call this out as a breaking change or offer any replacements to this removed property.

**Versions**
On Flutter v3.3.10
Found on fl_chart v0.55.2

**Comment by imaNNeoFighT** [comment]
We restructured SideTitles. Please read [0.50.0 release note](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.50.0).
