### ISSUE TITLE
How can I set a title for the tooltip?

### ISSUE THREAD

**Issue by taoyimin** [imaNNeoFighT/fl_chart#121]
I tried to insert an element to the collection, but it didn't work.
```
getTooltipItems: (List<LineBarSpot> touchedSpots) {
            if (touchedSpots == null) {
              return null;
            }

            List<LineTooltipItem> tooltipItems =
                touchedSpots.map((LineBarSpot touchedSpot) {
              if (touchedSpot == null) {
                return null;
              }
              final TextStyle textStyle = TextStyle(
                color: touchedSpot.bar.colors[0],
                fontWeight: FontWeight.bold,
                fontSize: 14,
              );
              return LineTooltipItem('${touchedSpot.y}', textStyle);
            }).toList();
            tooltipItems.insert(
              0,
              LineTooltipItem(
                'title',
                const TextStyle(
                  color: Colors.white,
                  fontWeight: FontWeight.bold,
                  fontSize: 14,
                ),
              ),
            );
            return tooltipItems;
          },
```

**Comment by imaNNeoFighT** [comment]
May I ask you explain it more?

**Comment by taoyimin** [comment]
![image](https://user-images.githubusercontent.com/21152164/69939573-28bd0d00-151b-11ea-81c7-886093bd0b04.png)

Like this, I want to generate the title.

**Comment by imaNNeoFighT** [comment]
Ok got it, currently, we don't support custom style for the tooltip,
we will have it ASAP.
Stay tuned!

**Comment by Wizzel1** [comment]
Anything new on this one ?

**Comment by imaNNeoFighT** [comment]
Unfortunately, not yet!

**Comment by Wizzel1** [comment]
No worries, i found a workaround by creating another LineChartBarData with invisible colors and get its data with getTooltipItems(). Luckily my model holds the data together with everything else, so it was easy to access it with the invisible LineBarSpot index.

**Comment by jlubeck** [comment]
We could definitely use this as well. Specially when you use an interval for the bottom SideTiles, and you open a tooltip in between those intervals, there is currently no way to display which X value corresponds to that tooltip

**Comment by jlubeck** [comment]
I kind of take that back. I was able to display the X value by doing a hackish thing. 

```dart
getTooltipItems: (List<LineBarSpot> lineBarsSpot) {
            return lineBarsSpot.map(
              (lineBarSpot) {
                int index = lineBarSpot.spotIndex;
                PatientReadingDTO reading = patientReadings[index];
                String date = reading.readingTime.toLocalShortDateString();
                print(date);
                final labels = ['SYS', 'DIA', 'PUL'];
                return LineTooltipItem(
                  '${lineBarSpot.barIndex == 0 ? '$date\n\n' : ''}${lineBarSpot.y.toStringAsFixed(0)} ${labels[lineBarSpot.barIndex]}',
                  TextStyle(
                      color: lineBarSpot.bar.colors.first,
                      fontWeight: FontWeight.bold),
                );
              },
            ).toList();
          }
```

But I can't give it a different style, since I HAVE to use an existing `LineTooltipItem`.

Being able to give a title/footer to the tooltip would be great

**Comment by mkprogrammer15** [comment]
Any news for customize spots in a tooltip? Need to change colors and radius. Also that touchedLine should be thinner. Is that possible?

**Comment by imaNNeoFighT** [comment]
Our [TooltipItem](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#LineTooltipItem) which you can pass a list of [TextSpan](https://api.flutter.dev/flutter/painting/TextSpan-class.html) and customize the tooltip'c content.

##### Check BarChartSample 1 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/edit/master/example/lib/bar_chart/samples/bar_chart_sample1.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_1.gif" width="300" >

**Comment by KonstiDE** [comment]
> I kind of take that back. I was able to display the X value by doing a hackish thing.
> 
> ```dart
> getTooltipItems: (List<LineBarSpot> lineBarsSpot) {
>             return lineBarsSpot.map(
>               (lineBarSpot) {
>                 int index = lineBarSpot.spotIndex;
>                 PatientReadingDTO reading = patientReadings[index];
>                 String date = reading.readingTime.toLocalShortDateString();
>                 print(date);
>                 final labels = ['SYS', 'DIA', 'PUL'];
>                 return LineTooltipItem(
>                   '${lineBarSpot.barIndex == 0 ? '$date\n\n' : ''}${lineBarSpot.y.toStringAsFixed(0)} ${labels[lineBarSpot.barIndex]}',
>                   TextStyle(
>                       color: lineBarSpot.bar.colors.first,
>                       fontWeight: FontWeight.bold),
>                 );
>               },
>             ).toList();
>           }
> ```
> 
> But I can't give it a different style, since I HAVE to use an existing `LineTooltipItem`.
> 
> Being able to give a title/footer with independent style to the tooltip would be great. Or maybe even just a Widget where you could put whatever you want in there...

Unfortunately, this did not work for me... When the lines intersect, its a bit buggy. Some might use the condition not with the bar index but serach always for the true maximum with `e.y == spots.map((e) => e.y).reduce(max)`, however, this only works if there is only one defined maximum
