### ISSUE TITLE
How to create an empty coordinate?

### ISSUE THREAD

**Issue by DylanXie123** [imaNNeoFighT/fl_chart#123]
I need to use a list of coordinate to plot math function `ln(x)` where `x` ranges from `-5` to `5`, but it doesn't seem to have a way to create empty coordinates where `x` ranges from `-5` to `0`.

I tried to use `FlSpot(-2.0, null)` or `null` to represent an empty coordinate, but none of these work.

Are there any solutions here?

**Comment by imaNNeoFighT** [comment]
I didn't get you, may I ask you to explain it more clear?

**Comment by DylanXie123** [comment]
I need to draw something like this

![ln(x)-plot](https://user-images.githubusercontent.com/29018622/70309064-9c2a8b80-1847-11ea-88fb-39a51092bb5f.png)

I can use some coordinates in [0, 5] to plot `ln(x)` in positive x-axis, but I also want to use some empty coordinates in [-5, 0] to negative x-axis.

**Comment by imaNNeoFighT** [comment]
Why empty states?

**Comment by DylanXie123** [comment]
😂 I want user to be able to scroll to see function image in all ranges.

**Comment by imaNNeoFighT** [comment]
Dude, you can draw it with transparent color, 
does it make sense?

**Comment by DylanXie123** [comment]
Sounds a great idea, thanks for your help
👍👍👍

**Comment by imaNNeoFighT** [comment]
Or maybe you can set the minY to -5,
I think it will work too.

**Comment by DylanXie123** [comment]
Thanks a lot, I'll try that

**Comment by imaNNeoFighT** [comment]
You are welcome.
