### ISSUE TITLE
LineChartBarData show BUG

### ISSUE THREAD

**Issue by DancyLon** [imaNNeoFighT/fl_chart#125]
In a LineChartBarData ,I set the "show=false",but when I touch the line,it will show the point data also

![chart2](https://user-images.githubusercontent.com/45644988/70203205-1c24f880-1757-11ea-8890-a1d0111e416f.png)
![chart1](https://user-images.githubusercontent.com/45644988/70203229-2ba44180-1757-11ea-91f1-1c41643d4104.png)
How could I do to hide this green point?

**Comment by imaNNeoFighT** [comment]
It was a severe bug.
It has just fixed in [0.5.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.5.1), check it out.
Thank you for reporting.
