### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by yuriy-ecraft** [imaNNeoFighT/fl_chart#128]
Hello. For example, if we have about 100 points along the X axis. Is it possible to scroll the Line Chart along the x axis?

**Comment by imaNNeoFighT** [comment]
Hello, unfortunately, we do not support it yet.
But it is on the [Roadmap](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/roadmap.md) stay tuned!

**Comment by imaNNeoFighT** [comment]
https://github.com/imaNNeoFighT/fl_chart/issues/71
