### ISSUE TITLE
issue when data Y =0

### ISSUE THREAD

**Issue by nitneuq33** [imaNNeoFighT/fl_chart#13]
Hello i tried to add minY: 0.0, but I have always  a screen freeze when a dataY passed to 0... I just use bar_chart_sample2.dart and change  this like that makeGroupData(0, 0, 12),

**Comment by imaNNeoFighT** [comment]
may I ask you in which version you got this issue?

**Comment by nitneuq33** [comment]
I use fl_chart: ^0.0.3

**Comment by imaNNeoFighT** [comment]
I reproduced it, thanks!
trying to fix it.

**Comment by imaNNeoFighT** [comment]
Fixed on 0.0.4,
check it out, 
Thanks!
