### ISSUE TITLE
Add field tooltip to ScatterSpot that is displayed as default

### ISSUE THREAD

**Issue by DavidHuebner** [imaNNeoFighT/fl_chart#135]
right now, the default tooltip when clicking on an element in a ScatterSpot is the radius as defined in the function 

```
ScatterTooltipItem defaultScatterTooltipItem (ScatterSpot touchedSpot) { 
[...]
return ScatterTooltipItem('${touchedSpot.radius.toInt()}', textStyle, touchedSpot.radius + (touchedSpot.radius * 0.2));
}
```

I would find it more natural if the ScatterSpot class has an additional variable named `String tooltip ` that is used for the tooltip and that radius is only used as a fallback if tooltip is not set.

**Comment by imaNNeoFighT** [comment]
Do you want to change the text of the tooltip?
Check this #138, it may help you.
