### ISSUE TITLE
Show integer values in tooltips instead of doubles

### ISSUE THREAD

**Issue by lukasschneiderapps** [imaNNeoFighT/fl_chart#138]
In my line chart I want to display integers inside the tooltip boxes instead of doubles.

As far as I am aware this is not possible at the moment, is it?

![](https://user-images.githubusercontent.com/48716544/71080791-251dbd00-218e-11ea-8743-7e60353a1d6a.PNG)

**Comment by imaNNeoFighT** [comment]
Implement the `getTooltipItems` function inside the [BarTouchTooltipData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#bartouchtooltipdata) to update the showing text.
Just like this sample:

##### Sample 1 ([Source Code](/example/lib/bar_chart/samples/bar_chart_sample1.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_1.gif" width="300" >

**Comment by imaNNeoFighT** [comment]
Feel free to close it if it works.
Thanks!

**Comment by lukasschneiderapps** [comment]
It works, thank you!

**Comment by imaNNeoFighT** [comment]
Pleasure!
