### ISSUE TITLE
曲线图出现Y出现负数

### ISSUE THREAD

**Issue by sanrixue** [imaNNeoFighT/fl_chart#139]
...
      minX: 0,
      maxX: 7,
      minY: 0,
      maxY: 300,
      lineBarsData: [
        LineChartBarData(
          spots: const [
            FlSpot(0, 300),
            FlSpot(1, 200),
            FlSpot(2, 10),
            FlSpot(3, 300),
            FlSpot(4, 1),
            FlSpot(5, 1),
            FlSpot(6, 300),
            FlSpot(7, 10),
          ],
...

**Comment by imaNNeoFighT** [comment]
Invalid issue!
