### ISSUE TITLE
Subsampling data before displaying line

### ISSUE THREAD

**Issue by fvisticot** [imaNNeoFighT/fl_chart#14]
I need to display 6000 points (distance and altitude).
Do I need to make a subsampling of the data ?
If I do that, I will probably not be useful if you add support to zoom in / zoom out

Do you plan to manage subsampling in this lib or do I need to make this subsampling before displaying the points ?

**Comment by imaNNeoFighT** [comment]
Hello,
currently, we haven't any plan to implement it, because there is a bunch of crucial things to implement.
maybe we implement it in the future.
