### ISSUE TITLE
LineChart width

### ISSUE THREAD

**Issue by Mboussa** [imaNNeoFighT/fl_chart#142]
hi, i am currently trying to put multiple line chart on he same grid chart, and mi question is:
It is possible to make the chart in landscape mode and to take all the space that is free? thx for your repsonses

**Comment by imaNNeoFighT** [comment]
Hi, I didn't get you,
explain clearly.
Thanks!

**Comment by Mboussa** [comment]
Sorry what im trying to say is how can mi Linechart widget take all thé landscape Space ? Thx

**Comment by imaNNeoFighT** [comment]
Put it in a `Container()` widget.

**Comment by imaNNeoFighT** [comment]
And let me know if it's worked.

**Comment by Mboussa** [comment]
It didn't work still the same a s before :/ 
<img width="892" alt="Capture d’écran 2019-12-23 à 15 48 38" src="https://user-images.githubusercontent.com/46162740/71364192-c300f580-259b-11ea-8632-3a094db6f5e8.png">

**Comment by Mboussa** [comment]
Maybe if I try to give a width in the container widget ?

**Comment by Mboussa** [comment]
Thats workers fin I used this to take all the space available: 
Container(
            width: MediaQuery.of(context).size.width / 1.25,
            child: LineChart(...)
)
