### ISSUE TITLE
lineTouchData的问题

### ISSUE THREAD

**Issue by jacky-yanglei** [imaNNeoFighT/fl_chart#145]
在触摸出现提示这个问题时会有bug，如果外层有元素包裹切设置了padding 这个触摸会有向右偏移的问题。这个问题怎么避免？
![image](https://user-images.githubusercontent.com/17645850/71441754-cdf38b80-273d-11ea-9982-741523bdcc0d.png)

**Comment by imaNNeoFighT** [comment]
Please speak English,
Thanks!

**Comment by jacky-yanglei** [comment]
There will be a bug when the touch prompts this problem. If the outer layer has element wrapping and cutting setting padding, the touch will have a right offset problem. How to avoid this problem?
![image](https://user-images.githubusercontent.com/17645850/71442021-09db2080-273f-11ea-8e05-ffed7460fe53.png)

**Comment by imaNNeoFighT** [comment]
Can you please provide me a sample code to reproduce it?
and which version are you using?

**Comment by jacky-yanglei** [comment]
fl_chart: ^0.5.2  # 图表插件

code：

import 'package:date_format/date_format.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
// import 'package:webview_flutter/webview_flutter.dart';
// import '../config/api_config.dart' as Api;


class FundDetails extends StatefulWidget {

  @override
  _FundDetailsState createState() => _FundDetailsState();
}

class _FundDetailsState extends State<FundDetails> {
  var _platformWidth;
  int _currentDate = 0;
  var a;
  @override
  void initState() {
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    _platformWidth = MediaQuery.of(context).size.width;
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(Icons.keyboard_arrow_left,color: Color.fromRGBO(119, 125, 180, 1)),
          onPressed: () => Navigator.of(context).pop(),
        ),
        centerTitle: true,
        elevation: 0,
        title: Column(
          children: <Widget>[
            Text('基金详情',
            style: TextStyle(color: Color.fromRGBO(19, 23, 125, 1)),),
            Text('data',style: TextStyle(color: Color.fromRGBO(4, 118, 255, 1)),)
          ],
        ),
        actions: [
          IconButton(
            icon: ImageIcon(AssetImage('lib/assets/images/shoucang.png')),
            tooltip: '加入收藏',
            onPressed: () {
              print('收藏');
            },
            color: Color.fromRGBO(119, 125, 180, 1),
          ),
        ]
      ),
      body: Container(
        child:ListView(
            padding: EdgeInsets.symmetric(horizontal: 17),
            children: [
              _fundDetailView(), // 上班部分的试图
              _bottomView() // 下半部分的试图
            ],
          )
        )
    );
  }

  Widget _fundDetailView() {
    return Container(
      margin: EdgeInsets.only(top: 20),
      padding: EdgeInsets.symmetric(vertical: 10),
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromRGBO(83, 75, 255, 0.2),
            blurRadius: 5.0,
          )
        ],
        borderRadius: BorderRadius.all(Radius.circular(20)),
        color: Colors.white
      ),
      child: Column(
        children: <Widget>[
          Container(
            padding: EdgeInsets.symmetric(horizontal: 13),
            alignment: Alignment.centerLeft,
            margin: EdgeInsets.only(bottom: 8),
            child: Row(
                // gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                //   crossAxisCount: 2,
                // ),
                children: <Widget>[
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children:[
                        Text('最新净值(12/20 16:00)', style: TextStyle(fontSize: 11, color: Color.fromRGBO(151, 157, 211, 1))),
                        Text('101.2107', style: TextStyle(fontSize: 15, color: Color.fromRGBO(19, 23, 125, 1), fontWeight: FontWeight.bold,))
                      ],
                    ),
                  ),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.end,
                      children: <Widget>[
                        Text('基金公司', style: TextStyle(fontSize: 11, color: Color.fromRGBO(151, 157, 211, 1))),
                        Text('BBshares', style: TextStyle(fontSize: 15, color: Color.fromRGBO(19, 23, 125, 1), fontWeight: FontWeight.bold))
                      ],
                    ),
                  )
                ],
              ),
          ),
          _selectDate(), // 选择图表展示周期
          _contentChart(), // 图表
          _resetDate(), // 重置时间组件
          _dataChart(),
        ],
      ),
    );
  }
  // 基金详情数据展示 带图表
  Widget _dataChart() {
    return Container(
      margin: EdgeInsets.only(top: 35),
      padding: EdgeInsets.symmetric(horizontal: 10),
      width: _platformWidth,
      child: Column(
        children: <Widget>[
          Container(
            margin: EdgeInsets.only(bottom: 30),
            child: Row(
              children: <Widget>[
                Expanded(
                  child: Container(
                    alignment: Alignment.centerLeft,
                    child: Row(
                      children: <Widget>[
                        Expanded(
                          child: Padding(
                            padding: EdgeInsets.only(left: 15),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: <Widget>[
                                Text('29.16%',style: TextStyle(fontSize: 17, color: Color.fromRGBO(68, 210, 207, 1), fontWeight: FontWeight.bold)),
                                Text('累计收益率',style: TextStyle(fontSize: 11, color: Color.fromRGBO(119, 125, 180, 1)),)
                              ],
                            ),
                          ),
                        ),
                        Expanded(
                          child: Container(
                            height: 40,
//                            color: Colors.redAccent,
                            child: LineChart(mainData([[2, 6], [3, 45], [4, 69], [5, 42]])),
                          ),
                        )
                      ],
                    ),
                  ),
                ),
                Expanded(
                  child: Row(
                    // color: Colors.red,
                      children: <Widget>[
                        Expanded(
                          child: Padding(
                              padding: EdgeInsets.only(left: 15),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: <Widget>[
                                  Text('30.12%',style: TextStyle(fontSize: 17, color: Color.fromRGBO(19, 23, 125, 1), fontWeight: FontWeight.bold)),
                                  Text('年化收益率',style: TextStyle(fontSize: 11, color: Color.fromRGBO(119, 125, 180, 1)),)
                                ],
                              )
                          ),
//                          child: Column(
//                            crossAxisAlignment: CrossAxisAlignment.start,
//                            children: <Widget>[
//                              Text('30.12%',style: TextStyle(fontSize: 17, color: Color.fromRGBO(19, 23, 125, 1), fontWeight: FontWeight.bold)),
//                              Text('年化收益率',style: TextStyle(fontSize: 11, color: Color.fromRGBO(119, 125, 180, 1)),)
//                            ],
//                          ),
                        ),
                        Expanded(
                          child: Container(
                            height: 40,
                            child: LineChart(mainData([[2, 6], [3, 45], [4, 69], [5, 42]])),
                          ),
                        )
                      ]
                  ),
                )
              ],
            ),
          ),
          Container(
            margin: EdgeInsets.only(bottom: 30),
            child: Row(
              children: <Widget>[
                Expanded(
                  child: Container(
                    alignment: Alignment.centerLeft,
                    child: Row(
                      children: <Widget>[
                        Expanded(
                          child: Padding(
                              padding: EdgeInsets.only(left: 15),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: <Widget>[
                                  Text('10.16%',style: TextStyle(fontSize: 17, color: Color.fromRGBO(19, 23, 125, 1), fontWeight: FontWeight.bold)),
                                  Text('最大回撤',style: TextStyle(fontSize: 11, color: Color.fromRGBO(119, 125, 180, 1)),)
                                ],
                              )
                          ),
//                          child: Column(
//                            crossAxisAlignment: CrossAxisAlignment.start,
//                            children: <Widget>[
//                              Text('10.16%',style: TextStyle(fontSize: 17, color: Color.fromRGBO(19, 23, 125, 1), fontWeight: FontWeight.bold)),
//                              Text('最大回撤',style: TextStyle(fontSize: 11, color: Color.fromRGBO(119, 125, 180, 1)),)
//                            ],
//                          ),
                        ),
                        Expanded(
                          child: Container(
                            height: 40,
                            child: LineChart(mainData([[2, 6], [3, 45], [4, 69], [5, 42]])),
                          ),
                        )
                      ],
                    ),
                  ),
                ),
                Expanded(
                  child: Row(
                      children: <Widget>[
                        Expanded(
                          child: Padding(
                              padding: EdgeInsets.only(left: 15),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: <Widget>[
                                  Text('1.6',style: TextStyle(fontSize: 17, color: Color.fromRGBO(19, 23, 125, 1), fontWeight: FontWeight.bold)),
                                  Text('夏普率',style: TextStyle(fontSize: 11, color: Color.fromRGBO(119, 125, 180, 1)),)
                                ],
                              )
                          ),
                        ),
                        Expanded(
                          child: Container(
                            height: 40,
                            child: LineChart(mainData([[2, 6], [3, 45], [4, 69], [5, 42]])),
                          ),
                        )
                      ]
                  ),
                )
              ],
            ),
          ),
          Container(
            child: Row(
              children: <Widget>[
                Expanded(
                  child: Row(
                    // color: Colors.red,
                      children: <Widget>[
                        Expanded(
                          child: Padding(
                            padding: EdgeInsets.only(left: 15),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: <Widget>[
                                Text('7.9',style: TextStyle(fontSize: 17, color: Color.fromRGBO(19, 23, 125, 1), fontWeight: FontWeight.bold)),
                                Text('卡玛比率',style: TextStyle(fontSize: 11, color: Color.fromRGBO(119, 125, 180, 1)),)
                              ],
                            )
                          ),
                        ),
                        Expanded(
                          child: Container(
                            height: 40,
                            child: LineChart(mainData([[2, 6], [3, 45], [4, 69], [5, 42]])),
                          ),
                        ),
                      ]
                  ),
                ),
                Expanded(
                  child: Container(),
                )
              ],
            ),
          )
        ],
      ),
    );
  }


  static List<String> _formats = [yyyy,'-',mm,'-',dd];
  String shartTime = formatDate(DateTime.now(), _formats);  // 开始时间
  String endTime = formatDate(DateTime.now(), _formats);  // 结束时间
  String _maxTime = formatDate(DateTime.now(), _formats); // 最大选择时间
  String _minTime = formatDate(DateTime.now(), _formats); // 最小选择时间
  // 重置时间组件
  Widget _resetDate() {
    return Container(
      padding: EdgeInsets.symmetric(horizontal: 10),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          Container(
            width: (110/375) * _platformWidth,
            height: 32,
            alignment: Alignment.center,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.all(Radius.circular(16.0)),
              boxShadow: [
                BoxShadow(
                  blurRadius: 5.0,
                  color: Color.fromRGBO(229, 234, 255, 1)
                )
              ]
            ),
            child: GestureDetector(
              child: Text(shartTime.toString(), style: TextStyle(fontSize: 15, color: Color.fromRGBO(19, 23, 125, 1))),
              onTap: () {
                showDatePicker(
                  context: context,
                  initialDate: DateTime.parse(shartTime),
                  firstDate: new DateTime(1900),
                  lastDate: DateTime.parse(_maxTime),
                ).then((onValue){
                  if (onValue != null) {
                    setState(() {
                      shartTime = formatDate(onValue, _formats);
                      _minTime = shartTime;
                    });
                  }
                });
              },
            ),
          ),
          Text('至', style: TextStyle(fontSize: 12, color: Color.fromRGBO(119,125,180,1)),),
          Container(
            width: (110/375) * _platformWidth,
            height: 32,
            alignment: Alignment.center,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.all(Radius.circular(16.0)),
              boxShadow: [
                BoxShadow(
                  blurRadius: 5.0,
                  color: Color.fromRGBO(229, 234, 255, 1)
                )
              ]
            ),
            child: GestureDetector(
              child: Text(endTime.toString(), style: TextStyle(fontSize: 15, color: Color.fromRGBO(19, 23, 125, 1))),
              onTap: () {
                showDatePicker(
                  context: context,
                  initialDate: DateTime.parse(endTime),
                  firstDate: DateTime.parse(_minTime),
                  lastDate: new DateTime.now(),
                ).then((onValue){
                  if (onValue != null) {
                    setState(() {
                      endTime = formatDate(onValue, _formats);
                      _maxTime = endTime;
                    });
                  }
                });
              },
            ),
          ),
          GestureDetector(
            onTap: () {
              print('重置时间');
            },
            child: Text('重置', style: TextStyle(color: Color.fromRGBO(119,125,180,1)),),
          )
        ],
      ),
    );
  }
  // 选择周期组件
  Widget _selectDate() {
    List data = ['全部', '近7日', '近1月', '近3月', '近1年', '今年'];
    // List colors = [Colors.green,Colors.red, Colors.greenAccent, Colors.pink, Colors.purple, Colors.purpleAccent, Colors.orange];
    List<Widget> listData = List();
    for (int i = 0;i < data.length; i++) {
      listData..add(
        GestureDetector(
            onTap: () {
              setState(() {
                _currentDate = i;
                print(data[i]);
              });
            },
            child: _currentDate == i ? _activeDate(data[i]) : Container(
              // color: colors[i] ,
              child:Text(
                data[i], 
                style: TextStyle(
                  fontSize: 13, 
                  color: Color.fromRGBO(119, 125, 180, 1)
                )
              )
            ),
          ),
      );
    }
    return Container (
      padding: EdgeInsets.only(top: 6),
      width: _platformWidth,
      color: Color.fromRGBO(245, 247, 255, 1),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: listData,
      ),
    );
  }
  // 选中时的日期样式
  Widget _activeDate(text) {
    return Container(
      child: Column(
        children: <Widget>[
          Text(text, style: TextStyle(color: Color.fromRGBO(19, 23, 125, 1), fontSize: 13),),
          Container(
            width: (15 / 375) * _platformWidth,
            height: 2,
            margin: EdgeInsets.only(top: 7),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  Color.fromRGBO(0, 184, 255, 1),
                  Color.fromRGBO(83, 75, 255, 1)
                ],
              )
            ),
          )
        ],
      ),
    );
  }
  // webView图表
  Widget _contentChart() {
    return AspectRatio(
      aspectRatio: 1.4,
      child: Container(
//        color: Colors.red,
        child: LineChart(mainData([[1571184000000.0,100.0000000000000000],[1571270400000.0,100.0000000000000000],[1571356800000.0,100.0000000000000000],[1571443200000.0,100.0000000000000000],[1571529600000.0,100.0000000000000000],[1571616000000.0,100.0000000000000000],[1571702400000.0,100.0000000000000000],[1571788800000.0,100.0000000000000000],[1571875200000.0,100.0000000000000000],[1571961600000.0,100.0000000000000000],[1572048000000.0,100.0627393523492811],[1572134400000.0,100.0627161091860813],[1572220800000.0,100.0627183915574731],[1572307200000.0,100.0627263955307099],[1572393600000.0,100.0627461764242253],[1572480000000.0,100.5293898275533098],[1572566400000.0,100.4407267117080339],[1572652800000.0,100.4755815282014865],[1572739200000.0,100.3316240132237727],[1572825600000.0,100.4161674297245682],[1572912000000.0,100.3781055520074819],[1572998400000.0,100.1933577155741067],[1573084800000.0,100.2331401486804290],[1573171200000.0,100.3345663343550124],[1573257600000.0,100.0744385513269899],[1573344000000.0,100.3878996453965290],[1573430400000.0,100.0126406862375916],[1573516800000.0,100.2678207386322092],[1573603200000.0,100.3313325956094319],[1573689600000.0,100.6297790325812605],[1573776000000.0,100.2831576440166553],[1573862400000.0,100.3752786133184471],[1573948800000.0,100.7602983435129214],[1574035200000.0,100.7708718718803506],[1574121600000.0,100.7855753599534450],[1574208000000.0,100.9353393680607506],[1574294400000.0,99.9291085586467752],[1574380800000.0,99.9323748720583576],[1574467200000.0,100.2780302874188251],[1574553600000.0,100.6909203373372683],[1574640000000.0,100.1928460351215344],[1574726400000.0,100.4513804632275000],[1574812800000.0,100.9453707623025000],[1574899200000.0,100.3406715022950000],[1574985600000.0,99.9432729805650000],[1575072000000.0,100.2888967847966417],[1575158400000.0,100.4137177735448350],[1575244800000.0,99.8165820314538715],[1575331200000.0,99.6197022965446593],[1575417600000.0,100.3604212634811412],[1575504000000.0,100.0898291309232904],[1575590400000.0,100.6987369279574329],[1575676800000.0,100.1275646671325839],[1575763200000.0,100.6507758228790306],[1575849600000.0,100.0143265754101295],[1575936000000.0,99.8668852754555244],[1576022400000.0,97.6977245683050542],[1576108800000.0,100.2889945633957030],[1576195200000.0,99.9282619535362420],[1576281600000.0,99.9294276686246443],[1576368000000.0,101.3739423305997305],[1576454400000.0,99.9301180775821008],[1576540800000.0,100.3805374096460123],[1576627200000.0,100.8141688605030659],[1576713600000.0,100.7593223958590559],[1576800000000.0,100.5956012302150679],[1576886400000.0,100.3017714583869146],[1576972800000.0,100.4749671001993830],[1577059200000.0,100.1311830219379899],[1577145600000.0,101.17191477248163270223825714]], true)),
      ),
//      child: WebView(
//        initialUrl: Api.Api_url,
//        javascriptMode: JavascriptMode.unrestricted,
//        // onWebViewCreated: (WebViewController web) {
//        //   print(web);
//        // }
//      ),
    );
  }
  int _currentTab = 0;
  Widget _bottomView() {
    return Container(
      margin: EdgeInsets.only(top: 10, bottom: 15),
      padding: EdgeInsets.only(top: 5),
      width: _platformWidth,
      decoration: BoxDecoration(
          boxShadow: [
            BoxShadow(
              color: Color.fromRGBO(83, 75, 255, 0.2),
              blurRadius: 5.0,
            )
          ],
          borderRadius: BorderRadius.all(Radius.circular(20)),
          color: Colors.white
      ),
      child: Column(
        children: <Widget>[
          Row(
            children: <Widget>[
              Expanded(
                child: GestureDetector(
                  onTap: () {
                    setState(() {
                      _currentTab = 0;
                    });
                    print('基金数据');
                  },
                  child: Container(
                    color: Colors.transparent,
                    padding: EdgeInsets.only(top: 5),
                    child: Column(
                      children: <Widget>[
                        Text('基金数据', style: TextStyle(color: _currentTab==0?Color.fromRGBO(19, 23, 125, 1):Color.fromRGBO(119, 125, 180, 1), fontSize: 17)),
                        Container(
                          margin: EdgeInsets.only(top: 4),
                          width: 20,
                          height: 2,
                          decoration: BoxDecoration(
                              gradient: _currentTab==0?LinearGradient(
                                  colors: [
                                    Color.fromRGBO(0, 184, 255, 1),
                                    Color.fromRGBO(83, 75, 255, 1)
                                  ]):null
                          ),
                        )
                      ],
                    ),
                  ),
                ),
              ),
              Expanded(
                child: GestureDetector(
                    onTap: () {
                      setState(() {
                        _currentTab = 1;
                      });
                      print('更多数据');
                    },
                  child: Container(
                    color: Colors.white,
                    padding: EdgeInsets.only(top: 5),
                    child: Column(
                      children: <Widget>[
                        Text('更多数据', style: TextStyle(color: _currentTab==1?Color.fromRGBO(19, 23, 125, 1):Color.fromRGBO(119, 125, 180, 1), fontSize: 17),),
                        Container(
                          margin: EdgeInsets.only(top: 4),
                          width: 20,
                          height: 2,
                          decoration: BoxDecoration(
                              gradient: _currentTab==1?LinearGradient(
                                  colors: [
                                    Color.fromRGBO(0, 184, 255, 1),
                                    Color.fromRGBO(83, 75, 255, 1)
                                  ]):null
                          ),
                        )
                      ],
                    ),
                  ),
                )
              )
            ],
          ),
          Container(
            height: 150,
            child: _currentTab == 0 ? _fundDateDetail(): _moreData(),
          )
        ],
      )
    );
  }
  Widget _fundDateDetail() {
    return Table(
      children: [
        TableRow(
            decoration: BoxDecoration(
                color: Color.fromRGBO(245, 247, 255, 1)
            ),
            children: [
              TableCell(
                child: Padding(
                  padding: EdgeInsets.only(left: 15),
                  child: MyText('期限',
                    color: Color.fromRGBO(119, 125, 180, 1),
                    alignment: Alignment.centerLeft,
                    fontSize: 11,
                  ),
                ),
              ),
              TableCell(
                child:Padding(
                  padding: EdgeInsets.only(left: 0),
                  child: MyText('收益率',
                    color: Color.fromRGBO(119, 125, 180, 1),
                    alignment: Alignment.center,
                    fontSize: 11,
                  ),
                ),
              ),
              TableCell(
                child:Padding(
                  padding: EdgeInsets.only(right: 15),
                  child: MyText('夏普率',
                    color: Color.fromRGBO(119, 125, 180, 1),
                    alignment: Alignment.centerRight,
                    fontSize: 11,
                  ),
                ),
              ),
            ]
        ),
        TableRow(
            children: [
              TableCell(
                child: Padding(
                  padding: EdgeInsets.only(left: 15),
                  child: MyText('近7日',
                      color: Color.fromRGBO(19, 23, 125, 1),
                      alignment: Alignment.centerLeft,
                      fontSize: 13,
                      fontWeight: FontWeight.bold
                  ),
                ),
              ),
              TableCell(
                child:Padding(
                  padding: EdgeInsets.only(left: 0),
                  child: MyText('11.2%',
                      color: Color.fromRGBO(0, 204, 200, 1),
                      alignment: Alignment.center,
                      fontSize: 13,
                      fontWeight: FontWeight.bold
                  ),
                ),
              ),
              TableCell(
                child:Padding(
                  padding: EdgeInsets.only(right: 15),
                  child: MyText('1.7',
                      color: Color.fromRGBO(19, 23, 125, 1),
                      alignment: Alignment.centerRight,
                      fontSize: 13,
                      fontWeight: FontWeight.bold
                  ),
                ),
              ),
            ]
        ),
        TableRow(
            children: [
              TableCell(
                child: Padding(
                  padding: EdgeInsets.only(left: 15),
                  child: MyText('11月份',
                      color: Color.fromRGBO(19, 23, 125, 1),
                      alignment: Alignment.centerLeft,
                      fontSize: 13,
                      fontWeight: FontWeight.bold
                  ),
                ),
              ),
              TableCell(
                child:Padding(
                  padding: EdgeInsets.only(left: 0),
                  child: MyText('11.2%',
                      color: Color.fromRGBO(0, 204, 200, 1),
                      alignment: Alignment.center,
                      fontSize: 13,
                      fontWeight: FontWeight.bold
                  ),
                ),
              ),
              TableCell(
                child:Padding(
                  padding: EdgeInsets.only(right: 15),
                  child: MyText('1.7',
                      color: Color.fromRGBO(19, 23, 125, 1),
                      alignment: Alignment.centerRight,
                      fontSize: 13,
                      fontWeight: FontWeight.bold
                  ),
                ),
              ),
            ]
        ),
        TableRow(
            children: [
              TableCell(
                child: Padding(
                  padding: EdgeInsets.only(left: 15),
                  child: MyText('第四季度',
                      color: Color.fromRGBO(19, 23, 125, 1),
                      alignment: Alignment.centerLeft,
                      fontSize: 13,
                      fontWeight: FontWeight.bold
                  ),
                ),
              ),
              TableCell(
                child:Padding(
                  padding: EdgeInsets.only(left: 0),
                  child: MyText('11.2%',
                      color: Color.fromRGBO(0, 204, 200, 1),
                      alignment: Alignment.center,
                      fontSize: 13,
                      fontWeight: FontWeight.bold
                  ),
                ),
              ),
              TableCell(
                child:Padding(
                  padding: EdgeInsets.only(right: 15),
                  child: MyText('1.7',
                      color: Color.fromRGBO(19, 23, 125, 1),
                      alignment: Alignment.centerRight,
                      fontSize: 13,
                      fontWeight: FontWeight.bold
                  ),
                ),
              ),
            ]
        ),
        TableRow(
            children: [
              TableCell(
                child: Padding(
                  padding: EdgeInsets.only(left: 15),
                  child: MyText('今年',
                      color: Color.fromRGBO(19, 23, 125, 1),
                      alignment: Alignment.centerLeft,
                      fontSize: 13,
                      fontWeight: FontWeight.bold
                  ),
                ),
              ),
              TableCell(
                child:Padding(
                  padding: EdgeInsets.only(left: 0),
                  child: MyText('11.2%',
                      color: Color.fromRGBO(0, 204, 200, 1),
                      alignment: Alignment.center,
                      fontSize: 13,
                      fontWeight: FontWeight.bold
                  ),
                ),
              ),
              TableCell(
                child:Padding(
                  padding: EdgeInsets.only(right: 15),
                  child: MyText('1.7',
                      color: Color.fromRGBO(19, 23, 125, 1),
                      alignment: Alignment.centerRight,
                      fontSize: 13,
                      fontWeight: FontWeight.bold
                  ),
                ),
              ),
            ]
        ),
      ],
    );
  }
  Widget _moreData() {
    TextStyle textStyle = TextStyle(
      color: Color.fromRGBO(19, 23, 125, 1),
      fontSize: 13,
      fontWeight: FontWeight.bold
    );
    return Container(
      margin: EdgeInsets.only(top: 5),
      padding: EdgeInsets.symmetric(horizontal: 15),
      child: Column(
        children: <Widget>[
          Padding(
            padding: EdgeInsets.symmetric(vertical: 8),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Text('卡玛比率', style: textStyle,),
                Text('2.3%', style: textStyle,)
              ],
            ),
          ),
          Padding(
            padding: EdgeInsets.symmetric(vertical: 8),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Text('年化风险率', style: textStyle,),
                Text('11.3%', style: textStyle,)
              ],
            ),
          ),
          Padding(
            padding: EdgeInsets.symmetric(vertical: 8),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Text('最大回撤期', style: textStyle,),
                Text('2018/05/11-2019/11/04', style: textStyle,)
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class MyText extends StatelessWidget {
  final String data;
  final Color color;
  final Alignment alignment;
  final double fontSize;
  final FontWeight fontWeight;
  MyText(this.data, {Key key, this.color, this.alignment, this.fontSize, this.fontWeight}):super(key: key);
  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: alignment,
      padding: EdgeInsets.symmetric(vertical: 5),
      child: Text(data, style: TextStyle(color: color, fontSize: fontSize, fontWeight: fontWeight),),
    );
  }
}

LineChartData mainData(lineList, [hasTouch]) {
  var max = lineList[0][1];
  var min = lineList[0][1];
  var isTouch = hasTouch==null || hasTouch == false?false:true;
  List<FlSpot> spot = List<FlSpot>.from(lineList.map((item) {
    if (item[1].toDouble() > max) {
      max = item[1].toDouble();
    }
    if (item[1].toDouble() < min) {
      min = item[1].toDouble();
    }
    return FlSpot(item[0].toDouble(), item[1].toDouble());
  }
  ).toList());
  return LineChartData(
    minY: min.toDouble()*0.995,
    maxY: max.toDouble()*1.005,
    clipToBorder: true,
    lineTouchData: LineTouchData(
        enabled: isTouch,
        touchTooltipData: LineTouchTooltipData(
          getTooltipItems: (touchedSpots) {
            return touchedSpots.map((LineBarSpot touchedSpot) {
              if (touchedSpot == null) {
                return null;
              }
              final TextStyle textStyle = TextStyle(
                color: Color.fromRGBO(19, 23, 125, 1),
                fontWeight: FontWeight.bold,
                fontSize: 14,
              );
              return LineTooltipItem(formatDate(DateTime.fromMicrosecondsSinceEpoch(touchedSpot.x.toInt() * 1000), [yyyy, '-', mm, '-', dd]) + '\n' + touchedSpot.y.toStringAsFixed(2), textStyle);
            }).toList();
          }
        )
    ),
    extraLinesData: ExtraLinesData(
        showHorizontalLines: false,
        horizontalLines: [
          HorizontalLine(
              x: 2,
              strokeWidth: 1
          )
        ]
    ),  // 额外的基准线
    gridData: FlGridData(
      show: false,  // 网格是否展示
      drawVerticalGrid: false,  // 是否展示Y轴网格
      drawHorizontalGrid: true, // 是否展示X轴网格
      getDrawingHorizontalGridLine: (value) {
        return const FlLine(
          color: Color.fromRGBO(210, 219, 255, 0.5),
          strokeWidth: .5,
        );
      }, // X轴网格
      getDrawingVerticalGridLine: (value) {
        return const FlLine(
          color: Color.fromRGBO(210, 219, 255, 0.5),
          strokeWidth: .5,
        );
      },
    ),
    titlesData: FlTitlesData(
      show: false,  // 是否展示X 和Y 轴的说明
      bottomTitles: SideTitles(
        showTitles: false,
        reservedSize: 22,
        textStyle: TextStyle(
            color: const Color(0xff68737d),
            fontWeight: FontWeight.bold,
            fontSize: 16
        ),
        margin: 8,
        interval: 1000.0,
        getTitles: (value) {
          if (value.toInt() == lineList[0][0].toInt() || value.toInt() == lineList[lineList.length-1][0].toInt()) {
             return formatDate(DateTime.fromMicrosecondsSinceEpoch(value.toInt() * 1000), [yyyy, '/', mm, '/', dd]);
          } else {
            
          }
          return '';
        },
      ),
      leftTitles: SideTitles(
        showTitles: true,
        textStyle: TextStyle(
          color: const Color(0xff67727d),
          fontWeight: FontWeight.bold,
          fontSize: 8,
        ),
        reservedSize: 14,
        margin: 0,
        getTitles: (value) {
            return value.toInt().toString();
        },
      ),
    ),
    borderData: FlBorderData(
        show: false,
        border: Border.all(color: const Color(0xff37434d), width: 1)
    ),  // 是否有边框
    lineBarsData: [
      LineChartBarData(
        spots: spot,
        isCurved: true,
        colors: [
          Color.fromRGBO(0, 184, 255, 1)
        ],
        barWidth: 1.5,
        isStrokeCapRound: true,
        dotData: const FlDotData(
          show: false,
        ),
        belowBarData: BarAreaData(
          show: true,
          colors: [
            Color.fromRGBO(0, 184, 255, 0.3),
            Color.fromRGBO(0, 184, 255, 0.0)
          ],
          gradientFrom: const Offset(0, 0),
          gradientTo: const Offset(0, 1),
          gradientColorStops: [
            0, 100
          ],
        ),
      ),
    ],
  );
}

**Comment by imaNNeoFighT** [comment]
Please use the latest version (now is '0.6.0`), and put the code in a file or shrink it.

**Comment by jacky-yanglei** [comment]
I streamlined the code：

[demo.dart.txt](https://github.com/imaNNeoFighT/fl_chart/files/4001176/demo.dart.txt)

dependence:

fl_chart: ^0.6.0
date_format: ^1.0.6

**Comment by imaNNeoFighT** [comment]
The file doesn't have the main function, and it's not working.
please provide me an error-free code.
Thanks!

**Comment by imaNNeoFighT** [comment]
It will be closed tomorrow if you don't provide the code.

**Comment by jacky-yanglei** [comment]
Sorry,This is code.

[main.dart.txt](https://github.com/imaNNeoFighT/fl_chart/files/4033246/main.dart.txt)

**Comment by shamilovtim** [comment]
@jacky-yanglei put the padding outside of the component

**Comment by shamilovtim** [comment]
Ancestor( ← padding here
  Parent( ← not here
    FLChart
  )
);
