### ISSUE TITLE
 Problem with drawing betweenBarData

### ISSUE THREAD

**Issue by mahmoud-eslami** [imaNNeoFighT/fl_chart#152]
`fl_chart` version : `0.6.2`

When using the `Betweenbardata` for drawing between two bars, if we use the `isCurve` attribute for that bar, The values between the two bar are not correctly drawn.
And this is the problem for the bar which we put in the `toIndex` attribute.

![Screenshot_1578126551](https://user-images.githubusercontent.com/57481226/71763089-038e3680-2eed-11ea-80bb-ac25cd9e896e.png)
![Screenshot_1578127858](https://user-images.githubusercontent.com/57481226/71763090-0557fa00-2eed-11ea-962e-419eb537fad2.png)

**Comment by imaNNeoFighT** [comment]
Hi @krispypen,
May I ask you to check it, if you have a little free time?

**Comment by imaNNeoFighT** [comment]
Could you please provide me a reproducible code?
I've checked it and it's working correctly.

**Comment by imaNNeoFighT** [comment]
It's gonna be closed tomorrow
