### ISSUE TITLE
the tooltip bubble overflow

### ISSUE THREAD

**Issue by jacky-yanglei** [imaNNeoFighT/fl_chart#159]
![image](https://user-images.githubusercontent.com/17645850/72049942-fb723480-32fa-11ea-9a2f-5b3e6b7e10ab.png)

How to display this prompt bubble in the screen?

**Comment by imaNNeoFighT** [comment]
You mean out of the chart?

**Comment by jacky-yanglei** [comment]
No，When it is near the edge of the screen, the position of the prompt can be shifted to the appropriate position to display the whole screen, or, Its position can be fixed

**Comment by imaNNeoFighT** [comment]
Got it

**Comment by imaNNeoFighT** [comment]
added fitInsideTheChart property inside BarTouchTooltipData and LineTouchTooltipData to force tooltip draw inside the chart (shift it to the chart) in [0.8.3](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.8.3).
Thanks for reporting!

**Comment by thebuggycoder** [comment]
Does `fitInsideTheChart` also work in case of vertical overflow ?

**Comment by imaNNeoFighT** [comment]
No, If you think it is needed to be implemented, make a new issue.
Thanks!

**Comment by thebuggycoder** [comment]
I think it would be a good idea to implement. I'll open a new issue and submit a PR if possible. Cheers!

**Comment by imaNNeoFighT** [comment]
Cheers!
