### ISSUE TITLE
Feature: add a range annotation

### ISSUE THREAD

**Issue by shamilovtim** [imaNNeoFighT/fl_chart#163]
A range annotation can be defined as shading the area between two intervals on the chart. It is depicted [here](https://google.github.io/charts/flutter/example/line_charts/range_annotation_margin) in the Google charts library. In our case we'll be doing several vertical annotations with no labels, depicted here:

<img width="363" alt="Screen Shot 2020-01-10 at 2 28 55 PM" src="https://user-images.githubusercontent.com/3495974/72270998-13480200-35f4-11ea-803c-328050a9a0df.png">

**Comment by imaNNeoFighT** [comment]
Fixed in [0.7.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.7.0)
