### ISSUE TITLE
Feature: add the ability for FLline to be dashed

### ISSUE THREAD

**Issue by shamilovtim** [imaNNeoFighT/fl_chart#164]
Adding the ability for an FLline to be dashed. Flutter_charts offers a [dashFunction](https://google.github.io/charts/flutter/example/line_charts/dash_pattern) which takes a simple anonymous function that should return a list of numbers `[1,2,3,4]`.  Not sure if this is deal or if there is a better way of handling it. The function they provide allows a lot of flexibility in defining a dash pattern but it adds a little bit of complexity to a simple scenario.

Requirements: any line on the chart should be able to be dashed, including interval lines, data lines and touch indicator line

<img width="348" alt="Screen Shot 2020-01-10 at 2 30 14 PM" src="https://user-images.githubusercontent.com/3495974/72274693-9ff5be80-35fa-11ea-9d3b-5587b363f8fe.png">

**Comment by imaNNeoFighT** [comment]
dashed lines feature is added in [0.8.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.8.0)

**Comment by shamilovtim** [comment]
closed via #171

**Comment by shamilovtim** [comment]
closed via #171
