### ISSUE TITLE
touch tooltip bubble have lot of decimal

### ISSUE THREAD

**Issue by nitneuq33** [imaNNeoFighT/fl_chart#168]
Hello and thank you for your work, I have a little observation when I touch data. During some seconds I have some decimal X.XXXXXXXXXX but after delay data show good value X.X. When I print my data, I have always a good output (X.X). 
![Screenshot_20200116-161335](https://user-images.githubusercontent.com/27624907/72537181-f45ba100-387b-11ea-8bb5-cff527f8d44e.png)

**Comment by imaNNeoFighT** [comment]
Hi, you're welcome,
which version of the `fl_chart` are you using?

**Comment by nitneuq33** [comment]
The last 0.6.3

Le jeu. 16 janv. 2020 à 20:10, iman khoshabi <notifications@github.com> a
écrit :

**Comment by imaNNeoFighT** [comment]
Please check the latest version `0.7.0`

**Comment by nitneuq33** [comment]
Yes ! thank i will check this

Le sam. 18 janv. 2020 à 20:33, iman khoshabi <notifications@github.com> a
écrit :

**Comment by nitneuq33** [comment]
Sorry, after more tests I have always the issue. And little question it's possible to cut negatif shape ? 

![RPReplay-Final1580030785](https://user-images.githubusercontent.com/27624907/73348093-0fb9a980-4289-11ea-888a-59ea28d00e1f.gif)

**Comment by nitneuq33** [comment]
Hello, I need to re-open ta new issue or can I re-open this issue ? 

thank you

**Comment by imaNNeoFighT** [comment]
Hello,
please create a new issue with a clear description and reproducible code.
Thanks!
