### ISSUE TITLE
Axis dimensions titles

### ISSUE THREAD

**Issue by apaolino** [imaNNeoFighT/fl_chart#17]
Hi, thanks for this great package.
Would be good if you could add axis titles options (i.e: "power" on y and "date" on x axis)

**Comment by imaNNeoFighT** [comment]
Hi, your welcome 🙏 ,
would you explain little more?

**Comment by apaolino** [comment]
I've seen that actually you can put titles on axis but only for particular axis values.
Would be useful to have axis to show dimensions (like power or time, or the generic X and Y). 
Them would appear on extreme top of axis (for Y) and extreme right (for X).

**Comment by imaNNeoFighT** [comment]
Aha, let's call it right and top titles, (currently we just have left and bottom),
is it correct?

**Comment by imaNNeoFighT** [comment]
4 day past and you didn't answer yet,
I will close it tomarrow night if there is no respond.

**Comment by Triipaxx** [comment]
It sounds like, he want to add a descriptive title to the x and y axis. Like: "Y-Axis" on y axis and "X-Axis" on x axis. 
I've added such information using text widgets...

**Comment by imaNNeoFighT** [comment]
Aha I think we don't need to implement it in the library, because we can combine logs of widgets together.
