### ISSUE TITLE
slide to show more infomation

### ISSUE THREAD

**Issue by YeFei572** [imaNNeoFighT/fl_chart#172]
I didn't catch any information about slide to show more from the readme, do we have this function?
just like this:
![image](https://media.giphy.com/media/ni7sTQ9Z0hrwPsV287/giphy.gif)

**Comment by imaNNeoFighT** [comment]
Out tooltip is not fully customizable yet.

**Comment by YeFei572** [comment]
Do you have a plan for these?
By the way,  If I want to display data for 30 days, can fl_chart support it?

**Comment by dazza5000** [comment]
How did you get the tooltip to persist after touching it?

**Comment by YeFei572** [comment]
@dazza5000 this pic is from another package repository, I think the UI of that package is not pretty, so I'm going suggest author add the function for this package repository.

**Comment by imaNNeoFighT** [comment]
> Do you have a plan for these?
> By the way, If I want to display data for 30 days, can fl_chart support it?

Sorry for the long delay.
Absolutely we have, but please be patient.
Thanks!

**Comment by zykoikaze** [comment]
Is this function available？

**Comment by imaNNeoFighT** [comment]
Not yet @zykoikaze

**Comment by fvisticot** [comment]
> Is this function available？

Did you speak about zooming / sliding or getting tooltip.
I'm very interested as well to get zooming / sliding support it would be awesome !

**Comment by IliaKhuzhakhmetovRoonyx** [comment]
And i too

**Comment by guigzp** [comment]
Any updates on this?

**Comment by imaNNeoFighT** [comment]
Not yet

**Comment by madatr** [comment]
update?

**Comment by imaNNeoFighT** [comment]
Not yet

**Comment by imaNNeoFighT** [comment]
There is an old open issue like it.
Let's follow scroll, zooming there. #71
