### ISSUE TITLE
Bug: First interval is drawn over top of the border

### ISSUE THREAD

**Issue by shamilovtim** [imaNNeoFighT/fl_chart#174]
When chart interval lines are enabled the very first interval line is being painted over top of the border. One of the two need to be removed because together they form a bug.

<img width="943" alt="Screen Shot 2020-01-20 at 4 52 17 PM" src="https://user-images.githubusercontent.com/3495974/72759957-4b77b380-3ba5-11ea-8439-d02d9f712576.png">

**Comment by imaNNeoFighT** [comment]
I didn't get what exactly did you mean

**Comment by shamilovtim** [comment]
@imaNNeoFighT the first (and last) interval lines are drawn in the same spot as the border. that's why the first line and the last line are red. they're supposed to be grey like the top and bottom border

**Comment by imaNNeoFighT** [comment]
Got it,
I think it's okay because users can prevent to draw the first and the last one manually.

**Comment by shamilovtim** [comment]
I suppose we could just draw borders last? It would take care of the issue

**Comment by imaNNeoFighT** [comment]
No we just can skip the first and the last lines of grid from drawing

**Comment by imaNNeoFighT** [comment]
Hi @shamilovtim 
I think this issue can be closed,
what do you think?

**Comment by shamilovtim** [comment]
No matter the size of the interval the first interval will always be painted on every users chart so every user who has an interval and a border will experience this bug and will need to write code to handle it. If the border is enabled there's no reason to leave it to the user to stop the interval from being draw over top of the border. So I would say it's still valid and still a bug.

**Comment by imaNNeoFighT** [comment]
Okay, it makes sense,
you are completely right.
we will skip the first and last interval,
agree?

**Comment by shamilovtim** [comment]
Yup exactly

**Comment by imaNNeoFighT** [comment]
Thanks!

**Comment by imaNNeoFighT** [comment]
Fixed in [0.8.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.8.1), thanks for reporting.

**Comment by shamilovtim** [comment]
There's a regression where this problem appears again but only for the last border

**Comment by imaNNeoFighT** [comment]
It will be fixed in the new version,
I think we have an issue for this reported by you?

**Comment by shamilovtim** [comment]
@imaNNeoFighT  The other issue caused this regression again, then the other issue got closed.
