### ISSUE TITLE
Providing custom painter for line chart

### ISSUE THREAD

**Issue by mikhailChibel** [imaNNeoFighT/fl_chart#177]
I looked through the code and cannot see if it possible to override or provide custom painter for the line chart, I need to draw arrows instead of lines for one of the data series.

**Comment by shamilovtim** [comment]
if you extend the line painter and `override paint` you should be able to do it

**Comment by mikhailChibel** [comment]
@shamilovtim thanks for assuring that it possible.
For my purpose, I need to show two series, one with normal line and one with arrows, thus overriding the painter will not do that as you can have only one painter per chart. I **solved** my problem by tweaking the logic inside line_chart_painter.dart.
