### ISSUE TITLE
FlDotData show: false does not hide the dot on touch

### ISSUE THREAD

**Issue by shamilovtim** [imaNNeoFighT/fl_chart#180]
Using the touchedSpotIndicator callback:

```dart
    getTouchedSpotIndicator: (LineChartBarData barData, List<int> spotIndexes) {
          return spotIndexes.map((spotIndex) {
            final FlSpot spot = barData.spots[spotIndex];
            if (spot.x == 0 || spot.x == 6) {
              return null;
            }
            return TouchedSpotIndicatorData(
              FlLine(color: TextBlackDark, strokeWidth: 1),
              FlDotData(show: false, dotSize: 0),
            );
          }).toList();
        },
```

1. getTouchedSpotIndicator is poorly named. it should be **set**TouchedSpotIndicator
2. FLDotData `show:false` does not hide the dot. Instead a dotSize of 0 must be set.

**Comment by imaNNeoFighT** [comment]
1. I've seen this pattern a lot (we want to get a value from the user to use it in our black box), and the one that I remember at the moment is in the `getSpanSize` of GridLayoutManager in android, see this [sample](https://stackoverflow.com/a/26907508/3543738)
2. If it is, it's a bug, thanks for reporting.

**Comment by imaNNeoFighT** [comment]
Fixed in [0.8.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.8.1), thanks for reporting.

**Comment by HieuNguyennd96** [comment]
Using the touchedSpotIndicator callback:

`return spotIndexes.map((e) {
            return TouchedSpotIndicatorData(
              FlLine(color: AppColors.spindle, strokeWidth: 1.0),
              FlDotData(
                show: true,
                checkToShowDot: (spot, data) {
                  if (spot.x == 1.0 || spot.x == 2.0) {
                    return false;
                  }
                  return true;
                },
              ),
            );
          }).toList();`

**Comment by imaNNeoFighT** [comment]
Are you sure you are returning false in 1.0 and 2.0?
Can you verify it by printing some logs?

**Comment by HieuNguyennd96** [comment]
I'm very sure. I've tried return false in all cases but dot doesn't hide 
```
return spotIndexes.map((e) {
            return TouchedSpotIndicatorData(
              FlLine(color: AppColors.spindle, strokeWidth: 1.0),
              FlDotData(
                show: false,
                checkToShowDot: (spot, data) {
                  return false;
                },
              ),
            );
          }).toList();
```

**Comment by HieuNguyennd96** [comment]
this is all my graph

**Comment by imaNNeoFighT** [comment]
Please give me a complete reproducible code (a complete `main.dart` file)
