### ISSUE TITLE
Hiding the touch tooltip while showing the touch line should be a setting

### ISSUE THREAD

**Issue by shamilovtim** [imaNNeoFighT/fl_chart#181]
Right now to hide the tooltip but show the line it's required to pass an empty callback:
```dart
 touchTooltipData: LineTouchTooltipData(
          getTooltipItems: (List<LineBarSpot> touchedBarSpots) {
            return touchedBarSpots.map((flSpot) {}).toList();
          },
        ),
```

Leaving aside that there's no way to declaratively style the line and the tooltip without callbacks, there's also no way to declaratively hide the tooltip without providing an empty callback to `getTooltipItems`. There should be a `showTooltip` setting that defaults to `true` which allows to easily shutoff the tooltip without a callback.

**Comment by darran-kelinske-fivestars** [comment]
Did you make a PR for this?

**Comment by shamilovtim** [comment]
@darran-kelinske-fivestars nope you're welcome to take a stab at it. i have a couple of other ones i'm working on

**Comment by imaNNeoFighT** [comment]
I think it is possible at the moment, by returning null in `getTooltipItems` of  the [LineTouchTooltipData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetouchtooltipdata).
@shamilovtim am I correct?

**Comment by shamilovtim** [comment]
Yeah the code up above does this

**Comment by imaNNeoFighT** [comment]
Then I'm gonna close it.
Thanks!
