### ISSUE TITLE
Chart height is not displayed correctly

### ISSUE THREAD

**Issue by master11641** [imaNNeoFighT/fl_chart#182]
BarChart is not displayed correctly color and height  when data has much difference .The following data are Related to the attached photo
0.0
 2.0
 84.0
 1400.0
 0.0
 0.0
 1809.0
All BarChartGroupData  have one BarChartRodStackItem with one color(Green) like this
BarChartRodStackItem(0, value, Color(0xff2bdb90))
![Screenshot_2020-01-26-19-45-36-990_com example fitness_flutter](https://user-images.githubusercontent.com/31819280/73138273-191ef800-4076-11ea-8709-5f2b3e9db762.png)

**Comment by imaNNeoFighT** [comment]
Hi, sorry for the delay,
may I ask you to provide a reproducible code?

**Comment by imaNNeoFighT** [comment]
It's gonna be closed tomorrow if you don't provide a reproducible code.
Thanks!
