### ISSUE TITLE
FlSpot with dynamic data

### ISSUE THREAD

**Issue by vineetpandit90** [imaNNeoFighT/fl_chart#188]
Flspot is not taking dynamic data. this require const data to initialize Flspot.
How to use dynamic y axis data.

**Comment by vineetpandit90** [comment]
solved

**Comment by vineetpandit90** [comment]
solved

**Comment by dhMagicTech** [comment]
pls teach me

**Comment by duhamelstuff** [comment]
> solved

Hello, how did you solved ?
