### ISSUE TITLE
How to clear LineChartBarData spots?

### ISSUE THREAD

**Issue by kashlo** [imaNNeoFighT/fl_chart#20]
when I setState and change FlSpot list data the old chart stays on screen, and the new data renders above

**Comment by imaNNeoFighT** [comment]
In which version you got this issue?

**Comment by kashlo** [comment]
> In which version you got this issue?

latest one 0.0.7

**Comment by imaNNeoFighT** [comment]
Ok I will check it

**Comment by kashlo** [comment]
Sorry, my mistake, was not clearing the list

**Comment by imaNNeoFighT** [comment]
Sure!
Thanks for your update.
