### ISSUE TITLE
Remove the line below indicator spot

### ISSUE THREAD

**Issue by tuanha2000vn** [imaNNeoFighT/fl_chart#205]
How do you remove this?
![image](https://user-images.githubusercontent.com/2765517/75024252-add91200-54cb-11ea-8017-0aacbb5cb714.png)

Thank you for the wonderful package. Really impressed.

**Comment by imaNNeoFighT** [comment]
Hi, you can customize the color and width of the line using `getTouchedSpotIndicator` inside the [LineChartData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetouchdata-read-about-touch-handling), check this code:
```
lineTouchData: LineTouchData(
        getTouchedSpotIndicator: (barData, spotIndexes) {
          return spotIndexes
              .map((e) => TouchedSpotIndicatorData(
                    FlLine(
                      color: Colors.transparent,
                    ),
                    FlDotData(
                      show: true,
                      dotColor: Colors.purple,
                      dotSize: 4,
                    ),
                  ))
              .toList();
        },
      ),
```
I know it is not well placed, and it's confusing, but please use transparent color as a hot fix, I will find a better way to do that.
Thanks!

**Comment by tuanha2000vn** [comment]
![Screenshot_1582342962](https://user-images.githubusercontent.com/2765517/75085858-170a6500-5560-11ea-9d8e-938794d309da.png)

Thank you so much, it look better now.

**Comment by imaNNeoFighT** [comment]
NoProblem
