### ISSUE TITLE
Issues controlling right margin on "single bar" barChart

### ISSUE THREAD

**Issue by mic-appiani** [imaNNeoFighT/fl_chart#209]
Hello, i'm trying to use a simple bar chart with only one bar and i'm having issues controlling the right margin (didn't find a way to move it tight to the chart to maximise space for the "Test" area, please see screenshot). Using fl_chart 0.8.1.

Can anyone suggest a way to reduce the right whitespace in the chart widget in this case?

![Screenshot_1582714196](https://user-images.githubusercontent.com/38383171/75338104-7df48a80-588e-11ea-9a4a-e95bdfa04237.png)

Chart code:
```dart
class NormalbarChart extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BarChart(
      BarChartData(
        borderData: FlBorderData(show: false),
        titlesData: FlTitlesData(
            show: true,
            leftTitles: SideTitles(
              showTitles: true,
              getTitles: (double value) => (value.toInt()).toString(),
              interval: 25,
              reservedSize: 30,
            ),
            bottomTitles: SideTitles(showTitles: false),
        ),
        barGroups: [
          BarChartGroupData(
            x: 0,
            barRods: [
              BarChartRodData(
                  y: 350.0, width: 50.0, color: Colors.red.shade600)
            ],
          ),
        ],
      ),
      swapAnimationDuration: Duration(milliseconds: 500),
    );
  }
}
```

Layout code:
```dart
class LiveStats extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Live Stats"),
      ),
      body: Center(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            Flexible(
                child: NormalbarChart()),
            Expanded(
              child: Column(
                children: <Widget>[Text("Test")],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by imaNNeoFighT** [comment]
What's the problem exactly?

**Comment by mic-appiani** [comment]
I don't understand why the barchart doesn't flex closer to the actual bar but leaves such a large white space, and if there's a way to change it.
Forcing the chart in a Container with a fixed width works fine.

**Comment by imaNNeoFighT** [comment]
Did you try using `alignment` in your `BarChart`?

**Comment by mic-appiani** [comment]
Yes, the bar moves around and aligns correctly but the dimensions of tha main "box" of the chart are the same.
![Screenshot_1582809082](https://user-images.githubusercontent.com/38383171/75448302-398aec80-596b-11ea-8dce-0347084570f2.png)

**Comment by imaNNeoFighT** [comment]
You can size it manually, we have to implement it in this way (at least at the moment we have to).

**Comment by mic-appiani** [comment]
Thanks for clarifying this is the expected behavior! I will close the issue

**Comment by imaNNeoFighT** [comment]
No problem.
