### ISSUE TITLE
Inverted y axis

### ISSUE THREAD

**Issue by Triipaxx** [imaNNeoFighT/fl_chart#21]
Is it possible to add an invert axis feature, so you can have a y axis with an origin in the top left corner. This would also render the x axis + horizontal titles to the top. 
I currently somehow achieved it by setting minY to the negative max value and multiply each value with -1. But the x axis and horizontal values are still on the bottom.

**Comment by imaNNeoFighT** [comment]
I think if we support top and right titles you can solve your issue,
Currently we support onluy bottom and left titles, but if we support top and right, you can clear bottom titles and enable top imstead, then you can invert your chart with this solution :
Imagine you have 0 to 10 values on the y axis, 
minY = 0,
maxY = 10,
And convert your points y values:
point.y = maxY - point.y
, and also draw left titles with reversed values.

**Comment by Triipaxx** [comment]
Yes, that would help. Are you planning to add support for top and right titles?

**Comment by imaNNeoFighT** [comment]
Yes, we can have this.

**Comment by imaNNeoFighT** [comment]
I will mark this issue as a enhancement to add top and right titles

**Comment by Triipaxx** [comment]
Awesome, thank you!
Any plans in which version you probably add this feature?

**Comment by imaNNeoFighT** [comment]
No idea about that but it will add as soons as possible (maybe next versiom)

**Comment by imaNNeoFighT** [comment]
Also pull requests are welcome, 
I will be happy if the community contribute on the library

**Comment by imaNNeoFighT** [comment]
Hi dude, how's it going?
I did it in [0.1.3](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.1.3) version, check it out.
[<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_6.png" width="300" >](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#sample-6---reversed-source-code),
I close this Issue,
Thanks for your patience.
