### ISSUE TITLE
Chart touch events

### ISSUE THREAD

**Issue by WildOrangutan** [imaNNeoFighT/fl_chart#213]
Hi!

I'm in a need of a chart library, that supports touch events, when they occur on the chart (not on a line or point). 

My requirement is to add points to a chart in more interactive manner. For example, if user clicks on a chart, I would like to add a point on that position.

So basically, I would need some basic callbacks (similar to `GestureDetector`), that also provide you with positional data translated to chart's domain. For example, callback that provides where on x and y axis click happened.

Are there any plans for implementing this?
How hard would it be to support this?

**Comment by imaNNeoFighT** [comment]
Hi, I encourage you to read the docs, 
and also check this sample, we've implemented tap gesture.
I promise we will improve it in the future, I think it's enough for your use-case for now.
Thanks!

##### Sample 2 ([Source Code](/example/lib/scatter_chart/samples/scatter_chart_sample2.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/scatter_chart/scatter_chart_sample_2.gif" width="300" >
