### ISSUE TITLE
Feature Request: Using IconData as a SideTitle

### ISSUE THREAD

**Issue by Kuoyhout** [imaNNeoFighT/fl_chart#215]
Is there some way I can use icon data as a side title instead of a string?

Ex: `
SideTitles(
  getTitles: (double value){
    return Icons.face
  }
)
`

**Comment by imaNNeoFighT** [comment]
#184 Is it work for you?

**Comment by Kuoyhout** [comment]
@imaNNeoFighT No, that's not what I mean. I want to change the '6.0, 4.0, 2.0, 0.0' on the left to a list of icons.

**Comment by imaNNeoFighT** [comment]
Got it

**Comment by shamilovtim** [comment]
this exists in the latest PR if 1) you're happy having the icons aligned along the border 2) you're providing the icons as SVGs or images. 

when i was investigating adding a flutter "Icon" widget to the chart it was just weird. flutter Icons are neither images nor vectors. they're one glyph of a font. I find it quite abnormal and difficult to work it.

**Comment by shamilovtim** [comment]
if you're not happy having them aligned along the border a PR to providing padding should be very very simple

**Comment by imaNNeoFighT** [comment]
@shamilovtim we can also support having image and vectors instead of text titles,
but as you said, there is a trick to have it at the moment.
Thanks for explaining.

**Comment by Kuoyhout** [comment]
@shamilovtim Yes, I don't want them aligned along the border. I want it to position just like the text title.

I managed to do this by wrapping the **Chart** and a **Column** (icon on the left) or **Row** (icon on the bottom) of icons in a **Row** (icon on the left) or **Column** (icon on the bottom)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-15 at 07 40 26](https://user-images.githubusercontent.com/5210467/76693285-12375d80-6695-11ea-9dfa-0a0f7d48f815.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-15 at 07 40 31](https://user-images.githubusercontent.com/5210467/76693286-15324e00-6695-11ea-808c-a2364bc330b2.png)

**Comment by MihailovDev** [comment]
Hey, can someone point to a snippet in how I can achieve having icons/images instead of string titles?

**Comment by sawirricardo** [comment]
Hi, it has been a year, any updates on this? Thank you.

**Comment by imaNNeoFighT** [comment]
Good news.
Please follow #183.
