### ISSUE TITLE
BarChart X axis title shows overflow?

### ISSUE THREAD

**Issue by mrmyn** [imaNNeoFighT/fl_chart#217]
If the title at the bottom of the histogram is too long, the display overlaps.
<img width="374" alt="Xnip2020-03-04_21-35-06" src="https://user-images.githubusercontent.com/20763281/75884565-06ab9180-5e60-11ea-8a4b-4eae535231be.png">

**Comment by mrmyn** [comment]
I still try to modify the interval and margin of SideTitles.

**Comment by mrmyn** [comment]
For example, I have 10 pieces of data, and I just want it to show 5 titles or less?

**Comment by mrmyn** [comment]
Sorry, I still have a problem with the pie chart. For example, I have 10 pieces of data and 3 of them are 0. Then the 3 pieces of 0 data only show a 0 in the pie chart. How can I solve it?
<img width="384" alt="Xnip2020-03-04_21-49-11" src="https://user-images.githubusercontent.com/20763281/75885743-057b6400-5e62-11ea-8c2d-9a70946aae63.png">

**Comment by imaNNeoFighT** [comment]
Dude, I can't understand anything from screenshots.
Please provide me a reproducible code, it helps me to find out the bug ASAP.
Thanks!

**Comment by imaNNeoFighT** [comment]
It's gonna be closed tomorrow if you don't provide a reproducible code.
Regards!
