### ISSUE TITLE
Bar Tooltip Indicators - Option to remove decimal point

### ISSUE THREAD

**Issue by joaowd** [imaNNeoFighT/fl_chart#218]
This is a pretty simple request, I would like to have the option to hide/remove the decimal points:

![Screenshot 2020-03-05 at 13 08 43](https://user-images.githubusercontent.com/10066011/75984660-b7f30b80-5ee2-11ea-90cd-283d975b792c.png)

And while I'm at it, the option to change the tooltip textStyle would be helpful.

**Comment by imaNNeoFighT** [comment]
Hi buddy
Use `getTooltipItems` inside the [LineTouchTooltipData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetouchtooltipdata) :
```dart
LineChartData(
   lineTouchData: LineTouchData(
      touchTooltipData: LineTouchTooltipData(
         tooltipBgColor: Colors.blueGrey.withOpacity(0.8),
         getTooltipItems: (List<LineBarSpot> spots) {
            return spots.map((LineBarSpot spot) {
               return LineTooltipItem(
                  spot.y.toInt().toString(), //any text you want to show
                  const TextStyle(color: Colors.black) //any style you want
               );
            }).toList();
         }
      ),
   )
)
```

**Comment by joaowd** [comment]
Hello,

I'm working with bar chart not with line charts

**Comment by imaNNeoFighT** [comment]
Nope!
