### ISSUE TITLE
Custom zero line width

### ISSUE THREAD

**Issue by Triipaxx** [imaNNeoFighT/fl_chart#22]
Is it possible to add a custom zero line width parameter to the FlGridData wich would render the zero line a bit more prominent. 

I currently stack my chart and draw a thicker divider using positioned widget to simulate that. But it is not very handy for dynamic charts.

Edit: oh and, is there a built in way to set a custom background color for the chart? Currently i use the stack approach described above.

**Comment by imaNNeoFighT** [comment]
Good odea, 
In the 0.0.7 version we have ExtraLines in LineChartData to draw some straight lines on the chart, you can use them until we add this feature.
Thanks!

**Comment by Triipaxx** [comment]
You're welcome :)
Thank you for this awesome library

**Comment by imaNNeoFighT** [comment]
Yhank you too,
It's my pleasure :)

**Comment by Triipaxx** [comment]
I tried the ExtraLine feature and it is a much better approach! Thank you for the tip!

**Comment by Triipaxx** [comment]
Do you have a feature to add a custom color as a grid background?

**Comment by imaNNeoFighT** [comment]
Yes its a good approach
, by the way we shoudl have a customizable background grid.

**Comment by imaNNeoFighT** [comment]
What do you mean?

**Comment by Triipaxx** [comment]
I mean, a color which is used as a background color for the grid. Which is drawn inside the border.

**Comment by Triipaxx** [comment]
Currently i use a container with a color and stack the chart on top. Using a positioned widget i can align my container with the chart.

![Simulator Screen Shot - iPhone Xs - 2019-06-13 at 19 36 25](https://user-images.githubusercontent.com/1990219/59454748-10452300-8e13-11e9-952e-40755f7e86b1.png)

**Comment by imaNNeoFighT** [comment]
Aha got it,
Sure we can but this is low priority, 
I'm trying to add interactivity to all charts, and I have to focus on it, 
But don't worry we can have this ASAP,
I ask you if you are interested to contribute and have enought time, let's add it and make your PR,
But before that if you were intrested to do that let me know to talking about how implement it

**Comment by Triipaxx** [comment]
Sure, i'm interested to contribute on that topic.

**Comment by imaNNeoFighT** [comment]
Great
Take a look on the code.

**Comment by Triipaxx** [comment]
i already did and already implemented a way. How do we discuss my thoughts without spamming this issue? 
I never contributed on a github project so far...

**Comment by imaNNeoFighT** [comment]
I think we can chat on twitter or whatsapp or telegram

**Comment by Triipaxx** [comment]
I've sent you an email to you gmail. Let's start with that for now.

**Comment by houqinzhe** [comment]
study

**Comment by imaNNeoFighT** [comment]
@houqinzhe what?

**Comment by imaNNeoFighT** [comment]
added in [0.0.8](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.0.8),
check it out
cheers!
