### ISSUE TITLE
Barchart (SideTitles) - Very bad performance

### ISSUE THREAD

**Issue by joaowd** [imaNNeoFighT/fl_chart#220]
When Left or Right SideTitles are visible (only this two), the performance of the view decreases **a lot**.

- Tested in iOS (iPad)

Very weird bug 🤔

**Comment by imaNNeoFighT** [comment]
I think you should increase the interval between titles (let me know if it's worked).
also don't forget to provide a reproducible code, It's crucial to find the bug.
Thanks!

**Comment by joaowd** [comment]
Code: https://gist.github.com/joaowd/e5993b2a0c90fac4c934acc01af7b1f9

![IMG_0036](https://user-images.githubusercontent.com/10066011/76210073-41644f80-61fb-11ea-8f94-f8d6d5893479.jpg)

**Comment by joaowd** [comment]
I don't have that many intervals, but the performance of the view is really bad.

**Comment by imaNNeoFighT** [comment]
Okay then provide me a full reproducible code (including main function)

**Comment by imaNNeoFighT** [comment]
It's gonna be closed tomorrow if you don't provide a fully reproducible code (including main function)

> Code: https://gist.github.com/joaowd/e5993b2a0c90fac4c934acc01af7b1f9
> 
> ![IMG_0036](https://user-images.githubusercontent.com/10066011/76210073-41644f80-61fb-11ea-8f94-f8d6d5893479.jpg)

I couldn't run this code because there are some invalid imports:
```dart
import 'package:nexso/utils/helpers/app_colors.dart';
import 'package:nexso/utils/helpers/app_text_styles.dart';
```
