### ISSUE TITLE
Get an option to remove all the grids

### ISSUE THREAD

**Issue by RedManBrasil** [imaNNeoFighT/fl_chart#223]
Hey, I'm really enjoying this package you made. But I'm finding very annoying that there isn't an option to just set all grids to false and, even setting off each one them manually, doesn't actually remove all of them. As shown below, there is still this grid, even after setting all of them off. There is a way to set this one off, without editing the package code? This is very important for me, since I'm looking for the most minimalist linear chart I can do.

<img width="318" alt="Screen Shot 2020-03-08 at 23 21 39" src="https://user-images.githubusercontent.com/22911992/76172192-a97f4b00-6193-11ea-91e5-dd97316b043a.png">

**Comment by imaNNeoFighT** [comment]
It's my pleasure, thanks.
There is a property called `gridData` inside [LineChartData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartdata),
did you check it?

**Comment by RedManBrasil** [comment]
Great!
