### ISSUE TITLE
Enable 'fitInsideTheChart' to support vertical tooltip overflow as well

### ISSUE THREAD

**Issue by thebuggycoder** [imaNNeoFighT/fl_chart#225]
Currently `fitInsideTheChart` restricts the chart tooltip bubble inside the chart bounds only if it overflows horizontally. Might be a good idea to add the same feature for vertical overflow as well.

Similar to #159 .

![image](https://user-images.githubusercontent.com/48513642/76220523-a2ad1280-623d-11ea-8553-095b0552571d.png)

**Comment by imaNNeoFighT** [comment]
As I remember you were supposed to try to implement it, right?

**Comment by thebuggycoder** [comment]
Yes. Will try to send a PR as soon as possible 😄

**Comment by imaNNeoFighT** [comment]
Thanks!

**Comment by imaNNeoFighT** [comment]
Added `fitInsideVertically` property in [0.8.4](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.8.4),
check it out.
Thanks for reporting, and for sure your help in implementing.
