### ISSUE TITLE
Clip the chart within it's border

### ISSUE THREAD

**Issue by onliner10** [imaNNeoFighT/fl_chart#228]
**Is your feature request relasted to a problem? Please describe.**
I want to present series which can have huge outliers , e.g. single value skyrocketing into thousands, where majority is in the -10 to 10 range. This makes the chart unreadable and impossibile to read important details. 

See the picture:
![skyrocket](https://user-images.githubusercontent.com/4688431/76517366-78d23680-645d-11ea-8af7-6ca6f4eb9022.png)

**Describe the solution you'd like**
I'd like to be able to "zoom in" and clip series within borders. Currently, we can restrain Y axis but the line still goes out of bound (as well as the tooltips).
![clipped](https://user-images.githubusercontent.com/4688431/76517422-956e6e80-645d-11ea-9d8a-a2248fefaf77.png)

Ideally, there should also be an indicator where line goes out of bound stating the outlier value (the thousands). If possibile, the tooltips should also be restrained within chart borders.

**Comment by imaNNeoFighT** [comment]
There is no way to represent both large, and small differences in a chart at once,
I think you need the `zoom feature`, to represent a portion of the chart.
The `zoom feature` is in our way to do.

**Comment by onliner10** [comment]
Actually, what I was thinking about is:
1. Keep lines within the range set by minY and minY
2. When line goes out of bound, give visual indicator of it's value

Something like this (just a rough sketch to illustrate my point)
![prop](https://user-images.githubusercontent.com/4688431/76521277-cbfbb780-6464-11ea-9ab1-3b604256e2d6.png)

Btw. Let me know if I can be of help, I'd be very eager to work with you on this feature

**Comment by imaNNeoFighT** [comment]
There is a property called `clipToBorder` in the [LineChartData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartdata), did you use it?

**Comment by onliner10** [comment]
Yes, but the lines were still going out of bounds. The second picture was taken from a chart with `clipToBorder` set to true.

Btw @imaNNeoFighT what do you think about implementing the indicators?

**Comment by imaNNeoFighT** [comment]
I think the indicator is an edge case and we do not handle the edge cases (you can do it in a separate fork).
could you please give me a reproducible code?

**Comment by onliner10** [comment]
Actually, it's enough to modify your examples giving one `FlSpot` value of e.g. 30.
![clipped](https://user-images.githubusercontent.com/4688431/76540292-3e2ec500-6482-11ea-939d-d9ec1dbb6dbf.png)

If you prefer a code sample though, I can prepare it for you

**Comment by imaNNeoFighT** [comment]
Got it, It's a duplicate issue, check #214.

**Comment by imaNNeoFighT** [comment]
Fixed in [0.8.4](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.8.4),
Thanks for reporting.
