### ISSUE TITLE
Empty space between the different stacked values

### ISSUE THREAD

**Issue by Dohan810** [imaNNeoFighT/fl_chart#229]
In my app there are 3 different y-axes namely Earn, Paid, Not Used...... and then the days of the week on the x-axes... I was curious about if there is a property that would insert a space or an empty section between the 3 y-axes values...

**Comment by imaNNeoFighT** [comment]
could you please make a representation of your idea?
I didn't fully get it.
Regards!

**Comment by Dohan810** [comment]
![image](https://user-images.githubusercontent.com/49713545/76589830-082a2900-64f4-11ea-9861-244df02e5009.png)

This is how I want it to look...

![image](https://user-images.githubusercontent.com/49713545/76589878-390a5e00-64f4-11ea-9d0c-6d8c5d9e09a7.png)

This is how it looks at the moment

**Comment by imaNNeoFighT** [comment]
We don't have this feature at the moment,
you can let this issue be open,
people can vote this buy thumb-up.
Thanks!

**Comment by Dohan810** [comment]
Is there a way to change the default colour to the background colour that you can simulate a space...Because I know if you change the values and you skip a value and start a new stack the default colour is blue

**Comment by imaNNeoFighT** [comment]
The default color is the [BarChartRodData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#barchartroddata)`.color` property.

**Comment by imaNNeoFighT** [comment]
I'm pretty sure it works, but you don't have rounded corners effect.
