### ISSUE TITLE
Changing dotColor: color

### ISSUE THREAD

**Issue by sudheer-palaparambil** [imaNNeoFighT/fl_chart#233]
Hi,

  Is there any way to change the color value of dotColor depends upon the underlying FlSpot data ? 
  FlDotData(show: true, **dotColor**: Colors.red, dotSize: 3.0). 

  Thanks for the great package.

**Comment by imaNNeoFighT** [comment]
Hi, we don't have this feature at the moment.
Stay tuned!
Thanks for suggesting.

**Comment by imaNNeoFighT** [comment]
[0.9.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.9.0) -> 
* Added strokeWidth, getStrokeColor, getDotColor in the FlDotData, also removed dotColor from it (you should use getDotColor instead, it gives you more customizability), now we have more customizability on FlDotData, check line_chart_sample3, and line_chart_sample5
