### ISSUE TITLE
Add a git hook to enforce dartfmt on the project and/or lint

### ISSUE THREAD

**Issue by shamilovtim** [imaNNeoFighT/fl_chart#239]
New PRs are causing whitespace issues due to formatter requirements not being followed. It's looking like a git hook call to dart formatter is going to be necessary and possibly linting

**Comment by imaNNeoFighT** [comment]
Thanks,
we will consider it ASAP.

**Comment by shamilovtim** [comment]
@imaNNeoFighT 

see https://github.com/bltavares/actions/tree/master/dartfmt. it can be setup as a github action to enforce formatting

**Comment by imaNNeoFighT** [comment]
I'm looking for an Action that checks your changes, and if you didn't format the code, it fails.
It's not good, but if we didn't find anything we will use it.
Thanks!

**Comment by imaNNeoFighT** [comment]
miss click :)

**Comment by shamilovtim** [comment]
We can just make one

**Comment by imaNNeoFighT** [comment]
Absolutely we can :)

**Comment by mhmdanas** [comment]
@imaNNeoFighT I have the command that you want! It is `flutter format --set-exit-if-changed --dry-run lib test example`. It will check if the the code is formatted correctly, and if it is not, it will return exit code 1.

I'd like to open a PR for this, but should I create a new workflow or can I add it to the existing `test.yml` workflow?

**Comment by mhmdanas** [comment]
By the way, I see that you setup Java in the `test.yml` workflow. I also used to setup Java, but then I removed it and the workflow continued to work correctly. I think it's not necessary because it's only useful if you want to build an APK on GitHub Actions, which doesn't seem to be the case. Removing it will save some time on the workflow!

**Comment by imaNNeoFighT** [comment]
Hi @mhmdanas ,
I don't know what java is doing,
I just copied it from Github's actions marketplace.
Let's have it in a separate workflow for code style checking (code format, or any linter rules).

**Comment by mhmdanas** [comment]
I also didn't know what Java is doing, so I removed it in my project and it continued to work just fine. So I believe removing it is better for now. What do you think about this @imaNNeoFighT ?

Anyway, I'm going to open a PR for this issue soon.

**Comment by mhmdanas** [comment]
BTW, the line length should be 100, right?

**Comment by imaNNeoFighT** [comment]
Does it have any cons, why you want to remove it?
I think it is 100, @shamilovtim  am I correct?

**Comment by mhmdanas** [comment]
No cons in particular, it would just reduce the workflow time.

**Comment by imaNNeoFighT** [comment]
Ok remove it.

**Comment by mhmdanas** [comment]
OK, PR coming up today or tomorrow!

**Comment by imaNNeoFighT** [comment]
I'm waiting for it

**Comment by shamilovtim** [comment]
Yes 100!

**Comment by imaNNeoFighT** [comment]
Thanks @shamilovtim!
That's promised formatter is coming man :)))
