### ISSUE TITLE
Widget as label in Piechart

### ISSUE THREAD

**Issue by adrianvintu** [imaNNeoFighT/fl_chart#249]
Instead of the percentages, I would like to add my own widget.

I see from the code it only takes strings for now.

Will you make a change here?

**Comment by imaNNeoFighT** [comment]
Hi,
It's very hard to have a widget inside our drawing engine, the canvas.
But we are trying to find a way to do that.
Stay tuned.
Thanks!

**Comment by adrianvintu** [comment]
Hi @imaNNeoFighT , i just took a look at the Tooltip class from flutter, they seem to do it very easily.

Maybe it's the same in your case?

The magic seems to be done by some Overlay class.

**Comment by imaNNeoFighT** [comment]
Yes, we can have a stack and overlay widgets, but I don't know how performant is it.

**Comment by adrianvintu** [comment]
Ah, ok. Haven't played with it much.

**Comment by imaNNeoFighT** [comment]
I close this issue because there is a duplicate one here: #72.
Thanks!
