### ISSUE TITLE
Bug: On some spots the touchline is not appearing but the tooltip is

### ISSUE THREAD

**Issue by shamilovtim** [imaNNeoFighT/fl_chart#250]
Tap on the first spot if it's near a border and it's currently only showing the tooltip but not the line.

<img width="437" alt="Screen Shot 2020-03-19 at 2 07 12 PM" src="https://user-images.githubusercontent.com/3495974/77099930-222fa400-69eb-11ea-924f-f738bde4fb75.png">

<img width="439" alt="Screen Shot 2020-03-19 at 2 10 27 PM" src="https://user-images.githubusercontent.com/3495974/77100090-6d49b700-69eb-11ea-99ef-532e0d686e69.png">

Repro is sample 8

**Comment by shamilovtim** [comment]
It's not first / last actually. Here it is happening on a random spot on the chart. I'm not sure what the problem is. It seems pretty random. But I know this never happened until the last couple of versions.

<img width="274" alt="Screen Shot 2020-03-19 at 3 09 58 PM" src="https://user-images.githubusercontent.com/3495974/77105292-ce758880-69f3-11ea-8827-3a76f01135e2.png">

**Comment by imaNNeoFighT** [comment]
Hi, It's not a bug.
There is a code to prevent drawing touch spots (line and dot) on x 0 and 6, that leads to this problem,
I've removed it, check it in this [commit](https://github.com/imaNNeoFighT/fl_chart/commit/0723e149028305a0fbc8e14ee3b9f6daa5f0861f).
I think you wrote that code in the initialization of line chart sample 8,  :)
Thanks for reporting!

**Comment by shamilovtim** [comment]
Oh no 😂
