### ISSUE TITLE
Horizontal Line null call when HorizontalLineLabel is not specified

### ISSUE THREAD

**Issue by andrewjallenuoft** [imaNNeoFighT/fl_chart#251]
**Describe the bug**
If you create a line chart with a HorizontalLine in ExtraLinesData without specifying a HorizontalLineLabel for this line, then it will cause a null call in fl_chart >= 0.8.5. Of course, this can be circumvented by specifying a line label with a resolver returning an empty string.

The error is as follows:
```
The following NoSuchMethodError was thrown building LineChart(duration: 150ms, dirty, dependencies: [MediaQuery], state: _LineChartState#25ae0(ticker active)):
The getter 'padding' was called on null.
Receiver: null
Tried calling: padding

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      HorizontalLineLabel.lerp (package:fl_chart/src/chart/line_chart/line_chart_data.dart:759:34)
#2      HorizontalLine.lerp (package:fl_chart/src/chart/line_chart/line_chart_data.dart:655:34)
#3      lerpHorizontalLineList.<anonymous closure> (package:fl_chart/src/utils/lerp.dart:61:29)
#4      new List.generate (dart:core/list.dart:165:28)
...
```

**To Reproduce**
Create a horizontal line in a line chart without specifying the label parameter. For example, a line chart with this:

`extraLinesData: ExtraLinesData(horizontalLines: [HorizontalLine(y: 10.0, color: Colors.green, strokeWidth: 3)]),`

**Versions**
Flutter: Lastest stable
FlChart: 0.8.5

**Comment by imaNNeoFighT** [comment]
Fixed in [0.8.6](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.8.6),
Thanks for reporting!
