### ISSUE TITLE
Bug in 0.8.6 label always appearing on lines even when not provided

### ISSUE THREAD

**Issue by shamilovtim** [imaNNeoFighT/fl_chart#256]
The labels on lines are now appearing by default without being provided. To make them go away I have to provide:

```dart
label: VerticalLineLabel(labelResolver: (line) {
              return '';
            })
```

![image](https://user-images.githubusercontent.com/3495974/77228312-d13fbd00-6b5c-11ea-8dd0-86bf22ef5976.png)

**Comment by imaNNeoFighT** [comment]
Added `show` property in the [VerticalLineLabel](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#verticallinelabel), and [HorizontalLineLabel](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#horizontallinelabel). 
And the default value is `false`, check it out in [0.8.7](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.8.7).
Thanks for reporting!
