### ISSUE TITLE
example 3 for Linechart is not working anymore

### ISSUE THREAD

**Issue by digitalwert-developer** [imaNNeoFighT/fl_chart#257]
**Describe the bug**
LineChart is not of Type Widget. See: https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample3.dart

**To Reproduce**
take example Widget with current fl_chart version and copy paste it into a project. :)
I really need some Quick Start Template otherwise this is not working out as a graph lib for me :)

**Screenshots**
[screenshot](https://www.dwpic.de/rh/tNbpkHF9hoUsevb4X5JMibki05qRgvY7YkG16nDJdsYNbppUpAmGlrUfzcA4lr42hlewApk00Zru1q20pnU49l0s3JSv1y8GsPLt.png)

**Versions**
 Flutter: stable latest
FL_chart:  ^0.2.0

**Comment by imaNNeoFighT** [comment]
Please use our latest version [0.8.7](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.8.7).
Thanks!
