### ISSUE TITLE
Bug in utils "getDefaultSize" function

### ISSUE THREAD

**Issue by BouncyButton** [imaNNeoFighT/fl_chart#258]
I have no time to submit a fix myself, but I found an error in utils/utils.dart:

```
/// Returns a default size based on the screen size
/// that is a 70% scaled square based on the screen.
Size getDefaultSize(Size screenSize) {
  Size resultSize;
  if (screenSize.width < screenSize.height) {
    resultSize = Size(screenSize.width, screenSize.width);
  } else if (screenSize.height < screenSize.width) {
    resultSize = Size(screenSize.height, screenSize.height);
  }
  return resultSize * 0.7;
}
```

There is a missing case whenever screenSize.height is equal to screenSize.width. This is possible for example in desktop browsers. The missing case causes a NoSuchMethodError, since `resultSize` is `null.`

**Comment by imaNNeoFighT** [comment]
Fixed in [0.8.7](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.8.7), also I've added a test case for it.
Thanks for reporting!
