### ISSUE TITLE
rotate text in BarTooltipItem

### ISSUE THREAD

**Issue by alexodus** [imaNNeoFighT/fl_chart#260]
**Is your feature request relasted to a problem? Please describe.**
If number is large it, overlaps over the bar

**Describe the solution you'd like**
I'd like to have an rotateAngle property also for BarTooltipItem

**Additional context**
![image](https://user-images.githubusercontent.com/2721510/77415743-31379d00-6dc3-11ea-88f4-08a4da5349a9.png)

**Comment by imaNNeoFighT** [comment]
Thanks for reporting,
we will add it ASAP.
Thanks!

**Comment by alexodus** [comment]
Hi @imaNNeoFighT , are there any news/progress?

**Comment by imaNNeoFighT** [comment]
Hi, unfortunately, we have more priority things todo (priority is determined by the count of thumbs up).
Also, notice that you can contribute and create a Pull Request and help us.
Thanks!

**Comment by imaNNeoFighT** [comment]
Hi. We have just added `rotateAngle` property in  [LineTouchTooltipData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetouchtooltipdata), [BarTouchTooltipData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#bartouchtooltipdata) and [ScatterTouchTooltipData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/scatter_chart.md#scattertouchtooltipdata).

Check it out in [0.36.2](https://github.com/imaNNeoFighT/fl_chart/releases/edit/0.36.2)
