### ISSUE TITLE
Can't swipe on points on the sample page charts anymore

### ISSUE THREAD

**Issue by shamilovtim** [imaNNeoFighT/fl_chart#263]
![Screen Recording 2020-03-25 at 12 27 26 PM](https://user-images.githubusercontent.com/3495974/77560857-57793d80-6e94-11ea-824a-a43c5c615003.gif)

Not sure if this existed before or not but it seems like a pretty new bug. I used to be able to change points across a chart in the sample pages from my memory.

**Comment by imaNNeoFighT** [comment]
If you long-press on the chart, it will take handle the ongoing touches, otherwise, `PageView` will handle the swipes, it was the default behavior.

**Comment by shamilovtim** [comment]
Fair enough, thanks! I see that the pan gets interrupted by the pageview but the longpress does not. To test the panning I had to just remove the pageview temporarily (or reduce it to one page).

**Comment by imaNNeoFighT** [comment]
No problem.
Thanks!
