### ISSUE TITLE
Bug: Wrong grid count

### ISSUE THREAD

**Issue by bdlukaa** [imaNNeoFighT/fl_chart#267]
When I add a grid to my chart, the `checkToShowHorizontalLine` method counts one less than the `maxY`. Example:
```

    BarChart(
      BarChartData(
        maxY: 5,
        gridData: FlGridData(
          show: true,
          checkToShowHorizontalLine: (value) {
            print(value);
            return true;
          },
          getDrawingHorizontalLine: (value) => FlLine(
            color: Colors.black,
            strokeWidth: 1,
          ),
        ),
      ),
    );

```

The result of the `print(value)` will be:
```
1.0
2.0
3.0
4.0
```

The `maxY` is `5` but, when building the grid, it passes only `4` values, so the chart draws only four lines instead of 5.

(sorry for the bad English)

**Comment by imaNNeoFighT** [comment]
Yes, actually it should be like this:
0.0
1.0
2.0
3.0
4.0
5.0

but because we are showing the Border around the chart, we don't count the first and the last lines,
we skip 0.0 and 5.0.
Does it make sense?

**Comment by bdlukaa** [comment]
It makes sense, but even with the border disabled the counter still countes from 1 to 4. And, sometimes i do want to add the last line in the grid and the border at the same time, but following your logic i can't.

(sorry for the bad english again, but i think you can understand)

**Comment by imaNNeoFighT** [comment]
No worries man, I'm not native English too.
May I ask you to explain your case?
How border and grids are not enough for you?

**Comment by imaNNeoFighT** [comment]
I think this is not an important issue,
people can use the [FlBorderData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#flborderdata) for the first and the last line of the grid.

**Comment by bdlukaa** [comment]
Oh, thanks for the advice. I wouldn't think on using the border as the last line.
