### ISSUE TITLE
How to add animation effects

### ISSUE THREAD

**Issue by houqinzhe** [imaNNeoFighT/fl_chart#27]
I wanted to animate the bars when I first entered the screen

**Comment by imaNNeoFighT** [comment]
Hi, we are not supporting any animation now,
but it is in our [RoadMap](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/roadmap.md), keep tack of it.

**Comment by imaNNeoFighT** [comment]
But you can handle some of them by yourself,
set and rebuild FLChart with your animated values.

**Comment by itzsrikanth** [comment]
> But you can handle some of them by yourself,
> set and rebuild FLChart with your animated values.

Any sample charts for animations handled external to library?
