### ISSUE TITLE
If interval is set to zero, the line chart component will infinite loop and consume all system memory until killed.

### ISSUE THREAD

**Issue by hoverlees** [imaNNeoFighT/fl_chart#270]
Sometimes the leftTitles interval attribute is dynamic computed and may be set to zero. When interval is set to zero, the line chart component will cause infinite loop until the system memory exhausted. No messages logged and it's hard to trace the problem. 
Maybe the component should add some assertions when interval is a invalid value.

**Comment by imaNNeoFighT** [comment]
Correct!
Thanks for suggesting.

**Comment by imaNNeoFighT** [comment]
Implemented in this commit 429ba9d9413c8d1721394a4427d49a72e6c43ff8.
Thanks for suggesting.
