### ISSUE TITLE
Ability to change default horizontal line color

### ISSUE THREAD

**Issue by lukepighetti** [imaNNeoFighT/fl_chart#273]
Hi there! I'd like to be able to change the color of the default horizontal lines. Is there any way to achieve it? Thanks so much! The API on the project is second to none!

<img width="465" alt="Screen Shot 2020-03-30 at 12 48 57 PM" src="https://user-images.githubusercontent.com/666539/77939216-d3082f80-7284-11ea-93bb-8662826f696b.png">

**Comment by imaNNeoFighT** [comment]
Hi there, there is a `gridData` field inside the [LineChartData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartdata),
you can customize the grid lines in your way.
