### ISSUE TITLE
Dots that match gradient color

### ISSUE THREAD

**Issue by lukepighetti** [imaNNeoFighT/fl_chart#274]
Hi there, I would like to be able to match the gradient color for the dots. Is there a way to achieve this? Thanks so much

<img width="399" alt="Screen Shot 2020-03-30 at 12 56 37 PM" src="https://user-images.githubusercontent.com/666539/77940020-06978980-7286-11ea-8782-adf6ba98e3b3.png">

**Comment by imaNNeoFighT** [comment]
Hi, at the moment there isn't a way to do that.

**Comment by lukepighetti** [comment]
@imaNNeoFighT Can you recommend the easiest way to implement this if I have time to contribute?

**Comment by imaNNeoFighT** [comment]
I don't have any idea at the moment :)

**Comment by lukepighetti** [comment]
@imaNNeoFighT maybe we could provide color for each dot manually? That would be a decent halfway point.

**Comment by imaNNeoFighT** [comment]
This feature is going to be implemented in the next version,
stay tuned!.

**Comment by imaNNeoFighT** [comment]
Good news are coming dude.

**Comment by imaNNeoFighT** [comment]
I'm glad to announce [0.9.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.9.0) version,
Now, the default color of spots is the color of line or gradient.
check it out:

##### Sample 5 ([Source Code](/example/lib/line_chart/samples/line_chart_sample5.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_5.png" width="300" >

**Comment by riccardocescon** [comment]
@imaNNeo this link is no valid anymore, could you please update it? Thanks!

**Comment by imaNNeo** [comment]
@riccardocescon What do you mean?

**Comment by riccardocescon** [comment]
> @riccardocescon What do you mean?

The 'source code' for the example Is a broken link, It goes to a Not Found page

**Comment by imaNNeo** [comment]
> > @riccardocescon What do you mean?
> 
> The 'source code' for the example Is a broken link, It goes to a Not Found page

I've updated the links. Thanks for letting me know
