### ISSUE TITLE
Issue if all data = 0 

### ISSUE THREAD

**Issue by nitneuq33** [imaNNeoFighT/fl_chart#28]
Hello, I have this issue if all data = 0

I/flutter ( 1389): Another exception was thrown: Offset argument contained a NaN value.
When I change one data more that 0 it's ok.

There is no visual bug, just error that I don't know if it important for google when I push the app on the playstore

version 0.0.8 

Thank you for your work

**Comment by imaNNeoFighT** [comment]
Hi, I think it's not important to Google,
but please let me know in which chart type you faced this issue

**Comment by nitneuq33** [comment]
I use barchart

Le dim. 23 juin 2019 à 16:48, iman khoshabi <notifications@github.com> a
écrit :

**Comment by imaNNeoFighT** [comment]
we have some errors happening in the library, but they are not critical,
by the way, I will check them once and fix all.
Thanks for the issue, no worry.

**Comment by jp1017** [comment]
Same issue

![image](https://user-images.githubusercontent.com/7868514/63309993-75455980-c32b-11e9-9dd3-3b6f94679a60.png)

Set y data all 0 makes this issue like top img.

@imaNNeoFighT

**Comment by jamesblasco** [comment]
@imaNNeoFighT Same issue for me. it would be nice to have it so the line can animate all from 0 to their numbers

**Comment by jamesblasco** [comment]
The error occurs when there is no maxY provided. But if you set all to 0 and a maxY like 100 it works :)

<img width="419" alt="Captura de pantalla 2019-10-08 a las 14 13 44" src="https://user-images.githubusercontent.com/19904063/66394623-e7562880-e9d5-11e9-81dc-8ecea02eb2c3.png">

**Comment by imaNNeoFighT** [comment]
@jamesblasco I don't know what are you talking about?
Does it related to this closed issue?
