### ISSUE TITLE
Last interval line is not being painted

### ISSUE THREAD

**Issue by shamilovtim** [imaNNeoFighT/fl_chart#280]
The farthest x point I have is 45 and my interval is 7. That means I should have 6 interval lines. However the last interval line is not being painted. 

**Screenshots**
There should be an interval line at 43
![image](https://user-images.githubusercontent.com/3495974/78211579-5c815280-747b-11ea-9b62-64567ed69c87.png)

**Comment by imaNNeoFighT** [comment]
Could you please drop here a reproducible code,
It helps me to reproduce it with just a copy-paste.
Thanks!

**Comment by shamilovtim** [comment]
In linechartsample8 replace gridData with:
```
gridData: FlGridData(
          show: true, drawVerticalLine: true, drawHorizontalLine: false, verticalInterval: 2),
```

You should be able to see 5 intervals since there are points up to x:11 and lines should be drawn every 2 units. However the last line does not show at 10.0

**Comment by imaNNeoFighT** [comment]
Thanks for the explanation,
it will be fixed in the new version.

**Comment by shamilovtim** [comment]
![image](https://user-images.githubusercontent.com/3495974/78280348-edd9de80-74e6-11ea-816e-ccbb501d7147.png)

regression: last interval is being painted over top of the border again

**Comment by imaNNeoFighT** [comment]
It shouldn't happen,
where did you check it?

**Comment by imaNNeoFighT** [comment]
Fixed in [0.9.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.9.0)
Thanks for reporting!

**Comment by shamilovtim** [comment]
Regression is still there from this change

![](https://user-images.githubusercontent.com/3495974/78280348-edd9de80-74e6-11ea-816e-ccbb501d7147.png)

**Comment by shamilovtim** [comment]
This went from the last border not being painted, to an interval being painted over top of the last border

**Comment by imaNNeoFighT** [comment]
![image](https://user-images.githubusercontent.com/7009300/79016547-91c92700-7b84-11ea-95c5-d843b44cc376.png)

It's the result of sample8 with this change:
```dart
gridData: FlGridData(
        show: true,
        drawVerticalLine: true,
        drawHorizontalLine: false,
        verticalInterval: 2,
        getDrawingVerticalLine: (value) => FlLine(color: Colors.red),
      )
```

What is the problem exactly?

**Comment by kevinxxq** [comment]
Hi Sir,
I have question or suggestion:
Is there a option to include/exclude min/max when draw gridline/titles?

**Comment by kevinxxq** [comment]
> Hi Sir,
> I have question or suggestion:
> Is there a option to include/exclude min/max when draw gridline/titles?

I found the option is 
                  checkToShowTitle: (minValue, maxValue, sideTitles,
                          appliedInterval, value) =>
                      true,

Thank you all.
