### ISSUE TITLE
getStrokeColor has a weird default

### ISSUE THREAD

**Issue by shamilovtim** [imaNNeoFighT/fl_chart#282]
getStrokeColor should probably be either transparent or the color of the actual dot but right now it's orange

**Comment by imaNNeoFighT** [comment]
As I see it's blue at the moment, how did you find it orange? :))

**Comment by imaNNeoFighT** [comment]
You're right it is red

**Comment by imaNNeoFighT** [comment]
In [0.9.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.9.0), the default dots fill color, and stroke color taken from the line's color.
Check it out:

##### Sample 5 ([Source Code](/example/lib/line_chart/samples/line_chart_sample5.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_5.png" width="300" >
