### ISSUE TITLE
Ability to show single points on a line graph

### ISSUE THREAD

**Issue by NiamhG** [imaNNeoFighT/fl_chart#287]
**Is your feature request related to a problem? Please describe.**

I want to be able to show a line chart with multiple LineChartBarData, where some of those may only have a single spot. I cannot seem to see a way to display those, I have also tried to enable show: true on the FlDotData but that does not show the single spot either. 

**Describe the solution you'd like**
An option to show single spots

**Describe alternatives you've considered**
I am currently checking if my list of FlSpot == 1, and if so, duplicate that point so there's 2 of the same points. This seems to show a (small) dot, which is better than nothing for the moment. 

Screenshot example where I have two lists of `FlSpot`, `[FlSpot(17, 1.0)]` and `[FlSpot(23, 5.0), FlSpot(24, 4.0)]`, but have duplicated the single spot one:
![image](https://user-images.githubusercontent.com/5803941/78452352-c3248d00-7682-11ea-9a71-614b672cbcad.png)

**Comment by imaNNeoFighT** [comment]
You can make a LineChartBarData with a single spot.
```dart
LineChartBarData(
  spots: [
    FlSpot(2, 4)
  ],
  dotData: FlDotData(
    show: true,
    getDotPainter: (spot, value, barData, barDataIndex) {
      return FlDotCirclePainter(
        radius: 12,
        color: Colors.red,
        strokeColor: Colors.yellow,
        strokeWidth: 4
      );
    }
  )
)
```

![image](https://user-images.githubusercontent.com/7009300/111887579-2ff77b00-89eb-11eb-809b-05bf354f0860.png)
