### ISSUE TITLE
Option to remove decimal point while showing LineChartBarData 

### ISSUE THREAD

**Issue by codesimar** [imaNNeoFighT/fl_chart#290]
Is it possible to add a property that rounds bar data points and does not show it as a double with a decimal point? e.g. 12.3 will be shown as 12.

**Comment by imaNNeoFighT** [comment]
You can simply do it using `.map` operator, and round them to whatever you want,
do you have a problem with painting points, or showing their number?

**Comment by davidedinuc** [comment]
Can i ask you how to use .map operator to round double data?

> 
> 
> You can simply do it using `.map` operator, and round them to whatever you want,
> do you have a problem with painting points, or showing their number?
