### ISSUE TITLE
Support for RichText Widget for LineTooltipItem

### ISSUE THREAD

**Issue by aseef17** [imaNNeoFighT/fl_chart#294]
Additional customisation support for the LineToolTipItem instead of just a string will be really helpful.

If not support for RichText, maybe adding support for rendering HTML will be helpful.

**What I have right now**
![Current](https://user-images.githubusercontent.com/26878414/78879663-d2844b80-7a71-11ea-888f-1391b5ab3948.png)

**What I would like to achieve**
![Design](https://user-images.githubusercontent.com/26878414/78879821-11b29c80-7a72-11ea-871b-a578cebcc4b3.png)

**Comment by MrdotSpock** [comment]
Hi,

Is there any progress with this enhancement? I am looking for a way to set different attributes to different parts of the text.

**Comment by imaNNeoFighT** [comment]
Hi, check out our new release: [0.35.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.35.0)

`children` property added  in the [LineTooltipItem](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetooltipitem), [BarTooltipItem](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#bartooltipitem) and [ScatterTooltipItem](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/scatter_chart.md#scattertooltipitem) which accepts a list of [TextSpan](https://api.flutter.dev/flutter/painting/TextSpan-class.html). It allows you to have more customized texts inside the tooltip.

Check below examples:

##### BarChartSample 1 ([Source Code](/example/lib/bar_chart/samples/bar_chart_sample1.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_1.gif" width="300" >

##### ScatterChartSample 2 ([Source Code](/example/lib/scatter_chart/samples/scatter_chart_sample2.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/scatter_chart/scatter_chart_sample_2.gif" width="300" >

**Comment by MrdotSpock** [comment]
Thanks, I will give it a try!
