### ISSUE TITLE
I can't change the background color

### ISSUE THREAD

**Issue by lukepighetti** [imaNNeoFighT/fl_chart#295]
I'm not sure what's going on, I feel like I'm making a mistake but for some reason I cannot change the background color

<img width="467" alt="Screen Shot 2020-04-09 at 8 19 42 PM" src="https://user-images.githubusercontent.com/666539/78951247-759f8a00-7a9f-11ea-9ed0-3b2c0e0e762e.png">

```dart
import 'package:flutter/material.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:provider/provider.dart';
import 'package:wlw/extensions/extensions.dart';
import 'package:wlw/state/app_state.dart';

class BalanceHistoryChart extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final appState = Provider.of<AppState>(context);

    final data = appState.transactions.getBalanceHistory();

    return Container(
      color: Colors.green,
      child: LineChart(
        LineChartData(
          backgroundColor: Colors.red,
          borderData: FlBorderData(show: false),
          titlesData: FlTitlesData(
            bottomTitles: SideTitles(showTitles: false),
            topTitles: SideTitles(showTitles: false),
            rightTitles: SideTitles(showTitles: false),
            leftTitles: SideTitles(showTitles: false),
          ),
          lineBarsData: [
            LineChartBarData(
              barWidth: 2.5,
              spots: [
                for (var d in data)
                  FlSpot(
                    data.indexOf(d).toDouble(),
                    d.amount,
                  ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by imaNNeoFighT** [comment]
I can not run this code to debug.

**Comment by lukepighetti** [comment]
```dart
import 'package:flutter/material.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:provider/provider.dart';
import 'package:wlw/extensions/extensions.dart';
import 'package:wlw/state/app_state.dart';

class BalanceHistoryChart extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final appState = Provider.of<AppState>(context);

    // final data = appState.transactions.getBalanceHistory();
    final data = [1, 2, 3, 4, 5, 6, 7, 8, 9];

    return Container(
      width: double.maxFinite,
      padding: EdgeInsets.symmetric(horizontal: 16),
      child: LineChart(
        LineChartData(
          borderData: FlBorderData(show: false),
          titlesData: FlTitlesData(show: false),
          lineTouchData: LineTouchData(enabled: false),
          // backgroundColor: Colors.white,
          lineBarsData: [
            LineChartBarData(
              barWidth: 2.5,
              dotData: FlDotData(show: false),
              spots: [
                for (var d in data)
                  FlSpot(
                    d * 2.0,
                    d * 1.0,
                  ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```
This gives me this. Are the horizontal lines getting stretched?
<img width="472" alt="Screen Shot 2020-04-09 at 9 43 53 PM" src="https://user-images.githubusercontent.com/666539/78954807-3840f980-7aab-11ea-9dd6-ca0545ff55b1.png">

**Comment by lukepighetti** [comment]
I had to do this to resolve. I don't think I've ever yelled at my computer so much before haha.

```

          gridData: FlGridData(show: false),

```

**Comment by imaNNeoFighT** [comment]
If this issue is resolved close remove it :))

**Comment by lukepighetti** [comment]
I don't consider it resolved. The grid data shouldn't ever look like a background.

**Comment by imaNNeoFighT** [comment]
Then please tell me what's wrong?
You should set `gridData: FlGridData(show: false),` to disable drawing horizontal lines.

**Comment by lukepighetti** [comment]
If you look at the example at the top the background is actually the grid data, but the lines are so close together it looks like a solid background. That's a bug.

**Comment by imaNNeoFighT** [comment]
> ```dart
> import 'package:flutter/material.dart';
> import 'package:fl_chart/fl_chart.dart';
> import 'package:provider/provider.dart';
> import 'package:wlw/extensions/extensions.dart';
> import 'package:wlw/state/app_state.dart';
> 
> class BalanceHistoryChart extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     final appState = Provider.of<AppState>(context);
> 
>     // final data = appState.transactions.getBalanceHistory();
>     final data = [1, 2, 3, 4, 5, 6, 7, 8, 9];
> 
>     return Container(
>       width: double.maxFinite,
>       padding: EdgeInsets.symmetric(horizontal: 16),
>       child: LineChart(
>         LineChartData(
>           borderData: FlBorderData(show: false),
>           titlesData: FlTitlesData(show: false),
>           lineTouchData: LineTouchData(enabled: false),
>           // backgroundColor: Colors.white,
>           lineBarsData: [
>             LineChartBarData(
>               barWidth: 2.5,
>               dotData: FlDotData(show: false),
>               spots: [
>                 for (var d in data)
>                   FlSpot(
>                     d * 2.0,
>                     d * 1.0,
>                   ),
>               ],
>             ),
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> This gives me this. Are the horizontal lines getting stretched?
> <img alt="Screen Shot 2020-04-09 at 9 43 53 PM" width="472" src="https://user-images.githubusercontent.com/666539/78954807-3840f980-7aab-11ea-9dd6-ca0545ff55b1.png">


Your sample is working well, and I see the background color working.

**Comment by lukepighetti** [comment]
That sample shows it working as intended. The above screenshot shows it working not as intended. I don't care if you close this issue but it is a bug.

**Comment by imaNNeoFighT** [comment]
I can't find the bug.
could you explain it clearly please?

**Comment by lukepighetti** [comment]
Don't worry about it. Thanks for your time and dedication to this package. :)
