### ISSUE TITLE
SizedPicture Equality test failing

### ISSUE THREAD

**Issue by mhmdanas** [imaNNeoFighT/fl_chart#296]
**Describe the bug**
It's not a bug per se, but I still think it's an issue.
I switch to the beta channel of Flutter today, and one of the tests is failing. Specifically, this line: https://github.com/imaNNeoFighT/fl_chart/blob/1ef12fae71ca6f10fc28dd1926f6ce3b8edf07d2/test/chart/line_chart/line_chart_data_test.dart#L106

**To Reproduce**
Upgrade to the beta channel of Flutter, and then run tests.

**Versions**
 - which version of the Flutter are you using?
```
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d3ed9ec945 (5 days ago) • 2020-04-06 14:07:34 -0700
Engine • revision c9506cb8e9
Tools • Dart 2.8.0 (build 2.8.0-dev.18.0 eea9717938)
```
 - which version of the FlChart are you using? Running tests on `master` channel.

By the way, to help us detect problems like this in the future, should we also run tests on the beta channel?

**Comment by mhmdanas** [comment]
This now Flutter stable. For example, see #339.

**Comment by imaNNeoFighT** [comment]
I've just removed it because there isn't any alternative solution.
BTW thanks for reporting.

**Comment by mhmdanas** [comment]
If equality isn't working, do you think we should not mixin `Equatable` for `SizedPicture`?

**Comment by imaNNeoFighT** [comment]
Yes you're right.
