### ISSUE TITLE
The following JSNoSuchMethodError was thrown while handling a gesture: NoSuchMethodError: invalid member on null: 'length'

### ISSUE THREAD

**Issue by KumarSunil17** [imaNNeoFighT/fl_chart#302]
**Describe the bug**
When I long press on bar

**To Reproduce**

BarChart(
                BarChartData(
                    minY: 0,
                    maxY: list.map((e) => e.value).reduce(max).toDouble(),
                    barTouchData: BarTouchData(
                      touchTooltipData: BarTouchTooltipData(
                        tooltipBgColor: Colors.transparent,
                        tooltipPadding: const EdgeInsets.all(0),
                        tooltipBottomMargin: 8,
                        getTooltipItem: (
                            BarChartGroupData group,
                            int groupIndex,
                            BarChartRodData rod,
                            int rodIndex,
                            ) {
                          return BarTooltipItem(
                            rod.y.round().toString(),
                            TextStyle(
                              color: Colors.black,
                              fontWeight: FontWeight.bold,
                            ),
                          );
                        },
                      ),
                    ),
                    titlesData: FlTitlesData(
                      show: true,
                      bottomTitles: SideTitles(
                        showTitles: true,
                        textStyle: TextStyle(
                            color: const Color(0xff7589a2),
                            fontWeight: FontWeight.bold,
                            fontSize: 14),
                        margin: 20,
                        getTitles: (double value) {
                          return list[value.toInt()].date;
                        },
                      ),
                      leftTitles: SideTitles(showTitles: false),
                    ),
                    borderData: FlBorderData(
                      show: false,
                    ),
                    barGroups: list
                        .map((e) => BarChartGroupData(
                      x: list.indexOf(e),
                      barsSpace: 20,
                      barRods: [
                        BarChartRodData(
                            y: e.value.toDouble(),
                            borderRadius: BorderRadius.circular(2),
                            width: 20,
                            color: Colors.lightBlueAccent),
                      ],
                      showingTooltipIndicators: const [],
                    ))
                        .toList()),
              )

**Versions**
 - 0.9.0

**Comment by mrverdant13** [comment]
I am having the same issue only when the `BarTouchData` is enabled.

**Comment by imaNNeoFighT** [comment]
The code is not reproducible.
provide the main function and everything, then I just copy-paste and run it to figure it out.

**Comment by KumarSunil17** [comment]
Here is the full code : 
```dart
import 'dart:math';
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';

class GraphData {
  final String date;
  final int value;

  GraphData(this.date, this.value);

  @override
  bool operator ==(Object other) =>
      other is GraphData && date == other.date && value == other.value;

  @override
  int get hashCode => date.hashCode ^ value.hashCode;
}

final List<Color> gradientColors = [
  const Color(0xffa18cd1),
  const Color(0xfffbc2eb),
];

class LevelGraph extends StatelessWidget {
  final Map<String, int> graphData = {
    "0": 206,
    "1": 16,
    "2": 6,
    "3": 2,
    "4": 0,
    "5": 1,
    "6": 0,
    "7": 0
  };

  @override
  Widget build(BuildContext context) {
    final List<GraphData> list = [];
    graphData.keys.forEach((element) {
      list.add(GraphData(element, graphData[element]));
    });
    return Container(
      height: 300,
      decoration: BoxDecoration(color: Colors.white, boxShadow: [
        BoxShadow(
            blurRadius: 8,
            color: gradientColors[0].withOpacity(0.3),
            spreadRadius: 2,
            offset: Offset(0, 2))
      ]),
      padding: const EdgeInsets.all(16),
      child: Row(
        children: [
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Levels',
                  style: Theme.of(context)
                      .textTheme
                      .subtitle1
                      .copyWith(color: Colors.black45)),
            ],
          ),
          SizedBox(
            width: 8,
          ),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.fromLTRB(16, 16, 16, 4),
              child: BarChart(
                BarChartData(
                    minY: 0,
                    maxY: list.map((e) => e.value).reduce(max).toDouble(),
                    barTouchData: BarTouchData(
                      touchTooltipData: BarTouchTooltipData(
                        tooltipBgColor: Colors.transparent,
                        tooltipPadding: const EdgeInsets.all(0),
                        tooltipBottomMargin: 0,
                        getTooltipItem: (
                          BarChartGroupData group,
                          int groupIndex,
                          BarChartRodData rod,
                          int rodIndex,
                        ) {
                          return BarTooltipItem(
                            rod.y.round().toString(),
                            TextStyle(
                              color: Colors.black,
                              fontWeight: FontWeight.bold,
                            ),
                          );
                        },
                      ),
                    ),
                    titlesData: FlTitlesData(
                      show: true,
                      bottomTitles: SideTitles(
                        showTitles: true,
                        textStyle: TextStyle(
                            color: const Color(0xff7589a2),
                            fontWeight: FontWeight.bold,
                            fontSize: 14),
                        margin: 20,
                        getTitles: (double value) {
                          return list[value.toInt()].date;
                        },
                      ),
                      leftTitles: SideTitles(showTitles: false),
                    ),
                    borderData: FlBorderData(
                      show: false,
                    ),
                    barGroups: list
                        .map((e) => BarChartGroupData(
                              x: list.indexOf(e),
                              barsSpace: 20,
                              barRods: [
                                BarChartRodData(
                                    y: e.value.toDouble(),
                                    borderRadius: BorderRadius.circular(2),
                                    width: 20,
                                    color: Colors.lightBlueAccent),
                              ],
                              showingTooltipIndicators: const [0],
                            ))
                        .toList()),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```

**Comment by imaNNeoFighT** [comment]
What should I do?
I just long pressed on bars and nothing happened!
