### ISSUE TITLE
Step Line Chart

### ISSUE THREAD

**Issue by dhs9004** [imaNNeoFighT/fl_chart#303]
Hi, I was wondering if there is an option to make a step Line chart.
Thanks,

**Comment by imaNNeoFighT** [comment]
Yay
Now we have `isStepLineChart` property in our [LineChartData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartdata),
check it out in [0.9.2](https://github.com/imaNNeoFighT/fl_chart/releases/edit/0.9.2).


##### Sample 3 ([Source Code](/example/lib/line_chart/samples/line_chart_sample3.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_3.gif" width="300" >
