### ISSUE TITLE
Can we add dropshadow on LineCharts?

### ISSUE THREAD

**Issue by honkevin** [imaNNeoFighT/fl_chart#304]
Can we add dropshadow on LineCharts?

**Comment by imaNNeoFighT** [comment]
Hi, not yet.

**Comment by honkevin** [comment]
Thanks for the great work!!! I am looking forward to this option.

**Comment by imaNNeoFighT** [comment]
Yay, implemented in [0.9.2](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.9.2), check it out!

##### Sample 5 ([Source Code](/example/lib/line_chart/samples/line_chart_sample5.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_5.png" width="300" >

**Comment by honkevin** [comment]
You are the man!!!!!!
