### ISSUE TITLE
How the BarChart shows the value column at the top?

### ISSUE THREAD

**Issue by inprise1980** [imaNNeoFighT/fl_chart#308]
How the BarChart shows the value column at the top?

**Comment by imaNNeoFighT** [comment]
##### Sample 3 ([Source Code](/example/lib/bar_chart/samples/bar_chart_sample3.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_3.png" width="300" >
