### ISSUE TITLE
linechart,If the y-axis data is 0, the curve will exceed the x-axis

### ISSUE THREAD

**Issue by inprise1980** [imaNNeoFighT/fl_chart#309]
linechart，
spots: [
          FlSpot(0, 1),
          FlSpot(1, 2),
          FlSpot(2, 0),
          FlSpot(3, 0),
          FlSpot(4, 3.5),
          FlSpot(5, 5),
          FlSpot(6, 8),
        ],

In the above array 2 and 3, if the y-axis data is 0, the curve will exceed the x-axis

**Comment by imaNNeoFighT** [comment]
Did you try to tweak `preventCurveOverShooting` and `preventCurveOvershootingThreshold` parameters in the [LineChartBarData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartbardata)?

**Comment by imaNNeoFighT** [comment]
Hello?
