### ISSUE TITLE
Recover API numbers and include in chart

### ISSUE THREAD

**Issue by lucalves** [imaNNeoFighT/fl_chart#31]
Hello everyone,

I am needing in my application to perform the query on an API that returns numbers and transform into graphics.

Does any developer know how I can do this in a simple way?

**Comment by imaNNeoFighT** [comment]
Hi, 
May I ask you tell it more clearly?

**Comment by imaNNeoFighT** [comment]
This issue will be closed tomorrow If I don't receive any answer.

**Comment by lucalves** [comment]
I solved the problem, thanks!
