### ISSUE TITLE
GetTooltipItems wrong

### ISSUE THREAD

**Issue by mutangtech** [imaNNeoFighT/fl_chart#314]
in `axis_chart_data.dart` , i found this code:
![image](https://user-images.githubusercontent.com/44760239/79916938-26246b00-845c-11ea-928a-6e5b629aa40e.png)

this `touchedSpots` should be `touchedSpot` ? and may cause exception:

![image](https://user-images.githubusercontent.com/44760239/79917058-5f5cdb00-845c-11ea-9218-bdf354042828.png)

**Comment by mhmdanas** [comment]
Do you wanna open a PR for this or should I do it?

**Comment by mutangtech** [comment]
> Do you wanna open a PR for this or should I do it?

I haven't   development environment, please do this :)

**Comment by mutangtech** [comment]
> Do you wanna open a PR for this or should I do it?

sorry , i didn't use the latest version, the problem has bean fixed, i will close this issue.
