### ISSUE TITLE
groupBarsPosition is null

### ISSUE THREAD

**Issue by mutangtech** [imaNNeoFighT/fl_chart#315]
Hi, thanks for this awesome library, but when i using BarChart, i got a exception as follow:

![image](https://user-images.githubusercontent.com/44760239/80023633-69401600-8510-11ea-973d-4f65e1f6e235.png)

**How to re-produce**
When touch the bar to show a tooltips, and then move finger to another bar, the tooltips won't show any more, and print the error-log.

**Possible reason**
It seems the `groupBarsPosition` property  is NULL in `bar_chart_painter.dart`

![image](https://user-images.githubusercontent.com/44760239/80023732-9096e300-8510-11ea-9752-852b06072479.png)

And in this commit [c0a14f97](https://github.com/imaNNeoFighT/fl_chart/commit/c0a14f97e6b2d4caa8eb34e8d88f437d515b9379#diff-17dcb978a384ae3efb3b2bce1f7bd55b) 

It looks like this bit of commented out code might help? 
[https://github.com/imaNNeoFighT/fl_chart/blob/master/lib/src/chart/bar_chart/bar_chart_painter.dart#L571](https://github.com/imaNNeoFighT/fl_chart/blob/master/lib/src/chart/bar_chart/bar_chart_painter.dart#L571)

```
if (groupBarsPosition == null) {
  return null;
}
```

**Comment by mutangtech** [comment]
This error also occurs in exmple  `bar_chart_sample1.dart`  .
and this issue [issuecomment-616123536](https://github.com/imaNNeoFighT/fl_chart/issues/202#issuecomment-616123536)

**Comment by imaNNeoFighT** [comment]
#313 
Duplicate!

**Comment by imaNNeoFighT** [comment]
Fixed in [0.9.3](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.9.3),
Thanks for reporting!
