### ISSUE TITLE
Black shadows are default on since 0.9.2

### ISSUE THREAD

**Issue by krispypen** [imaNNeoFighT/fl_chart#316]
Since version 0.9.2 , PR #305 , every line has a shadow, this should not be standard behavior.

My suggestion is to add a color property to the default " ?? const Shadow()" at https://github.com/imaNNeoFighT/fl_chart/blob/ef6ee3f882cbb01a5661c998fa67633f1c23144d/lib/src/chart/line_chart/line_chart_data.dart#L393
and set it to Colors.transparent . Then it's ignored during rendering in the _drawBarShadow method because the opacity is 0.0

Not 100% sure but if that's the best solution, I can create a PR too

**Comment by imaNNeoFighT** [comment]
Yes, that's the best solution,
make a PR dude.
Thanks!

**Comment by imaNNeoFighT** [comment]
Fixed in [0.9.3](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.9.3),
Thanks for reporting!
And for sure thanks for contributing!
