### ISSUE TITLE
How to set the space value between chart and SideTitles in barChart

### ISSUE THREAD

**Issue by fg2q1q3q** [imaNNeoFighT/fl_chart#317]
Thanks to open source for such a practical library，But I have two questions in the process of using. Please take the time to answer them. Thank you.

 - **How to set the space value between chart and SideTitles in barChart**
The current gap is too large, but I can't find a way to modify it
 - **How to display the lines of x-axis and y-axis**
I set `griddata`, but it don't include the axis

**Comment by imaNNeoFighT** [comment]
You're welcome,

> **How to set the space value between chart and SideTitles in barChart?**

use `margin` and `reservedSize` in the [SideTitles](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#sidetitles)

> **How to display the lines of x-axis and y-axis?**

we have something called [ExtraLinesData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#extralinesdata), but it only works in the LineChart,
we used it to show an average line in this sample:

##### [Sample 3](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#sample-3-source-code)
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_3.gif" width="300" >

If it works for you, please file an issue to follow it up to adding in the BarChart too.

Thanks!

**Comment by fg2q1q3q** [comment]
ok,thanks for you

**Comment by imaNNeoFighT** [comment]
You're welcome!

**Comment by Ankit-Kumar-Dhangar1** [comment]
hi hi
