### ISSUE TITLE
Allow to pass custom LineChartPainter

### ISSUE THREAD

**Issue by Mazas17** [imaNNeoFighT/fl_chart#32]
Could you add possibility to pass custom `LineChartPainter` to `LineChart`? I would like to paint some additional data on line point click.

**Comment by imaNNeoFighT** [comment]
what kind of additional data would you paint?

**Comment by Mazas17** [comment]
I would like to add some additional text. In any case, this shouldn't matter, because I would just override paint method and repaint whatever I need.

**Comment by imaNNeoFighT** [comment]
Ok let me investigate on it, I will back you soon

**Comment by imaNNeoFighT** [comment]
Hi, currently we can't have a CustomPainter, because it will add non-valuable complexity,
and for now, we have a long path, this is not critical for now, and it needs lots of effort.
but maybe in the future, we have something like this.
Thanks! cheers!

**Comment by goatandsheep** [comment]
Hi @imaNNeoFighT are you open to PRs on this ticket?

**Comment by imaNNeoFighT** [comment]
Hi @goatandsheep 
PRs are always welcome!
Please let me know what you're gonna do before you start
