### ISSUE TITLE
Min / max algorithms are slightly off and letting lines pass border

### ISSUE THREAD

**Issue by shamilovtim** [imaNNeoFighT/fl_chart#325]
When letting the chart handle maxes and mins by itself, it lets the curve pass the borders by a few pixels. This might be because of a combination of a thick line and a small border. The chart should understand the thickness of different things and not send them past the border. My suggestion would be at least a pixel or two of white space minimum between the edge of a line and a border. Lines should never touch the border, it looks wrong.

<img width="357" alt="Screen Shot 2020-04-29 at 10 46 37 PM" src="https://user-images.githubusercontent.com/3495974/80667002-f8e34880-8a6b-11ea-8aeb-9048ab7ae08c.png">

**Comment by imaNNeoFighT** [comment]
The image you've provided shows more than one or two pixels whitespace,
the problem is that you have a point outside of the bounds, right?

**Comment by shamilovtim** [comment]
@imaNNeoFighT no the points are within bounds this happens when I don't have a max set. so the chart is supposed to adjust to any max.

**Comment by imaNNeoFighT** [comment]
If you don't provide a specified min or max value, it tries to obtain it from the provided values,
please give me a reproducible code to check it out,
Thanks!

**Comment by imaNNeoFighT** [comment]
Hello?

**Comment by shamilovtim** [comment]
Sorry I'll take another pass at this as soon as I am able. I think the ideal solution is to let the user provide some sort of internal padding but I'm not sure how to implement yet.
