### ISSUE TITLE
BarChart Touch must be clicked on BarRod?

### ISSUE THREAD

**Issue by attex** [imaNNeoFighT/fl_chart#328]
Hi there, 
is there a way to fetch touches/clicks on the whole Y-axis position? 

![Bildschirmfoto 2020-05-02 um 17 05 53](https://user-images.githubusercontent.com/9304272/80867933-57403f00-8c97-11ea-898c-453ef5e9b0b5.png)

In the above Chart 2 second Bar is pretty small and cannot be touched. Or just with a pen or much luck. 

Thanks in advance.

att3x

**Comment by imaNNeoFighT** [comment]
Hi, you're welcome.
try to have a transparent `backDrawRodData` in your [BarChartRodData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#barchartroddata), then set `allowTouchBarBackDraw` to true in the [BarTouchData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#bartouchdata-read-about-touch-handling).

**Comment by attex** [comment]
The touchevent still return null.

Here ist my code 

`return BarChart(
                BarChartData(
                  barGroups: _getBarGroups(snapshot.data),
                  alignment: BarChartAlignment.spaceBetween,
                  titlesData: FlTitlesData(show: false),
                  axisTitleData: FlAxisTitleData(show: false),
                  borderData: FlBorderData(show: false),
                  barTouchData: BarTouchData(
                      allowTouchBarBackDraw: true,
                      touchTooltipData: BarTouchTooltipData(
                        tooltipBgColor: MyColors.divTimerMediumBlue,
                        getTooltipItem: (group, groupIndex, rod, rodIndex) {
                          return null;
                        },
                      ),
                      touchCallback: (BarTouchResponse response) {
                        if (response.spot != null &&
                            response.touchInput is! FlPanEnd &&
                            response.touchInput is! FlLongPressEnd) {
                          setState(() {
                            _chartTouched = true;
                            _currentMonth =
                                response.spot.touchedBarGroupIndex + 1;
                          });
                        } else {
                          setState(() {
                            _chartTouched = false;
                          });
                        }
                      }),
                ),
              ),
List<BarChartGroupData> _getBarGroups(data) {
    List<BarChartGroupData> barGroups = new List<BarChartGroupData>();

    for (int i = 0; i < data.length; i++) {
      double val = data[i]['val'];
      double valc = data[i]['valc'];
      barGroups.add(
        BarChartGroupData(
          x: i,
          barsSpace: 2,
          barRods: [
            BarChartRodData(
              backDrawRodData:
                  BackgroundBarChartRodData(color: Colors.transparent),
              y: val,
              borderRadius: BorderRadius.zero,
              width: 18,
              rodStackItem: [
                BarChartRodStackItem(
                    0,
                    val - valc,
                    _currentMonth - 1 == i
                        ? Colors.grey),
                BarChartRodStackItem(
                    val - valc,
                    val,
                    _currentMonth - 1 == i
                        ? Colors.white.withOpacity(0.8))
              ],
            )
          ],
        ),
      );
    }

    return barGroups;
  }
`

**Comment by attex** [comment]
That fixed it. 

I just had to provide the parameters y:maxHeight and show:true

Thanks

**Comment by attex** [comment]
@imaNNeoFighT  is there a way to provide the same functionality to Linecharts as well?

**Comment by imaNNeoFighT** [comment]
No, you can create an issue to follow it up.
