### ISSUE TITLE
Height compresses when I have too many points on the x-axis. 

### ISSUE THREAD

**Issue by moisesv** [imaNNeoFighT/fl_chart#329]
Height messes up when I have too many points on the x-axis. 
Any advice would be great. 

Using fl_chart: ^0.9.4

![image](https://user-images.githubusercontent.com/158709/80936597-7aeaae80-8d97-11ea-8fe7-6f7bd2e0377b.png)

**Comment by imaNNeoFighT** [comment]
Give us a reproducible code please

**Comment by imaNNeoFighT** [comment]
Hello?

**Comment by moisesv** [comment]
> Hello?

Sorry. Not sure what it was. Scraped the code and replaced it with sample code and it worked.
