### ISSUE TITLE
missing data support in line chart

### ISSUE THREAD

**Issue by Prrrince** [imaNNeoFighT/fl_chart#330]
Please add support to indicate missing data in line chart.
for eg:- if data is missing for one hour in a 24 hour chart, line should be erased for that one hour.
we can indicate missing data by passing  null as value

**Comment by imaNNeoFighT** [comment]
Check [LineChartSample8](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#sample-8-source-code)

**Comment by imaNNeoFighT** [comment]
Did you check it?

**Comment by Prrrince** [comment]
yes, its working.
thank you :smile: 
and sorry for not checking all examples properly before raising request
