### ISSUE TITLE
Negative and Positive bar on the same index of x axis in Bar Chart

### ISSUE THREAD

**Issue by Prrrince** [imaNNeoFighT/fl_chart#334]
Please add feature to have Negative and Positive bar on the same position ( sharing same x axis index)

**Comment by imaNNeoFighT** [comment]
I was waiting for it to raise,
thanks :)))

**Comment by donflopez** [comment]
I would really love to see this, I need something similar to iOS heart rate bars. I'd be happy to implement this feature, I'm new to flutter and dart and I could use some guidance!

**Comment by devdutt10** [comment]
Dug into the code and I was able to accomplish this by providing a negative value to the `barsSpace` property on a `BarChartGroupData`, with 2 items in its `barRods` property: one each for the positive and negative `y` values. Need to test more but it looks like it works.

**Comment by imaNNeoFighT** [comment]
Now you can use `fromY` and `toY` properties in each BarRod.
Check below samples:

##### BarChartSample 5 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample5.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_5.gif" width="300" >

##### BarChartSample 6 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample6.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_6.png" width="300" >
