### ISSUE TITLE
FLSpot LineTouchData y

### ISSUE THREAD

**Issue by cankaplanbeautinda** [imaNNeoFighT/fl_chart#335]
Can't change the ratio of the value. For Example: You have the values 100€, 420€, 320€...
You can divide the Strings, so you get 1, 4.2 and 3.2 for "y" value. But you can't reverse the y value to 100€, 420€, 320€ to show it as the LineTouchData/ LineTouchTooltipData.

**Comment by imaNNeoFighT** [comment]
I didn't get you

**Comment by imaNNeoFighT** [comment]
Could you please explain it more?

**Comment by cankaplanbeautinda** [comment]
Sorry for the late response. 

See the attached picture. I want to show my dynamic double values to the user, when he hovers over the LineChart. I have values like 300€ or 80,50€. The lineChart ratio doesn't adapt to higher values. I have to divide my values. But then, the divided value is shown in the UI.

![IMG_6323](https://user-images.githubusercontent.com/64465042/81710596-23250500-9473-11ea-85b1-f23686780a8c.jpg)

**Comment by igoriuz** [comment]
You get through [touchToolTipData](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample1.dart#L152) the getTooltipItem where you can mulitply by 100 and add € in the end.

**Comment by imaNNeoFighT** [comment]
Yes, @igoriuz is right,
check this sample for more details.

##### [LineChart Sample](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#sample-3-source-code)
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_3.gif" width="300" >

**Comment by cankaplanbeautinda** [comment]
Thank you for your help!

But unfortunately LineChartData only has "getToolTipItems: (touchedSpots) {}" 
How can I multiply the by 100 there? I tried everything...
<img width="409" alt="Bildschirmfoto 2020-05-25 um 08 55 48" src="https://user-images.githubusercontent.com/64465042/82786804-89435c00-9e65-11ea-9578-11dd6f766b36.png">

**Comment by imaNNeoFighT** [comment]
Multiply what by 100?

**Comment by igoriuz** [comment]
You create a TooolTipItem like in the sample https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample3.dart#L67
