### ISSUE TITLE
LineChart align values of LineChartBarData to the right

### ISSUE THREAD

**Issue by matejhocevar** [imaNNeoFighT/fl_chart#336]
Hey, fl_chart community!

First I want to say thank you for your amazing plugin and all features.

I'm wondering if it's possible to achieve the right alignment on the LineChartBarData.

This is what I want:
![Screenshot 2020-05-07 at 14 57 01](https://user-images.githubusercontent.com/3007189/81297587-bde8a280-9073-11ea-9d5a-e60e5fa9996e.png)

This is the current status:
![Screenshot 2020-05-07 at 15 01 47](https://user-images.githubusercontent.com/3007189/81297597-c3de8380-9073-11ea-9058-d70a6f531b15.png)

How can I align the line chart to the right to be more in sync with the first image?

**Comment by imaNNeoFighT** [comment]
Hey, dude,
Thanks for your kind speak.
I think you can achieve that by mapping your spot's data, and somehow convert them to get this result.
(I mean it doesn't need a feature I think)

**Comment by imaNNeoFighT** [comment]
BTW I will close this issue,
Thanks!
