### ISSUE TITLE
Is there a way to see the first and last spot values without the need for a touch interactivity?

### ISSUE THREAD

**Issue by S1nPur1ty** [imaNNeoFighT/fl_chart#338]
I try to achieve the following:
![Screenshot 2020-05-07 at 7 45 16 PM](https://user-images.githubusercontent.com/61484213/81327259-4a5a8b80-909b-11ea-8632-72fe70e35514.png)

As you can see, the first and last spot need to show the values without the need for a touch interactivity. 

Currently, all I have is this:
![Screenshot_20200507-200657](https://user-images.githubusercontent.com/61484213/81329245-8cd19780-909e-11ea-873d-7e7ac87e134f.jpg)

Is this already possible?

**Comment by imaNNeoFighT** [comment]
Yes, it is possible,
you should show tooltip items by default, and set the background color transparent,
check this sample:



##### [Sample 5](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#sample-5-source-code)
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_5.png" width="300" >

**Comment by S1nPur1ty** [comment]
> Yes, it is possible,
> you should show tooltip items by default, and set the background color transparent,
> check this sample:
> 
> ##### [Sample 5](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#sample-5-source-code)
> <img alt="" width="300" src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_5.png">

Honestly great work, but I noticed that when I enable the LineTouchData, the tooltip text dissapears.. This is what I have:

```
 enabled: false,
        getTouchedSpotIndicator:
            (LineChartBarData barData, List<int> spotIndexes) {
          return spotIndexes.map((index) {
            return TouchedSpotIndicatorData(
              FlLine(color: Colors.transparent, strokeWidth: 0),
              FlDotData(
                show: true,
              ),
            );
          }).toList();
        },
```

Is there something that I overlooked? Please let me know how I can solve this.

**Comment by S1nPur1ty** [comment]
@imaNNeoFighT 

I have managed to fix the issue with the touchCallback:

```
bool hideSpotData = false;
...
touchCallback: (LineTouchResponse touchResponse) {
          if (touchResponse.touchInput is FlPanStart ||
              touchResponse.touchInput is FlPanMoveUpdate ||
              touchResponse.touchInput is FlLongPressStart ||
              touchResponse.touchInput is FlLongPressMoveUpdate) {
            hideSpotData = true;
          } else {
            hideSpotData = false;
          }

          setState(() {});
        },
        enabled: hideSpotData,
```

However, is it ok if I use setState every time when a touch interaction occurs? I mean, will it affect the performance of phones in a bad way or is it ok to leave it like this? Please let me know.

**Comment by imaNNeoFighT** [comment]
It is okay
