### ISSUE TITLE
SideTitles for x value on BarChartData

### ISSUE THREAD

**Issue by tomosullivan8** [imaNNeoFighT/fl_chart#342]
I've had a bit of an issue showing the date which I've used in as `x` for the `BarChartGroupData` and converting to the `SideTitles` for the group value.

It looks like the group value shows the index of the `BarChartGroupData` instead of the x value?

Can you let me know if there is a way to get the `x` value in the `bottom: SideTitles`? 

I have been able to do it fine with the `LineBarChart` where it takes the `x` from the `FLSpots`, and the `y` value pulls through as expected for the `left: SideTitle`.

**Comment by imaNNeoFighT** [comment]
Could you please show me your use-case?
I know what you mean roughly, but I'm not clear about it.
Thanks!

**Comment by tomosullivan8** [comment]
I've included an example which should hopefully make it clear!

First, the `BarChartGroupData` where i've input my data to pull through onto the graph.

```
BarChartGroupData(
      x:  12,   /// This doesn't pull through to the X-axis (bottomTitles value).
      barRods: BarChartRodData(
          y: 72.0, /// This pulls through to the Y-axis (leftTitles value)
          width: 12.0,
      ),
    );
```
The FlTitlesData to show the data on the X and Y Axis.

```
titlesData: FlTitlesData(
        show: true,
        bottomTitles: SideTitles(
          interval: intervals,
          showTitles: true,
          textStyle: titleStyle(theme),
          getTitles: (double value) {
              return '$value'; // This doesn't pull through the X-axis from the above data.
          },
        ),
        leftTitles: SideTitles(
          showTitles: true,
          textStyle: titleStyle(theme),
          interval: 20.0,
          getTitles: (value) {
            return value.round().toString(); // This pulls through the Y-axis from above data.
          },
        ),
      ),
```

As you can see below, the 72 pulls through to the Y-Axis and the BarChartData with the intervals at 20.0, but the X-axis shows 0.0. instead of the 12.

![image](https://user-images.githubusercontent.com/36487764/81672889-ba259900-9442-11ea-9294-79d76ae7abfb.png)

I have been using the X-Axis to pull through the date in `millisecondsSinceEpoch` format, and it pulls through as expected for a line graph, but not for the bar chart.

![image](https://user-images.githubusercontent.com/36487764/81673291-52238280-9443-11ea-9e51-93ab35f15699.png)

Can you let me know if I'm using the `BarChartGroupData` incorrectly, or if there is a way around this?

**Comment by imaNNeoFighT** [comment]
I agree with you, 
It will be fixed in the new version, and thank you!

**Comment by imaNNeoFighT** [comment]
Check out the [0.10.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.10.1) version.
Cheers!

**Comment by matthewrice345** [comment]
Is there any way both the index and the x value can both be part of GetTitleFunction? After updating to 0.10.1 there is now no way to show the bottom tittles correctly, I used the index to know where to pull the display data. I think there are valid use-cases for each piece of data.
