### ISSUE TITLE
curveSmoothness

### ISSUE THREAD

**Issue by NaarGes** [imaNNeoFighT/fl_chart#344]
Hi, 
First of all, Thank you for your great job in making this repo.
I'm wondering what is the best value of curveSmoothness in LineChartBarData? because with the default value (0.35) I get some abnormal curves. you can see some of them here

![photo_2020-05-16 22 58 07](https://user-images.githubusercontent.com/15056339/82127441-c2762f00-97c8-11ea-8a68-375044d46bdf.jpeg)
![photo_2020-05-16 22 58 10](https://user-images.githubusercontent.com/15056339/82127443-c609b600-97c8-11ea-98f8-dd4bad84c260.jpeg)

**Comment by imaNNeoFighT** [comment]
Hi,
You should tweak it to find a value that fits in our charts.
