### ISSUE TITLE
is there a way to scale an line in the chart with respect to the another line?

### ISSUE THREAD

**Issue by a43mrk** [imaNNeoFighT/fl_chart#345]
Hello! i need to show lines in one chart but some of them have different ranges.
Let's say i have an chart with many lines to plot, some of the lines have same range of y  but there are some lines that have really different y ... is there an option to scale the lines without change data before plot?

**Comment by imaNNeoFighT** [comment]
You should scale it before passing your data to the FL Chart,
I mean it should be handled outside of this lib.
Thanks!

**Comment by a43mrk** [comment]
how about the labels?

**Comment by a43mrk** [comment]
Hello! thanks for the response! Can you post an example please?
