### ISSUE TITLE
Use Point from 'dart:math' instead of FlSpot

### ISSUE THREAD

**Issue by mhmdanas** [imaNNeoFighT/fl_chart#346]
This has some advantages:
- We don't need to create our own point class
- The class is builtin in Dart

This change will break almost all code that uses this library, so I thought about how to ease migration. Here's my idea:
- Replace all occurrences of `FlSpot` in this repository with `Point`
- Add all `FlSpot` methods and properties (`isNull`, `lerp`, etc.) not available on `Point` as extension methods and properties on `Point`
- Make `FlSpot` extend from `Point`
- Mark `FlSpot` as deprecated

I'm willing to open a PR for this in case we decide to do this.

**Comment by imaNNeoFighT** [comment]
Hmm, let me think about it.
But I'm looking for more advantages, both advantages that you've mentioned are the same.
What is your problem with `FlSpot`, there is a suggestion to rename it to something like `FlPoint`, but I think it's okay to have our own class.

**Comment by mhmdanas** [comment]
I don't have a specific problem with `FlSpot`, I just think that using builtin stuff is better. Also, isn't renaming `FlSpot` to `FlPoint` just as breaking as using `Point`?

Some other advantages that I can think of:
- Other packages from pub that work with points might use the `Point` class, so we will be able to work with them.
- `Point` has some useful methods such as `distanceTo`, `+`, `-`, and `*`. We won't need to implement them if we need them in the future. Also, some useful methods might be added to `Point` in future versions of Dart. `dart:math` also has a few classes like `Rectangle`, which accept `Point`s. We might need them later. (Or maybe not. But who knows?)
- If we don't use the migration plan that I suggested in my first comment, isn't renaming `FlSpot` to `FlPoint` just as breaking as using `Point` instead of `FlSpot`?

**Comment by mhmdanas** [comment]
I just searched the source code for NNBD `Point`, and it seems `x` and `y` can't be null. But I want to say something here. I think `x` and `y` should not be null. When NNBD is in Flutter stable, the compiler will force us to handle the possibility of `x` and/or `y` being null every time we use them. That would be tiresome. What do you think?

**Comment by imaNNeoFighT** [comment]
I think `FlSpot` is fine, and we should focus on more important things.
let it be `FlSpot` for now, it is working well, and the only cost is a mapper, and it should be fine.
Thanks!
Close this issue if you are convinced.

**Comment by mhmdanas** [comment]
Yes, you're right. This is too trivial and there are other important things.
