### ISSUE TITLE
Option to align title

### ISSUE THREAD

**Issue by walteryaron** [imaNNeoFighT/fl_chart#35]
today its hardcoded in "void drawTitles"
in this line
final TextPainter tp = TextPainter(text: span, **textAlign: TextAlign.center**, textDirection: TextDirection.ltr);

**Comment by imaNNeoFighT** [comment]
May I ask you to show your use-case, I want to know why you need it.

**Comment by walteryaron** [comment]
![Simulator Screen Shot - iPhone 8 - 2019-07-09 at 08 59 13](https://user-images.githubusercontent.com/735919/60863075-2c788c00-a228-11e9-9062-5146aab340ce.png)

**Comment by walteryaron** [comment]
![Screen Shot 2019-07-09 at 9 37 33](https://user-images.githubusercontent.com/735919/60864874-70ba5b00-a22d-11e9-8e0f-cd1e0953149b.png)

**Comment by imaNNeoFighT** [comment]
Hi,
Unfortunately, Github started banning Iranian users while ago,
If they didn't stop their action, I can't continue on this repo,
read more it [here](https://medium.com/@hamed/github-blocked-my-account-and-they-think-im-developing-nuclear-weapons-e7e1fe62cb74),
If you want to prevent this unfair action, give a start on this [repository](https://github.com/1995parham/github-do-not-ban-us) and say your support by creating an issue, and spread it.
Best regards,
Iman Khoshabi

**Comment by imaNNeoFighT** [comment]
I think it is not related to the alignment of text,
you can prevent to draw your first title to solve your problem.
let me know if you still need the alignment feature

**Comment by imaNNeoFighT** [comment]
I'm gonna close it If I don't get any answer till tomorrow.

**Comment by walteryaron** [comment]
Sorry for the delay
I manage to create a similar feature
Thanks

Sent from my iPhone

On 12 Oct 2019, at 21:18, iman khoshabi <notifications@github.com> wrote:

﻿

I'm gonna close it If I don't get any answer till tomorrow.

**Comment by imaNNeoFighT** [comment]
What?

**Comment by walteryaron** [comment]
Please close this

Sent from my iPhone

On 12 Oct 2019, at 23:24, iman khoshabi <notifications@github.com> wrote:

﻿

What?
