### ISSUE TITLE
SideTiles animation during resizing

### ISSUE THREAD

**Issue by igoriuz** [imaNNeoFighT/fl_chart#358]
I noticed that text in sideTiles are instantly shown when a new intervall is given. This looks somehow strange during the animation between two data sets. Example is below in a clip:
[strange behaviour during resizing.zip](https://github.com/imaNNeoFighT/fl_chart/files/4700108/strange.behaviour.during.resizing.zip)

**Comment by imaNNeoFighT** [comment]
Thanks for reporting the bug, we will fix it.
and about legends, at the moment it is not our priority (but you can make a separate issue, people can vote it with their thumbs up).
Cheers!

**Comment by igoriuz** [comment]
Okay, thanks for the info. I removed it from this issue and created a new one. By the way: great package!

**Comment by mr-mamali** [comment]
anyupdate

**Comment by imaNNeoFighT** [comment]
Not yet!

**Comment by imaNNeoFighT** [comment]
It has been fixed previously but I forgot to let you know.
Sorry about that.
It should be fixed in our latest version (0.20.1).

Thanks!
