### ISSUE TITLE
Graph not completly drawing

### ISSUE THREAD

**Issue by igoriuz** [imaNNeoFighT/fl_chart#359]
**Describe the bug**
One graph is not drawing completly while showing data in the tooltip.

**Video**
[bug within the chart.zip](https://github.com/imaNNeoFighT/fl_chart/files/4700183/bug.within.the.chart.zip)

**Versions**
 - which version of the Flutter are you using?
1.18.0-11.1.pre
 - which version of the FlChart are you using?
0.10.0-dev

**Comment by imaNNeoFighT** [comment]
Please provide a reproducible code (simplify it and make a runnable main.dart without any third-party dependency).
Thanks!
