### ISSUE TITLE
Double Axis

### ISSUE THREAD

**Issue by gmaxferr** [imaNNeoFighT/fl_chart#36]
Hey!

An important improvement for this component, in my opinion would be the possibility to have two axis, left and right of the chart. Also a scrolling option.

Great work!
Guilherme

**Comment by imaNNeoFighT** [comment]
Hey, How’s it going?
Do you mean left and right titles?
about the scrolling, follow the [Roadmap](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/roadmap.md) we will implement zoom and scrolling ASAP.

**Comment by imaNNeoFighT** [comment]
Hey, any answer?

**Comment by gmaxferr** [comment]
Sorry about the delay, yes, as you have a left titles bar, yout could also alow have one at the right. This should be so that when having 2 lines in the chart, one of them references the left bar's values and the other references the right bar's values.

**Comment by imaNNeoFighT** [comment]
Hi,
about the left and right titles, I made a sample, check its source code and find out how can do that.
[<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_6.png" width="300" >](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#sample-6---reversed-source-code),

about the indicator, currently there are lots of critical features that we have to implement, then we can't investigate on it right now, maybe if requests for this feature raised, we add it in future.

and about the tooltip, I want to make some changes, and I will add a sample to check how you could do that.
Thanks for the contribution, Cheers!
