### ISSUE TITLE
touchedBarGroup 添加选中背景颜色设置

### ISSUE THREAD

**Issue by wukongssl** [imaNNeoFighT/fl_chart#365]
就是bargroup点击以后， 当前的选中的bargroup有明显的背景颜色，体现出选中效果

**Comment by imaNNeoFighT** [comment]
Speak English, please

**Comment by wukongssl** [comment]
**BarChartGroupData ,BarTouchData  touchCallback**   
Click to change the background color ，how to do?
thanks a million

**Comment by imaNNeoFighT** [comment]
Check this [sample](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#sample-1-source-code), here we change the foreground color, and for sure you can apply this approach for changing the background color too.

<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_1.gif" width="300" >
