### ISSUE TITLE
Question About Gradientfrom top to bottom  for lineChart Below bar data

### ISSUE THREAD

**Issue by charm-cloud** [imaNNeoFighT/fl_chart#367]
[line_chart_eg.txt](https://github.com/imaNNeoFighT/fl_chart/files/4719271/line_chart_eg.txt)

I tried above but ,but the first color is skipped. Thanks

**Comment by imaNNeoFighT** [comment]
what if you remove `gradientColorStops`?

**Comment by charm-cloud** [comment]
then only first color shows

**Comment by imaNNeoFighT** [comment]
Weird!

**Comment by imaNNeoFighT** [comment]
Try this:
`gradientColorStops: [0.3, 0.6, 0.7, 1]`

**Comment by charm-cloud** [comment]
If I make it [.6,.7,.9,1]  only then it shows,but data from api will be variable

**Comment by imaNNeoFighT** [comment]
Did you use this?
`gradientColorStops: [0.3, 0.6, 0.7, 1]`?

**Comment by charm-cloud** [comment]
yes ,

**Comment by charm-cloud** [comment]
[line_chart_eg_new.txt](https://github.com/imaNNeoFighT/fl_chart/files/4719785/line_chart_eg_new.txt)

**Comment by imaNNeoFighT** [comment]
You're welcome, and is that work?

**Comment by charm-cloud** [comment]
I get data from api and I map it.If the below graph area is too small(based on api data),the vertical gradient doesn't show properly. If the below graph area is high enough it works well I am not sure why is it so.Thanks for your help
