### ISSUE TITLE
PieChart does not repsonse on touch with only one section

### ISSUE THREAD

**Issue by attex** [imaNNeoFighT/fl_chart#368]
Hi there, 

i recently faced an issue with the piechart. 

`PieChart(
        PieChartData(
          sections: _showingSections(data),
          pieTouchData: PieTouchData(touchCallback: (pieTouchResponse) {
            setState(() {
             if (pieTouchResponse != null &&
                        pieTouchResponse.touchInput is! FlPanEnd &&
                        pieTouchResponse.touchInput is! FlLongPressEnd) {
                _touchedIndex = pieTouchResponse.touchedSectionIndex;
              }
            });
          }),
          borderData: FlBorderData(
            show: false,
          ),
          sectionsSpace: 0,
          centerSpaceRadius: 40,
        ),
      ),`

When there is only one section the `pieTouchResponse.touchedSectionIndex` returns null. 

Shouldn't it just return 0 ? 

Thanks in advance

**Comment by imaNNeoFighT** [comment]
Oh man, sorry about that,
It was an edge case, and thanks for reporting!

**Comment by imaNNeoFighT** [comment]
It will be fixed in the new version.

**Comment by imaNNeoFighT** [comment]
Check out the [0.10.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.10.1) version.
Cheers!

**Comment by makss68** [comment]
The same issue occurs when there are multiple sections but only one of them has a non-zero value.
