### ISSUE TITLE
Listen to normal tap on Tooltip instead of longpress

### ISSUE THREAD

**Issue by sukhcha-in** [imaNNeoFighT/fl_chart#37]
First of all, thank you for this amazing library <3

Please provide `onTap` option with some sort of `MoveUpdate` to show Tooltip on chart as an alternative to `onLongPress`

Looking forward for this library

**Comment by imsurajsharma** [comment]
Yes, I also want the same thing. Please provide that functionality.

**Comment by odonc** [comment]
Would be great, I don't know if user with realise they can long press to show tip. Normal press would be better.

**Comment by imaNNeoFighT** [comment]
I think it should handle out of the chart,
I mean you can tell to the chart, which  tooltip should be shown now, 
then you can keep the state of selected tooltip on your side,
and it is more customizable.
@Mazas17

**Comment by Mazas17** [comment]
Also sounds good

**Comment by MostHated** [comment]
To take this one further, I am wanting to use this on desktop. Is there a way to make it so that if a mouse is hovering over it, it shows all the time and follows the mouse as if you are holding down a press?

**Comment by imaNNeoFighT** [comment]
Yes, for sure we will add the Desktop compatibility,
I just need time :),
Also, all contributions are welcome,
give it a try!
@MostHated

**Comment by imaNNeoFighT** [comment]
Hi,
Unfortunately, Github started banning Iranian users while ago,
If they didn't stop their action, I can't continue on this repo,
read more it [here](https://medium.com/@hamed/github-blocked-my-account-and-they-think-im-developing-nuclear-weapons-e7e1fe62cb74),
If you want to prevent this unfair action, give a start on this [repository](https://github.com/1995parham/github-do-not-ban-us) and say your support by creating an issue, and spread it.
Best regards,
Iman Khoshabi

**Comment by dipendra-sharma** [comment]
`library fl_chart;

import 'package:flutter/material.dart';

import 'src/chart/bar_chart/bar_chart.dart';
import 'src/chart/base/base_chart/base_chart.dart';
import 'src/chart/base/base_chart/base_chart_painter.dart';
import 'src/chart/base/base_chart/touch_input.dart';
import 'src/chart/line_chart/line_chart.dart';
import 'src/chart/pie_chart/pie_chart.dart';

export 'src/chart/bar_chart/bar_chart.dart';
export 'src/chart/bar_chart/bar_chart_data.dart';
export 'src/chart/base/axis_chart/axis_chart_data.dart';
export 'src/chart/base/base_chart/base_chart_data.dart';
export 'src/chart/base/base_chart/touch_input.dart';
export 'src/chart/line_chart/line_chart.dart';
export 'src/chart/line_chart/line_chart_data.dart';
export 'src/chart/pie_chart/pie_chart.dart';
export 'src/chart/pie_chart/pie_chart_data.dart';

/// A base widget that holds a [BaseChart] class
/// that contains [BaseChartPainter] extends from [CustomPainter]
/// to paint the relative content on our [CustomPaint] class
/// [BaseChart] is an abstract class and we should use a concrete class
/// such as [LineChart], [BarChart], [PieChart].
class FlChart extends StatefulWidget {
  final BaseChart chart;
  var enableTap;

  FlChart({
    Key key,
    @required this.chart,
    this.enableTap = true,
  }) : super(key: key) {
    if (chart == null) {
      throw Exception('chart should not be null');
    }
  }

  @override
  State<StatefulWidget> createState() => _FlChartState();
}

class _FlChartState extends State<FlChart> {
  ///We will notify Touch Events through this Notifier in form of a [FlTouchInput],
  ///then the painter returns touched details through a StreamSink.a
  FlTouchInputNotifier _touchInputNotifier;

  @override
  void initState() {
    super.initState();
    _touchInputNotifier = FlTouchInputNotifier(null);
  }

  @override
  Widget build(BuildContext context) {
    return widget.enableTap ? _widgetWithTap() : _widgetWithLongPress();
  }

  Widget _widgetWithTap() {
    Offset _offset;
    return GestureDetector(
      onHorizontalDragEnd: (d) {
        _touchInputNotifier.value = FlLongPressEnd(
          _globalToLocal(context, _offset),
        );
      },
      onHorizontalDragStart: (d) {
        _touchInputNotifier.value = FlLongPressStart(
          _globalToLocal(context, d.globalPosition),
        );
      },
      onHorizontalDragUpdate: (d) {
        _offset = d.globalPosition;
        _touchInputNotifier.value = FlLongPressMoveUpdate(
          _globalToLocal(context, d.globalPosition),
        );
      },
      child: CustomPaint(
        painter: widget.chart.painter(
          touchInputNotifier: _touchInputNotifier,
          touchResponseSink: widget.chart
              .getData()
              .touchData
              .touchResponseSink,
        ),
      ),
    );
  }

  Widget _widgetWithLongPress() {
    return GestureDetector(
      onLongPressStart: (d) {
        _touchInputNotifier.value = FlLongPressStart(
          _globalToLocal(context, d.globalPosition),
        );
      },
      onLongPressEnd: (d) {
        _touchInputNotifier.value = FlLongPressEnd(
          _globalToLocal(context, d.globalPosition),
        );
      },
      onLongPressMoveUpdate: (d) {
        _touchInputNotifier.value = FlLongPressMoveUpdate(
          _globalToLocal(context, d.globalPosition),
        );
      },
      child: CustomPaint(
        painter: widget.chart.painter(
          touchInputNotifier: _touchInputNotifier,
          touchResponseSink: widget.chart
              .getData()
              .touchData
              .touchResponseSink,
        ),
      ),
    );
  }

  Offset _globalToLocal(BuildContext context, Offset globalPosition) {
    final RenderBox box = context.findRenderObject();
    return box.globalToLocal(globalPosition);
  }

  @override
  void dispose() {
    super.dispose();
    _touchInputNotifier.dispose();
  }
}
`

**Comment by dipendra-sharma** [comment]
Update fl_chart main widget as per your uses;

`Widget _widgetWithTap() {
    Offset _offset;
    return GestureDetector(
      onHorizontalDragEnd: (d) {
        _touchInputNotifier.value = FlLongPressEnd(
          _globalToLocal(context, _offset),
        );
      },
      onHorizontalDragStart: (d) {
        _touchInputNotifier.value = FlLongPressStart(
          _globalToLocal(context, d.globalPosition),
        );
      },
      onHorizontalDragUpdate: (d) {
        _offset = d.globalPosition;
        _touchInputNotifier.value = FlLongPressMoveUpdate(
          _globalToLocal(context, d.globalPosition),
        );
      },
      child: CustomPaint(
        painter: widget.chart.painter(
          touchInputNotifier: _touchInputNotifier,
          touchResponseSink: widget.chart
              .getData()
              .touchData
              .touchResponseSink,
        ),
      ),
    );
  }`

**Comment by dipendra-sharma** [comment]
Replace your fl_chart.dart with attached file (Remove .txt).
[fl_chart.dart.txt](https://github.com/imaNNeoFighT/fl_chart/files/3451322/fl_chart.dart.txt)

**Comment by odonc** [comment]
Are you getting shut down?

**Comment by sukhcha-in** [comment]
@dipendra-sharma Thank you, works as expected ;)

**Comment by MostHated** [comment]
> Yes, for sure we will add the Desktop compatibility,
> I just need time :),
> Also, all contributions are welcome,
> give it a try!
> @MostHated

I am having a go at this to see what I can come up with.

**Comment by imaNNeoFighT** [comment]
No, I will not shut down this repo, I just need some free times to improve it
@odonc

**Comment by dipendra-sharma** [comment]
Hi, @imaNNeoFighT Please add me in contributors. I've already done it, will create a PR. Both the features will be there Long press & Tap.

**Comment by imaNNeoFighT** [comment]
You can make a PR already,
clone the project,
make a new branch,
push your changes to each branch separately (or maybe both of them in one branch),
then make a PR from your Repo branch to This Repo master branch.
@dipendra-sharma

**Comment by dipendra-sharma** [comment]
> > Yes, for sure we will add the Desktop compatibility,
> > I just need time :),
> > Also, all contributions are welcome,
> > give it a try!
> > @MostHated
> 
> I am having a go at this to see what I can come up with.
> 
> I tried adding/changing this below. It works, but the position available for Listeners vs Gesture is only d.position and d.localPosition, so it kind of acts weird and some of the points jump to another spot on the graph with 3 lines when you get close to them slowly, lol.
> 
> I want to try a few things first to see if there is a way to fix the position before I do a PR.
> 
> ```dart
> class FlChart extends StatefulWidget {
>   final BaseChart chart;
>   var enableTap;
>   var enablePointer;
> 
>   FlChart({
>     Key key,
>     @required this.chart,
>     this.enableTap = true,
>     this.enablePointer = true,
>   }) : super(key: key) {
>     if (chart == null) {
>       throw Exception('chart should not be null');
>     }
>   }
> ```
> 
> ```dart
>   @override
>   Widget build(BuildContext context) {
>     return widget.enablePointer ? _withPointerInput() : widget.enableTap ? _widgetWithTap() : _widgetWithLongPress();
>   }
> ```
> 
> ```dart
>   Widget _withPointerInput() {
>     return Listener(
>       onPointerEnter: (d) {
>         _touchInputNotifier.value = FlLongPressStart(
>           _globalToLocal(context, d.localPosition),
>         );
>       },
>       onPointerHover: (d) {
>         _touchInputNotifier.value = FlLongPressMoveUpdate(
>           _globalToLocal(context, d.localPosition),
>         );
>       },
>       onPointerExit: (d) {
>         _touchInputNotifier.value = FlLongPressEnd(
>           _globalToLocal(context, d.localPosition),
>         );
>       },
>       child: CustomPaint(
>         painter: widget.chart.painter(
>           touchInputNotifier: _touchInputNotifier,
>           touchResponseSink: widget.chart.getData().touchData.touchResponseSink,
>         ),
>       ),
>     );
>   }
> ```

@MostHated Have you tested it? it is not working on iPhone 7.

**Comment by dipendra-sharma** [comment]
@imaNNeoFighT 

Remote: Permission to imaNNeoFighT/fl_chart.git denied to dipendra-sharma. unable to access 'https://github.com/imaNNeoFighT/fl_chart.git/': The requested URL returned error: 403

**Comment by imaNNeoFighT** [comment]
Sorry you have to firstly fork it in your profile,
Then clone it and...

**Comment by MostHated** [comment]
> > > Yes, for sure we will add the Desktop compatibility,
> > > I just need time :),
> > > Also, all contributions are welcome,
> > > give it a try!
> > > @MostHated
> > 
> > 
> > I am having a go at this to see what I can come up with.
> > I tried adding/changing this below. It works, but the position available for Listeners vs Gesture is only d.position and d.localPosition, so it kind of acts weird and some of the points jump to another spot on the graph with 3 lines when you get close to them slowly, lol.
> > I want to try a few things first to see if there is a way to fix the position before I do a PR.
> > ```dart
> > class FlChart extends StatefulWidget {
> >   final BaseChart chart;
> >   var enableTap;
> >   var enablePointer;
> > 
> >   FlChart({
> >     Key key,
> >     @required this.chart,
> >     this.enableTap = true,
> >     this.enablePointer = true,
> >   }) : super(key: key) {
> >     if (chart == null) {
> >       throw Exception('chart should not be null');
> >     }
> >   }
> > ```
> > 
> > 
> > ```dart
> >   @override
> >   Widget build(BuildContext context) {
> >     return widget.enablePointer ? _withPointerInput() : widget.enableTap ? _widgetWithTap() : _widgetWithLongPress();
> >   }
> > ```
> > 
> > 
> > ```dart
> >   Widget _withPointerInput() {
> >     return Listener(
> >       onPointerEnter: (d) {
> >         _touchInputNotifier.value = FlLongPressStart(
> >           _globalToLocal(context, d.localPosition),
> >         );
> >       },
> >       onPointerHover: (d) {
> >         _touchInputNotifier.value = FlLongPressMoveUpdate(
> >           _globalToLocal(context, d.localPosition),
> >         );
> >       },
> >       onPointerExit: (d) {
> >         _touchInputNotifier.value = FlLongPressEnd(
> >           _globalToLocal(context, d.localPosition),
> >         );
> >       },
> >       child: CustomPaint(
> >         painter: widget.chart.painter(
> >           touchInputNotifier: _touchInputNotifier,
> >           touchResponseSink: widget.chart.getData().touchData.touchResponseSink,
> >         ),
> >       ),
> >     );
> >   }
> > ```
> 
> @MostHated Have you tested it? it is not working on iPhone 7.

I would assume that is because iPhone does not have a pointer. It uses touch/ gesture. Pointer is for desktop platform.  It works for me on both go-flutter and flutter- desktop- embedded

**Comment by dipendra-sharma** [comment]
@MostHated Pointer was not working on the iPhone device.

**Comment by MostHated** [comment]
Yes, did you read my explanation above?

**Comment by imaNNeoFighT** [comment]
Hi, thanks all for your patience,
It is added in [0.1.6](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.1.6), If you had any feedback, feel free to let me know.
and also there are a lot of features to implement and pull requests are welcome.
Best regards!

**Comment by jlubeck** [comment]
@imaNNeoFighT was the MouseOver on desktop that was mentioned by @MostHated ?
I can't seem to find it in the code or documentation...

thanks!

**Comment by imaNNeoFighT** [comment]
Hi @jlubeck 
At the moment our main focus is on the Quality and Stability in the android and iOS,
even though, we will focus on web and desktop, when they are stabled in the Flutter.
Thanks for reaching me out.

**Comment by imaNNeoFighT** [comment]
Also, feel free to make an issue about it,
we can follow it up there.

**Comment by jlubeck** [comment]
Ok, I was asking mainly because @MostHated seemed to had it working... I'll create the new ticket. Thank you

**Comment by imsurajsharma** [comment]
> I've done this enhancement. Replace your fl_chart.dart with attached file (Remove .txt).
> [fl_chart.dart.txt](https://github.com/imaNNeoFighT/fl_chart/files/3451322/fl_chart.dart.txt)

Thanks for this. But It throws error in v0.9.4 . When I try to add the same it throws error while building package. The owner remove this changes in new version. @imaNNeoFighT please add this feature in the current version. As, it is useful for us. 

Also, when I try to use[ v0.1.6](https://github.com/imaNNeoFighT/fl_chart/issues/37#issuecomment-521785965) in which you made changes. That package won't work for me as I made my graph using the latest version. So, old version is not working either.
