### ISSUE TITLE
Tooltip Position

### ISSUE THREAD

**Issue by danielhdezs** [imaNNeoFighT/fl_chart#371]
Hi,

I was wondering if there is a way to control the position of the tooltip. 

It shows OK when the values are in the bottom
![Screenshot_1591226618](https://user-images.githubusercontent.com/46684523/83698712-5ca6e700-a5bf-11ea-8ba1-cd83fdcc52a0.png)
but it disappears when it is on the top
![Screenshot_1591226631](https://user-images.githubusercontent.com/46684523/83698785-895afe80-a5bf-11ea-9d9f-ad1513055f2f.png)

Thanks,

**Comment by imaNNeoFighT** [comment]
Hi,
You can use [LineTouchTooltipData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetouchtooltipdata).`fitInsideVertically` to force it to show in the screen.
