### ISSUE TITLE
how to remove or hide decimal place 

### ISSUE THREAD

**Issue by VarmaTech** [imaNNeoFighT/fl_chart#373]
HI ,
i have to show count as Y axis but it accepting only double instead of int , so its showing decimal place as show in image , so how to remove the decimal place as i need to show count value
Like 51  76   instead of 51.0 76.0

![image](https://user-images.githubusercontent.com/16360182/83969346-23d37e80-a8ed-11ea-925e-1af6c658bf17.png)

**Comment by kdmatrosov** [comment]
You can use `barTouchData`->`BarTouchTooltipData` properties and describe your own format with **getTooltipItem**

**Comment by imaNNeoFighT** [comment]
Yes that's right,
Thanks @kdmatrosov
