### ISSUE TITLE
Cant set padding from pie chart sections

### ISSUE THREAD

**Issue by benthemobileguy** [imaNNeoFighT/fl_chart#377]
I am trying to set some padding or saving for my pie chart sections/items. I did not like the idea of the clustered together. I tried doing this with the "sectionsSpace" property inside "PieChartData" bt it does not get effected. Please help.

**Comment by imaNNeoFighT** [comment]
Hi, as we mentioned [here](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/pie_chart.md#piechartdata), you can set `centerSpaceRadius` to `double.nan` to let the library calculate the centerSpaceRadius, in that way padding will be applied.
Does it make sense?
Do you think we should use `double.infinity` instead?

**Comment by imaNNeoFighT** [comment]
BTW, you should use `double.infinity` instead or `double.nan` in the new version.
Cheers!

**Comment by imaNNeoFighT** [comment]
Check out the [0.10.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.10.1) version.
Cheers!
