### ISSUE TITLE
Show custom data on Tooltip from both axis

### ISSUE THREAD

**Issue by sukhcha-in** [imaNNeoFighT/fl_chart#38]
Hello, Can we pass custom data to Tooltip?
For example i want to show `5 Jul: ₹200` on tooltip instead of `200.0`
Like i also want to grab some data from horizontal axis to show date and also the price from vertical axis.

To achieve this i think i have to pass all of my hotizontal axis values and then `onLongPress` i have to get data from it.
If i add all of my `Date` data to horizontal axis, it gets overlapped.
Like this:
![Demo](https://i.imgur.com/0kdnQrb.jpg)
Can you please add option to set how many values developer wants to show on chart, so that remaining values remain hidden instead of overlapping? Same thing on vertical axis will be a PlusPlus.

**Comment by imaNNeoFighT** [comment]
Hi, 
Does it help you?
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_3.gif" width="300" >
If yes, check the [source code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample3.dart),
I didn't get your next question.

**Comment by sukhcha-in** [comment]
Thank you i have figured out both things.

**Comment by enricobenedos** [comment]
Hi guys, if you want I can create a new issue but I think we can reuse it.
I have a problem with the tooltip values. I'm trying to change the numeric value mantaining the beautiful standard text color.
This is my chart:
![image](https://user-images.githubusercontent.com/12233746/64441554-6651fb80-d0ce-11e9-95f7-c5e1fb4aca6a.png)
It is perfect, I need only to apply this formula to the two double values: (value*5)/100.
I've tried to do that using the `TouchTooltipData` class but I don't understand how to mantain the two original colors.
Can anyone please help me?

**Comment by imaNNeoFighT** [comment]
Hi @enricobenedos, do you want to change the opacity of the tooltip texts color?

**Comment by enricobenedos** [comment]
Hi, I need to know how to change the tooltip value. For example from 2.5 to 25, but maintaining the text style.

**Comment by imaNNeoFighT** [comment]
Ok, got it, check this [sample](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#sample-1-source-code), we changed the text of tooltip, (this is a bar chart, but the tooltip is the same in the line chart)
@enricobenedos

**Comment by enricobenedos** [comment]
I already tried this. It works but in this way I will lose the inherited text style. In my case 3.025 --> blue and 2.5 --> green

**Comment by imaNNeoFighT** [comment]
I know, but you can set any [TextStyle](https://api.flutter.dev/flutter/dart-ui/TextStyle-class.html) with a custom color that you want in the [TooltipItem](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#tooltipitem),
I use the line color for showing related text, you can do it by yourself.
Does it make sense?

**Comment by enricobenedos** [comment]
It make sense! My problem was the colors, now finally I understood how to retrieve the colors calling `touchedSpot.getColor()`

```dart
lineTouchData: LineTouchData(touchTooltipData:
                                      TouchTooltipData(
                                          getTooltipItems: (touchedSpots) {
                                    return touchedSpots.map((touchedSpot) {
                                      return TooltipItem(
                                          touchedSpot.spot.y.toString(),
                                          TextStyle(
                                              color: touchedSpot.getColor(),
                                              fontWeight: FontWeight.bold));
                                    }).toList();
                                  })),
```
