### ISSUE TITLE
How to enable Pinch Zoom and Pan for line chart.

### ISSUE THREAD

**Issue by Saran90** [imaNNeoFighT/fl_chart#380]

**Comment by imaNNeoFighT** [comment]
Hi, Unfortunately, we didn't implement this feature yet.
Stay tuned!

**Comment by Saran90** [comment]
That could make this a complete library. Eagerly waiting for that. Cheers

**Comment by fvisticot** [comment]
adding this feature would be awesome !! it is required for many projets. Can you please plan this enhancement ?

**Comment by thermoChas** [comment]
Any update on this?

**Comment by imaNNeoFighT** [comment]
Follow it up in #71.
Don't forget to thumbs it up
