### ISSUE TITLE
Unable to control chart size in flutter web

### ISSUE THREAD

**Issue by EsCharlo** [imaNNeoFighT/fl_chart#383]
When I create a line chart, I try to implement it inside a container, but either way the chart takes up the entire screen instead of just the container space

flutter web user

**Comment by imaNNeoFighT** [comment]
Hi, at the moment, we have changed our draw approach. Now we use RenderObjects for drawing, sizing, and touches. (previously, we used CustomPainter).
RenderObjects is more stable and error-prone. Please check this issue with our new release [0.30.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.30.0). Let me know whether it has been fixed or not.
