### ISSUE TITLE
ScatterSpot "show" value seems to be ignored?

### ISSUE THREAD

**Issue by cudajo** [imaNNeoFighT/fl_chart#385]
I'm creating a `ScatterChart` with `ScatterChartData` that contains multiple `ScatterSpot`s. 
Despite setting show to `false` for some of these spots, they are shown anyway.

Example: 
`ScatterSpot(0, 0, show: false);`
`ScatterSpot(10, 10, show: true);`

Result: Both ScatterSpots are shown...

**Comment by imaNNeoFighT** [comment]
Fixed in [0.11.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.11.0),
Thanks for reporting!
