### ISSUE TITLE
BarChart slide

### ISSUE THREAD

**Issue by liuswong** [imaNNeoFighT/fl_chart#387]
BarChart Whether it can display fixed data, if it exceeds, you can slide it left and right

**Comment by imaNNeoFighT** [comment]
Sorry, I didn't get you,
could you please explain it?

**Comment by liuswong** [comment]
![image](https://user-images.githubusercontent.com/18181024/87282320-bc7d9f80-c526-11ea-8286-84cfee039c84.png)
There are only 5 sets of data displayed here, if it is exceeded, can you swipe left and right to view more data,

**Comment by liuswong** [comment]
I solved the problem by flipping the data into barchart, wrapping a Container with a width set to 75 8 list.length, and wrapping a sliding SingleChildScrollView with scrollDirection: Axis.horizontal, you can perform data beyond the screen. Swipe
