### ISSUE TITLE
Label in the center of Pie Chart

### ISSUE THREAD

**Issue by guigzp** [imaNNeoFighT/fl_chart#388]
It would be nice if we could add a Widget in the center of the donut.

**Comment by imaNNeoFighT** [comment]
Hi, you can wrap your PieCart in a Stack widget, then put your second widget in the middle to achieve your result.

**Comment by imaNNeoFighT** [comment]
Hi, you can wrap your PieCart in a Stack widget, then put your second widget in the middle to achieve your result.

**Comment by imaNNeoFighT** [comment]
Hi, you can wrap your PieCart in a Stack widget, then put your second widget in the middle to achieve your result.
