### ISSUE TITLE
Disable animation

### ISSUE THREAD

**Issue by Moaminv** [imaNNeoFighT/fl_chart#389]
Hello. is it possible to disable animation in line_chart_sample2?

**Comment by imaNNeoFighT** [comment]
Yes, as we mentioned [here](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/handle_animations.md) (read the last line)
just set `swapAnimationDuration` to Duration.zero,

```
LineChart(
  showAvg ? avgData() : mainData(),
  swapAnimationDuration: Duration.zero,
),
```
