### ISSUE TITLE
LineCharts, get touched line

### ISSUE THREAD

**Issue by AtomicNicos** [imaNNeoFighT/fl_chart#390]
I've wanted to do the LineChart line highlight on hover, but I can't get the actual touched line, just all the lines / points at the x-coordinate that was hovered.

Like with PieCharts, it would be awesome if the lineTouchResponse would also enable getting the exact line that was touched (or closest), either by reference or by index.

**Comment by imaNNeoFighT** [comment]
Got it, and it's a great feature,
We will consider it ASAP.
Thanks!

**Comment by imaNNeoFighT** [comment]
In the [LineTouchResponse](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetouchresponse), we have a list of [LineBarSpot](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#LineBarSpot), which click happens on.

You can find `bar`, and `barIndex` in LineBarSpot.
