### ISSUE TITLE
custom BarTooltipItem as per BarChartRodStackItem

### ISSUE THREAD

**Issue by harishrathi** [imaNNeoFighT/fl_chart#393]
As per the current implementation of `BarTooltipItem`, the function to customize the tooltip is as below

`BarTooltipItem touchTooltipData(BarChartGroupData group, int groupIndex, BarChartRodData rod, int rodIndex)`

The callback is missing the index for `stack` position, because of this the tooltip cannot be customized as per stack position. 

**Versions**
 - Flutter: 1.17.5
 - FlChart: 0.10.1

**Comment by imaNNeoFighT** [comment]
Added `touchedStackItem` and `touchedStackItemIndex` properties in the [BarTouchedSpot ](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#bartouchedspot),
check it out in the [0.11.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.11.0) version.
Thanks for your suggestion!

**Comment by harishrathi** [comment]
But this still does not help with tooltop, I am specifically talking about callback defined to get tooltip text...  
`BarTooltipItem touchTooltipData(BarChartGroupData group, int groupIndex, BarChartRodData rod, int rodIndex)`, 

Can you pass `BarTouchedSpot` to `BarTouchData(touchTooltipData)`? It would be a breaking change, but would be better than having 6 parameters to a function.
