### ISSUE TITLE
Showing A tooltip based on touch event on a rod 

### ISSUE THREAD

**Issue by pradt** [imaNNeoFighT/fl_chart#397]
I'm guessing this is not a bug but a problem with my code/config of fl_chart. I trying to shop the tooltip based on the user touching the rod. I've had a look at Sample 1 of the Line Graph. However, I'm either showing the tooltip for all the rods or none at all. 

In touchCallBack - I'm seeing that its called multiple times - first time I'm able to set the touchIndex and the second time I'm not able to : 

`BarChartData(
                  alignment: BarChartAlignment.spaceAround,
                  maxY: _getMax(),
                  barTouchData: BarTouchData(
                    handleBuiltInTouches: true,
                    touchCallback: (response) {
                      print('touchcallback');

                      setState(() {
                        if (response.spot != null &&
                            response.touchInput is! FlPanEnd &&
                            response.touchInput is! FlLongPressEnd) {
                          touchedIndex = response.spot.touchedBarGroupIndex;
                        } else {
                          touchedIndex = -1;
                        }
                        print('TouchIndex $touchedIndex ');
                      });
                    },
                    enabled: true,
                    touchTooltipData: BarTouchTooltipData(
                      tooltipRoundedRadius: 4,
                      tooltipBgColor: Colors.blueGrey,
                      tooltipPadding: const EdgeInsets.all(0),
                      tooltipBottomMargin: 8,
                      getTooltipItem: (
                        BarChartGroupData group,
                        int groupIndex,
                        BarChartRodData rod,
                        int rodIndex,
                      ) {
                        //print('click - ${rod.y.toString()}');
                        //print('Same $touchedIndex and $rodIndex');
                        if (touchedIndex == rodIndex) {
                          print('Same $touchedIndex and ${rod.y.toString()}');
                          
                          return BarTooltipItem(
                            "\$ ${rod.y.round().toString()}",
                            TextStyle(
                              color: Colors.yellow,
                              fontWeight: FontWeight.bold,
                            ),
                          );

                        }
                      },
                    ),
                  ),
                  titlesData: FlTitlesData(
                    show: true,
                    bottomTitles: SideTitles(
                      showTitles: true,
                      textStyle: TextStyle(
                          color: const Color(0xff7589a2),
                          fontWeight: FontWeight.bold,
                          fontSize: 14),
                      margin: 10,
                      getTitles: (double value) {
                        switch (value.toInt()) {
                          case 0:
                            return 'J';
                          case 1:
                            return 'F';
                          case 2:
                            return 'M';
                          case 3:
                            return 'A';
                          case 4:
                            return 'M';
                          case 5:
                            return 'J';
                          case 6:
                            return 'J';
                          case 7:
                            return 'A';
                          case 8:
                            return 'S';
                          case 9:
                            return 'O';
                          case 10:
                            return 'N';
                          case 11:
                            return 'D';
                          default:
                            return '*';
                        }
                      },
                    ),
                    leftTitles: SideTitles(
                      showTitles: false,
                      textStyle: const TextStyle(
                          color: Color(
                            0xff939393,
                          ),
                          fontSize: 1),
                      margin: 0,
                    ),
                  ),
                  borderData: FlBorderData(
                    show: false,
                  ),
                  barGroups: _buildBarGroups(),
                ),`

This is the output from a single touch : 

> flutter: touchcallback
> flutter: TouchIndex 2
> flutter: touchcallback
> flutter: TouchIndex -1

**Comment by pradt** [comment]
@imaNNeoFighT  sorry, I thought I had added as much information as possible - is there anything else I should add ?

**Comment by harishrathi** [comment]
If I understand correct, `touchTooltipData` is missing information about the `stacked rod item` being touched.

**Comment by imaNNeoFighT** [comment]
Aha, got it,
I see this behaviour of touching, and at the moment it is okay and it does not make any problem.
We should improve our touching flow, and then this behaviour will be fixed ASAP.
Thanks for reporting!

**Comment by harishrathi** [comment]
adding rod index to `touchTooltipData / getTooltipItem` should resolve the issue
