### ISSUE TITLE
how to show all tooltip data

### ISSUE THREAD

**Issue by jitenders859** [imaNNeoFighT/fl_chart#40]
I want to show all the tooltip data not by pressing but showing all by default how to do it.

**Comment by imaNNeoFighT** [comment]
There is no way right now,
but we can investigate it,
stay tuned!

**Comment by Keanyuan** [comment]
wo can use onTapDown or onTapUp get TapDownDetails
      onTapDown: (d){
        _touchInputNotifier.value = FlLongPressStart(
          _globalToLocal(context, d.globalPosition),
        );
      },
//      onLongPressStart: (d) {
//        _touchInputNotifier.value = FlLongPressStart(
//          _globalToLocal(context, d.globalPosition),
//        );
//      },
//      onLongPressEnd: (d) {
//        _touchInputNotifier.value = FlLongPressEnd(
//          _globalToLocal(context, d.globalPosition),
//        );
//      },
//      onLongPressMoveUpdate: (d) {
//        _touchInputNotifier.value = FlLongPressMoveUpdate(
//          _globalToLocal(context, d.globalPosition),
//        );
//      },

**Comment by imaNNeoFighT** [comment]
I know, but it needs more changes,
for now, everybody can fork and edit the repo like you said until I add them in the next version.
@Keanyuan

**Comment by imaNNeoFighT** [comment]
Hi,
Unfortunately, Github started banning Iranian users while ago,
If they didn't stop their action, I won't continue on this repo and maybe,
read more [here](https://medium.com/@hamed/github-blocked-my-account-and-they-think-im-developing-nuclear-weapons-e7e1fe62cb74),
and If you want to prevent this unfair action, give a start to this [repository](https://github.com/1995parham/github-do-not-ban-us) and say your support by creating an issue, and spread it.
Best regards,
Iman Khoshabi

**Comment by imaNNeoFighT** [comment]
As I don't have enough time to do resolve all of issues,

**Comment by imaNNeoFighT** [comment]
Hi, I am back after 3 months :)
sorry for the delay, I was as busy as bee.
In [0.4.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.4.0) we have added `showingTooltipIndicators` and `showingIndicators`, and now you can show any of tooltips or indicators manually.
Also, I demonstrated it in the [LineChart Sample5](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#sample-5-source-code).


<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_5.png" width="300" >

Thanks for being patient.
