### ISSUE TITLE
Press and hold the chart and slide left and right to display related data dynamically. Just like the iOS stock app.

### ISSUE THREAD

**Issue by zxl777** [imaNNeoFighT/fl_chart#402]
Press and hold the chart and slide left and right to display related data dynamically. Just like the iOS stock app.

**Comment by zxl777** [comment]
I have a suggestion: 
Press and hold any position to instantly display valid data or not show nothing. 
The program can automatically jump to the nearest point with data.

**Comment by imaNNeoFighT** [comment]
Sorry I didn't get you,
can you explain it more?
