### ISSUE TITLE
Bar graphs draw below the bottom axis when minY is set

### ISSUE THREAD

**Issue by blough** [imaNNeoFighT/fl_chart#404]
When using a bar graph, if the minY value is set on the BarGraphData then the bars draw below the bottom axis covering the titles.

The can be reproduced with the example application.  Open the file bar_chart_sample3.dart and add `minY: 5` at line 21 (just above the line `maxY: 20`).

Here is how it looks without a maxY value set
<img width="317" alt="no minY" src="https://user-images.githubusercontent.com/55713224/88826887-44a2ac80-d197-11ea-9662-dc9e91399955.png">

Here is how it looks with a maxY set to 5
<img width="317" alt="minY set to 5" src="https://user-images.githubusercontent.com/55713224/88826970-584e1300-d197-11ea-8024-4a0351994795.png">

Flutter 1.17.5 
FlChart 0.11.0

Thank you for a great library!

**Comment by blough** [comment]
Would it work to change line 237 of bar_chart_painter.dart (https://github.com/imaNNeoFighT/fl_chart/blob/master/lib/src/chart/bar_chart/bar_chart_painter.dart#L237) from

`final bottom = getPixelY(0, drawSize);` 
to 
`final bottom = getPixelY(data.minY ?? 0, drawSize);`

to fix the issue?

**Comment by imaNNeoFighT** [comment]
Hi, sorry for the late answer,
you are exactly right, and you got it. 
Make a PR and fix it by yourself :)
Also, you should fix this issue for the negative values too (check line [247](https://github.com/imaNNeoFighT/fl_chart/blob/master/lib/src/chart/bar_chart/bar_chart_painter.dart#L247) too)
Thanks for reporting and contributing.
Cheers!

**Comment by imaNNeoFighT** [comment]
And thanks for your great explanation.

**Comment by ulusoyca** [comment]
@imaNNeoFighT Thanks for the answer. Looks like our project is blocked by this issue. Do you have any updates?

**Comment by imaNNeoFighT** [comment]
Okay, 
I'm on it :)

**Comment by imaNNeoFighT** [comment]
Sorry for the delay, fixed in [0.11.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.11.1), 
check it out.

Thanks for reporting and contributing.

**Comment by ulusoyca** [comment]
@imaNNeoFighT Thanks for the effort. Much appreciated!
