### ISSUE TITLE
Hide values outside of min & max in LineChartData

### ISSUE THREAD

**Issue by Jon1105** [imaNNeoFighT/fl_chart#405]
When data is more or less than the applied min and max values, the lines overflow out of the designated area of the graph. 
I have tried wrapping the chart in a clipRRect and it did remove all overflow. However some axes labels were being cut and the touch tool tip was being cut or not shown at all.

**Comment by imaNNeoFighT** [comment]
Hi,
Did you try to set `clipData` in the [LineChartData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartdata)?
