### ISSUE TITLE
How to scroll horizontally if there is too much data on the horizontal axis?

### ISSUE THREAD

**Issue by ProFive** [imaNNeoFighT/fl_chart#407]
Hi Guys, 
Please help me with how to scroll horizontally data inside the content char.

<img width="337" alt="Screen Shot 2020-08-12 at 1 41 49 PM" src="https://user-images.githubusercontent.com/5170616/89983442-c1f31480-dca1-11ea-8220-ce49af96528c.png">

**Comment by imaNNeoFighT** [comment]
Dup of #71
