### ISSUE TITLE
Scrollable chart

### ISSUE THREAD

**Issue by matthewmiddlebrook-acu** [imaNNeoFighT/fl_chart#41]
I'd love to be able to have a chart where you can horizontally (or vertically) scroll to show more data. Probably to keep the interactability there would have to be a scrollbar you'd drag. I guess currently you could do something similar but the axis labels would disappear.

Whelp looks like this has already been said. Oops...

**Comment by imaNNeoFighT** [comment]
Hi, as you now we have a [roadMap](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/roadmap.md) here, and one of our goals is `Add Zoom feature`, for sure when we have zoom feature, we need to have scroll feature too,
Then I will close it to keep the issue list clean.
