### ISSUE TITLE
How to access BarTouchResponse from within getTooltipItem

### ISSUE THREAD

**Issue by tanzilzubair** [imaNNeoFighT/fl_chart#422]
I need the touchedStackItem's values to display in the tooltip, but it seems that I can't pass it into the tooltip, and there's no way to access it from within getTooltipItem. Pease help

**Comment by imaNNeoFighT** [comment]
We have `touchedStackItem`, and `touchedStackItemIndex` in [BarTouchedSpot](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#BarTouchedSpot) which you can use.
