### ISSUE TITLE
Change bar color and below bar area color

### ISSUE THREAD

**Issue by Uraskin** [imaNNeoFighT/fl_chart#423]
When I touch chart I need to change bar color and below bar area color.

**Comment by Uraskin** [comment]
[https://github.com/imaNNeoFighT/fl_chart/pull/420]

**Comment by imaNNeoFighT** [comment]
Check [this implementation](https://gist.github.com/imaNNeoFighT/2ed984a72781641cceab55a8a94cb7e6) without any change on the fl_chart.

![line-dynamic-color](https://user-images.githubusercontent.com/7009300/111377370-cd824000-86b5-11eb-9e41-f507cfad79eb.gif)
