### ISSUE TITLE
Scatter chart with String/date label in xAxis

### ISSUE THREAD

**Issue by Mehta2015** [imaNNeoFighT/fl_chart#430]
I want to set xAxis lable as shown in image. Is there any way to set String or Datetime lable in xAxis of Scatter chart. 

![image](https://user-images.githubusercontent.com/13146176/91849283-710b8600-ec79-11ea-881a-ad4b371b415c.png)

**Comment by Ehouman09** [comment]
Hello @Mehta2015 , have you found a solution ?

**Comment by imaNNeoFighT** [comment]
Check `getTitles` in FlTitlesData.

##### [Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample2.dart)
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_2.gif" width="300" >
