### ISSUE TITLE
Display data in the ToolTip that is different than the value of the point?

### ISSUE THREAD

**Issue by johnwiese-ms** [imaNNeoFighT/fl_chart#431]
Is it possible to display something other than the value of the point in the tooltip?  If so how?  For instance, let's say I'm showing golf scores on a linechart but I want to also show the score relative to par.  I could just have 2 different charts, but ideally I could just show the score relative to par in the tooltip .  So while the dot is at a Y value of 37, the tooltip would show +2.

I haven't been able to figure out if this is possible.

**Comment by imaNNeoFighT** [comment]
Hi there,
Did you check [this](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#sample-3-source-code) sample?

##### Sample 3 ([Source Code](/example/lib/line_chart/samples/line_chart_sample3.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_3.gif" width="300" >

**Comment by johnwiese-ms** [comment]
Thanks, not sure how I missed that one.
