### ISSUE TITLE
Get index of stack on touch

### ISSUE THREAD

**Issue by guigzp** [imaNNeoFighT/fl_chart#432]
It would be nice if the touch callback in a Stacked Bar Chart returned the index of the stack that was touched. That way i could change the events based on which part of the bar was touched.

As an example, i'm trying to show different tooltips in this chart, one for the deep purple and other for the light purple.

![flutter_01](https://user-images.githubusercontent.com/33470622/91896562-76fc6980-ec6f-11ea-8d09-b0a660d70dc7.png)

**Comment by imaNNeoFighT** [comment]
We have `touchedStackItem`, and `touchedStackItemIndex` in [BarTouchedSpot](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#BarTouchedSpot) which you can use.
