### ISSUE TITLE
Animation Curve For Swap Animation

### ISSUE THREAD

**Issue by eli-front** [imaNNeoFighT/fl_chart#436]
Instead of a linear animation for the chart swap animation, there should be an option to create a Curved Animation (Ex: Ease In or Ease Out).

**Comment by imaNNeoFighT** [comment]
That's a great and simple feature!

**Comment by wandbrandon** [comment]
any update on this?

**Comment by imaNNeoFighT** [comment]
`swapAnimationCurve` property added in all of our chart widgets.
Check it out in [0.30.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.30.0)

**Comment by eli-front** [comment]
Thanks @imaNNeoFighT!
