### ISSUE TITLE
Change dotsize and color of Touchline?

### ISSUE THREAD

**Issue by attex** [imaNNeoFighT/fl_chart#441]
Hi there, 

is there a way to change the color and stroke-width of the touchline in a Linechart and the size of the Dot on touch on a linechart? 

Kind regrads.

**Comment by imaNNeoFighT** [comment]
Hi, did you check our [samples](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#some-samples)?
Check [LineTouchData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetouchdata-read-about-touch-handling)
