### ISSUE TITLE
get FlSpot in getTiles instead of value

### ISSUE THREAD

**Issue by dario-digregorio** [imaNNeoFighT/fl_chart#442]
Hey I really like your package and I am wondering why you do not return `FlSpot()` in `getTiles()`? Or is there a way to obtain the y-value when implementing bottomTiles or topTiles?

**Comment by imaNNeoFighT** [comment]
Because you may have a lot of spots at a specific x (I'm talking about the LineChart),
But it is possible in the BarChart because we have one `y` per each `x`,
which do you mean?

**Comment by dario-digregorio** [comment]
I am using a LineChart where every x has only one FlSpot. Is there another way to get the FlSpot from a specific x?

**Comment by dario-digregorio** [comment]
And why do I have to return a String in `getTiles`? I would prefer to return a Widget there so I can choose what I'd like to show in the tile.

**Comment by imaNNeoFighT** [comment]
You can find it in your input data (I mean you can search and find the spot used in a specific x, then get the y value).
We are not able to get a Widget at the moment, but we are trying to find a way to do it.
Thanks for your feedback!
