### ISSUE TITLE
Is it possible to draw live charts like for the stocks market?

### ISSUE THREAD

**Issue by josephwaiguru** [imaNNeoFighT/fl_chart#444]
hello, i have a line chart which i am populating with new data after a few seconds. However i want the chart to draw like below. How can this be achieved.

![WhatsApp Image 2020-09-09 at 8 02 29 AM](https://user-images.githubusercontent.com/5208669/92563838-e16d6500-f280-11ea-9e28-184817a8ac61.jpg)

**Comment by imaNNeoFighT** [comment]
I will implement a sample (whenever I was not busy)

**Comment by amartya-dev** [comment]
+1 for this feature @imaNNeoFighT please look into this, any time series example should help

**Comment by imaNNeoFighT** [comment]
Follow it up here #438

**Comment by Trung15010802** [comment]
any update?
