### ISSUE TITLE
Adaptive barRod width, BarChartRodData spacing, and BarChartGroupData.

### ISSUE THREAD

**Issue by dbenedictos** [imaNNeoFighT/fl_chart#447]
Currently the bar chart rods can only be provided by a constant width and/or spacing. I suggest to add a feature where the bars can automatically space themselves and/or set their width automatically depending on the number of bars present in the screen. If the number of bars exceeds the screen already maybe add a scroll feature as well? Thank you for taking the time to read my feature request. :)

**Comment by imaNNeoFighT** [comment]
Hi there,
I appreciate your suggestion because that's the correct way we should handle the scroll feature.
We have an [issue ](https://github.com/imaNNeoFighT/fl_chart/issues/71)about it, and I prefer to follow it up there.
I close this issue.
Thanks!
