### ISSUE TITLE
Variable x-axis value alignment

### ISSUE THREAD

**Issue by marcel-bluestone** [imaNNeoFighT/fl_chart#449]
I have to add measurement data, that was taken at various points in time. Some were taken on the same day at different times, others a couple of days later. The spread of x values is therefore variable and not even speed. Is there a possibility to automatically adjust the spread of points on the curve, based on a DateTime object? 
If not, this would be a great feature.

**Comment by imaNNeoFighT** [comment]
Hi, I didn't understand what you mean,
can you show me a visualized example?
