### ISSUE TITLE
bottomTitles rotateAngle can create overlapping next widget

### ISSUE THREAD

**Issue by marcel-bluestone** [imaNNeoFighT/fl_chart#450]
** Don't make a duplicate issue.
I did not find any similar issue.

On a line-chart I do rotate the x-axis (bottomTitles) text 90 degrees in order to stay readable. This however does not correctly set the vertical size of the chart, so the following widget in the column is overlapping with the bottomTitles text. 

Here's the relevant code:
`return Scaffold(
      appBar: AppBar(
        title: Text("Stability Trends Overview"),
      ),
      body: Padding(
        padding: const EdgeInsets.all(18.0),
        child: Column(
          children: [
            Visibility(
              visible: _visible,
              child: AspectRatio(
                aspectRatio: 1.23,
                child: Container(

                  child: LineChart(

                    historyData,

                  ),
                ),
              ),
            ),
            Card(
              child: getStatsWidget(),

            )
          ],
        ),
      ),
    );`

Here's a screenshot:
![Screen Shot 2020-09-14 at 11 45 49](https://user-images.githubusercontent.com/60437522/93072032-262e3d00-f681-11ea-9e02-b5f88ad7a951.png)

Flutter version: 1.22.0-1.0*pre channel dev
fl_chart: 0.11.1

**Comment by imaNNeoFighT** [comment]
You should handle it with `reservedSize` property in our [SideTitles](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#sidetitles).
