### ISSUE TITLE
aboveBarData: paint area disappears after flickering, while  belowBarData stay persistant in LineChart

### ISSUE THREAD

**Issue by nilotpalkapri** [imaNNeoFighT/fl_chart#454]
belowBarData: BarAreaData(show: true,
                                colors: [
                                  const Color(0xff12c2e9).withOpacity(0.4),
                                  const Color(0xffc471ed).withOpacity(0.4),
                                  const Color(0xfff64f59).withOpacity(0.4),
                                ],
                                cutOffY: double.parse(_avgValue[j].toStringAsFixed(2)),
                                applyCutOffY: true,),
                              aboveBarData: BarAreaData(show: true,
                                colors: [
                                  const Color(0xff12c2e9).withOpacity(0.4),
                                  const Color(0xffc471ed).withOpacity(0.4),
                                  const Color(0xfff64f59).withOpacity(0.4),
                                ],
                                cutOffY: double.parse(_avgValue[j].toStringAsFixed(2)),
                                applyCutOffY: true,),

**Comment by imaNNeoFighT** [comment]
Duplicate, #440
