### ISSUE TITLE
Animated Painting from Left to Right (Line Chart)

### ISSUE THREAD

**Issue by jamesnicholls04** [imaNNeoFighT/fl_chart#455]
I was wondering whether it is possible to paint (animate) a line chart from left to right?

Something like this: 

https://dribbble.com/shots/2475280-Line-chart-graph-animation

Great work on this package, thanks!

**Comment by imaNNeoFighT** [comment]
Hi, I think it is a duplicate, because we have another issue for BarChart, but when we implement it, it will be available in all charts,
please put your sample [here](https://github.com/imaNNeoFighT/fl_chart/issues/406), I close it.
Thanks!

**Comment by nm-JihunCha** [comment]
any sample code ? or solution?

**Comment by imaNNeoFighT** [comment]
As you know, this issue has been closed. So please follow it up here: #406
