### ISSUE TITLE
Handling timeseries plan?

### ISSUE THREAD

**Issue by bendoum** [imaNNeoFighT/fl_chart#462]
Hi There,

First thanks for the beautiful chart library, it's really awesome.  

For now creating the chart is pretty manual, you need to create the axises data and all the spots manually, do you have in mind adding feature to handling specific type of data automatically, such as timeseries?

Thanks,
Ben

**Comment by imaNNeoFighT** [comment]
I think there is a duplicate issue.
If you found it, please mention it here and close this issue.
And yes we are going to handle it if I find free time.
Also always you can make us happy with your Pull Request.
Thanks!

**Comment by imaNNeoFighT** [comment]
Follow it up here #438
