### ISSUE TITLE
Background bands

### ISSUE THREAD

**Issue by mweber26** [imaNNeoFighT/fl_chart#472]
Is there a way to color the background of the chart with bands like the image?  I know I can use getDrawingHorizontalLine with a large stroke width, but it's hard to know how thick to make it.

![image](https://user-images.githubusercontent.com/197305/96349374-3456eb00-107d-11eb-9ffe-0455c46de23c.png)

**Comment by imaNNeoFighT** [comment]
Also, you can put the chart in a Stack. Then put a view behind the chart.

**Comment by mweber26** [comment]
Great idea.  Thanks!
