### ISSUE TITLE
Is it possible to view the x-coordinate value in the tool tip pop up when hovering over graph?

### ISSUE THREAD

**Issue by LondonTran** [imaNNeoFighT/fl_chart#473]
Currently, when you drag your finger along a line chart, a tooltip pops up showing the Y-coordinate value, but not the X-coordinate value (shown in the attached image). It may be useful to also show the X-coordinate value, especially when there are a lot of spots plotted on the graph. I am willing to work on adding this feature if anyone else finds it useful. Let me know your thoughts. 

![121708333_351502832737290_4230319913039187456_n](https://user-images.githubusercontent.com/55134653/96359305-5bde9f80-10df-11eb-8bb4-cd329135f4a9.jpg)

**Comment by imaNNeoFighT** [comment]
Check [this](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#sample-3-source-code) sample to have a customized tooltip

<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_3.gif" width="300" >

**Comment by LondonTran** [comment]
Perfect! Thanks Iman!

**Comment by imaNNeoFighT** [comment]
No problem!
