### ISSUE TITLE
Text gets blurred on web when chart is used

### ISSUE THREAD

**Issue by melwinlobo18** [imaNNeoFighT/fl_chart#474]
**Describe the bug**
The text gets blurred on Flutter Web when the chart is used.

**To Reproduce**
https://gist.github.com/melwinlobo18/a9850a09cc742558b6176a7f19814dd2

**Screenshots**
![blurry_text](https://user-images.githubusercontent.com/29202917/96578209-7046b600-12f2-11eb-94c5-19a819b255f7.jpg)

**Versions**
 - Flutter 1.22.1 • channel beta
 - fl_chart: ^0.12.0

**Comment by imaNNeoFighT** [comment]
Sorry but the link doesn't work for me.

![image](https://user-images.githubusercontent.com/7009300/96580416-1ab7dc80-12e5-11eb-976b-5fa43a95ee4e.png)

**Comment by imaNNeoFighT** [comment]
Because. I'm in Iran. and we are under those fucking sanctions.

**Comment by melwinlobo18** [comment]
Oops. My bad. I made it public now.

**Comment by imaNNeoFighT** [comment]
It's not your bad.
It's Github's bad that follows U.S sanction that applied sanctions against innocent people.
It's my bad that was born in Iran.

**Comment by imaNNeoFighT** [comment]
BTW Thank you I will check it out.

**Comment by melwinlobo18** [comment]
Hey @imaNNeoFighT , this is an issue with the framework itself. In some screen resolutions it displays properly and in others it gets blurred. 

I also tried with different chart libraries and the result was same. I'm not sure what's causing this problem.

**Comment by imaNNeoFighT** [comment]
I think that is the rendering text using canvas APIs.
There should be an open issue in the Flutter source code.

**Comment by melwinlobo18** [comment]
Thanks for your quick response😊. This is an amazing library💖. Great to see your contribution to the community in spite of all the difficulties you are facing.

I hope your problems are sorted out soon. All the best✨
