### ISSUE TITLE
Chart out of boundaries with custom minY

### ISSUE THREAD

**Issue by davidmarinangeli** [imaNNeoFighT/fl_chart#48]
As you can see from the screenshots there is a problem when I set my `minY` value. If I set `0` everything works fine but if I set it programmatically it has strange behaviour.

In this example I would like to set the min to `4` or `3`, based on the data I have

I have already tried to change the style and the position to the one that we can find on the examples but nothing changes. I had `0.1.2` and everything worked well: this error is only after the `0.1.4` update.

![Screenshot_20190712-172336](https://user-images.githubusercontent.com/19487461/61139839-7a142380-a4ca-11e9-98b0-abfc99371702.jpg)
![Screenshot_20190712-172503](https://user-images.githubusercontent.com/19487461/61139840-7aacba00-a4ca-11e9-82e6-6bb174143178.jpg)

**Comment by imaNNeoFighT** [comment]
Holy Poly
I will fix it ASAP
Thanks for the report!

**Comment by imaNNeoFighT** [comment]
fixed in [0.1.5](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.1.5),
Thanks for the contribution! Cheers!

**Comment by davidmarinangeli** [comment]
What a speed!! 😍

Thanks a lot
