### ISSUE TITLE
How to display spot data above it?

### ISSUE THREAD

**Issue by hojjat-faryabi** [imaNNeoFighT/fl_chart#49]
Hi
First of all, thank you for this amazing library 👍 👍 💯 
How to display spot data above it like picture ? 

![Untitled](https://user-images.githubusercontent.com/17961198/61597837-4c498000-ac2a-11e9-9619-4570c20be72c.png)

**Comment by imaNNeoFighT** [comment]
Hi, Thanks man,
It's a good feature, but unfortunately, we didn't have this right now,
I will add this possibility ASAP.
