### ISSUE TITLE
Can we change LineTouchData

### ISSUE THREAD

**Issue by draxex** [imaNNeoFighT/fl_chart#490]
Hello,
My question is can I change the LineTouchData value?

![Adsız](https://user-images.githubusercontent.com/69625295/98088391-6e542980-1e92-11eb-9d66-4b3b031a34e5.jpg)

For example, can I write 50k instead of 5.0 in that spot? I think that only shows spots value, can I change them with my values?

Thank you...

**Comment by imaNNeoFighT** [comment]
Check [this sample](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#sample-1-source-code).

**Comment by draxex** [comment]
How can I implement that to LineTouchData because it requires **getTooltipItems** not **getTooltipItem**. Are there any examples of that?
