### ISSUE TITLE
怎么才能固定滑块

### ISSUE THREAD

**Issue by hu70258tao** [imaNNeoFighT/fl_chart#500]
![image](https://user-images.githubusercontent.com/20218008/100076599-56ae0680-2e7c-11eb-80db-e7145c6335e8.png)
当showOnTopOfTheChartBoxArea为true的时候,我想把LineTooltipItem固定在Chart顶部的正中央,因为在显示边界的时候,LineTooltipItem经常不能完整地显示.

**Comment by imaNNeoFighT** [comment]
Please explain it in english
