### ISSUE TITLE
i want to create ontouch callback on badges in pie chart

### ISSUE THREAD

**Issue by sk784** [imaNNeoFighT/fl_chart#502]
Hello, is it possible to create the same ontouch callback on badges in pie chart as ontouch callback on corresponding section?

**Comment by gmaggio** [comment]
@sk784 Since the badges are widgets, you should be able to wrap them with `GestureDetector` to detect taps/touches and make use of the chart's _touched indexes_ (`PieTouchResponse`) to determine which one is touched.

**Comment by imaNNeoFighT** [comment]
@gmaggio Is right. You can wrap your widget with the `GestureDetector`.
Thanks @gmaggio.
