### ISSUE TITLE
Realtime data plotting support

### ISSUE THREAD

**Issue by ManojPrabhakar-dev** [imaNNeoFighT/fl_chart#505]
**Requesting feature to support realtime data plot**

Plot the stream of data coming from sources like sensors (via BLE communication) , etc.,
X-Axis visible range(MaxCount) can be customizable and once it reaches the Max count, element in 0th index can be sliced/removed and further incoming stream data can be added to FIFO.

**Comment by brazc** [comment]
I am using ChangeNotifierProvider as a bridge to do realtime data plotting.

The BLE Service parses the message and adds the data to a Hive box.
My hive service itself is a change notifier, will rebuild listeners everytime data is added to the box. Likewise it also has a method that returns a List of FlSpots in my case.

My FLChart Widget has a controller that manages the value of the axes and other stuff regarding it.

In the screen where I'm displaying the chart, I have Consumer2 providing the FlChart widget with the controller and the data from the hive service.

---

So this is one way of doing it.. probably not optimal. But it works.

**Comment by imaNNeoFighT** [comment]
Hi. I made a real-time sample.
Check it out:

##### Sample 10 ([Source Code](/example/lib/line_chart/samples/line_chart_sample10.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_10.gif" width="300" >

**Comment by chillbrodev** [comment]
> Hi. I made a real-time sample. Check it out:
> 
> ##### Sample 10 ([Source Code](/example/lib/line_chart/samples/line_chart_sample10.dart))
> <img alt="" width="300" src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_10.gif">

@imaNNeoFighT Hey there, I tried to go to the source code link and it says not found. I could really use this in my project. Would you be able to repost the code. PS. Sent you 5 coffees on the donation site ☕

**Comment by chillbrodev** [comment]
I found the link, it is now here https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample10.dart
