### ISSUE TITLE
Problem when dynamically generating pie chart. Pie chart crashes if list of sections shrinks.

### ISSUE THREAD

**Issue by nicolo-fr** [imaNNeoFighT/fl_chart#507]
**Describe the bug**
I try to generate a pie chart showing categories of expenses for a given month. If, from month 1 to 2, the number of categories increases or stays the same, the pie chart updates with no problem. If, on the contrary, the number of categories decreases, the pie chart crashes. 

This is the error code: 
════════ Exception caught by widgets library ═══════════════════════════════════
The following RangeError was thrown building PieChart(duration: 150ms, dirty, dependencies: [_EffectiveTickerMode, MediaQuery], state: _PieChartState#56c28(ticker active)):
RangeError (index): Invalid value: Only valid value is 0: 1

The relevant error-causing widget was
PieChart
lib/main.dart:150
When the exception was thrown, this was the stack
#0      List.[] (dart:core-patch/growable_array.dart:177:60)
#1      _PieChartState.build.<anonymous closure>
package:fl_chart/…/pie_chart/pie_chart.dart:171
#2      new _GrowableList.generate (dart:core-patch/growable_array.dart:128:28)
#3      _PieChartState.build
package:fl_chart/…/pie_chart/pie_chart.dart:167
#4      StatefulElement.build
package:flutter/…/widgets/framework.dart:4744
...

**Versions**
fl_chart: ^0.12.0

**To Reproduce**
See code below.
Tap button 'Month 1", then "Month 2", then either "Month 1" or "Month 3". The app crashes.

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:fl_chart/fl_chart.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'FL Chart demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Category> categoriesMonth1 = [
    Category(
      color: Colors.blue,
      title: 'Travel',
      value: 100,
      icon: Icon(Icons.card_travel),
    )
  ];

  List<Category> categoriesMonth2 = [
    Category(
      color: Colors.blue,
      title: 'Travel',
      value: 50,
      icon: Icon(Icons.card_travel),
    ), 
    Category(
      color: Colors.amber,
      title: 'Food',
      value: 50,
      icon: Icon(Icons.restaurant)
    ),
  ];

  List<Category> categoriesMonth3 = [
    Category(
      color: Colors.amber,
      title: 'Food',
      value: 100,
      icon: Icon(Icons.restaurant)
    ),
  ];

  List<Category> monthOnDisplay =  [];

  void showCategoriesMonth1() {
    setState(() {
      monthOnDisplay = categoriesMonth1;
    });
  }
  void showCategoriesMonth2() {
    setState(() {
      monthOnDisplay = categoriesMonth2;
    });
  }
  void showCategoriesMonth3() {
    setState(() {
      monthOnDisplay = categoriesMonth3;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: [
                RaisedButton(onPressed: showCategoriesMonth1, child: Text('Month 1')),
                RaisedButton(onPressed: showCategoriesMonth2, child: Text('Month 2')),
                RaisedButton(onPressed: showCategoriesMonth3, child: Text('Month 3')),
              ],
            ),
            CustomPieChart(monthOnDisplay),
          ],
        ),
      ),
    );
  }
}

class Category {
  Color color;
  double value;
  String title;
  Icon icon;
  Category({this.color, this.icon, this.title, this.value});
}

class CustomPieChart extends StatelessWidget {
  List<Category> categoriesList;
  CustomPieChart(this.categoriesList);
  @override
  Widget build(BuildContext context) {
    final double radius = 24;
    final double widgetSize = 60;

    final List<PieChartSectionData> sectionList = [];

    categoriesList.forEach((category) {
      PieChartSectionData sectionData = PieChartSectionData(
        color: category.color,
        value: category.value,
        title: category.title,
        showTitle: false,
        radius: radius,
        badgeWidget: _Badge(
          category.icon,
          size: widgetSize,
          borderColor: category.color,
        ),
      );
      sectionList.add(sectionData);
    });

    return AspectRatio(
      aspectRatio: 16 / 9,
      child: Container(
        child: AspectRatio(
          aspectRatio: 1,
          child: PieChart(
            PieChartData(
              borderData: FlBorderData(
                show: false,
              ),
              sectionsSpace: 0,
              centerSpaceRadius: 72,
              sections: sectionList,
            ),
          ),
        ),
      ),
    );
  }
}

class _Badge extends StatelessWidget {
  final Icon icon;
  final double size;
  final Color borderColor;

  const _Badge(
    this.icon, {
    Key key,
    @required this.size,
    @required this.borderColor,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return AnimatedContainer(
      duration: PieChart.defaultDuration,
      width: size,
      height: size,
      padding: EdgeInsets.all(size * .15),
      child: Center(child: icon),
    );
  }
}

**Comment by imaNNeoFighT** [comment]
Fixed in [0.12.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.12.1). Check it out!
Thanks for reporting.

**Comment by nicolo-fr** [comment]
Thanks!!

**Comment by pharshdev** [comment]
Facing this exact same issue in LineChart. 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)
    ! Error: Living Room is not connected. Xcode will continue when Living Room is connected. (code -13)

• No issues found!
```
```
fl_chart: ^0.20.1
```
