### ISSUE TITLE
Possability of having a second Y axis on the right using a separate scale?

### ISSUE THREAD

**Issue by MostHated** [imaNNeoFighT/fl_chart#51]
Hey there,
     I was just wondering what the possibility of allowing for a second Y-axis on the right side of the chart which uses a different scale might be and then allowing say one line graph and then one bar on the same chart?

Thanks,
-MH

**Comment by imaNNeoFighT** [comment]
May I ask you to demonstrate your idea?
paint it somehow.

**Comment by imaNNeoFighT** [comment]
Unfortunately, I will close it, because you didn't explain it more

**Comment by lukepighetti** [comment]
We are also looking for the ability to do dual Y-axis. https://docs.oracle.com/en/cloud/saas/enterprise-performance-reporting-cloud/dmepr/understanding_dual_y_axis_222x8ba01f6c.html
