### ISSUE TITLE
Line Chart isn't expanding and filling all available width

### ISSUE THREAD

**Issue by biklas7** [imaNNeoFighT/fl_chart#518]
**Describe the bug**
I have a `LineChart` inside a `SizedBox` that is inside a `Column` and I'm trying to fill the available width by setting the `SizedBox` width to `double.maxFinite`, but the chart seems to have some kind of margin on the left side that I can't remove.

Tried searching on the issues and on the source code and haven't found any tips about it. Maybe I'm missing something since I'm new to this package.

**To Reproduce**
The `Column` is inside a `ListView` that has some horizontal padding and I'm trying to fill the rest of the space with the chart.

```
  List<LineChartBarData> _getGraphData() {
    final LineChartBarData overallLine = LineChartBarData(
      colors: [Colors.red],
      dotData: FlDotData(show: false),
      spots: [
        FlSpot(0, 2),
        FlSpot(1, 3),
        FlSpot(2, 5),
        FlSpot(3, 4),
        FlSpot(4, 2),
        FlSpot(5, 1),
      ],
    );

    return [overallLine];
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: double.maxFinite,
      height: 242,
      child: LineChart(
        LineChartData(
          minY: 0,
          maxY: 5,
          minX: 0,
          maxX: 5,
          lineBarsData: _getGraphData(),
        ),
      ),
    );
  }
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4192633/102388986-70012900-3fca-11eb-8412-19322364025e.png)

**Versions**
 - Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale en_US.UTF-8)
 - 0.12.1

**Comment by biklas7** [comment]
While customizing the chart I found out that the `SideTitles` have a pre-defined reserved size of 40. Source code [here](https://github.com/imaNNeoFighT/fl_chart/blob/eff89161992d5367c59d91250b1a6b7b6ab5db4a/lib/src/chart/base/axis_chart/axis_chart_data.dart#L207).

Maybe this could be useful for someone else.

**Comment by zzterrozz** [comment]
> While customizing the chart I found out that the `SideTitles` have a pre-defined reserved size of 40. Source code [here](https://github.com/imaNNeoFighT/fl_chart/blob/eff89161992d5367c59d91250b1a6b7b6ab5db4a/lib/src/chart/base/axis_chart/axis_chart_data.dart#L207).
> 
> Maybe this could be useful for someone else.

```dart

            titlesData: FlTitlesData(show: false, bottomTitles: SideTitles(margin: 0.0), leftTitles: SideTitles(margin: 0.0), rightTitles: SideTitles(margin: 0.0), topTitles: SideTitles(margin: 0.0)),
````

doesn't work to fix this gap. 
What solution did you find please?
