### ISSUE TITLE
Tooltip cut off at top of screen

### ISSUE THREAD

**Issue by ozzy1873** [imaNNeoFighT/fl_chart#530]
If the chart line is too close to the top of the screen, the tooltip extends beyond the top of the screen and is cut off. It would be nice if it would reposition itself so that it is always entirely within the bounds of the screen.

**Comment by ozzy1873** [comment]
Sorry, I see that there is a flag to control this. Closing.

**Comment by Matungos** [comment]
What flag?

**Comment by excogitatr** [comment]
What is the flag called @ozzy1873?
