### ISSUE TITLE
When iscurved is true, the bottom data arc is out of bounds

### ISSUE THREAD

**Issue by aiyakuaile** [imaNNeoFighT/fl_chart#534]
<img width="485" alt="WX20210106-130846" src="https://user-images.githubusercontent.com/13814081/103731560-60508f80-5020-11eb-8f61-96ac4f2f79e4.png">

Is there any way or method to control it ？？？

**Comment by francescovallone** [comment]
Try to add `clipData: FlClipData.all(),` to your `LineChartData` widget.

**Comment by imaNNeoFighT** [comment]
Try to use `preventCurveOverShooting`, and `preventCurveOvershootingThreshold` in your [LineChartBarData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartbardata)
