### ISSUE TITLE
Questions about the direction of the barCahrt

### ISSUE THREAD

**Issue by kim-king-rong** [imaNNeoFighT/fl_chart#536]
I checked the document, and it seems that I didn't find any related settings regarding the arrangement direction of the bar graph. Did I not find the right place? If so, can you please tell me the relevant document location? Thank you

**Comment by imaNNeoFighT** [comment]
Hi, Unfortunately, we don't support Horizontal Bar Chart yet.
We have an open issue about it. you can follow it up here #113.

**Comment by imaNNeoFighT** [comment]
Also, you can thumb it up to bring it to the top of my priority list.
