### ISSUE TITLE
I have a question about how to show values above each point in a line chart

### ISSUE THREAD

**Issue by nedalex99** [imaNNeoFighT/fl_chart#537]
https://stackoverflow.com/questions/59357427/flutter-charts-display-value-above-each-point

I found this issue here that I am also encountering. Is it possible to do this and if so, can you give an answer?

Thank you!

**Comment by imaNNeoFighT** [comment]
Check it out, you just need to remove the background color.

##### [Sample 5](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#sample-5-source-code) ([Source Code](/example/lib/line_chart/samples/line_chart_sample5.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_5.png" width="300" >
