### ISSUE TITLE
PieChart sections's data changed, but the view is not updating

### ISSUE THREAD

**Issue by kelisiki** [imaNNeoFighT/fl_chart#539]
FLChart - v12.2

Issue - when the sections's data are changed, the view is not updated accordingly (still remain as the view during its first build)

**Comment by imaNNeoFighT** [comment]
Can you check it in [0.12.3](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.12.3) again?
It may be fixed.
Let me know.
