### ISSUE TITLE
Touching Chart Removes X Axis Titles

### ISSUE THREAD

**Issue by zerox1212** [imaNNeoFighT/fl_chart#543]
** Don't make a duplicate issue.
 I could not find this problem in previous issues

**Describe the bug**
I'm overriding `getTitles : ` in `FlTitlesData()` to add custom strings on the X axis. I set `Interval :` to 1 so that I can decide which title for every data point. In many cases I don't want a title, so I return `null`. This part works fine. However as soon as I touch the chart to highlight a value all titles EXCEPT the first and last are removed.  
  
From what I can tell, touching the chart causes flutter to redraw the screen, this triggers `getTitles` to execute again, but for some reason not all `Strings` are rendered.

**To Reproduce**
Will add later if needed. I'm fitting Time-Series data into these charts and it's a lot of code to reformat for a issue. I am hoping there is an obvious answer from someone who knows the library.

**Screenshots**
If applicable, add screenshots, or videoshots to help explain your problem.
![image](https://user-images.githubusercontent.com/13090472/104336725-56b0a700-54ba-11eb-8b56-7408132ee9f0.png)

**Versions**
 - which version of the Flutter are you using?
1.22.4
 - which version of the FlChart are you using?
0.12.2

**Comment by imaNNeoFighT** [comment]
Hi there.
You can make a simple `main.dart` file, and reproduce it with some fake data and chart style.
You don't need to provide the exact code that you have faced the error.
It can help us a lot to understand the problem.
Thanks!

**Comment by zerox1212** [comment]
@imaNNeoFighT I plan to investigate this more in the next few days. Then I will update this.

**Comment by imaNNeoFighT** [comment]
Any update?

**Comment by imaNNeoFighT** [comment]
Any update?

**Comment by zerox1212** [comment]
Our app is seasonal, there is no development work planned for the next 6 months. Sorry.
