### ISSUE TITLE
Iteration

### ISSUE THREAD

**Issue by michael-william** [imaNNeoFighT/fl_chart#546]
** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.

**Describe the bug**

**To Reproduce**
Provide us a completely reproducible code (contains the main function) in a file, it helps us to find the bug immediately.

**Screenshots**
If applicable, add screenshots, or videoshots to help explain your problem.

**Versions**
 - which version of the Flutter are you using?
 - which version of the FlChart are you using?

**Comment by imaNNeoFighT** [comment]
I close this issue because there is nothing provided.
