### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by enyo** [imaNNeoFighT/fl_chart#548]
Are there plans to add null safety support, and if so: when do you think this might happen.

Thanks!

**Comment by imaNNeoFighT** [comment]
We must support null safety, and I can't promise when we are going to implement it.
I have to work in my free time.

**Comment by jlubeck** [comment]
An increasing number of libraries and dependencies are moving to null safety, and updating to the latests branches of flutter is failing to compile because of the lack of it on this library. Would love to help but I don't know if someone already started doing this?

**Comment by jlubeck** [comment]
I went ahead and created a PR for this: https://github.com/imaNNeoFighT/fl_chart/pull/576

**Comment by imaNNeoFighT** [comment]
Hi everybody.
I'm really happy to announce that we have migrated to the null-safety!
You can use [0.20.0-nullsafety1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.20.0-nullsafety1) from now!

Also, it would be great if you review my migration code in [this branch](https://github.com/imaNNeoFighT/fl_chart/tree/0.20.0-nullsafety1), and let me know if you have any idea to make it better.

Don't forget to check it in your project, and let me know if there is any problem or bug.

Thanks!
