### ISSUE TITLE
bar_chart_sample1 example doesn't show correct days on x-axis

### ISSUE THREAD

**Issue by dhust** [imaNNeoFighT/fl_chart#549]
I copy and pasted this [bar chart example code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample1.dart) and it doesn't show the days properly on the x-axis. It shows Mn, Te, Wd, Tu, Tu, Tu. Printing out value from `getTitles: (double value)` outputs `0.0, 1.0, 2.0, 3.0`. It doesn't go up to 6 as expected. Any thoughts?

**Comment by imaNNeoFighT** [comment]
I didn't understand the problem.
Can you explain it more?
