### ISSUE TITLE
How to make after a tap on the chart point, popup text will display without disappearance

### ISSUE THREAD

**Issue by olympea** [imaNNeoFighT/fl_chart#551]
Is it possible to make after a tap on the chart point, popup text will display without disappearance? Especially on Line Chart.
And hide the popup text when you tap on the chart again? How to do it?

**Comment by imaNNeoFighT** [comment]
You can implement it yourself in your project by overriding touch behaviors.
Check [this sample](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/scatter_chart.md#sample-2-source-code).
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/scatter_chart/scatter_chart_sample_2.gif" width="300" >
