### ISSUE TITLE
Horizontal Bar Chart

### ISSUE THREAD

**Issue by JavierOramas** [imaNNeoFighT/fl_chart#552]
It would be nice to have a horizontal bar chart on the Sample charts, thats a very useful way to show data

**Comment by imaNNeoFighT** [comment]
Hi, Unfortunately, we don't support it yet.
We have an open issue about it. you can follow it up here #113.

**Comment by imaNNeoFighT** [comment]
Also, you can thumb it up to bring it to the top of my priority list.

**Comment by Yetispapa** [comment]
Hey @imaNNeoFighT,

first thanks for this great framework, it brings really functionality with it which other chart frameworks miss. 

Now in terms of the horizontal bar charts, we also wanted to point out that we would need them. For now we used an workaround by wrapping the BarChart in:

```
RotatedBox(
      quarterTurns: -1,
      child: BarChart(
```

and rotate the titles like so:

```
topTitles: SideTitles(
              showTitles: true,
              getTextStyles: (value) => labelStyle,
              rotateAngle: 90,
              getTitles: (double value) {
                return data.toString();
              },
            )
```

But of course this is not the best solution. So it would be great if the framework would support this at some point.

Thank you

**Comment by jacksonw765** [comment]
I would love an update on this, a horizontal chart would be great. Or at least a way to rotate BarTouchData.

**Comment by imaNNeoFighT** [comment]
This is a closed issue.
Follow #113 and thumb it up.
