### ISSUE TITLE
Dots in the Graph

### ISSUE THREAD

**Issue by xOldeVx** [imaNNeoFighT/fl_chart#558]
As you asked me a separate issue:

About the **barWidth**, if it set to **0**, so the line is still appear, it could be good and right that 0 value make the line transparent (because it's **ZERO**, and not 1 that mean the thinnest line).
**In this, only the DOTS of the line displayed.**
In my case it's help to see a dangerous wind that more than 20km/h
The expected result:
![gg](https://user-images.githubusercontent.com/24361103/106199338-f6aa4800-61bd-11eb-89cb-0851ec34b7e5.png)
Instead of (working now):
![fdf](https://user-images.githubusercontent.com/24361103/106199344-fad66580-61bd-11eb-932c-c0b4c485babc.jpg)

**Comment by imaNNeoFighT** [comment]
Hi, What if you set the transparent color?
(BTW we should fix the 0 width)

**Comment by xOldeVx** [comment]
transparent color hide the line and the dots together.
**0 Width** really must to change to invisible line

**Comment by imaNNeoFighT** [comment]
You are right.
For now just invisible it as a workaround.
We will fix it ASAP.
Thanks!

I will notify you here when it has fixed.

**Comment by imaNNeoFighT** [comment]
Fixed in [0.12.3](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.12.3).
Thanks for contributing!
