### ISSUE TITLE
Graph gradient colors vertical

### ISSUE THREAD

**Issue by xOldeVx** [imaNNeoFighT/fl_chart#559]
It's can be VERY USEFUL to set the fill gradient colors **vertical** (from 0 celsius to 50 for example), currently only **horizontal** is working.

The expected result:
![gg](https://user-images.githubusercontent.com/24361103/106200599-e2ffe100-61bf-11eb-97d0-582d71866aa7.png)

Currently only horizontal working:
![ff](https://user-images.githubusercontent.com/24361103/106200603-e4310e00-61bf-11eb-976b-5412d2bbe799.png)

**Comment by imaNNeoFighT** [comment]
You can change the `gradientFrom`, and `gradientTo` properties of [BarAreaData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#barareadata) to customize the gradient's direction.

**Comment by jacobokoenig** [comment]
> You can change the `gradientFrom`, and `gradientTo` properties of [BarAreaData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#barareadata) to customize the gradient's direction.

@imaNNeoFighT could you kindly explain what the offset values should contain to make it vertical?

**Comment by imaNNeoFighT** [comment]
Yes. here you go.

```dart
gradientFrom: Offset(0.5, 0.0), // top center
gradientTo: Offset(0.5, 1.0), // bottom center
```
