### ISSUE TITLE
show dotData with x- and y-values instead of y-value only

### ISSUE THREAD

**Issue by lgwds** [imaNNeoFighT/fl_chart#560]
<img src="https://user-images.githubusercontent.com/67753842/106308678-53ab0a00-6261-11eb-9ec4-4f442a89ecc8.jpg" width="300">

Currently, by opting to show dotData only the y-value is shown. 
<img src="https://user-images.githubusercontent.com/67753842/106308855-98cf3c00-6261-11eb-970d-34be79cb0050.png" width="150">

It would be great to be able to show the x-value in the same box. For instance:
x = 28/01
y = 11.0

**Comment by imaNNeoFighT** [comment]
You must override the [LineTouchData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetouchdata-read-about-touch-handling) then override the `touchTooltipData`.
I know it is complicated. We will improve its accessibility.

BTW check [this sample code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample3.dart), We did something like that.

<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_3.gif" width="300" >

**Comment by lgwds** [comment]
Thanks, this works! :)
