### ISSUE TITLE
How to change BarTooltipItem's text color?

### ISSUE THREAD

**Issue by minkithub** [imaNNeoFighT/fl_chart#562]
```BarTooltipItem defaultBarTooltipItem(
  BarChartGroupData group,
  int groupIndex,
  BarChartRodData rod,
  int rodIndex,
) {
  const TextStyle textStyle = TextStyle(
    color: Colors.black, // I want change this color
    fontWeight: FontWeight.bold,
    fontSize: 14,
  );
  return BarTooltipItem(rod.y.toString(), textStyle);
}```

I want to change BarTooltipItem's text color which I see when I touched bar graph. How can I do this?

**Comment by imaNNeoFighT** [comment]
You must implement your custom `getTooltipItem` in the [BarTouchTooltipData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#bartouchtooltipdata), which is inside the [BarTouchData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#bartouchdata-read-about-touch-handling).
