### ISSUE TITLE
Version solving failed if you have latest pre-release of flutter_svg 

### ISSUE THREAD

**Issue by talhabalaj** [imaNNeoFighT/fl_chart#564]
This is the exact message that is displayed on `flutter pub get`. 

```
Because no versions of fl_chart match >0.12.2 <0.13.0 and fl_chart 0.12.2 depends on path_drawing ^0.4.1, fl_chart ^0.12.2 requires path_drawing ^0.4.1.
And because flutter_svg >=0.20.0-nullsafety.0 depends on path_drawing ^0.5.0-nullsafety.0, fl_chart ^0.12.2 is incompatible with flutter_svg >=0.20.0-nullsafety.0.
So, because uet_lms depends on both flutter_svg 0.20.0-nullsafety.3 and fl_chart ^0.12.2, version solving failed
```

Flutter version: 1.26.0-17.1.pre
FlChar Version: 0.12.2

**Comment by imaNNeoFighT** [comment]
Can you check it in [0.12.3](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.12.3) again?
It may be fixed.
Let me know.

**Comment by imaNNeoFighT** [comment]
Please use [0.20.0-nullsafety1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.20.0-nullsafety1) version when you are in beta channel.
