### ISSUE TITLE
70% scaled container based on the available screen size is what i get, but 100% is what i need

### ISSUE THREAD

**Issue by martin-ksti** [imaNNeoFighT/fl_chart#565]
the getDefaultSize method from utils.dart of this project scales the container that's surrounding the diagram to 70% of the  size that MediaQuery.of(context).size returns.

i expected this size depends on the resulting chart size and is not a fix value. why is it fix to 70% and not parameterizable?

if i want to get a pie diagram with a diameter that is exactly the hight of the screen in landscape orientation or the width in portrait orientation, than the diagram stands out over edges of the box and the _touchHandler doesn't works there.

![pieChartOverflowsBorder](https://user-images.githubusercontent.com/72558028/106935136-44253880-671b-11eb-8069-86c3ac5757bd.png)

**Comment by imaNNeoFighT** [comment]
Hi. I'm sorry about that issue.
It must be fixed now, can you please check it out in our latest release?
