### ISSUE TITLE
because of upgrading flutter to new version, some problems have been occurred in drawing fl-charts

### ISSUE THREAD

**Issue by ahazizzadeh** [imaNNeoFighT/fl_chart#566]
because of upgrading flutter to new version, some problems have been occurred in drawing fl-charts. Can any one help me to solve this please?

flutter --version :
Flutter 1.26.0-17.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 4b50ca7f7f (4 days ago) • 2021-02-04 19:44:27 -0800
Engine • revision 2c527d6c7e
Tools • Dart 2.12.0 (build 2.12.0-259.8.beta)

**Comment by imaNNeoFighT** [comment]
Please use 0.20.0-nullsafety1 version when you are in beta channel.
