### ISSUE TITLE
Full customize ToolTip

### ISSUE THREAD

**Issue by xOldeVx** [imaNNeoFighT/fl_chart#569]
That can be useful if the **LineTooltipItem** was return a _Widget_ instead of _Text_ and _TextStyle_, in this way the tooltip can be full customize.
In my case i need to add a _Row_ with _Text_ and _Container_ (e.g Radius.circular(x)), and that the result:
![Screenshot_20210210-184926](https://user-images.githubusercontent.com/24361103/107542723-28b1a600-6bd1-11eb-97a0-e75730d97f77.png)

In this way It's able to change the text-color, depending on the color of his line, what i can't do when i have more than 2 rows in the tooltip

<details>
<summary>Code snippet</summary>
<p>

```
LineChart(
                LineChartData(
                  lineTouchData: LineTouchData(
                    touchTooltipData: LineTouchTooltipData(
                        tooltipBgColor: Colors.blueGrey.withOpacity(0.8),
                        getTooltipItems: (List<LineBarSpot> touchedBarSpots) {
                          return touchedBarSpots.map((barSpot) {
                            return LineTooltipItem(
                              barSpot.bar.colors[0] == const Color(0xff00ff75)
                                  ? '${vaccinated[barSpot.spotIndex].date}'
                                  : '${vaccinated[barSpot.spotIndex].vaccinatedFirstPerc}%\n${vaccinated[barSpot.spotIndex].vaccinatedSecondPerc}%',
                              TextStyle(color: Colors.white),
                            );
                          }).toList();
                        }),
                  ),
           ...
           ...
```

</p>
</details>

**Comment by imaNNeoFighT** [comment]
There is an open issue about having custom widgets inside the tooltip. #72.
I close this issue, we can follow it up there.
Thanks!
