### ISSUE TITLE
How we get dynamic titles on all axis with getTitle? 

### ISSUE THREAD

**Issue by DTharaka** [imaNNeoFighT/fl_chart#570]
when we displaying a graph of variations with a dynamic y-axis, it is not possible to show. 
For example, when we displaying monthly earnings of someone. Will take as he earned On January $ 500, on February $30,000, march $5000. On  January I want to scale y-axis with $100 gap. (0- $100, $100 - $200 ... ). But it comes to February I want to change the y-axis to $1000 gaps. 
In here, Graph change according to the highest-earning in what month of the whole year. It is also easy to see the difference between earnings. So how we manage this kind of thing?

**Comment by jonny7737** [comment]
I have a FAB that adjusts a value used in the title determination.  onTap function makes adjustments to the var maxX inside a setState.

The getTitles looks like this:
`                getTitles: (value) {
                  if (value % 5 != 0) return '';
                  return (maxX - value - 1).truncate().toString();
                },
`
And titles are returned as calculated in the return statement.

**Comment by imaNNeoFighT** [comment]
Thanks @jonny7737! You are correct.
