### ISSUE TITLE
How to set constant number of y-axis?

### ISSUE THREAD

**Issue by Telomeraz** [imaNNeoFighT/fl_chart#571]
Let's say we have 0 to 100 values for y-asis (leftTitles of LineChartData), and set interval to 50 and it will be lik 0 - 50 - 100. It's ok for now. However, when i have 0 to 200 values it will still display like 0 - 50 - 100 - 150 - 200. But this is not what i want. I want to set a constant number of y-asis to 3 let's say, and it will always divide 3 as equal.
When setting the value to 3, it will be displayed like below:

0 to 100 ==> 0 - 50 - 100
0 to 200 ==> 0 - 100 - 200
50 to 450 ==> 50 - 250 - 450
Always have different intervals but same number of y-axis.

Is there any way to do this?

**Comment by LondonTran** [comment]
Hi @Telomeraz ,

Once you find your Min and Max Y values, you can do something like this: 

```
import 'dart:math';
List<double> yAxisValues;
double minY;
double maxY;
double difference;
int firstYAxisLabel;
int secondYAxisLabel;
int thirdYAxisLabel;

getDifference(){
     difference = maxY - minY;
}
getLabels(List<double> yAxisValues ) {
     firstYAxisLabel = yAxisValues.reduce(min).toInt()
     secondYAxisLabel = (yAxisValues.reduce(min) + (difference / 2)).toInt();
     thirdYAxisLabel = yAxisValues.reduce(max).toInt();
}
```

Then when you get to the Y-axis label section for your graph, you can do this: 

```
titlesData: FlTitlesData(
        bottomTitles: SideTitles(
          showTitles: true,
          reservedSize: 30,
          getTextStyles: (value) => const TextStyle(
            color: Color(0xff72719b),
            fontWeight: FontWeight.bold,
            fontSize: 16,
          ),
          margin: 10,
          interval: 1,
          getTitles: (value) {
//Y AXIS LABELS
            //1st Y-axis label
            if (value.toInt() == firstYAxisLabel) {
              return (something here);
            }

            // 2nd Y-axis label
            if (value.toInt() == secondYAxisLabel) {
              return (something here);
            }

            // 3rd Y-axis label
            if (value.toInt() == thirdYAxisLabel) {
              return (something here);
            }
            return '';
          },
        ),

```

**Comment by Telomeraz** [comment]
Hi, @LondonTran 

Firstly, thank you for your answer. I could also use getEfficientInterval function which is built-in. But I think this should be done by giving parameter to the class.

**Comment by imaNNeoFighT** [comment]
Hi, @Telomeraz.
You can just copy-paste the getEfficientInterval logic and modify it with your need.
Thanks!
