### ISSUE TITLE
Offset argument contained a NaN value - PieChart 

### ISSUE THREAD

**Issue by strato-cruiser** [imaNNeoFighT/fl_chart#582]
Hey Guys,

found a little issue creating a PieChart. When creating PieChartSectionData and the value = 0 for all PieChartSectionDatas, I get the following error message. However If I set any of the three PieChartSectionData value to >= 1; than it works. This is the error message:

The following assertion was thrown during paint():
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 43: '<optimized out>'

The relevant error-causing widget was: 
 
When the exception was thrown, this was the stack: 
#2      _offsetIsValid (dart:ui/painting.dart:43:10)
#3      Canvas.drawLine (dart:ui/painting.dart:3702:12)
#4      CanvasWrapper.drawLine (package:fl_chart/src/utils/canvas_wrapper.dart:54:62)
#5      PieChartPainter._removeSectionsSpace.<anonymous closure> (package:fl_chart/src/chart/pie_chart/pie_chart_painter.dart:165:21)
#6      ListMapView.forEach (dart:_internal/list.dart:242:8)
...
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#71dd4
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=130.0, h=130.0)
...  size: Size(130.0, 130.0)
RenderObject: RenderCustomPaint#71dd4
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=130.0, h=130.0)
  size: Size(130.0, 130.0)
...  child: _RenderLayoutBuilder#5d300 NEEDS-PAINT
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=130.0, h=130.0)
...    size: Size(130.0, 130.0)
...    child: RenderConstrainedBox#30f98 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=130.0, h=130.0)
...      size: Size(130.0, 130.0)
...      additionalConstraints: BoxConstraints(unconstrained)

This is the code: 

    Container(
                    height: 150,
                    width: 200,
                    decoration: BoxDecoration(
                      color: Theme.of(context).cardColor,
                      borderRadius: BorderRadius.circular(
                        screenSizeFactor(
                          context,
                          10,
                        ),
                      ),
                    ),
                    child: Stack(
                      alignment: Alignment.center,
                      children: [
                        Padding(
                          padding: EdgeInsets.all(10),
                          child: AspectRatio(
                            aspectRatio: 1,
                            child: PieChart(
                              PieChartData(
                                borderData: FlBorderData(show: false),
                                sections: [
                                  PieChartSectionData(
                                    badgePositionPercentageOffset: 0,
                                    showTitle: false,
                                    color: Colors.blue,
                                    radius: 5,
                                    value: 0,
                                  ),
                                  PieChartSectionData(
                                    showTitle: false,
                                    color: Colors.red,
                                    radius: 5,
                                    value: 0,
                                  ),
                                  PieChartSectionData(
                                    showTitle: false,
                                    color: Theme.of(context).indicatorColor,
                                    radius: 5,
                                    value: 0,
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),

**Comment by imaNNeoFighT** [comment]
Reproducible code should contain the main function.

**Comment by c0pp1ce** [comment]
I am having that error aswell.

**Comment by imaNNeoFighT** [comment]
Hi, at the moment, we have changed our draw approach. Now we use RenderObjects for drawing, sizing, and touches. (previously, we used CustomPainter).
RenderObjects is more stable and error-prone. Please check this issue with our new release [0.30.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.30.0). Let me know whether it has been fixed or not.

**Comment by c0pp1ce** [comment]
While I dont get a NaN error anymore there is still an issue : 

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:flutter/src/rendering/box.dart': Failed assertion: line 2784 pos 18: 'transformed == position - childParentData.offset': is not true.

The error is thrown when tapping on the pie chart while all values are 0.

**Comment by imaNNeoFighT** [comment]
It should be fixed in our new version.
Please check [0.35.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.35.0), and verify it is working properly.
