### ISSUE TITLE
[Feature] ChartController

### ISSUE THREAD

**Issue by kattatzu** [imaNNeoFighT/fl_chart#583]
First of all, excellent work !! 

it will be feasible to include a "ChartController" to avoid redrawing the entire widget and its containers.  

with a controller:
- it might be simpler to implement data realtime and get only the graph to update.  
- you could inject a Stream, Future, callback or as a widget as in the examples.  
- the graph could be manipulated through an "api".  

My opinion is within the limits of my knowledge. 

regards!!

**Comment by imaNNeoFighT** [comment]
You are right!
Thanks for the suggestion.
Also, I will be happy if you contribute!
