### ISSUE TITLE
Issues with Piecharts after upgrading to 0.12.3

### ISSUE THREAD

**Issue by devpsolutions** [imaNNeoFighT/fl_chart#584]
Hi,

first of all great work!

I've just upgraded to version 0.12.3 and encountered some issues with the new Version.
It seems that the touch handling and the parameter "centerSpaceRadius: double.infinity" of the PieChart do not work anymore.

Code:
```
Container(
            child: PieChart(PieChartData(
                pieTouchData: PieTouchData(
                    enabled: true,
                    touchCallback: (pieTouchResponse) {
                      // ... some code.  <--- callback does not get called anymore when pie chart is touched
                    }),
                sectionsSpace: 0,
                centerSpaceRadius: double.infinity, <---
                borderData: FlBorderData(
                  show: false,
                ),
                sections: sectionData(widget.data.table))),
          ),
        ]));
```

Error caused by "centerSpaceRadius: double.infinity":
> Cannot interpolate between finite and non-finite values
> 'dart:ui/lerp.dart':
> Failed assertion: line 21: '<optimized out>'

Other Issue:
When the PieChart is touched the touchCallback does not get called.

Thanks,
Stefan

**Comment by imaNNeoFighT** [comment]
Hi, at the moment, we have changed our draw approach. Now we use RenderObjects for drawing, sizing, and touches. (previously, we used CustomPainter).
RenderObjects is more stable and error-prone. Please check this issue with our new release [0.30.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.30.0). Let me know whether it has been fixed or not.
