### ISSUE TITLE
Dual Y-axis. Allow data series to be bound to one of two Y-axis (default = left-Y)

### ISSUE THREAD

**Issue by abhinavc** [imaNNeoFighT/fl_chart#587]
Hello,
Thanks for a wonderful package. I was wondering if you could give your thoughts on how #51 could be done. The issue was closed for lack of input. But thereafter, someone uploaded an image what is expected. 

If there could be a way to define 2 Y-axis, each with their minX and minY and then a way to bind a data-series to one of the two, then I think #51  could be achieved - along with #429.  

Unless, there already is a way that I missed. I'm still new to the package. 

Thanks 
Abhinav.

**Comment by imaNNeoFighT** [comment]
Hi @abhinavc.
Thanks for letting me know about the #51 sample image.
As you mentioned, we have an already opened issue about it (here #429).
I will close this issue and follow it up in #429. However, you can thumb up to make it more prioritize.
