### ISSUE TITLE
Negative value due to curve

### ISSUE THREAD

**Issue by MiguelSOliveira** [imaNNeoFighT/fl_chart#593]
This is caused when all the values are 0, except one. You can see that, due to the curve, the y axis value turns negative around "Friday".

Is there a way to make this not happen but still have the curve, somehow?
<img width="381" alt="image" src="https://user-images.githubusercontent.com/8149533/110224946-3f010800-7ed8-11eb-977c-3447a9d22a4d.png">

Thank you!

**Comment by imaNNeoFighT** [comment]
We have `preventCurveOverShooting` and `preventCurveOvershootingThreshold` properties in [LineChartBarData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartbardata).
You can use them to fix this issue.
