### ISSUE TITLE
is there a way for show different value not point value when pressing the graph 

### ISSUE THREAD

**Issue by avcholding** [imaNNeoFighT/fl_chart#594]
is it possible to show x and y point both and different values

**Comment by imaNNeoFighT** [comment]
Yes, did you check the samples?

**Comment by imaNNeoFighT** [comment]
Check ScatterChartSample2 ([Source Code](/example/lib/scatter_chart/samples/scatter_chart_sample2.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/scatter_chart/scatter_chart_sample_2.gif" width="300" >

**Comment by imaNNeoFighT** [comment]
Or LineChart Sample 9 ([Source Code](/example/lib/line_chart/samples/line_chart_sample9.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_9.gif" width="300" >
