### ISSUE TITLE
Stroke for Pie Chart Sections

### ISSUE THREAD

**Issue by DooRooSA** [imaNNeoFighT/fl_chart#606]
It would be great if we could specify a stroke (color, thickness) for individual pie chart sections. See attached image:

![Capture](https://user-images.githubusercontent.com/17521217/111478464-c6504600-8738-11eb-8a2c-5cb19546bbcc.PNG)

**Comment by imaNNeoFighT** [comment]
Hi. we have just added `borderSide` property in [PieChartSectionData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/pie_chart.md#piechartsectiondata).

Please check it out in [0.36.3](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.36.3)

**Comment by DooRooSA** [comment]
You guys/gals are legends! Thank you very much!!!

**Comment by imaNNeoFighT** [comment]
Thanks

### checkout our pie sample 1.
----
##### Sample 1 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/pie_chart/samples/pie_chart_sample1.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/pie_chart/pie_chart_sample_1.gif" width="300" >
