### ISSUE TITLE
When to add animation support ？

### ISSUE THREAD

**Issue by xSILENCEx** [imaNNeoFighT/fl_chart#61]
I like this plugin ,but its not supports animation .

**Comment by imaNNeoFighT** [comment]
Thanks, I'm on it ;)
stay tuned.

**Comment by imaNNeoFighT** [comment]
you can watch on the repo, I will add animations ASAP.

**Comment by davidmarinangeli** [comment]
The attention to details of this repo is really stunning! Great work @imaNNeoFighT !

**Comment by imaNNeoFighT** [comment]
Thanks
