### ISSUE TITLE
I am looking for a different kind of Pie Chart.

### ISSUE THREAD

**Issue by ShahzadUmarBaig** [imaNNeoFighT/fl_chart#611]
I have been searching your charts library but couldn't find a customized chart like the one I am looking for, attaching the issue with example so you can explore it. Can you improvise your package and include such charts?  Else I can work on this and produce a Pull Request.

https://github.com/hashirshoaeb/star_book/issues/214#issue-825889704

Look into the attached issue.

**Comment by imaNNeoFighT** [comment]
Hi, which part is missing?
I think you can put a circle card above the pie chart (using the Stack widget) to achieve that result.

**Comment by hashirshoaeb** [comment]
Thanks @imaNNeoFighT

**Comment by imaNNeoFighT** [comment]
If you think your issue is resolved, feel free to close this issue.
Thanks!

**Comment by hashirshoaeb** [comment]
@imaNNeoFighT Yup it is resolved. Thanks.
