### ISSUE TITLE
Unidentified

### ISSUE THREAD

**Issue by alexandranb** [imaNNeoFighT/fl_chart#617]
Hi, not a bug, more like a question. Could anyone tell me why is there put Unidentified to the pub.dev plugin title?
![image](https://user-images.githubusercontent.com/17476028/112493823-2d01df00-8d8b-11eb-8290-7cca44c0c4e3.png)

**Comment by imaNNeoFighT** [comment]
Where did you see this?
I couldn't find it.

**Comment by alexandranb** [comment]
It is solved now. Dunno how, but doesn't appear anymore.
