### ISSUE TITLE
Year/Month base line chart

### ISSUE THREAD

**Issue by Hong822** [imaNNeoFighT/fl_chart#619]
Hello,

I make a FlSpot list like below and x value means 'Year + Month'

_0 = {FlSpot} (202012.0, 8465.696263643998)
1 = {FlSpot} (202101.0, 7771.7867338371125)
2 = {FlSpot} (202102.0, 8789.520710887211)_

I tried drawing a line char using the data but unexpected x values are generated between 202012 and 202101. For instance 2020-22.

Could you help me how to get rid of the unnecessary values?
Thank you.

=======================================================================
**<Line Chart Code>**

LineChartData(
              lineTouchData: LineTouchData(enabled: true),
              titlesData: FlTitlesData(
                show: true,
                bottomTitles: SideTitles(
                    showTitles: true,
                    rotateAngle: 60,
                    getTitles: (value) {
                      String temp = value.toInt().toString();
                      String Year = temp.substring(2, 4);
                      String Month = temp.substring(4);
                      return Year + "-" + Month;
                    }),
                leftTitles: SideTitles(
                  interval: 500,
                  showTitles: true,
                  getTitles: (value) {
                    String temp = value.toInt().toString();
                    return temp + "\nKRW";
                  },
                ),
              ),
              minX: double.parse(widget.sStartMonth),
              maxX: double.parse(widget.sEndMonth),
              minY: GetMinMaxPrice(false) - 1000,
              maxY: GetMinMaxPrice(true) + 1000,
              gridData: FlGridData(
                show: true,
                drawVerticalLine: true,
                drawHorizontalLine: true,
                horizontalInterval: 500,
                getDrawingHorizontalLine: (value) {
                  return FlLine(
                    color: Colors.black,
                    strokeWidth: 1,
                  );
                },
                // checkToShowHorizontalLine: (value){
                //   if(value > 9000)
                //     return true;
                //   else
                //     return false;
                // },
              ),
              borderData: FlBorderData(
                show: true,
                border: Border.all(
                  color: Colors.black,
                  width: 1,
                ),
              ),
              lineBarsData: [
                LineChartBarData(
                  spots: _GetCharData(0),
                  isCurved: false,
                  colors: [
                    Colors.red,
                  ],
                  barWidth: 1,
                  dotData: FlDotData(
                    show: true,
                  ),
                ),
                LineChartBarData(
                  spots: _GetCharData(1),
                  isCurved: false,
                  colors: [
                    Colors.orange,
                  ],
                  barWidth: 1,
                  isStrokeCapRound: true,
                  dotData: FlDotData(
                    show: true,
                  ),
                ),
                LineChartBarData(
                  spots: _GetCharData(2),
                  isCurved: false,
                  colors: [
                    Colors.yellow,
                  ],
                  barWidth: 1,
                  isStrokeCapRound: true,
                  dotData: FlDotData(
                    show: true,
                  ),
                ),
              ]),
        ),

**Screenshots**
![image](https://user-images.githubusercontent.com/47422913/112655162-776e8300-8e93-11eb-8395-507594b3847a.png)

**Versions**
 - which version of the Flutter are you using? ==> 2.0.1
 - which version of the FlChart are you using? ==> 0.12.2

**Comment by OlegNovosad** [comment]
Try to play with `interval` on the bottom titles. By default it is calculated using `getEfficientInterval`. Per docs:

```dart
/// Returns an efficient interval for showing axis titles, or grid lines or ...
///
/// If there isn't any provided interval, we use this function to calculate an interval to apply,
/// using [axisViewSize] / [pixelPerInterval], we calculate the allowedCount lines in the axis,
/// then using  [diffInYAxis] / allowedCount, we can find out how much interval we need,
/// then we round that number by finding nearest number in this pattern:
/// 1, 2, 5, 10, 20, 50, 100, 200, 500, 1000, 5000, 10000,...
double getEfficientInterval(double axisViewSize, double diffInYAxis,
    {double pixelPerInterval = 10}) {
  final allowedCount = axisViewSize ~/ pixelPerInterval;
  final accurateInterval = diffInYAxis / allowedCount;
  return _roundInterval(accurateInterval).toDouble();
}
```

**Comment by imaNNeoFighT** [comment]
Hi sir.
You need to map your values into FlSpot to show it correctly.

Check [this snippet](https://gist.github.com/imaNNeoFighT/04b1a38b5948c6b295880dbb14131507)

<img src="https://user-images.githubusercontent.com/7009300/116826661-67407680-abaa-11eb-8863-d16bbf6582fc.png" width=300 />
