### ISSUE TITLE
Add feature to color area between graph line and a certain y value

### ISSUE THREAD

**Issue by marijannovak123** [imaNNeoFighT/fl_chart#62]
Attaching a sketch to visualize.

yellow line represent the y value in question

![sketch-1566764723395](https://user-images.githubusercontent.com/32665759/63656256-d3da5f80-c791-11e9-8907-fa93f9f6efda.jpg)

**Comment by imaNNeoFighT** [comment]
added in [0.0.3](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.3.3), check this sample:

<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_4.png" width="300" >

here is the [source code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample4.dart).
