### ISSUE TITLE
[BUG] Null check operator used on a null value -  version 0.30.0

### ISSUE THREAD

**Issue by darkh** [imaNNeoFighT/fl_chart#621]
**Describe the bug**
I am using stream to rebuild the widget whenever I got new data, every time new data coming the console throw the follow error but the app not crashing and the data showing right it's just the error show in the console

this error didn't appear when I used older version it's start only when switched to flutter 2

seems the error happens on this line 
childParentData.offset = badgeOffsets[counter++]! - sizeOffset;

I don't use the badge on my code 

════════ Exception caught by rendering library ═════════════════════════════════
The following _CastError was thrown during performLayout():
Null check operator used on a null value

The relevant error-causing widget was
PieChart
lib/…/widgets/pie_chart.dart:72
When the exception was thrown, this was the stack
#0      RenderPieChart.performLayout
package:fl_chart/…/pie_chart/pie_chart_renderer.dart:115
#1      RenderObject._layoutWithoutResize
package:flutter/…/rendering/object.dart:1641
#2      PipelineOwner.flushLayout
package:flutter/…/rendering/object.dart:884
#3      RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:453
#4      WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:874
...
The following RenderObject was being processed when the exception was fired: RenderPieChart#4220f NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
RenderObject: RenderPieChart#4220f NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=318.9, h=318.9)
    size: Size(318.9, 318.9)
    child 1: RenderLimitedBox#340b0 relayoutBoundary=up1
        parentData: offset=Offset(-79.4, 0.0); id=null (can use size)
        constraints: BoxConstraints(0.0<=w<=318.9, 0.0<=h<=318.9)
        size: Size(318.9, 318.9)
        maxWidth: 0.0
        maxHeight: 0.0
        child: RenderConstrainedBox#3bac3 relayoutBoundary=up2
            parentData: <none> (can use size)
            constraints: BoxConstraints(0.0<=w<=318.9, 0.0<=h<=318.9)
            size: Size(318.9, 318.9)
            additionalConstraints: BoxConstraints(biggest)
    child 2: RenderLimitedBox#68375 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: offset=Offset(0.0, 0.0); id=null (can use size)
        constraints: BoxConstraints(0.0<=w<=318.9, 0.0<=h<=318.9)
        size: Size(318.9, 318.9)
        maxWidth: 0.0
        maxHeight: 0.0
        child: RenderConstrainedBox#589e5 relayoutBoundary=up2 NEEDS-PAINT
            parentData: <none> (can use size)
            constraints: BoxConstraints(0.0<=w<=318.9, 0.0<=h<=318.9)
            size: Size(318.9, 318.9)
            additionalConstraints: BoxConstraints(biggest)
════════════════════════════════════════════════════════════════════════════════

**Versions**
 - which version of the Flutter are you using?
 Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (9 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
 - which version of the FlChart are you using?
 fl_chart: ^0.30.0

**Comment by imaNNeoFighT** [comment]
Hi, it should be fixed in [0.35.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.35.0).
Check it out and let me know whether it has been fixed or not.

**Comment by darkh** [comment]
@imaNNeoFighT Hi, try it, and works fine now, no error in the console 
Thank you

**Comment by imaNNeoFighT** [comment]
Thank you!
