### ISSUE TITLE
Can't install with latest dart version

### ISSUE THREAD

**Issue by lzharif** [imaNNeoFighT/fl_chart#622]
I tried to install fl_chart for my project, yet when running "flutter pub get" the issue happened:

`Because appstest depends on fl_chart >=0.20.0-nullsafety1 which requires SDK version >=2.12.0-259.12.beta <3.0.0, version solving failed.
pub get failed (1; Because appstest depends on fl_chart >=0.20.0-nullsafety1 which requires SDK version >=2.12.0-259.12.beta <3.0.0, version solving failed.)
exit code 1`

Details:
Dart SDK version: 2.9.0.
Flutter: 1.20.1
fl_chart: ^0.30.0

**Comment by darkh** [comment]
you should use the older version because your app still on the older flutter and dart version 
try this version 0.12.3
or you should do a flutter upgrade to upgrade your flutter and dart to the latest version so you can use the latest version of this

**Comment by OlegNovosad** [comment]
Upgrade to dart 2.12 or use fl_chart version 0.12.3 or lower.

@imaNNeoFighT I think this one can be closed as irrelevant.

**Comment by imaNNeoFighT** [comment]
@darkh @OlegNovosad, you both are correct!
Thanks!
