### ISSUE TITLE
Left titles spam on animate big range Y values

### ISSUE THREAD

**Issue by orteney** [imaNNeoFighT/fl_chart#626]
Hello, thanks for the lib x)
Please help me figured out how to remove this Y titles spam on animation from big maxY to small maxY.
It is very strange that this behavior is only when the Y values are decreasing.

**Spam example**
![ezgif-2-badc2e4d521a](https://user-images.githubusercontent.com/26565071/113539772-ba092b80-9608-11eb-9876-cc18898568b6.gif)

Also decreasing the value even further, for example from 15k to 5, takes too long and causes the UI to freeze. In the profiler, I found that the summed time of the _drawTitle reaches up to 1 second. Maybe these problems are related :<

**Freezing example**
![ezgif-2-02082f39c33b](https://user-images.githubusercontent.com/26565071/113540777-0d7c7900-960b-11eb-82c9-b7606ce516ad.gif)

P.S. Disabling animation completely fixes these problems

**Versions**
 - Flutter 2.0.2
 - FlChart 0.30.0

**Comment by orteney** [comment]
So i solved my issue. I have a precalculated interval for my maxY to display only 6 left titles. 
When i update BarChart or LineChart with new maxY and left titles interval, animation is launched with lerp maxY and interval values, but `_drawTitles `method always using final value of interval and drawing all this texts :)

**Comment by imaNNeoFighT** [comment]
Hi sir, If you think there is nothing left feel free to close this issue.
Thanks for explaining your solution.

**Comment by Prn-Ice** [comment]
Hi @orteney @imaNNeoFighT, im having this same issue but cant find a fix, I also have a function for custom intervals.

**Comment by imaNNeoFighT** [comment]
Hi @Prn-Ice .
Can you provide me a reproducible code?
