### ISSUE TITLE
Radar Chart circular border

### ISSUE THREAD

**Issue by Mohdx** [imaNNeoFighT/fl_chart#627]
Sorry for the silly question, But I couldn't find color parameter for the circular border around the whole radar chart
I'm trying to make it transparent color, or find a way to remove it ![20210406_103150.jpg](https://user-images.githubusercontent.com/51845593/113650757-5a238b00-96c3-11eb-825e-e5bc677cd9dc.jpg)

**Comment by imaNNeoFighT** [comment]
@payam-zahedi Can you check it out?

**Comment by payam-zahedi** [comment]
@Mohdx you can use the [`radarBorderData`](https://github.com/imaNNeoFighT/fl_chart/blob/2d42fdb0969eb3e3a8eac39637ea96083fe28b94/lib/src/chart/radar_chart/radar_chart_data.dart#L24) field in [`RadarChartData`](https://github.com/imaNNeoFighT/fl_chart/blob/2d42fdb0969eb3e3a8eac39637ea96083fe28b94/lib/src/chart/radar_chart/radar_chart_data.dart#L16) chart class.

The sample code for that would look something like this:

``` dart
RadarChartData(
                dataSets: showingDataSets(),
                radarBorderData: const BorderSide(color: Colors.transparent),
                ...
            ),
```

**Comment by Mohdx** [comment]
> 
> 
> @Mohdx you can use the [`radarBorderData`](https://github.com/imaNNeoFighT/fl_chart/blob/2d42fdb0969eb3e3a8eac39637ea96083fe28b94/lib/src/chart/radar_chart/radar_chart_data.dart#L24) field in [`RadarChartData`](https://github.com/imaNNeoFighT/fl_chart/blob/2d42fdb0969eb3e3a8eac39637ea96083fe28b94/lib/src/chart/radar_chart/radar_chart_data.dart#L16) chart class.
> 
> The sample code for that would look something like this:
> 
> ```dart
> RadarChartData(
>                 dataSets: showingDataSets(),
>                 radarBorderData: const BorderSide(color: Colors.transparent),
>                 ...
>             ),
> ```

Yeah its there ` radarBorderData: const BorderSide(color: Colors.transparent),` . But the border still visible, not transparent 👀

**Comment by payam-zahedi** [comment]
you are right @Mohdx, I checked out the source code and found that we had some changes in the drawing radar chart.
@imaNNeoFighT  I will create a PR for this issue ASAP.

**Comment by markovicdenis** [comment]
Any update on when this will get merged?

**Comment by imaNNeoFighT** [comment]
Tonight.

**Comment by imaNNeoFighT** [comment]
It must be fixed in [0.36.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.36.0). Check it out and let me know.

**Comment by imaNNeoFighT** [comment]
@Mohdx Feel free to close this issue

**Comment by Mohdx** [comment]
Thank you all. Appreciate it
