### ISSUE TITLE
LineChart Crossing the line

### ISSUE THREAD

**Issue by HelooM** [imaNNeoFighT/fl_chart#633]
![image](https://user-images.githubusercontent.com/16040084/113976832-3489b380-9874-11eb-8f29-ffbf1bcb2b3d.png)
I use the 0.12.2 version.how can i fix this issues?

**Comment by RTsosssoldi** [comment]
Hey, i solved this by using:
`LineChartBarData(
          isCurved: true,
          preventCurveOverShooting: true,
          ...
 ),`

**Comment by imaNNeoFighT** [comment]
@HelooM  can you try @RTsosssoldi's solution?

**Comment by epietrowicz** [comment]
@imaNNeoFighT , @RTsosssoldi 's solution worked for me
