### ISSUE TITLE
APP Released for WEB Problem

### ISSUE THREAD

**Issue by Parufrade** [imaNNeoFighT/fl_chart#636]
The charts blocks the UI and does not show the charts on an APP released for WEB.

**Comment by GP4cK** [comment]
I had the issue when I was on 0.12.2 with flutter stable 2.0.4.
Upgrading `fl_chart` to 0.35.0 fixed it.

Also quick tip: when you ask a question, try to give a meaningful title like "Charts don't show on web".

**Comment by imaNNeoFighT** [comment]
@GP4cK is right.
Thanks for explaining.

@Parufrade Also it is better to mention your fl_chart, and flutter version.

**Comment by moioo91120** [comment]
Hello, I have the same problem.

fl_chart v0.35
Flutter 2.0.1

It works on web with html render, but not with canvas render.
With canvas render, I have the following error 
══ Exception caught by rendering library ═════════════════════════════════
  BindingError: Tried to invoke ctor of Path with invalid number of parameters (1) - expected (0) parameters instead!
The relevant error-causing widget was
LineChart
..\…\graph-fl\graph-fl.dart:6 

With a basic 
class GraphFl extends StatelessWidget {
  Widget build(BuildContext context) {
    return LineChart(
      sampleData1(),
      swapAnimationDuration: Duration(milliseconds: 150), // Optional
      swapAnimationCurve: Curves.linear, // Optional
    );
  }
}

coming directly from the documentation

**Comment by imaNNeoFighT** [comment]
Please check it with the latest flutter version.
It must be fixed in [2.0.5](https://flutter.dev/docs/development/tools/sdk/releases?tab=linux)
