### ISSUE TITLE
Chart triggers Scrolling

### ISSUE THREAD

**Issue by florianh01** [imaNNeoFighT/fl_chart#637]
**Describe the bug**
First of all: Thank you very much for this great package!
I have the following problem and unfortunately I couldn't solve it.

When moving the ToolTip on the chart, the vertical scroll position also changes. Is there any way to prevent this behavior? You can see the problem on the gif - the white spot is my finger position. 
The automatic scrolling behavior gives a really strange user experience.

**To Reproduce**
<details>
<summary>Code to reproduce</summary>

```
import 'package:flutter/material.dart';
import 'package:fl_chart/fl_chart.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  SliverToBoxAdapter _buildChart() {
    return SliverToBoxAdapter(
      child: Container(
        padding: EdgeInsets.all(16),
        height: 200,
        width: 200,
        child: LineChart(
          LineChartData(
            lineBarsData: [
              LineChartBarData(
                spots: spots,
                isCurved: true,
                barWidth: 3,
                dotData: FlDotData(show: false),
                preventCurveOverShooting: true,
                curveSmoothness: 5,
              ),
            ],
            gridData: FlGridData(show: false),
            titlesData: FlTitlesData(show: false),
            borderData: FlBorderData(show: false),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('Test')),
        body: CustomScrollView(
          physics: ClampingScrollPhysics(),
          slivers: [
            SliverToBoxAdapter(
              child: SizedBox(height: 500),
            ),
            _buildChart(),
            SliverToBoxAdapter(
              child: SizedBox(height: 500),
            ),
          ],
        ),
      ),
    );
  }
}

List<FlSpot> spots = [
  FlSpot(1.0, 1.0),
  FlSpot(2.0, 2.0),
  FlSpot(3.0, 2.0),
  FlSpot(4.0, 2.0),
  FlSpot(5.0, 2.0),
  FlSpot(6.0, 3.0),
  FlSpot(7.0, 6.0),
  FlSpot(8.0, 13.0),
  FlSpot(9.0, 15.0),
  FlSpot(10.0, 25.0),
  FlSpot(11.0, 27.0),
  FlSpot(12.0, 30.0),
  FlSpot(13.0, 35.0),
  FlSpot(14.0, 42.0),
  FlSpot(15.0, 48.0),
  FlSpot(16.0, 53.0),
  FlSpot(17.0, 72.0),
  FlSpot(18.0, 72.0),
  FlSpot(19.0, 81.0),
  FlSpot(20.0, 98.0),

];
```
</details>

**Screenshots**
![20210412_201030](https://user-images.githubusercontent.com/78513002/114446304-62069200-9bd1-11eb-9540-1cd5ba702571.gif)

**Versions**
 - which version of the Flutter are you using? --> 2.0.4
 - which version of the FlChart are you using? --> 0.35.0

**Comment by florianh01** [comment]
FYI: ListView() instead of CustomScrollView() does not help either

**Comment by florianh01** [comment]
For anyone else encountering this Problem, I found a workaround:

Wrapping The Chart inside a GestureDetector Widget + overriding onHorizontalDragUpdate function works surprisingly well:

```
GestureDetector(
      onHorizontalDragUpdate: (x) {},
      child: LineChart()
)
```

**Comment by tsuruobiz** [comment]
Same problem, it is not good user experience, I think too.

**Comment by tsuruobiz** [comment]
Related to this issue, I confuse horizontal scroll in `PageView` or `TabBarView`. When moveing the tooltip on the chart, these views also changes page. it looks like conflicts two swipe action. I think it is also strange use experience.

this is `main.dart` example.

![fl_chart_horiziontal_scroll](https://user-images.githubusercontent.com/59546923/114481996-b6952600-9c40-11eb-8de2-03d282a19d01.gif)

**Comment by tsuruobiz** [comment]
**Additional:** 
@jfmichel workaround `onHorizontalDragUpdate: (x) {},` also works fine Horizontal Scroll in `PageView`. 
Thanks!

![good](https://user-images.githubusercontent.com/59546923/114483606-9e72d600-9c43-11eb-9beb-068eb2af3322.gif)

**Comment by imaNNeoFighT** [comment]
I think @florianh01 solution is the best at the moment (I don't have any better Idea)
We just can embed this code in the library, and give a flag outside to handle this.
Do you think it should be handled in the library? or it is fine to handle it with a trick?

**Comment by imaNNeoFighT** [comment]
We handled it by wrapping the chart inside a GestureDetector with onLongPress implementation.
It should be fixed now.
