### ISSUE TITLE
Show number tooltip on the closest value to the cursor even when treshold is set

### ISSUE THREAD

**Issue by RedyAu** [imaNNeoFighT/fl_chart#641]
_I'm sorry if this is a duplicate, I've looked trough the issues quickly, but I might have missed a similar one._

My problem is that when the user taps the graph, the number shows up to the right of the cursor, at the distance of the treshold.\
Treshold works great when there are only a few values in a graph, meaning it snaps to the closest value in that range, working both in the right and left directions.
**However, when there are many values, the tooltip appears way off to the side.**\
I understand this may be beneficial in cases where you have to avoid showing the value below the user's finger, but in our case, this is more annoying than is useful, we're getting bug reports of it.\
Also, like this, it's hard to check the values right at the start of the graph, or even impossible on smaller screens.
#### Demonstration:
![image](https://user-images.githubusercontent.com/12989935/115144240-e9c62380-a04b-11eb-89c6-89836c0a28bc.png)

#### Proposal:
There could be an option to turn on "closest-snap", meaning the tooltip would show for the closest value to the cursor in the range of the treshold on the graph.

**Comment by imaNNeoFighT** [comment]
Hi sir.

Did you check our LineChartSample9? It works great in close values.

##### Sample 9 ([Source Code](/example/lib/line_chart/samples/line_chart_sample9.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_9.gif" width="300" >

BTW there is a `touchSpotThreshold` property in [LineTouchData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetouchdata-read-about-touch-handling) which allows you to change the sensitivity.

**Comment by imaNNeoFighT** [comment]
Does it make sense?

**Comment by RedyAu** [comment]
I think the mentioned PR might fix this, but the sample you linked doesn't seem to be connected to this.

**Comment by imaNNeoFighT** [comment]
Got it.

**Comment by imaNNeoFighT** [comment]
Fixed in [0.41.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.41.0).
Please check it out!
