### ISSUE TITLE
getNearestTouchedSpot in LineChartPainter not working as intended

### ISSUE THREAD

**Issue by PerLycke** [imaNNeoFighT/fl_chart#645]
As I read it getNearestTouchedSpot in LineChartPainter should return the nearest touched spot, but in fact it returns the first occurrence of a spot within a threshold. I would like to set a very big threshold and just activate the nearest spot clicking anywhere on my line chart, but this won't work due to above functionality.

I created https://github.com/imaNNeoFighT/fl_chart/pull/644 which fixes this

**Comment by imaNNeoFighT** [comment]
Oh, you are right. It is not working properly.
I think #641 is related to this issue right?

**Comment by imaNNeoFighT** [comment]
Dup of #641

**Comment by imaNNeoFighT** [comment]
Fixed in [0.41.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.41.0).
Please check it out!
