### ISSUE TITLE
How to get touched coordinate line chart

### ISSUE THREAD

**Issue by alpmusti** [imaNNeoFighT/fl_chart#646]
```
minX: 0,
maxX:24,
minY:0,
maxY: 100
```
How can i be able to detect user's touched coordinate like `(x: 15, y:20)` even if no spot was added to touched point. I've tried `touchCallback` but it just gives me `PointerEvent` not the touched coordinates on the chart.

In other words, how can I add a new `FlSpot` based on  touched coordinate on the line chart.

**Comment by jseminck** [comment]
Try this. This is how I get the touched chart point with the `touchCallback`:

```dart
FlSpot touchedSpot = chartData[touchResponse.lineBarSpots[0].spotIndex];
```

**Comment by imaNNeoFighT** [comment]
@jseminck Is exactly correct.
