### ISSUE TITLE
centerSpaceRadius set to double.infinity renders empty

### ISSUE THREAD

**Issue by emlynmac** [imaNNeoFighT/fl_chart#652]
** Don't make a duplicate issue.
I didn't find an existing issue

**Describe the bug**
Following the example to set a donut-style pie chart which fills the area by setting centerSpaceRadius to `double.infinity` results in an empty area.

**To Reproduce**
using:
```
Container(
height: 66,
width: 66,
child: AspectRatio(
    aspectRatio: 1,
    child: FlChart(
        chart: PieChart(
            PieChartData(
                borderData: FlBorderData(show: false),
                centerSpaceRadius: double.inifity,
                sectionSpace: 1,
                sections: chartSections,
                startDegreesOffset:270),
))));
```

**Versions**
Flutter 2.0.4
FlChart 0.2.2

**Comment by imaNNeoFighT** [comment]
Please provide me a valid reproducible code (a main.dart file).

Thanks!

**Comment by emlynmac** [comment]
Sorry, just realized I cannot reproduce this on the current version of the FlChart library. 0.36.0 is fine and renders properly.

The issue I now have is a dependency mess; to roll up to null safety, I need to use equatable >2.0.0 as a dependency of fl_chart, but Artemis (graphQL library has its dependency as of ^1.2.5.
