### ISSUE TITLE
I am using line chart and it seems you don't allow customization to hide or show lines in chart or X-Y axis value. 

### ISSUE THREAD

**Issue by arslankaleem7229** [imaNNeoFighT/fl_chart#661]
Here is output of the code vs what I want my output. I just want to hide X-Y values and graph like and only want graph.
<img width="237" alt="Screen_Shot_2021-05-04_at_1 18 57_PM" src="https://user-images.githubusercontent.com/49631685/117223669-99124100-ae27-11eb-9fce-d15d62f0cc01.png">
![Screenshot_1620211902](https://user-images.githubusercontent.com/49631685/117223673-9a436e00-ae27-11eb-82fb-6fe87e3f7bfa.png)

to look like

**Comment by imaNNeoFighT** [comment]
Hi. there is a `titlesData` property in the [LineChartData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartdata) which helps you to modify titles behavior. Also, I strongly recommend you to check out our [LineChart samples](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#some-samples).

**Comment by arslankaleem7229** [comment]
Oh yes I figured it out. Thanks

**Comment by AlaaEdAouimeur** [comment]
Hello @imaNNeoFighT , is it possible to show the titles even if no data with that value is available ?
ex: 
my values are [51, 53, 40, 46]
can I show the titles as following  '40', '50' , '60'
Because as far as I understood from the examples, the value NEEDS to be present in order to show it's title !

**Comment by imaNNeoFighT** [comment]
@AlaaEdAouimeur 
You need to provide `minX`, `maxX`, `minY`, `maxY` and fill the `titlesData` property to customize it.
