### ISSUE TITLE
Web version don't render Line Chart

### ISSUE THREAD

**Issue by e-duarte** [imaNNeoFighT/fl_chart#662]
I'm using the Web for debugging my application. However, when I execute Line Chart this error message is showed:

BindingError: Tried to invoke ctor of Path with invalid number of parameters (1) - expected (0) parameters instead!

**Comment by imaNNeoFighT** [comment]
Hi. which version of `flutter` and `fl_chart` are you using?

**Comment by e-duarte** [comment]
Hello, I'm flutter sdk between">=2.7.0 <3.0.0" e   fl_chart: ^0.36.0. The execution in Mobile works.

**Comment by imaNNeoFighT** [comment]
Hi. it seems you are out of date. Please upgrade your `dart` and `flutter` version.
Run `flutter upgrade` command to upgrade the `flutter`.
and change `2.7.0` number to `2.12.0` to upgrade the `dart` version.
