### ISSUE TITLE
Have Line chart stop halfway

### ISSUE THREAD

**Issue by jacksonw765** [imaNNeoFighT/fl_chart#663]
Is there a way to have a line chart stop halfway? Like for a stock ticker I want the chart to end abruptly. 
![image](https://user-images.githubusercontent.com/13068724/117244572-47f25500-ae07-11eb-9ceb-b365d04ab581.png)

**Comment by imaNNeoFighT** [comment]
Sorry, I didn't understand the problem.

**Comment by jacksonw765** [comment]
I would like to have the line chart stop before reaching the end of the end of the screen like in the example above. Does this plugin support this or do I have to use other flutter widgets to achieve this effect?

**Comment by AmarjotSingh21** [comment]
Yes, you need to add maxX param in LineChartData, https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartdata

**Comment by imaNNeoFighT** [comment]
Yes, @AmarjotSingh21 is exactly correct!

You need to set a proper `maxX` to achieve your result.
