### ISSUE TITLE
Line color based on value always gets the last value

### ISSUE THREAD

**Issue by roderikpeeters** [imaNNeoFighT/fl_chart#664]
Im trying to create a linegraph with the line color be unique based on the value.

Using this function:

```dart
getColor() {
    for (MapEntry entry in dataList.asMap().entries) {
      double value = entry.value.dat;
      if (value > -2) {
        return step6Color;
      } else {
        return step1Color;
      }
    }
  }
```

Using getColor at the parameter. But depending on the last value in the data the line will be the same color instead of every datapoint a different color.

How can I fix this?

**Comment by imaNNeoFighT** [comment]
Hi. Can yo tell me your fl_chart version?
If you are in `0.36.0`, can you check it in `0.35.0`?

**Comment by imaNNeoFighT** [comment]
Also it is great to provide me a reproducible code.

**Comment by mkprogrammer15** [comment]
Good day! 
As I see this topic is still open.
I have the same question. 
But I just do it in this way:

colors: spotValue < 0
                      ? gradientColors2
                      : gradientColors1
                          .map((color) => color.withOpacity(0.52))
                          .toList(),
And it seems that the whole line gets the gradientColors2 if value somewhere is lower than 0.
