### ISSUE TITLE
Multiple charts tooltip display same value 

### ISSUE THREAD

**Issue by spacebacker** [imaNNeoFighT/fl_chart#665]
I faced a bug touchTooltipData show the same y-axis value for different charts in lineBarsData array. This bug exist only in version 0.36.0, downgrading to 0.35.0 helps. it's easy to reproduce with [Sample 1](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample1.dart). 

 0.36.0
<img src="https://user-images.githubusercontent.com/58192541/117302189-0784ec80-ae84-11eb-844e-3bcb3444006e.png" width="200">

0.35.0
<img src="https://user-images.githubusercontent.com/58192541/117302204-0b187380-ae84-11eb-8780-d370ac50ba34.png" width="200">

**Comment by imaNNeoFighT** [comment]
Holly polly!!
