### ISSUE TITLE
How to add Spots ?

### ISSUE THREAD

**Issue by MarcelHH** [imaNNeoFighT/fl_chart#668]
Hello i realy like Fi_chart but how i can add spots dynamic?

can I do something like that?

```
spots.add( 
 FlSpot(1, 1.4),
 FlSpot(2, 3.4),
)
```
I don't know how to do it

```
      spots: [
// add
      ],
```

**Comment by AlexEckstein** [comment]
I fixed it in my repo for the LineChartBar. Here is a link to my fork if you want to use it. https://github.com/AlexEckstein/fl_chart

**Comment by MarcelHH** [comment]
I've already solved it like this

```
List<FlSpot> mySpots = [];
mySpots.add(FlSpot(1, 2));
```

**Comment by imaNNeoFighT** [comment]
Hi. please check this sample:

We add spots dynamically in the time.

##### Line Sample 10 ([Source Code](/example/lib/line_chart/samples/line_chart_sample10.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_10.gif" width="300" >

**Comment by zzdota** [comment]
> I've already solved it like this
> 
> ```
> List<FlSpot> mySpots = [];
> mySpots.add(FlSpot(1, 2));
> ```
I add spots like this

  List<FlSpot> _getMainDatas() {
    List<FlSpot> list = [];
    for (int i = 0; i < 20; i+=2) {
      list.add(FlSpot(i.toDouble(),Random().nextInt(10).toDouble()));
    }
    return list;
  }
