### ISSUE TITLE
Performance Issue with getTitles with large range between flSpots.

### ISSUE THREAD

**Issue by kizmiaz7** [imaNNeoFighT/fl_chart#67]
Hello,

I am having a similar issue to that described in #54.

For example, the following:
FlSpot(1,-1000000) , 
FlSpot(1, 1000000)], 
minY = -1000000, 
leads to 1,000,000+ calls to the function that getTitles in the FlTitlesData() widget points too. This results in my app becoming completely non-responsive for a while until all these calls have completed. 

**Here's the code for my line chart:** 
Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.center,
      children: <Widget>[
        const SizedBox(
          height: 18,
        ),
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: SizedBox(
            width: MediaQuery.of(context).size.width * .95,
            height: MediaQuery.of(context).size.height * .8,
            child: FlChart(
              chart: LineChart(
                LineChartData(
                  lineTouchData: const LineTouchData(enabled: false),
                  lineBarsData: [
                    LineChartBarData(
                      spots: getSpots(),
                      isCurved: false,
                      barWidth: 8,
                      colors: [
                        Colors.indigo,
                      ],
                      belowBarData: BelowBarData(
                        show: true,
                        colors: [Colors.deepPurple.withOpacity(0.2)],
                      ),
                      dotData: FlDotData(
                        show: false,
                      ),
                    ),
                  ],
                  minY: widget.minY,
                  titlesData: FlTitlesData(
                    bottomTitles: SideTitles(
                        showTitles: true,
                        textStyle: TextStyle(
                            fontSize: 10,
                            color: Colors.purple,
                            fontWeight: FontWeight.bold),
                        getTitles: (value) {
                          return value.toStringAsFixed(0);
                        }),
                    leftTitles: SideTitles(
                      showTitles: true,
                      getTitles: (value) {
                        return getLeftTitle(value); _**//This function gets called 1,000,000+ times**_
                      },
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ],
    );

Map<double, String> leftTileValues = {};

String getLeftTitle(double value) {
    return widget.leftTileValues[value]; **_//it doesn't seem to matter what I do here, this function is called 1,000,000+ times._**
}

Here, the getLeftListTile(value) function gets called 1,000,000 + times.

Since my FlSpots are created dynamically, and minY and maxY values are determined at runtime, I am not using a switch to return the titles as you do in the examples provided. Instead, I created a Map<double,String> with 10 entries that are spaced evenly between the range of FlSpots. In other words (maxY - minY).

Is there a better way for me to dynamically create 10 titles evenly spaced between a large range of values over the Y axis (set an interval for Y axis titles) or is this a bug?

**Comment by wksvo** [comment]
me too.

**Comment by imaNNeoFighT** [comment]
Hi guys, I know your problem, but not sure what could we do,
I think you guys can scale down your values to fix this problem, is it works?

**Comment by kizmiaz7** [comment]
Hey Iman,

Thanks for taking the time to respond. Unfortunately this would not work in my case, which is that I wish to implement a PNL graph.

Depending on the user (and their currencies), values can range in the 1000s or 10,000,000s. 

While I do understand that your current implementation of line charts does not support a large range in values, it may be something you wish to consider implementing in the future as this issue is bound to prop up for others.

For example, any finance app that supports a low value currency that wishes to use your line chart will need it to support large range of values.

Do put the word out if you decide to work on it.

Outside of that, thanks for all the work you've done on this package :).

**Comment by imaNNeoFighT** [comment]
Your welcome, and it's my pleasure to read your text,
You are right, we should fix this problem,
as I understand the problem is just about y titles right? 
Your welcome,
Thanks!

**Comment by kizmiaz7** [comment]
You're welcome and thanks for your response!

I have not tested it for the x-axis but but it looks to me like it would work the same way when getTitles() is called for titles of the x-axis too. 

I fear the same issue may result if the graph needs to plot points with a large range of x values as well.

**Comment by stevenspiel** [comment]
I'm running into this issue, as well.

**Comment by imaNNeoFighT** [comment]
Ok, I will check it too,
stay tuned.
Thanks!

**Comment by imaNNeoFighT** [comment]
Fixed problem in [0.3.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.3.1), you can now set the `interval` in the [SideTitles](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#sidetitles) to fix your problem.
