### ISSUE TITLE
Line chart real time input and adjusts dynamically.

### ISSUE THREAD

**Issue by corteXnzt** [imaNNeoFighT/fl_chart#672]
Hi, I'm new with flutter and trying to use your wonderful library. I have some few questions and I'm sorry this are not issues but some kind of a guidance needed.

1. Is live data push on every points possible? I need to push new data every 50ms-100ms on the graph. And clear the datapoints of the linechart when start button is pressed, before showing new data again.

2. If 1 is possible do you have sample demo of that?

3. I want the graph to adjust dynamically like if max value is only 250Newton the graph max Y axis should only show 500N max value. Is that possible?

4. And the values display on each point should show exact value, like 247N should show 247. Currrently with the demo I need to set it to 2.47 to be able to accomodate on the graph demo. Is that doable?

5. Lastly can I display a stack on the graph  some values like the peak force like that when test is done?

TIA.

![tmp](https://user-images.githubusercontent.com/49268713/117661927-915cee80-b1d1-11eb-8045-3e7359dd6913.jpg)

**Comment by imaNNeoFighT** [comment]
Hi, I made a real-time example.

Check out LineChartSample10

[Source Code](/example/lib/line_chart/samples/line_chart_sample10.dart)
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_10.gif" width="300" >
