### ISSUE TITLE
Use WidgetSpan for BarTooltipItem

### ISSUE THREAD

**Issue by NadezhdaVoytova** [imaNNeoFighT/fl_chart#674]
Versions
 -  Flutter (Channel stable, 2.0.4),
 -  fl_chart: ^0.36.1

I have problem with using BarTooltipItem with WidgetSpan : after touch by BarChartRodData get error: 

![image](https://user-images.githubusercontent.com/40092437/118129771-43303100-b405-11eb-9dc3-bab379d11884.png)

```
BarChartData(
  barTouchData: BarTouchData(
      enabled: true,
      touchTooltipData: BarTouchTooltipData(
          maxContentWidth: 100,
          tooltipBgColor: Colors.white,
          getTooltipItem: (_a, _b, _c, _d) =>
              BarTooltipItem('Date', TextStyle(), children: [
                TextSpan(
                  text: "Text",
                  style: TextStyle(),
                  children: [
                    WidgetSpan(
                        child: Container(
                      width: 10,
                      height: 10,
                      color: Colors.red,
                    ))
                  ],
                ),
              ]))),
  groupsSpace: 20,
  alignment: BarChartAlignment.start,
  titlesData: FlTitlesData(
    show: false,
  ),
  gridData: FlGridData(
    show: false,
  ),
  borderData: FlBorderData(
    show: false,
  ),
  barGroups: getData(),
),
```

**Comment by imaNNeoFighT** [comment]
Hi.
Unfortunately, we don't support WidgetSpan at the moment.

You can follow this issue: #675

We hope to add widget support in the tooltip.

**Comment by flipperji** [comment]
> Hi.
> Unfortunately, we don't support WidgetSpan at the moment.
> 
> You can follow this issue: #675
> 
> We hope to add widget support in the tooltip.

Hi ,sir. which version will the tooltips support widgetspan?

**Comment by imaNNeoFighT** [comment]
Hi. sorry, there is not any estimation.
