### ISSUE TITLE
Is it possible to customize rods and tooltip?

### ISSUE THREAD

**Issue by Wizzel1** [imaNNeoFighT/fl_chart#675]
I need to wrap the rods in a neumorphic style shadow like this : 
![Unbenannt](https://user-images.githubusercontent.com/43343510/118178056-ca949900-b433-11eb-9e1d-11f2eef6ec3c.PNG)

Is there any possibility to change the appereance of the rods? Same applies to the tooltip when I hover over the bar.

**Comment by darekmm** [comment]
Sorry, not much help here but just wanted to say it would be great to have the rods take any scalable widget/child as a parameter - then it'd be possible to achieve almost *any* look you can think of.

**Comment by Wizzel1** [comment]
Yes, that would be immensely helpful.

**Comment by AliYar-Khan** [comment]
Any luck for customization .of tooltipitem .. i want to achieve this 
![Screenshot (142)](https://user-images.githubusercontent.com/37889962/119225586-f42d7e80-bb1d-11eb-868c-c048a18ac4e7.png)

**Comment by Wizzel1** [comment]
Yes, that should be achievable. Try changing the properties of "BarTouchTooltipData" of your chart.

**Comment by imaNNeoFighT** [comment]
Hi. It isn't easy to support widgets on rods. we can't support widgets everywhere.
Also, we are thinking of having widgets on the tooltip. I think there are several open issues about it.

**Comment by randomjoho** [comment]
Hope support customize  widgets on tooltip . thanks

**Comment by imaNNeoFighT** [comment]
There is a duplicate issue here: #72 
Follow it to get updates.
