### ISSUE TITLE
BarChart doesn't response when all BarChartRodData.y = 0

### ISSUE THREAD

**Issue by bigbang489** [imaNNeoFighT/fl_chart#682]
I'm using Bart chart to display my monthly Spending vs Income. The chart works fine when there are at least 1 BarChartRodData.y (see my example code in the attachment) has none zero value, but if all BarChartRodData.y are zero, the app stop responding and crashed
<img width="597" alt="Screen Shot 2021-05-23 at 13 42 09" src="https://user-images.githubusercontent.com/29498440/119250926-a83a1280-bbcd-11eb-8a72-8df22a009e55.png">

**Comment by imaNNeoFighT** [comment]
I checked and it's working fine with 0 values on y.

Please make a reproducible code If you think anything is wrong.

Thanks!

**Comment by oy3** [comment]
It doesn't work for mine also.  It returns `Another exception was thrown: Unsupported operation: Infinity or NaN toInt`

**Comment by imaNNeoFighT** [comment]
Great!
Now you can provide me a reproducible code here.
