### ISSUE TITLE
Border for Tooltip.

### ISSUE THREAD

**Issue by P-B1101** [imaNNeoFighT/fl_chart#692]
Hello and Thanks for AMAZING package.
It would be great if we could add some border styling for tooltip. until you guys handle tooltip with widget.
Thanks a lot.

**Comment by emelinepal** [comment]
Hello :) For my studies I have to contribute to an opensource project by completing an Issue, can I take this one ?

**Comment by imaNNeoFighT** [comment]
Hi, @emelinepal. 
That would be great. I appreciate it!
You can start by reading our contribution guidelines [here](https://github.com/imaNNeoFighT/fl_chart/blob/master/CONTRIBUTING.md).
Then start working on the code. I will be available if you have any questions.

Thanks!

**Comment by emelinepal** [comment]
Hello @imaNNeoFighT ! I just made a PR, I am waiting for your feedback :)

**Comment by imaNNeoFighT** [comment]
This feature has just landed in [0.50.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.55.0).

Thanks, @emelinepal, for her contribution.
