### ISSUE TITLE
How to show tooltip by default?

### ISSUE THREAD

**Issue by joaopedrocoelho** [imaNNeoFighT/fl_chart#696]
How can I always display the tooltip above the spot on a line chart, without the need for the user to touch it?

**Comment by micaelsn** [comment]
same issue here

**Comment by imaNNeoFighT** [comment]
Hi. please check this sample:



##### LineChart Sample 5 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample5.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_5.png" width="300" >
