### ISSUE TITLE
How to change the number format of Bar chart label when tap on a bar?

### ISSUE THREAD

**Issue by bigbang489** [imaNNeoFighT/fl_chart#698]
Is there any parameter to change the number format in the image?. Thanks

![fbb69fcd6ecd9a93c3dc](https://user-images.githubusercontent.com/29498440/122378319-12a55f00-cf90-11eb-9ac4-648fee9d12d9.jpg)

**Comment by imaNNeoFighT** [comment]
Hi.
There are a lot of samples [here](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#some-samples). Please check them, we customized tooltip in some of them like this one:

##### Line Sample 1 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample1.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_1.gif" width="300" >
