### ISSUE TITLE
[Line chart] Bottom title bar display invalid 

### ISSUE THREAD

**Issue by mduccc** [imaNNeoFighT/fl_chart#70]
[Line chart] Bottom title bar display invalid between 0h07 and 5h07 titles, see image below:
![Screenshot_20190928-153233(1)](https://user-images.githubusercontent.com/18674411/65813962-0d294380-e206-11e9-82cf-c5778f9202ec.png)

**Comment by imaNNeoFighT** [comment]
Hi, may I ask you to share your code?

**Comment by imaNNeoFighT** [comment]
Please provide me a sample code to reproduce it, otherwise, it is gonna closed.

**Comment by imaNNeoFighT** [comment]
Unfortunately, I'm gonna close it,
reopen it with your sample code to reproduce.
Thanks.
