### ISSUE TITLE
BarCharts - Option to make gradient relative to each bars height, not the height of the chart

### ISSUE THREAD

**Issue by Hampfh** [imaNNeoFighT/fl_chart#703]
Currently, my problem lies in the bar gradients being uniform, meaning that there seems to be only one gradient applied to all bars. What I'd like instead would be to have an option to make each barData have the full span of the gradient. 

**Why is this necessary?**
If you have a gradient from one color to another where one of the colors is transparent then lower bars disappear almost completely in the charts. When I define the top color of the gradient I'd like that color to always be on top of the bar no matter the height of the bar. This would mean that for smaller bars the gradient would have to be shrunken to fit its height.

![image](https://user-images.githubusercontent.com/30767818/122731013-26e0a900-d27b-11eb-8e35-8eaa24febcd3.png)

Edit: Expected outcome would be something like this
![image](https://user-images.githubusercontent.com/30767818/122786292-71324c00-d2b4-11eb-9031-134523963b6f.png)

**Comment by arsalalgorepublic** [comment]
Any solution so far for this problem?

**Comment by imaNNeoFighT** [comment]
Fixed in [0.50.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.50.0).
Please check out the [migration guide](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/migration_guides/MIGRATION_00_50_00.md), we have some breaking changes.

**Comment by derrikf-spindance** [comment]
Is there a way to achieve the appearance in OP's attached pictures with the latest version?
