### ISSUE TITLE
How to show / hide toggle particular bar in group bars case?

### ISSUE THREAD

**Issue by kamleshwebtech** [imaNNeoFighT/fl_chart#705]
Thanks to entire team for developing this beautiful and robust chart package. It is very easy to use. Just a request, kindly keep the related document and examples updated.

I have created a grouped bar chart. You can see it's output in attached screenshot. My query is that I did not find any feature which can be used to show/hide particular typed bar in grouped bars case. eg. As per attached screenshot, I want to show/hide all the bars of `Male` or `Female` when user clicks on 'Male' or 'Female' legends text.  Do we have such in-built feature or will you need to develop it? There should be a feature of `show: true/false` for each bar so that we can toggle them by clicking on external button / legend text. 

Kindly suggest me how can we do this? Thanks a lot.

![bar-chart](https://user-images.githubusercontent.com/43021973/123477544-d622d480-d61b-11eb-8e0d-a0c91ee9c218.jpg)

**Comment by imaNNeoFighT** [comment]
Hi. it should be handled outside of the chart functionalities.
I just wrote a sample, check out the code [here](https://gist.github.com/imaNNeoFighT/b8b020c682fc1a697b4992277ff8890c).

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/7009300/124258393-963f7e00-db42-11eb-8a64-b15f3dde8556.gif)
