### ISSUE TITLE
Is there already a opportunity to implement Drilldowns ? 

### ISSUE THREAD

**Issue by Ronjack** [imaNNeoFighT/fl_chart#706]
Hello fellow flutter-chart-enthusiasts, I wanted to ask if it gives a easy way to implement drilldowns in fl_chart or if there is already a (easy and) small implementation for it? 

Thanks.

greetings, Robin

**Comment by imaNNeoFighT** [comment]
Hi @Ronjack.
Can you explain more about Drilldowns?

**Comment by Ronjack** [comment]
https://en.wikipedia.org/wiki/Data_drilling

Nevermind, just solved the requirement with ontap functionality from your charts.
