### ISSUE TITLE
PieChart onClick is unreliable

### ISSUE THREAD

**Issue by bernaferrari** [imaNNeoFighT/fl_chart#708]
PieChart triggers `clickHapened` and `pieTouchResponse.touchInput is PointerExitEvent ||
                pieTouchResponse.touchInput is PointerUpEvent` when navigating back on a screen and just scrolling (when mouse gets on top of the chart, these are triggered). Therefore, the whole app gets buggy.

**Comment by imaNNeoFighT** [comment]
Hi. can you please provide a reproducible code?
