### ISSUE TITLE
When there is too much data in the histogram, it can't be scrolled laterally, it can be overlapped

### ISSUE THREAD

**Issue by jingzhanwu** [imaNNeoFighT/fl_chart#713]
When there is too much data in the histogram, it can't be scrolled laterally, it can be overlapped

**Comment by imaNNeoFighT** [comment]
Please provide a reproducible code.
Thanks!

**Comment by RohanPatil1** [comment]
Basically suppose I want to show a yearly LineChart with X-axis having "JAN  FEB MARCH..." and Y-axis having some data,how can we scroll horizontally to view next months data ? I didn't find any example showing scrolling the data....Please help!
