### ISSUE TITLE
Add borders to BarChart bars

### ISSUE THREAD

**Issue by eliseyOzerov** [imaNNeoFighT/fl_chart#714]
**Is your feature request relasted to a problem? Please describe.**
In our BarChart implementation, a part of the current daily bar (weekly chart where each bar is a day) doesn't represent a value, hence it's white. Because the background of the app is also white, there's no way to distinguish the empty bar from the background. That's mandated by our design doc so I can't just change the color.

**Describe the solution you'd like**
We'd like to have an option to add borderData for each BarChartRodData in the BarChart.

**Describe alternatives you've considered**
As I said above, the only other option I see to solve our problem would be to change the color of that particular bar segment, but that's currently not an option.

**Comment by imaNNeoFighT** [comment]
Does `backDrawRodData` help you?

Check the below sample.

### Some Samples
----
##### Sample 1 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample1.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_1.gif" width="300" >

**Comment by imaNNeoFighT** [comment]
Hi.
We have just added `borderSide` property in [BarChartRodData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#barchartroddata) and [BarChartRodStackItem](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#barchartrodstackitem) to draw strokes around each bar and rod stack items in [0.36.4](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.36.4).
check it out!

Thanks @samiazar, hope to see more from you :)
