### ISSUE TITLE
show x axis values regardless the chart line exists or not

### ISSUE THREAD

**Issue by kostas95** [imaNNeoFighT/fl_chart#715]
Is it possible to display x axis values regardless the existence of line spots? For example, let's say the x axis displays the 24 hours of a day, but the line of our data has data from 6 AM to 12 PM, is it possible to implement this scenario?

Below i post a photo, that displays what im explaining above

![IMG_20210708_140517](https://user-images.githubusercontent.com/21286858/124911778-d47ee680-dff5-11eb-930b-13468746cb98.jpg)

Is there any way to achive this?

**Comment by imaNNeoFighT** [comment]
Hi. By default, we set `minX` and `maxX` values based on your dataset.
You can change `minX` to 00 and `maxX` to 24.
