### ISSUE TITLE
The height of the chart is distorted after the screen is rotated

### ISSUE THREAD

**Issue by flipperji** [imaNNeoFighT/fl_chart#717]
Hi , When I rotate the screen, the height of the chart has changed. Is there a better way to solve it?
![image](https://user-images.githubusercontent.com/19375309/125617682-39b5a06f-081c-4b30-9657-c7b7b80f0f29.png)

**Comment by imaNNeoFighT** [comment]
Hi. It is not `fl_chart` library problem.
You should handle it outside of the chart by deciding a proper size for the child to be responsive.
BTW we are rewriting the sample app. It will be fixed in the next sample app.

Thanks for reporting.
