### ISSUE TITLE
How to show both x-axis and y-axis data in tooltip while using line-chart

### ISSUE THREAD

**Issue by akashlilhare** [imaNNeoFighT/fl_chart#719]

**Comment by imaNNeoFighT** [comment]
Check this sample please:

##### Sample 9 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample9.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_9.gif" width="300" >
