### ISSUE TITLE
Is it possible to use 2 different maxY for 2 different ChartBarData on a lineChart?

### ISSUE THREAD

**Issue by alvimpaulo** [imaNNeoFighT/fl_chart#726]
I would like to show 2 lines with different data in each one in the same chart, but at the same time, i would like to make it scale to its own maxY. Is this possible?

**Comment by kevinxxq** [comment]
I have the same question and thought of one possible implementation, please consider rightTitles as second yAxis and you need scale your data by yourself.

**Comment by imaNNeoFighT** [comment]
Follow #429
