### ISSUE TITLE
Y-axis overflow problem

### ISSUE THREAD

**Issue by superwei629** [imaNNeoFighT/fl_chart#728]
Thanks to the developer, how to solve the problem of y-axis overflow? Can you directly set it to the position of Max instead of overflow after exceeding max-y

![image](https://user-images.githubusercontent.com/51434982/126887362-1c97b0d4-d238-45b5-9872-93058e485afd.png)

**Comment by king-jinho** [comment]
as a workaround, when setting maxY, i set it to maxY * 1.2
