### ISSUE TITLE
getTitles -> month, year, 5 years, 10 years

### ISSUE THREAD

**Issue by mkprogrammer15** [imaNNeoFighT/fl_chart#729]
I thought wether its possible to scale x-Achsis, if a user chooses a month to show up his relevant data or 10 years? Is there any solution? f.e like in yahoo finance or coinbase graphs?
For a months we could set 1-31 days. For a year just show up months  "jan, feb, march," etc...and for years 1-year, 2-year, 3-year.

**Comment by mkprogrammer15** [comment]
Just found a different way! It works!

**Comment by jaiswalshubham84** [comment]
@mkprogrammer15 
can u please share ur solution

**Comment by mkprogrammer15** [comment]
typedef Callback = void Function(int value);

class TimeSelector extends StatelessWidget {
  int timeFrame = 2;
  final Callback onTimeElementClick;

  TimeSelector({Key? key, this.timeFrame = 2, required this.onTimeElementClick})
      : super(key: key);

  _checkTimeFrameAndChangeTitleColor(int value) {
    if (timeFrame == value) {
      return RentabloColors.lightBlueGrey;
    }
    return RentabloColors.blueyGrey;
  }

  _checkTimeFramefAndChangeTitleFontsize(int value) {
    if (timeFrame == value) {
      return 20.0;
    }
    return 17.0;
  }

  Widget _textButtonChooseTimeLine(
      int value, String buttonText, BuildContext context) {
    return TextButton(
        onPressed: () {
          onTimeElementClick(value);
        },
        child: Text(
          buttonText,
          style: Theme.of(context).textTheme.headline1?.copyWith(
              color: _checkTimeFrameAndChangeTitleColor(value),
              fontSize: _checkTimeFramefAndChangeTitleFontsize(value)),
        ));
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        _textButtonChooseTimeLine(0, '1Week', context),
        _textButtonChooseTimeLine(1, '1Month', context),
        _textButtonChooseTimeLine(2, '1Year', context),
        _textButtonChooseTimeLine(3, 'From Begin', context)
      ],
    );
  }
}
