### ISSUE TITLE
Is it possible to set the color of bar when we touch on it?

### ISSUE THREAD

**Issue by nimesh1997** [imaNNeoFighT/fl_chart#73]
When I touch on the bar chart I want to set the colour on that particular bar and should not disappear when I remove my hand?

**Comment by imaNNeoFighT** [comment]
Check it out:

![bar_click](https://user-images.githubusercontent.com/7009300/111708641-761dd480-885b-11eb-860b-d1aacecd885c.gif)

[SourceCode](https://gist.github.com/imaNNeoFighT/7eaf2ac51c9b870e5c61abd47275a328)
