### ISSUE TITLE
Is it possible to show FlSpot value and detailed tooltip ?

### ISSUE THREAD

**Issue by elmaniakos** [imaNNeoFighT/fl_chart#733]
Actual result :
<img width="278" alt="Capture d’écran 2021-07-28 à 23 04 07" src="https://user-images.githubusercontent.com/62660749/127402219-392afae0-0f15-48c5-8882-e949be603a0f.png">

Needed result when user push a value in chart:
<img width="312" alt="Capture d’écran 2021-07-28 à 23 12 17" src="https://user-images.githubusercontent.com/62660749/127402947-38764f44-818c-4e12-9442-1c9ee5a5c93d.png">

**Comment by Ankan1998** [comment]
Yes you can 
```
LineTouchData(

        //enabled: true,
        handleBuiltInTouches: true,
        touchTooltipData: LineTouchTooltipData(
            tooltipRoundedRadius: 10,

            tooltipBgColor:Color(0x33EC6666),
            getTooltipItems: (List<LineBarSpot> touchedBarSpots){
              return touchedBarSpots.map((barSpot) {
                final flSpot = barSpot;
                return LineTooltipItem(
                   '${now.subtract(Duration(days:6-flSpot.x.toInt())).day} ${month[now.subtract(Duration(days:6-flSpot.x.toInt())).month-1]} \n ${flSpot.y}',
                  TextStyle(
                    color: Colors.grey[900],
                    fontWeight: FontWeight.bold,
                  ),
                );
              }).toList();
            }


            //getTooltipItems:
        )
```

getToolTipItem receives a callback to function where u can define your desired tooltip description and then map it to flspot x axis

**Comment by imaNNeoFighT** [comment]
Thanks @Ankan1998 

BTW you can check our LineChartSample3

##### Sample 3 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample3.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_3.gif" width="300" >

**Comment by imaNNeoFighT** [comment]
Also your design looks amazing :)
