### ISSUE TITLE
Line chart SideTitles problem 

### ISSUE THREAD

**Issue by momenamiin** [imaNNeoFighT/fl_chart#738]
Hello all, 

When using a value range below 1 as of [ 0.1 , 0.2 , 0.3, ..etc]  the getTitles function in the SideTitles doesn't work properly.
it only gives the minimum value even when removing the overriding and using the default function it only shows the minimum value. 

code sample

```
leftTitles: SideTitles(
          showTitles: true,
          margin: 8,
          reservedSize: 30,
          getTextStyles: (value) => const TextStyle(
            color: Colors.indigo,
            fontWeight: FontWeight.bold,
            fontSize: 10,
          ),
          getTitles: (value) {
            // the only value i get here is the minmum
            print('value in get titles +$value');
            return value.toString();
          },
        ),
```

**Screenshots**
![image](https://user-images.githubusercontent.com/18642838/128862464-fa3d4dec-ed6c-44d2-ba33-39f507e5729d.png)

**Versions**
 - Flutter 2.2.3 stable channel 
 - fl_chart: ^0.36.3

**Comment by imaNNeoFighT** [comment]
`SideTitles.interval` property is `1.0` by default.
Try to set `0.2` in your design.

**Comment by kamleshwebtech** [comment]
@momenamiin  Thanks for asking this question, your question has a solution which solved my problem :)
