### ISSUE TITLE
feature suggestion: ability to rotate titlesData text

### ISSUE THREAD

**Issue by mahmoudparandeh** [imaNNeoFighT/fl_chart#75]
hi there, thanks for your great library. as you know when the bottomTitles are more for example months. if we can rotate text for example 90 degrees we can handle long text in bottomTitles. if you need more info i can create image for that.

**Comment by mahmoudparandeh** [comment]
![rotate](https://user-images.githubusercontent.com/36625602/65837449-6d061400-e304-11e9-875b-2916e3f9efee.png)
some think like this one, i hear about RotatedBox which rotate child widget. maybe its helped.

**Comment by imaNNeoFighT** [comment]
Hi, That's great,
We will implement it soon, also pull requests are welcome,
stay tuned, Thanks!

**Comment by mahmoudparandeh** [comment]
hi, there. don't forget this in next release. thanks :)

**Comment by imaNNeoFighT** [comment]
Hi there, long time no see :)
It has been added in [0.6.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.6.0), now we have `rotateAngle` property in our [SideTitles](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#sidetitles), you can use it to rotate the titles.
Thank you for suggesting, and thanks @arefhosseini  for implementing.

##### Sample 5 ([Source Code](/example/lib/bar_chart/samples/bar_chart_sample5.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_5.png" width="300" >

**Comment by imaNNeoFighT** [comment]
I think it is the first teamwork that happened between three Iranians in the Flutter community :)
I like that.
Thanks a lot.

**Comment by arefhosseini** [comment]
Yeah I get more motivation for developing flutter. Thank to both of you.

**Comment by wiany11** [comment]
Not anymore...?

**Comment by imaNNeo** [comment]
> Not anymore...?

What do you mean?

**Comment by wiany11** [comment]
@imaNNeo 
```
fl_chart: ^0.61.0
```
```
  FlTitlesData get titlesData => FlTitlesData(
    show: true,
    bottomTitles: AxisTitles(
      sideTitles: SideTitles(
        showTitles: true,
        reservedSize: 30,
        getTitlesWidget: getTitles,
        //rotateAngle: -90,  // The named parameter 'rotateAngle' isn't defined. (Documentation)
      ),
    ),
    ...,
  );
```
I am currently using like the above. (Thanks for the beautiful library!)
But I cannot add the property `rotateAngle` to `SideTitles` or somewhere else... 
Is the property no long supported...?

**Comment by imaNNeo** [comment]
You can override the [getTitlesWidget](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#sidetitles).

Please check the [0.50.0 migration guide](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/migration_guides/0.50.0/MIGRATION_00_50_00.md)

**Comment by wiany11** [comment]
@imaNNeo Thank you so much!

```
  FlTitlesData get titlesData => FlTitlesData(
    show: true,
    bottomTitles: AxisTitles(
      sideTitles: SideTitles(
        showTitles: true,
        reservedSize: 30,
        getTitlesWidget: Transform.translate(
          offset: const Offset(0.0, 10.0),
          child: Transform.rotate(
            angle: - pi / 4,
            child: SideTitleWidget(
              axisSide: meta.axisSide,
              space: 4,
              child: Text(text, style: style),
            ),
          ),
        ),
      ),
    ),
    ...,
  );
```

**Comment by imaNNeo** [comment]
You're welcome 🎉
