### ISSUE TITLE
Remove the vertical line on x-axis  when toolTip is touched

### ISSUE THREAD

**Issue by Ankan1998** [imaNNeoFighT/fl_chart#750]
### Result
![Screenshot (11)](https://user-images.githubusercontent.com/36896102/130262756-10e83a39-2ebd-4336-acea-db67e9707afc.png)

### Desired
![Screenshot (13)](https://user-images.githubusercontent.com/36896102/130262767-ba459b98-e700-4dc7-a0b6-641ca89e4cd3.png)

**Comment by imaNNeoFighT** [comment]
Using below code you can change return your customized TouchedSpotIndicatorData() which contains a `FlLine`.

```
lineTouchData: LineTouchData(
  getTouchedSpotIndicator: (barData, spotIndexes) {
    return List.generate(spotIndexes.length, (index) => TouchedSpotIndicatorData(
      FlLine(
        color: Colors.transparent
      ),
      FlDotData(
        show: true,
        getDotPainter: (spot, _, __, ___) {
          return FlDotCirclePainter(
              color: Colors.blueAccent,
              strokeWidth: 0,
              radius: 8,
              strokeColor: Colors.transparent
          );
        }
      )
    ));
  }
),
```

**Comment by Ankan1998** [comment]
Thanks a lot. It worked. Very much appreciate for your effort in creating this flutter package

**Comment by imaNNeoFighT** [comment]
You're welcome
