### ISSUE TITLE
Error: The argument type 'TextStyle Function(BuildContext)' can't be assigned to the parameter type 'TextStyle? Function(BuildContext, double)?'.

### ISSUE THREAD

**Issue by kostas95** [imaNNeoFighT/fl_chart#752]
I just upgraded to 0.36.4 version for flutter and i'm facing the error below

> Error: The argument type 'TextStyle Function(BuildContext)' can't be assigned to the parameter type 'TextStyle? 
> Function(BuildContext, double)?'.
>  - 'TextStyle' is from 'package:flutter/src/painting/text_style.dart' ('../../../development/flutter/packages/flutter/lib/src/painting/text_style.dart').
>  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/framework.dart').
>             getTextStyles: (context) => TextStyle(fontSize: 12),

I'm just setting the `getTextStyles` property of `SideTitles` as following

`getTextStyles: (context) => TextStyle(color: Colors.blue, fontSize: 12),`

What should i change after upgrading to the new version?

**Comment by nosuke0926** [comment]
Hi, like this.
```
SideTitles(
    getTextStyles: (context, value) {
        return TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 12,
         );
    },
),
```

**Comment by kostas95** [comment]
Thanks for the reply @nosuke0926 

I've tried this kind of solution and i'm getting the following

![image](https://user-images.githubusercontent.com/21286858/130643281-85116aae-35a6-46ce-8221-9b22e3b8608f.png)

**Comment by imaNNeoFighT** [comment]
@kostas95  I don't know what is your problem. But I'm pretty sure @nosuke0926's solution must work.

You can follow our [releases page](https://github.com/imaNNeoFighT/fl_chart/releases)  to resolve the breaking changes (I write about them in each release that has BREAKING CHANGE).
(In [0.36.4](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.36.4) I forgot to mention it. But now it has just updated and I added the **BREAKING** CHANGE guide note)

**Comment by kostas95** [comment]
Yes that's the correct solution.

The only thing i needed to do was to go to `Dart Analysis` and hit the `Restart Dart Analysis Server`. After the errors were gone. Thank  you
