### ISSUE TITLE
Is it possible to skip blank space when there is no data?

### ISSUE THREAD

**Issue by macropusgiganteus** [imaNNeoFighT/fl_chart#754]
I have a line chart with 200 spot data [ FlSpot(datetime, double) ] and there are some empty data on specific time (holidays).
Is there a way to skip the empty value (or remove space) and make data continuous?
![image](https://user-images.githubusercontent.com/35326900/130582149-97b6d3fc-b1b4-4c79-b166-8c8c5b1e4479.png)
Please help me to resolve this problem.

Best Regards,

**Comment by macropusgiganteus** [comment]
I'm able to find a way around, Thank you.

**Comment by imaNNeoFighT** [comment]
Hi @macropusgiganteus 
It would be great if you share your workaround. Other people will see your issue in the future.

**Comment by macropusgiganteus** [comment]
My solution is to create new list to store datetime and use index of the datetime in FlSpot instead.

```
// Old way
List<FlSpot> spots = data.map((e) {
         return FlSpot(e.datetime.millisecondsSinceEpoch.toDouble() , e.yValue);
      }).toList();

// New way ( the solution )
List<double> time = [];
List<FlSpot> spots = data.map((e) {
         double dateTimeDouble = e.datetime.millisecondsSinceEpoch.toDouble();
         time.add(dateTimeDouble);
         return FlSpot(time.indexOf(dateTimeDouble).toDouble(), e.yValue);
      }).toList();

```
Old result:
![image](https://user-images.githubusercontent.com/35326900/130712373-9ea8a00b-3110-4346-b8c9-61ecd89c98a8.png)

New result:
![image](https://user-images.githubusercontent.com/35326900/130712268-5ae561cf-ab69-4bcc-984a-50297a68ef5e.png)

Hope it helps everyone facing the same problem!
