### ISSUE TITLE
BarChartRdData border background color

### ISSUE THREAD

**Issue by kostas95** [imaNNeoFighT/fl_chart#758]
I have a question on if it's possible to change the background color of the border that contains the data of a bar. For example in the picture below, the color is dark grey as you can see. Is there any way of changing it? 

![image](https://user-images.githubusercontent.com/21286858/131657078-abf9acab-85df-4958-b204-2590af46fa8d.png)

If not, is there any way of giving a color to the text inside that border, that is also different to the color of the bar? For example, in the picture the text color is deep blue just like the bar's color. Is there a way to give a white color to the text inside the border, and keep the deep blue to the bar?

Thank you in advance

**Comment by imaNNeoFighT** [comment]
You can customize both:

For background check this sample:
