### ISSUE TITLE
Error Type: 'MouseCursor' not found.

### ISSUE THREAD

**Issue by wakeyhazey** [imaNNeoFighT/fl_chart#765]
Hi guys! 

I ran into an error when updating fl chart version to ^0.40.0.

The error appears in terminal immediately by just importing the package in a code, not using any of the functions yet.

**The error in terminal:**
../../../flutter/.pub-cache/hosted/pub.dartlang.org/fl_chart-0.40.0/lib/src/chart/base/base_chart/base_chart_data.dart:199:60: Error: Type 'MouseCursor' not found.
typedef MouseCursorResolver<R extends BaseTouchResponse> = MouseCursor Function(FlTouchEvent, R?);

- flutter version 2.0.3 on the stable channel
- fl chart version 0.40.0

Cheers

**Comment by adojayfan** [comment]
My flutter version is also 2.0.3 ，you just need to switch the version to 0.36.4 or upgrade the flutter version to the latest version.

**Comment by imaNNeoFighT** [comment]
Yes you need to use the latest flutter version.
