### ISSUE TITLE
How do I make two Y axis in Barchart?

### ISSUE THREAD

**Issue by balaji101010** [imaNNeoFighT/fl_chart#771]
Hello,

I am using BarChartRodData() which has two bars in BarChart, I want to show the left title value from one Y axis value and right title value from another Y axis

Example, Range of 1000 to 100000 of left bar and Range of 10 to 100 of right bar.
So the left and right bar should be same height if I give value of (y1:1000,y2:10)

**Comment by balaji101010** [comment]
Closing this because It's more of a individual developer issue, we need to use our own logic.

**Comment by imaNNeoFighT** [comment]
Hi. Yes, you can change left and right titles based on your need. 
Thanks for writing your opinion.

**Comment by Nliuco** [comment]
Hi, @balaji101010 
I encountered the same issue you described.Could you please share how you coded it? That would be super helpful!
