### ISSUE TITLE
How to show tooltip data on tap and drag in v0.40.0 like with v0.36.3?

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [imaNNeoFighT/fl_chart#772]
Love that the new update lets us handle touch events, but I am a bit unclear on how to reproduce the old functionality where touching a graph and dragging around (no long press required) would display the tooltip for the current touch point.

After this change it appears to only show you the initial touch point.

Any help here is appreciated!

**Comment by imaNNeoFighT** [comment]
Hi @TheMeanCanEHdian 
Everything should work like before on touch handling. We just added support for long-press.
Can you explain a little more about the problem? Is it reproducible in our samples? 
If you can please provide me a reproducible code.

Thanks!

**Comment by TheMeanCanEHdian** [comment]
Sure thing. I have created a repo for fl_chart [`36.4`](https://github.com/TheMeanCanEHdian/fl_chart_36_4) and [`40.0`](https://github.com/TheMeanCanEHdian/fl_chart_40) where I introduced 2 changes to the example code.
1. I commented out all pages but the `LineChartPage`
2. I added fl_chart to the pubspec

On `36.4` pressing and dragging will update the tooltip, but on `40.0` you have to long press to achieve this.

Here are GIFs of the behavior
### 36.4
![HjexFH7GNw](https://user-images.githubusercontent.com/16025103/135639464-50f4d33a-8bbd-4ba1-a480-8d2b7708372c.gif)

### 40.0
![HWl7PlYGub](https://user-images.githubusercontent.com/16025103/135639592-6411f123-6a09-4eab-8908-d730b65c5c91.gif)

**Comment by TheMeanCanEHdian** [comment]
Any thoughts on this?

**Comment by imaNNeoFighT** [comment]
Yes. when you long-press on a chart, the parent's scroll will be locked. Then chart will receive the touch events.

**Comment by nezoat** [comment]
Is there a way to eliminate the need for a long press before touch events, and revert back to the previous behavior of immediate touch events when swiping over data in a graph?
