### ISSUE TITLE
Turn off hover for tooltip desktop

### ISSUE THREAD

**Issue by bremington** [imaNNeoFighT/fl_chart#775]
Hi, my app's charts work great on both iOS, Android, and now macOS. However, when I run the macOS version and move my cursor to reposition the app window, the mouse hovers quickly over a chart, and I get all the tooltips. My users need to get the tooltip if they tap with the mouse, not hover. Can I turn the hover off and use just a top for the macOS/desktop use?

Thank you!

**Comment by imaNNeoFighT** [comment]
Hi.
You need to override `LineTouchData` to implement your logic.
First, disable the `handleBuiltInTouches`.  Then try to implement the logic we've used in the `LineChart` class (to mimic the built-in touches). Then you can change it based on your need.

I tried to implement it [here](https://gist.github.com/imaNNeoFighT/e4ce7c0b2b8db519e5d70c405ab4c873).
Check it out!

https://user-images.githubusercontent.com/7009300/135586177-a1effefb-85fa-41be-92aa-3b15e614b6e7.mov
