### ISSUE TITLE
Pie chart Gradient

### ISSUE THREAD

**Issue by Nirsu** [imaNNeoFighT/fl_chart#777]
Hello,
This is probably a duplication of #166 but this issue is open for 1 year

The request was to have the gradient on a pie chart, I would like to know if this idea was abandoned or if it was implemented, how to realize it? because I need to realize this pie chart:
![image](https://user-images.githubusercontent.com/33753020/134523709-561d93c6-5a30-4d6b-b2f4-90081f774333.png)

Thanks in advance

**Comment by imaNNeoFighT** [comment]
Hi. No, it is not implemented yet. Because the main issue is open yet (because I didn't have time to work on it).
Please follow #166. I will close this issue. 
Thanks!
