### ISSUE TITLE
StateError thrown in bar_chart_painter.dart when no elements in barGroups (v0.36.2)

### ISSUE THREAD

**Issue by ToyWalrus** [imaNNeoFighT/fl_chart#797]
A `StateError` gets thrown when a bar chart is rendered without any bar groups.

In this case specifically it's happening in the `BarChartAlignment.spaceEvenly` switch case, but it appears that it would throw the same error in some of the other cases as well.

I should note that this doesn't crash the app and the chart still renders as would be expected, with just a base line and an empty chart area. No labels.

![Screen Shot 2021-10-18 at 10 20 51 AM](https://user-images.githubusercontent.com/25328178/137770240-67518a21-0a24-4440-9aed-a1e0be5413ac.png)

Using version **^0.36.2**

**Comment by imaNNeoFighT** [comment]
Fixed in [0.40.5](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.40.5).
Please check it out!
