### ISSUE TITLE
Error when the chart sections list is empty

### ISSUE THREAD

**Issue by phillausofia** [imaNNeoFighT/fl_chart#799]
Sometimes, when the chart sections list is empty, I receive a "Bad state: No element" error, coming from the pie_chart_data.dart file, at line 37.

`  double get sumValue => sections
      .map((data) => data.value)
      .reduce((first, second) => first + second);`

Will replacing the reduce function with fold help solve this problem?

**Comment by 2shrestha22** [comment]
Empty sectons in PieChart always gives Bad state: No element exception when touched.

**Comment by imaNNeoFighT** [comment]
Please drop me a reproducible code (contains in a main.dart file)

**Comment by IsaiasCuvula** [comment]
If somehow the value is 0 and you try to tap on the chart will throw an exception.

`PieChartSectionData(
          color: category.color,
          value: myValue, //here is the problem
          title: '$percentage %',
          radius: radius,
          titleStyle: TextStyle(
            fontSize: fontSize,
            fontWeight: FontWeight.bold,
            color: context.colorScheme.background,
          ),
          badgeWidget: _Badge(
            color: category.color,
            icon: category.icon,
            size: iconSize,
          ),
          badgePositionPercentageOffset: .98,
        );`
        
        ════════ Exception caught by gesture library ═══════════════════════════════════
Bad state: No element
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
Bad state: No element
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
Bad state: No element

**Comment by imaNNeo** [comment]
> If somehow the value is 0 and you try to tap on the chart will throw an exception.

Please mention your fl_chart version and provide a reproducible code.

**Comment by ganwumeng** [comment]
Same problem under fl_chart: 0.70.2 and 1.0.0. When section is empty and touchCallback is set, an error will be reported when the mouse passes over the chart.
