### ISSUE TITLE
LineChart with two data with very different scales

### ISSUE THREAD

**Issue by dhs9004** [imaNNeoFighT/fl_chart#800]
Hi,
I'm trying to find a way to show two data with very different scales in a Linechart, so far the best idea that I have is to split it into two charts, so I'm basically creating two charts. Is there a better way to accomplish this? 

based on the 2 charts solution, I would like to active the tooltip on all the charts when the user touches a chart based on the flSpot.x. Is there a way to do this?

![image](https://user-images.githubusercontent.com/38137546/138617781-e65c4174-b7b0-49ff-a9d1-e9029995b354.png)

Thanks,

**Comment by imaNNeoFighT** [comment]
Dup of #429
