### ISSUE TITLE
LineChart issue when consecutive values are 0

### ISSUE THREAD

**Issue by chrisvidal** [imaNNeoFighT/fl_chart#804]
**To Reproduce**
Provide a list of consecutive values equal to 0, and you will see the line going below the 0 bottom as per screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/2263496/139043438-0951c6be-f134-4521-a76c-0e170b48b641.png)

**Versions**
 - Flutter 2.5
 - FlChart fl_chart: ^0.40.2

**Comment by jlnrrg** [comment]
This happens because you set the `LineChartBarData` `isCurved` to `true`, but not `preventCurveOverShooting` to `true`.
For more information read the [Documentation](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#LineChartBarData) or the issue #25.

**Comment by chrisvidal** [comment]
thanks
