### ISSUE TITLE
Double y-axis range issue

### ISSUE THREAD

**Issue by Maheswari81** [imaNNeoFighT/fl_chart#807]
I am giving the following data in the Multi Line chart. It seems, the range of the y axis is always taken from one side, it doesn’t normalise to common factor if we give different range values. Should I refactor the ranges to common range (Ex: 0 to 6) and apply the same for all lines? Or will the chart do the normalise automatically?

final List<FlSpot> revenueData = [
  FlSpot(0, 250),
  FlSpot(1, 500),
  FlSpot(2, 351),
  FlSpot(3, 1000),
  FlSpot(4, 1500),
  FlSpot(5, 755)
];

final List<FlSpot> unitData = [
  FlSpot(0, 15),
  FlSpot(1, 30),
  FlSpot(1, 45),
  FlSpot(3, 60),
  FlSpot(4, 45),
  FlSpot(5, 35)
];

final List<FlSpot> orderData = [
  FlSpot(0, 25),
  FlSpot(1, 30),
  FlSpot(2, 45),
  FlSpot(3, 35),
  FlSpot(4, 36),
  FlSpot(5, 41)
<img width="269" alt="Screenshot 2021-10-31 at 6 55 19 PM" src="https://user-images.githubusercontent.com/90443429/139585760-8d672ed9-a13f-4f51-a63d-29e6c1378b54.png">
];

**Comment by imaNNeoFighT** [comment]
No, we don't have any normalization. You should handle it yourself.
