### ISSUE TITLE
how can i paint gradient ?

### ISSUE THREAD

**Issue by Benife** [imaNNeoFighT/fl_chart#808]
hi.

I want to give a gradient to the line, how do I do it?
I want to draw like the picture below.

please help me.
![image](https://user-images.githubusercontent.com/1705741/139676904-d754de01-61cf-4ce7-bf1e-453bbe309e7c.png)

**Comment by imaNNeoFighT** [comment]
Hi. You can set `isStepLineChart: true` to achieve a step line chart.
There is also a class called `LineChartStepData` which lets you customize the `stepDirection`.

Check the below sample:
<img src="https://user-images.githubusercontent.com/7009300/140233306-214286bc-364c-40ea-8187-f8231e1d1784.png" width=400/>

([Here is the source code](https://gist.github.com/imaNNeoFighT/d21e6ef74f49f5fae7b09ca3e186b238))
