### ISSUE TITLE
show indicator for only one line chart if there are more than one line charts

### ISSUE THREAD

**Issue by khushwin0303** [imaNNeoFighT/fl_chart#813]
Can we show tool tip indicators for only one graph instead of all of them?

**Comment by imaNNeoFighT** [comment]
Hi. You can achieve that with a little customization.
Please check the below sample ([full source code is here](https://gist.github.com/imaNNeoFighT/a6c565bee38c360178f657a2b8617775)):

https://user-images.githubusercontent.com/7009300/151675062-32b48529-861c-4b25-8b35-1c6dfff39b3a.mp4
