### ISSUE TITLE
Tooltip is displayed below the bottom axis when the Bar has value=0

### ISSUE THREAD

**Issue by bigbang489** [imaNNeoFighT/fl_chart#815]
**To Reproduce**
Create a BarChart with 2 bars, the first bar value > 0, the 2nd bar value=zero, tooltip is always displayed, (showingTooltipIndicators=[...]), 

Expect behavior: the tooltip of the 2nd bar should be display above the bottom axis line
Actual behavior: The 2nd Tooltip is displayed below the bottom axis line

**Screenshots**
![image](https://user-images.githubusercontent.com/29498440/141788003-9992be31-4254-48e6-a206-accdec71fa37.png)

**Versions**
 - 0.35.0
 - 0.40.2

**Comment by imaNNeoFighT** [comment]
An equals (`=`) character fixed this issue :)))
If you are interested, check it out in [this commit](https://github.com/imaNNeoFighT/fl_chart/commit/f2351ff34b3ae1360d7d4b5805c7a5c2bdcbc7d8).

Fixed in [0.40.5](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.40.5).
Please check it out!
