### ISSUE TITLE
Piechart border color between segments

### ISSUE THREAD

**Issue by johanlantz** [imaNNeoFighT/fl_chart#818]
Maybe this behaviour is by design but I would expect the border to be present also between segments?

```
PieChartSectionData(
  borderSide: BorderSide()

```
![Screenshot_20211117-194055](https://user-images.githubusercontent.com/7461655/142263347-ae156e2d-97dc-4692-b9a9-d7c6a2e56abf.png)

**Comment by imaNNeoFighT** [comment]
Hi. That was a bug, which we have just fixed it now.
Thanks for reporting!

You only need to update your package to [0.40.5](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.40.5) without any change.
