### ISSUE TITLE
Sample 2 Need to be updated

### ISSUE THREAD

**Issue by kelvin147789** [imaNNeoFighT/fl_chart#82]
Compiler message:
lib/weekly_challenge.dart:149:25: Error: The method 'BarAreaData' isn't defined for the class '_LineChartSample2State'.
 - '_LineChartSample2State' is from 'package:mobile_application_activity_03/weekly_challenge.dart' ('lib/weekly_challenge.dart').
Try correcting the name to the name of an existing method, or defining a method named 'BarAreaData'.
          belowBarData: BarAreaData(                                    
                        ^^^^^^^^^^^                                     
lib/weekly_challenge.dart:252:25: Error: The method 'BarAreaData' isn't defined for the class '_LineChartSample2State'.
 - '_LineChartSample2State' is from 'package:mobile_application_activity_03/weekly_challenge.dart' ('lib/weekly_challenge.dart').
Try correcting the name to the name of an existing method, or defining a method named 'BarAreaData'.
          belowBarData: BarAreaData(show: true, colors: [               
                        ^^^^^^^^^^^

**Comment by kelvin147789** [comment]
Should be 👍 

belowBarData:BelowBarData

Instead of 👎 
belowBarData: BarAreaData

**Comment by imaNNeoFighT** [comment]
Hi buddy, [BarAreaData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#barareadata) is correct.
As I mentioned in the [0.3.3](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.3.3) version we had some BREAKING CHANGES, read about them.
