### ISSUE TITLE
LineChart TooltipLine does not display the correct color

### ISSUE THREAD

**Issue by jlnrrg** [imaNNeoFighT/fl_chart#822]
**Describe the bug**
The Tooltip Line of the LineChart is by default colored as the upper positioned line, this works very unreliably. See image for a visual impression: 

![Screenshot from 2021-11-22 17-29-05](https://user-images.githubusercontent.com/77293597/142899264-9fcbab31-1f29-4ed9-9ee6-2682e47259e2.png)

The bottom brown vertical line should be red from my understanding.

**Versions**
 <details><summary>Flutter version</summary>

```bash
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (5 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```
</details>
 
Fl Chart Version: 
```yaml
  fl_chart: ^0.40.2
```

**Comment by imaNNeoFighT** [comment]
The indicator lines are drawn by the order of the lines.
In your example, brown is the frontest line and that's why you see brown.

**Comment by jlnrrg** [comment]
An understandable programming pov, but from the design perspective this might need improvement.
I understand if this is too much effort to do, so I'd argue, to handle it like syncfusions chart package and to be able to set the line color as one color (if that is not already possible)

**Comment by imaNNeoFighT** [comment]
I understand it is not good from design perspective.
There is an opened issue already. 
You can follow-up this issue here: #198

**Comment by jlnrrg** [comment]
Thank you for linking the right issue.
I close this one as duplicate of #198.
