### ISSUE TITLE
Prompts the bubble to stay where it was last clicked

### ISSUE THREAD

**Issue by guicai666** [imaNNeoFighT/fl_chart#825]
![image](https://user-images.githubusercontent.com/31101499/142967091-7545c9c7-ea7d-4682-800e-363dffca94e5.png)
Hello, I hope to get your technical support. The requirement is as follows: after clicking, the prompt bubble will display in the current position and will not disappear

**Comment by macropusgiganteus** [comment]
You can use `showingTooltipIndicators` to show specific tooltips.

I've done it following [linechart sample 5](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample5.dart) and [scatterchart sample 2](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/scatter_chart/samples/scatter_chart_sample2.dart)
with custom touch behavior (tap to show, tap again to hide).
```
List<int> showIndexes = []
final lineBarsData = [LineChartBarData(
  showingIndicators: showIndexes,
  ...
)]


LineChartData(
  showingTooltipIndicators: showIndexes
                    .map((index) => ShowingTooltipIndicators([
                          LineBarSpot(
                              lineBarsData[0], 0, lineBarsData[0].spots[index])
                        ]))
                    .toList(),
  lineTouchData: LineTouchData(
    ...
    handleBuiltInTouches: false, 
    touchCallback: (FlTouchEvent event, LineTouchResponse? touchResponse) { 
      if (touchResponse == null || touchResponse.lineBarSpots == null) return;
      if (event is FlTapUpEvent) {
          touchedIndex = touchResponse.lineBarSpots!.first.spotIndex
          setState(() {
            if (showIndexes.contains(touchedIndex)) {
              showIndexes.clear();
            } else {
              showIndexes = [touchedIndex];
            }
          });
      }
    })
)
```
>the code is modified from my project's code but you should get the idea.

hope that helps.

**Comment by imaNNeoFighT** [comment]
@macropusgiganteus is correct!

**Comment by IvanYue** [comment]
@imaNNeo Please tell me BarChart supports this? Prompts the bubble to stay where it was last clicked

**Comment by imaNNeo** [comment]
> @imaNNeo Please tell me BarChart supports this? Prompts the bubble to stay where it was last clicked

We have a snipped which is for LineChart, but you can use the exact approach for BarChart too:
[source code](https://gist.github.com/imaNNeo/bce3f0169ff3fd6c3f137cdeb5005c0e)

https://user-images.githubusercontent.com/7009300/156784816-53f95dd9-f387-4600-8a92-d05b1aeea3da.mov
