### ISSUE TITLE
is flchart support x axis as datetime and y axis double?

### ISSUE THREAD

**Issue by abhipoojary** [imaNNeoFighT/fl_chart#828]
** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.

**Is your feature request relasted to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jlnrrg** [comment]
Please consider reading the documentation before posting an issue and providing actual information in your issue.
To answer your question: yes you can accieve it, by using the `getTitles` method of the `SideTitles` to customize the axis descriptions.
