### ISSUE TITLE
New animations only are correct for data aligned left

### ISSUE THREAD

**Issue by bcurley2314** [imaNNeoFighT/fl_chart#83]
The new animations are great, however they only look correct for data that is static on the left side of the chart (beginning of the List<>). I'm currently using fl_charts for data that is over time (i.e. - the most recent data point is on the furthest right point). When I change time frames (by adding more points, "older" points to left beginning of the list (left), the animation starts over from the left and stretches out again, where I'd like to animation to "pin" on the right, and add data to the left and animate out.

I've attached a slowed down version of my issue to show what I'm talking about. Ideally, I believe the animation should have an alignment, allowing for the user to choose how to animate new data points in/out of the chart.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35980864/66328659-0c299d80-e8fb-11e9-8e43-8f475400e3d3.gif)

**Comment by imaNNeoFighT** [comment]
Hi, 
May I ask you to give me a sample to reproduce it?
I think I know the problem, but I want to know your exact concern.

**Comment by bcurley2314** [comment]
I don't have a quick sample at the moment, but if you simply change the maxX value (and have corresponding Y values to load) and watch the animation, you'll see it animates from the bottom Left position, which works well for some instances where you have a 0,0 graph, however mine is a timeline chart

**Comment by imaNNeoFighT** [comment]
If you just update the maxX, I think there shouldn't be any problem (may I ask you to test it?),
I think the problem is adding new spots, or removing them.

**Comment by bcurley2314** [comment]
yes that is exactly what the animation is showing above. I am adding and removing values to the X-axis when i tap last 5, last 10, etc. The problem isn't with updating the X values, it's the alignment of the animation (being bottom left, instead of bottom right)

**Comment by imaNNeoFighT** [comment]
Got your problem, what if you update the minX manually?
It applys animation on the left side.

**Comment by bcurley2314** [comment]
Correct it does. This seems like a hack as I'm having to convert the data from 0 - 29 (for a month view), to -29 - 0 in order to get the right side to stay stationary during the animation. With the maxY then changing as well, it just doesn't look right for my application at the moment. I'll close the bug as I don't believe this is a bug, but just a personal preference for my one case. Thanks for the prompt response!

**Comment by ManojMM026** [comment]
I have same case where animation doesn't look good. 

![fl_chart](https://user-images.githubusercontent.com/2713390/70131912-1e307e00-16a9-11ea-9ccb-8028aa61920f.gif)
