### ISSUE TITLE
 PieChart Widget cannot be rendered on the branch of the flutter SDK version flutter-2.5-candidate.9.

### ISSUE THREAD

**Issue by yanwei49** [imaNNeoFighT/fl_chart#830]
I used fl_chart version 0.36.4. The PieChart Widget cannot be rendered on the branch of the flutter SDK version flutter-2.5-candidate.9. The stable branch of the flutter SDK version is normal, and once the PieChart Widget is used on the branch of the flutter-2.5-candidate.9, the Widget in the whole dart file cannot be rendered

**Comment by imaNNeoFighT** [comment]
Where can I find `flutter-2.5-candidate.9` changes?
