### ISSUE TITLE
How to add a text of value on the bar chart top?

### ISSUE THREAD

**Issue by BadReese** [imaNNeoFighT/fl_chart#84]
Great library!!
I want a effect like this, but I found out that topTitles seems to doesn't work on bar chart .
Would you please give me some tips ?
thank you.
![image](https://user-images.githubusercontent.com/18170860/66697259-92cce900-ed06-11e9-9ee5-c08e77cddbe3.png)

**Comment by BadReese** [comment]
I would like to add a text of value like "1:20'" on the top each bar , can anybody helps me ?

**Comment by BadReese** [comment]
I would like to add a text of value like "1:20'" on the top each bar , can anybody helps me ?

**Comment by imaNNeoFighT** [comment]
Thanks,
Currently, there isn't the possibility to show a title on top of each bar,
I will add it ASAP but notice that pull requests are welcome, and try to contribute and implement it.
And feel free to ask any questions about it.
If you are interested to implement this feature, let me know.

**Comment by BadReese** [comment]
Thanks for your reply and I will be waiting for your good news .

**Comment by imaNNeoFighT** [comment]
Stay tuned :)

**Comment by imaNNeo** [comment]
Hi,
In [0.4.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.4.0) version we have added `showingTooltipIndicators` in [BarChartGroupData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#barchartgroupdata) to show tooltips (bubble tooltips) manually,
and you can show all tooltips, and set background color transparent,
I have added bar chart sample3 to demonstrate it,
check it out:
[<img src="https://github.com/imaNNeo/fl_chart/raw/main/repo_files/images/bar_chart/bar_chart_sample_3.png" width="300" >](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/bar_chart.md#sample-3-source-code),
Thanks for being patient.

**Comment by BadReese** [comment]
@imaNNeoFighT Thank you! You are really nice!

**Comment by Kimsoer** [comment]
If I want to add Image widget on top of each bar chart, how can I do?

**Comment by imaNNeo** [comment]
> add Image widget on top of each bar chart, how can I do

Not yet. BTW there are some tricks. You can use font-icons to put an icon in a Text.
We are working on an ability to put widgets in the tooltips. Then you can put any Flutter widget you want in the tooltips.
Stay tuned!

**Comment by imaNNeo** [comment]
Added a new functionality for this issue in [1.2.0](https://github.com/imaNNeo/fl_chart/releases/tag/1.2.0)
Please have a look!
