### ISSUE TITLE
ScatterChart: No left Titles if minY and maxY == 0

### ISSUE THREAD

**Issue by SuricateTrading** [imaNNeoFighT/fl_chart#842]
No left Titles in ScatterChart if minY and maxY == 0.
The title is only shown if maxY is 0.0001 for example.

**Comment by imaNNeoFighT** [comment]
Why do you want to show titles on min, max 0?
That's not a **valid** chart.

**Comment by SuricateTrading** [comment]
It is a valid chart and works great. It has only one row. However, I still need a description what this one row is supposed to show ;)

**Comment by imaNNeoFighT** [comment]
Okay, I am convinced it is a **valid** chart now :))
Thanks for explaining. I will fix it ASAP.

**Comment by erlangparasu** [comment]
https://github.com/imaNNeoFighT/fl_chart/issues/879#issuecomment-1019085190

**Comment by imaNNeoFighT** [comment]
Hi. 
We have just fixed it in [0.45.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.45.0).
Please check it out!
