### ISSUE TITLE
Bottom Tile don't show full text when side tile text is long.

### ISSUE THREAD

**Issue by KyawSoeW1n** [imaNNeoFighT/fl_chart#855]
![Simulator Screen Shot - iPhone 13 - 2021-12-14 at 10 04 23](https://user-images.githubusercontent.com/26593483/145928551-3411be15-2b14-4171-aaac-ed36dbd722dd.png)
Step 1 - Rotate -90 degree.
After that , text is not showing full text.

**Comment by nikhil-s-b** [comment]
You can wrap the BarChart with padding widget and give required padding for bottom attribute. That should work

**Comment by imaNNeoFighT** [comment]
Or you can increase `reservedSize` in [SideTitles](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#SideTitles)
