### ISSUE TITLE
LineChart crashes if all Flspot has the same y value

### ISSUE THREAD

**Issue by dennyak47** [imaNNeoFighT/fl_chart#857]
**Describe the bug**

LineChart crashes if all Flspot has the same y value

showing:
════════ Exception caught by rendering library ═════════════════════════════════
Unsupported operation: Infinity or NaN toInt

**To Reproduce**

try a list with several flSpot with same y value in Linechart

**Comment by Qormix** [comment]
I'm also experiencing this issue it started with version 0.40, version 0.36.4 seems fine.

**Comment by tijee** [comment]
Hi, I am having the sam exception, v0.41.0.

**Comment by X-SLAYER** [comment]
i have the same error

**Comment by erlangparasu** [comment]
https://github.com/imaNNeoFighT/fl_chart/issues/879#issuecomment-1019085190

**Comment by imaNNeoFighT** [comment]
It might related to #842

**Comment by imaNNeoFighT** [comment]
Hi. 
We have just fixed it in [0.45.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.45.0).
Please check it out!
