### ISSUE TITLE
[Question] [LineChart] How to get a callback when click is done on a Dot ?

### ISSUE THREAD

**Issue by fvisticot** [imaNNeoFighT/fl_chart#859]
In the image below, you can see the red dots on the line.

When clicking on the red dots, I need a callback to know the "clicked dot". 

![image](https://user-images.githubusercontent.com/153679/146653817-3eebef55-5afa-4555-83e3-5c70a3cef69f.png)

**Comment by imaNNeoFighT** [comment]
In `touchCallback` you have [FlTouchEvent](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#fltouchevent). 
If it is `FlTapUpEvent`, it means touch happened.
