### ISSUE TITLE
Make tooltip togglable (push to show, push to hide)

### ISSUE THREAD

**Issue by large** [imaNNeoFighT/fl_chart#868]
**Is your feature request relasted to a problem? Please describe.**
Sometimes it is handy to let the BarTouchData() stay until the user push the screen/mouse again.

**Describe the solution you'd like**
An option in BarTouchData() -> boolean: "toggleToolTip"
When  enabled the last tooltip shown stays until the user click on it (close) or push another rod (new tooltip)

**Describe alternatives you've considered**
I tried to override the handleBuiltInTouches and show it myself, but it never worked for me.

**Comment by imaNNeoFighT** [comment]
Hi. You can implement it yourself by overriding the touch flow.
Unfortunately, there is no implementation to mention, but I can implement it if I found some free time.

**Comment by large** [comment]
Hmm.... I tried several solutions to get the tooltip to stay, only way was to modify FLTouchEvent
https://github.com/imaNNeoFighT/fl_chart/blob/cff6ef797278bc1cc6841d09c2eab3b248937071/lib/src/chart/base/base_chart/fl_touch_event.dart#L26-L28

Modifying to something simple as this :)
```dart
     if (this is FlTapUpEvent) { 
       return true; 
     } 
```

Only problem then is that toggling only work with longpress or pan :)
As you probably figured out my Flutter skills are not best, but I'm learning each day.

This was more like a "hack" to get this working, but the touch-events got to complex for me to handle.
In the "touchCallback" for BarTouchData() you don't have any control over the events sent to the tooltip, so it goes away when releasing button/touch.

**Comment by imaNNeoFighT** [comment]
Check this sample ([source code](https://gist.github.com/imaNNeoFighT/bce3f0169ff3fd6c3f137cdeb5005c0e)). It's so easy.

https://user-images.githubusercontent.com/7009300/156784816-53f95dd9-f387-4600-8a92-d05b1aeea3da.mov

**Comment by large** [comment]
Thank you for this! Worked like a charm!

**Comment by IRTonyCHAN** [comment]
Is there any example for line chart also?

**Comment by helloworkcupid** [comment]
> Check this sample ([source code](https://gist.github.com/imaNNeoFighT/bce3f0169ff3fd6c3f137cdeb5005c0e)). It's so easy.
> 
>  toggle.mov
<img width="898" alt="image" src="https://user-images.githubusercontent.com/25734405/231492650-413b75b2-118f-4527-84dc-f1a52e0d817e.png">

the code page is loseing

**Comment by imaNNeo** [comment]
Sorry about that invalid link,
It should be fixed now (I edited my comment)
Here is the [link](https://gist.github.com/imaNNeo/bce3f0169ff3fd6c3f137cdeb5005c0e)

**Comment by helloworkcupid** [comment]
thank you
