### ISSUE TITLE
fl_chart is so great

### ISSUE THREAD

**Issue by liuyasss** [imaNNeoFighT/fl_chart#87]
I want have scrollable on linechart,

Or can you guide me how to achieve it?

thanks by liuyasss

**Comment by imaNNeoFighT** [comment]
Hi, thanks, please choose meaningful names,
also, there is a duplicate issue [here](https://github.com/imaNNeoFighT/fl_chart/issues/71) (there is a temporary solution), please search before creating an issue.
Cheers!

**Comment by liuyasss** [comment]
> Hi, thanks, please choose meaningful names,
> also, there is a duplicate issue [here](https://github.com/imaNNeoFighT/fl_chart/issues/71) (there is a temporary solution), please search before creating an issue.
> Cheers!

thanks
