### ISSUE TITLE
如何实现x轴滚动拖拽呢

### ISSUE THREAD

**Issue by iamBaijun** [imaNNeoFighT/fl_chart#871]
我的x轴的数据很多，要展示一个月或者7一天24小时，甚至一天中每5分钟一个点的数据，数据量大的时候要考虑拖拽

**Comment by vincenzopalazzo** [comment]
Hi @iamBaijun,

can you post your question in english?

**Comment by vin-lz** [comment]
@vincenzopalazzo @iamBaijun


> 我的x轴的数据很多，要展示一个月或者7一天24小时，甚至一天中每5分钟一个点的数据，数据量大的时候要考虑拖拽

He/She has many data points on the x-axis. He/She needs to display the data for a whole month or 7 * 24 hours, with a resolution of 5-minute for every data point. When the amount of data points is this high, it needs to be able to pan/drag/scroll.

**Comment by imaNNeoFighT** [comment]
Follow this feature here: #71
