### ISSUE TITLE
Is "ranged bar chart" supported (Apple pulsation chart type) ?

### ISSUE THREAD

**Issue by fvisticot** [imaNNeoFighT/fl_chart#875]
I would like to display a chart with bars with ranged valued like the Apple pulsation chart (cf. screen capture).
Is it possible with this library ?

![IMG_5D2211543911-1](https://user-images.githubusercontent.com/153679/149025904-18c6f13f-aeee-436a-b902-9ec3157bebb6.jpeg)

or :

![IMG_52AC07DD3EEC-1](https://user-images.githubusercontent.com/153679/149025570-e6919349-7366-4c5e-bcf1-a41704efc4e8.jpeg)
?

**Comment by fvisticot** [comment]
> I would like to display a chart with bars with ranged valued like the Apple pulsation chart (cf. screen capture). Is it possible with this library ?
> 
> ![IMG_5D2211543911-1](https://user-images.githubusercontent.com/153679/149025904-18c6f13f-aeee-436a-b902-9ec3157bebb6.jpeg)
> 
> or :
> 
> ![IMG_52AC07DD3EEC-1](https://user-images.githubusercontent.com/153679/149025570-e6919349-7366-4c5e-bcf1-a41704efc4e8.jpeg) ?

Update :
I was thinking to use BarChartRodStackItem but the issue I have with this solution is that I can not use Border radius property for the rodStackItems

**Comment by imaNNeoFighT** [comment]
Now you can use `fromY` and `toY` properties in each BarRod in [0.46.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.46.0).
Check below samples:

##### BarChartSample 5 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample5.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_5.gif" width="300" >

##### BarChartSample 6 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample6.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_6.png" width="300" >
