### ISSUE TITLE
Add flexibility to getTitles in bottomTitles: SideTitles()

### ISSUE THREAD

**Issue by Najib90** [imaNNeoFighT/fl_chart#880]
**Is your feature request related to a problem? Please describe.**
I like to have more flexibility with the `getTitles` in `bottomTitles: SideTitles()`

**Describe the solution you'd like**
Flexibility to add widgets - such as Icons

**Additional context**
So what's in the bottom 'Mn Te Wd Tu Fr St Sn Ll` should be able to replace it with Icons of choice or any other widget that would make sense.
![Screenshot 2022-01-21 at 21 47 20](https://user-images.githubusercontent.com/56278665/150598003-91b9347e-408f-4c77-973f-90aa0b8fda04.png)

**Comment by imaNNeoFighT** [comment]
Hi. At the moment there is no possibility to support Widgets in the title.
(I hope we can implement it in the future)

As a workaround, you can have an icon font to implement icons instead of texsts.

**Comment by Najib90** [comment]
> 

All right Iman aqa, thank you for your reply. I thought of using icon fonts indeed, but unfortunately they wouldn't match with the icons I already have. If you could point me in the right direction on how you think Widgets should be implemented, then I can maybe have a look at it independently.
