### ISSUE TITLE
LineChart - hiding data Out of Bounds

### ISSUE THREAD

**Issue by LondonJammo** [imaNNeoFighT/fl_chart#881]
When drawing points on a LineChart, in order to make the curves at the start and end correct, I need to make additional "off scale" points.

![image](https://user-images.githubusercontent.com/3718237/150657357-2c4bb3b7-68ef-4c64-acff-2775040de0d5.png)

These get drawn outside of the min/max axes. I'm still in 2 minds whether I like this effect or not, but is there a toggle to display or hide these parts of the line?

Notice I still want everything in the active graph area to be drawn, as long as it's within the axes and not external (just to keep the starting and ending curve shapes straight).

Many thanks,
J

**Comment by imaNNeoFighT** [comment]
You can use `clipData` property of [LineChartData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartdata).
