### ISSUE TITLE
How to cutOffY for line in LineChart

### ISSUE THREAD

**Issue by DVCStudioX** [imaNNeoFighT/fl_chart#888]
![how_to_cutoff](https://user-images.githubusercontent.com/50172145/151653834-b632847e-9dee-4798-9314-d5e1c195951a.jpg)

Hi, I set `minY `= -300, so how can I `cutOffY` for line =-300 same as belowBarData `belowBarData: BarAreaData(show: true, applyCutOffY: true, cutOffY: -300)`

**Comment by imaNNeoFighT** [comment]
You can use `clipData` property of [LineChartData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartdata).

**Comment by DVCStudioX** [comment]
It works! Thank you for the great package xD

**Comment by imaNNeoFighT** [comment]
Then you don't need `cutOffY` anymore.
