### ISSUE TITLE
Select single spot in case of multiple lines

### ISSUE THREAD

**Issue by joeldomke** [imaNNeoFighT/fl_chart#892]
I want to select only one point on one line. But if I have multiple lines and I tap the chart, the `LineChartReponse` will include the closest spots within the threshold for all lines.

I would like to implement a feature that allows single spot selection, and there are multiple approaches:

1. Add flag to only return the closest `LineBarSpot`.
2. Return closest LineBarSpot for each line, but add a `distance` property to the `LineBarSpot` and let the user decide what to do with that.
3. Return LineBarSpots for all spots within the threshold (along with the distance) and let the user decide what to do with that.

I prefer option 2 or 3, since it's unclear how spots of different lines, with same x and y coordinate should be handled in option 1.

**Comment by imaNNeoFighT** [comment]
You have fixed it in [0.45.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.45.0) :)
Thanks for contributing!
