### ISSUE TITLE
Add possibility to sync movements and scales between plots

### ISSUE THREAD

**Issue by gvozditskiy** [imaNNeoFighT/fl_chart#9]
![sync_state 2019-06-07 08_22_00](https://user-images.githubusercontent.com/16043598/59082790-5ffc8980-88fd-11e9-87ec-61f46f2170e1.gif)

**Comment by imaNNeoFighT** [comment]
May I ask you explain more about it?

**Comment by gvozditskiy** [comment]
@imaNNeoFighT in my case a have dozens of plots in the list and if i scale or move one of them, others should do the same, like in the gif above.

**Comment by imaNNeoFighT** [comment]
ok, it will implement when zoom feature provided, Follow the [RoadMap](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/roadmap.md) I will add a goal for the zoom feature.
then I close this issue.
