### ISSUE TITLE
Feature to add labels around the spot in scatter chart

### ISSUE THREAD

**Issue by prajwal27** [imaNNeoFighT/fl_chart#902]
**Is your feature request relasted to a problem? Please describe.**
I would like to have a feature where the item labels are around the spot in scatter chart. If the raidus is big enough, it can be inside the circle as well.
![image](https://user-images.githubusercontent.com/31249460/153654101-948825ce-1b92-4d77-af91-19af5e7ef7a9.png)

**Describe the solution you'd like**
My Solution is to draw the text after drawing the spots. However, the key thing is to position it below/above/left/right of the spot so that it doesn't cross the chart.

**Describe alternatives you've considered**

**Additional context**
I've shared the desired output above.

**Comment by prajwal27** [comment]
@imaNNeoFighT   I'm trying to work on this. Have you tried this before or if you have any suggestions, it would really help.

**Comment by imaNNeoFighT** [comment]
Hi @prajwal27 
Happy to see you again :)

No, I didn't try to implement something like that.
Go ahead and let me know what did you do :)

* You can access to `width` of drawing text using TextPainter.

**Comment by imaNNeoFighT** [comment]
I think at the moment we are using tooltip to show those texts (which is a trick)
You can add a feature to show a `text` on each spot. (A separate concept from tooltip)

**Comment by imaNNeoFighT** [comment]
Added in [0.45.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.45.1).
Thanks for your contribution :)
