### ISSUE TITLE
Stacked Bar/Bar chart domain labels overflow

### ISSUE THREAD

**Issue by mohammedX6** [imaNNeoFighT/fl_chart#911]
![Screenshot_20220221_080748](https://user-images.githubusercontent.com/24648104/154899102-9fc54f66-d114-45cf-8159-c9e1cbe330dc.png)

Any way to make labels show correctly without changing the height?
For example, showing labels for every 3 items?

` 

    numericData.forEach((key, value) {
      maxValue = maxValue < value[0][0].y ? value[0][0].y : maxValue;

      testCharts.add(Series<ChartStackedModel, String>(
          domainFn: (ChartStackedModel sales, _) => sales.x,
          measureFn: (ChartStackedModel sales, _) => sales.y,
          colorFn: (ChartStackedModel sales, _) =>
              ColorUtil.fromDartColor(sales.color),
          data: value[0],
          //fillColorFn: (_, __) => MaterialPalette.blue.shadeDefault.lighter,
          id: key));
    });

    return BarChart(
      testCharts,
      animate: true,
      vertical: false,
      behaviors: [
    //SlidingViewport(),
    //PanAndZoomBehavior(),
    new InitialHintBehavior(maxHintTranslate: 4.0),
    SeriesLegend(
      desiredMaxRows: 2,
      outsideJustification: OutsideJustification.middle,
      horizontalFirst: false,
      cellPadding: EdgeInsets.only(
        right: 4.0,
        left: 6,
        bottom: 4.0,
        top: 6,
      ),
    )
      ],
      animationDuration: Duration(milliseconds: animationTimer.ceil()),

    );`

**Comment by amrtaleb** [comment]
same problem with me !!
![Screenshot_1645910482](https://user-images.githubusercontent.com/57676660/155992438-016af6f8-5d74-4e9e-8319-3e8ddc4be537.png)
!

**Comment by imaNNeoFighT** [comment]
You can use `inverval` property in titles.
