### ISSUE TITLE
FlGridData vertical line not showing

### ISSUE THREAD

**Issue by josephmangmang** [imaNNeoFighT/fl_chart#92]
Hello, 
Thank you for the great library. 
I found a problem while using this library. Vertical Gridline is not showing using this code:

`gridData: FlGridData(
                      show: true,
                      getDrawingHorizontalGridLine: (value) {
                        return FlLine(
                            color: ColorRes.button_border, strokeWidth: 1);
                      },
                      checkToShowHorizontalGrid: (value) {
                        final val = _maxY / 100;
                        if (value % (val.floor() * 50 / val.floor()) == 0) {
                          return true;
                        }
                        return false;
                      },
                      getDrawingVerticalGridLine: (value) {
                        return FlLine(
                            color: ColorRes.button_border, strokeWidth: 5);
                      },
                      checkToShowVerticalGrid: (value) => true,
                      drawHorizontalGrid: true,
                      drawVerticalGrid: true),`

This is the result. Only horizontal grid is showing.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/pZx1wJM/Screen-Shot-2019-10-21-at-5-48-12-PM.png" alt="Screen-Shot-2019-10-21-at-5-48-12-PM" border="0"></a>

**Comment by imaNNeoFighT** [comment]
Hi, since [0.3.4 ](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.3.4) version, we swapped the `horizontal` and `vertical` functionalities, maybe this is your problem, check it out.

**Comment by imaNNeoFighT** [comment]
Any answer?

**Comment by imaNNeoFighT** [comment]
Heloo?

**Comment by josephmangmang** [comment]
@imaNNeoFighT I tried switching to  0.3.3. drawVerticalGrid affects Horizontal line. But drawVerticalGrid=true doesn't show the vertical grid.

**Comment by josephmangmang** [comment]
<a href="https://imgbb.com/"><img src="https://i.ibb.co/tctFzyt/Screen-Shot-2019-10-23-at-11-46-02-AM.png" alt="Screen-Shot-2019-10-23-at-11-46-02-AM" border="0"></a>

if drawVerticalGrid=true it should draw the vertical line.(green)
and for drawHorizontalGrid=true it should draw the horizontal line.(blue)

**Comment by imaNNeoFighT** [comment]
You are correct, but it is not important to made breaking changes.
I will fix them at a proper time.
Thank you!

**Comment by josephmangmang** [comment]
Thanks @imaNNeoFighT

**Comment by imaNNeoFighT** [comment]
You're welcome!

**Comment by imaNNeoFighT** [comment]
Hi there, It has been renamed in [0.6.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.6.0).
Thanks for reporting :)

**Comment by Serty32** [comment]
I have the same problem. Version 0.36.1

**Comment by imaNNeoFighT** [comment]
@Serty32 What is your problem exactly?

**Comment by Serty32** [comment]
@imaNNeoFighT Vertical lines are not visible.

**Comment by imaNNeoFighT** [comment]
Okay got it. we decided to remove the horizontal value concept from the BarChart. That's why we don't show anything.
Feel free to make a new issue to follow up on this decision. I need to understand the use case (Because I think in the barChart only yAxis is important).

**Comment by Peazzycole** [comment]
Hey please can i get the bar chat code you used to create this?
