### ISSUE TITLE
text direction and text alignment ignored in line chart tooltip implementation

### ISSUE THREAD

**Issue by prajwal27** [imaNNeoFighT/fl_chart#927]
**Describe the bug**
I have a line chart with tooltip enabled. I've set the `textAlign` and `textDirection` property as well. It seems that it doesn't work.
The below screenshot has `textDirection` set to `TextDirection.ltr` and `textAlign` set to `TextAlign.left` . But it's center aligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/31249460/156807842-9d85b22f-52e9-4dca-8010-6db10c2c5b43.png)

**Versions**
 - which version of the Flutter are you using? -- 2.10
 - which version of the FlChart are you using? --  0.45.1

**Comment by imaNNeoFighT** [comment]
I checked it. It seems there is no problem with `textAlign`.
Can you please share a reproducible code?

##### Sample 3 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/dev/example/lib/line_chart/samples/line_chart_sample3.dart))
<img src="https://user-images.githubusercontent.com/7009300/157278930-d8525a9c-4a5c-4dc4-8a55-c9ff210fb3fa.gif"  with=300 />

**Comment by imaNNeoFighT** [comment]
Okay. It breaks when we have some text lines.

**Comment by imaNNeoFighT** [comment]
Fixed in [0.46.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.46.0)

Thanks for contributing!
