### ISSUE TITLE
Add support for shading area between two lines

### ISSUE THREAD

**Issue by andermoran** [imaNNeoFighT/fl_chart#93]
Can we get support to shade above one line until another? This is helpful if we have to lines (lower range & upper range) and we went to shade the possible values between these two lines. So far, I can see we can only cutoff to a constant value.

**Comment by imaNNeoFighT** [comment]
Interesting,
We will consider it.

**Comment by imaNNeoFighT** [comment]
Also if it is possible, provide an image and demonstrate your idea.
It helps me and other people.

**Comment by andermoran** [comment]
<img width="821" alt="Screen Shot 2019-10-22 at 8 40 57 AM" src="https://user-images.githubusercontent.com/15237301/67291836-c0a0f300-f4a7-11e9-95c1-6a820268a1c0.png">
This is a graph with 80% and 90% confidence intervals. See how the range of values between the confidence intervals is shaded? I'd like to be able to plot the line, a line above it, and a line below it (I can do this all right now) but I'd like to shade between the line above and the line below (I can't do this).

**Comment by imaNNeoFighT** [comment]
Thank you for the details.

**Comment by krispypen** [comment]
Hi, has anyone suggestions about how we should configure this? I just got it working, but i added a bool property "cutOffPreviousLine" on BarAreaData, so it's like the cutOffY property but then a cutOff by the previous line. Suggestions for a better naming is welcome :-)

**Comment by imaNNeoFighT** [comment]
I think we can have a property outside of the BarAreaData.
I suggest to have it in the LuneChartData directly, and have a new member called BetweenBarsData. 
Then we can specify `fromLine` (index of line) , `toLine` (index of line), `color`, `gradient`,... 
What do you think?

**Comment by imaNNeoFighT** [comment]
Resolved and added `betweenBarsData` field in [0.6.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.6.1),
check this sample:

##### Sample 7 ([Source Code](/example/lib/line_chart/samples/line_chart_sample7.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_7.png" width="300" >

**Comment by imaNNeoFighT** [comment]
It will be great if you implement your sample and submit a PR to add it to our samples.
Thanks!
