### ISSUE TITLE
Smaller radius bubble hidden behind larger radius bubble

### ISSUE THREAD

**Issue by prajwal27** [imaNNeoFighT/fl_chart#930]
**Describe the bug**
The user may give a list of Scatter Spots in any order and the package is drawing spots in that order. Sometimes, the smaller radius bubble gets hidden behind the larger radius bubble.

**Solution**
Need to sort the list of Scatter spots in decreasing order of the radius before the spots are drawn.

**Versions**
 - which version of the Flutter are you using? -- 2.10.0
 - which version of the FlChart are you using? - 0.45.1

**Comment by imaNNeoFighT** [comment]
Fixed in [0.46.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.46.0)

Thanks for contributing!
