### ISSUE TITLE
A FlTouchInputNotifier was used after being disposed.

### ISSUE THREAD

**Issue by hsj86715** [imaNNeoFighT/fl_chart#94]
E/flutter (19034): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: A FlTouchInputNotifier was used after being disposed.
E/flutter (19034): Once you have called dispose() on a FlTouchInputNotifier, it can no longer be used.
E/flutter (19034): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:105:9)
E/flutter (19034): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:111:6)
E/flutter (19034): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:200:12)
E/flutter (19034): #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:273:5)
E/flutter (19034): #4      _FlChartState._releaseTouch.<anonymous closure> (package:fl_chart/fl_chart.dart:121:27)
E/flutter (19034): #5      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (19034): #6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (19034): #7      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter (19034): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter (19034): #9      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter (19034): #10     Future._complete (dart:async/future_impl.dart:512:7)
E/flutter (19034): #11     new Future.delayed.<anonymous closure> (dart:async/future.dart:313:16)
E/flutter (19034): #12     _rootRun (dart:async/zone.dart:1120:38)
E/flutter (19034): #13     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (19034): #14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (19034): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (19034): #16     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (19034): #17     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (19034): #18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter (19034): #19     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter (19034): #20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (19034): #21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (19034): #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by hsj86715** [comment]
Add the FlChart as content of a List item, them touch scroll the screen up and down, this exception would happen.

**Comment by imaNNeoFighT** [comment]
Shitt, Thanks for reporting.

**Comment by imaNNeoFighT** [comment]
I couldn't reproduce it, may I ask you to prepare a video shot?

**Comment by imaNNeoFighT** [comment]
Or maybe a sample code

**Comment by imaNNeoFighT** [comment]
Heloooo?

**Comment by hsj86715** [comment]
this no longer happened in new version
