### ISSUE TITLE
Color choices between line segments.

### ISSUE THREAD

**Issue by zugspitze** [imaNNeoFighT/fl_chart#96]
Thanks a lot for amazing package, I was wondering if it's possible to choose a color for different line segments. For example, if I have 4 points: A, B, C, D. I want to color the line between A-B in red, B-C in blue, C-D in green.

**Comment by imaNNeoFighT** [comment]
Hi, pleasure,
You can have 4 different line chart with different colors.
Cheers!

**Comment by zugspitze** [comment]
@imaNNeoFighT Thank you for quick reply :-)

I managed to use your trick to display different colors in line segments. Do you know how I can display only one tooltip instead of two for the points where line segments are touching. Please see the attached image.
<img width="402" alt="Screen Shot 2019-11-01 at 12 10 05" src="https://user-images.githubusercontent.com/12557673/68021213-17c17780-fca1-11e9-89bf-84c8c46ab7ea.png">

**Comment by imaNNeoFighT** [comment]
Use this code:
```dart
FlChart(
  chart: LineChart(
    LineChartData(
      .
      .
      .
      lineTouchData: LineTouchData(
        enabled: true,
        touchTooltipData: TouchTooltipData(
          getTooltipItems: (touchedSpots) {
            final tooltipItems = <TooltipItem>[];
            for (int i = 0; i < touchedSpots.length; i++) {
              if (i >= 1) {
                tooltipItems.add(null);
                continue;
              }
              final spot = touchedSpots[i];
              tooltipItems.add(TooltipItem(
                spot.spot.y.toString(),
                TextStyle(color: spot.getColor()),
              ));
            }
            return tooltipItems;
          }
        )
      ),
      .
      .
      .
    )
  ),
)
```
Inside the [getTooltipItems](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#touchtooltipdata) you can return null to skip show the [TooltipItem](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#tooltipitem).

**Comment by zugspitze** [comment]
Thanks a lot @imaNNeoFighT for your reply, it works :-)

**Comment by biklas7** [comment]
@imaNNeo sorry to awake this old issue, I didn't think I should open a new one just to ask this. How do you make the lines match when they are curved and have any smoothness?

**Comment by imaNNeo** [comment]
> @imaNNeo sorry to awake this old issue, I didn't think I should open a new one just to ask this. How do you make the lines match when they are curved and have any smoothness?

Hi, No problem
Unfortunately, I think there is no way to do this with curved lines.
