### ISSUE TITLE
LineChart 0.50.0 leftTitle and bottom title can't custom size

### ISSUE THREAD

**Issue by nelson1110** [imaNNeoFighT/fl_chart#965]
for example, I make the width as 110, but it doesn't work.

```dart
SideTitles(
        getTitlesWidget: (position, meta) => Container(
          width: 110,
          child: Text(
            position.toStringAsFixed(2),
          ),
        ),
        showTitles: true,
        interval: (state.maxY - state.minY) / 10,
        reservedSize: 10,
      ),
```

**Screenshots**
![image](https://user-images.githubusercontent.com/14796888/161364879-270e370e-a28a-4d34-bada-087460cbdef6.png)

**Versions**
 - 2.10.4
 - 0.50.0

**Comment by imaNNeoFighT** [comment]
The size of drawing texts determines by `reservedSize` property. (There is no possibility to set different sizes for each titles)
