### ISSUE TITLE
how to make fixed left titles when x axis scroll?

### ISSUE THREAD

**Issue by ninetowns** [imaNNeoFighT/fl_chart#971]
I have use below code to make scroll x axis, but left title isn't fixed 

SingleChildScrollView(
  scrollDirection: Axis.horizontal,
  child: Container(
    width: 1000,
    padding: EdgeInsets.all(8),
    child: flchart.BarChart(
      ...
    ),
  )
)

**Comment by imaNNeoFighT** [comment]
Because left titles are drawn inside the BarChart class.
Actually, in our latest release, we introduced a ChartScaffold class to separate the chart and titles.
Now it allows us to have the chart itself scrollable (with fixed titles).

BTW you can try to contribute. 
Follow this issue: #71

**Comment by basnetjiten** [comment]
@imaNNeoFighT could you please add description on ChartScaffold? I couldn't find it anywhere else in the documentation.

**Comment by Leanhdung2881999** [comment]
This is my problem too, can someone help?

**Comment by imaNNeoFighT** [comment]
@basnetjiten AxisChartScaffoldWidget is an inner and private widget and unfortunately, there is no public access to it yet. 
You can fork the fl_chart and add your customizations here:

https://github.com/imaNNeoFighT/fl_chart/blob/0d8ecade338f0a7dc501f60c18b2f18c0d63516d/lib/src/chart/base/axis_chart/axis_chart_scaffold_widget.dart#L7
