### ISSUE TITLE
If the bar chart shows too much data, the content will overlap. Does FL_chart support horizontal sliding?

### ISSUE THREAD

**Issue by haoyuanwu** [imaNNeoFighT/fl_chart#974]
If there are 80 bar chart data, the width of the phone is not enough to display the content, how to slide the horizontal display, and how to set the spacing between each bar chart,

![image](https://user-images.githubusercontent.com/13009425/163079568-a57eb855-9a86-45a9-8a2a-2186b47beb60.png)
This is what is displayed with the BarChartData alignment set to end. Set the spacing between each bar while allowing you to slide left and right

**Comment by imaNNeoFighT** [comment]
Dup of #71
