### ISSUE TITLE
RadarChart display more than 3 vertices .

### ISSUE THREAD

**Issue by Shiba-Kar** [imaNNeoFighT/fl_chart#976]
## Can we achieve the below !!

![image](https://user-images.githubusercontent.com/24454722/163722717-b864d43c-e1fa-40d9-a8b3-137fb4ceeb81.png)

**Comment by imaNNeoFighT** [comment]
Hi. Yes, you can.
Did you check our sample source code [here](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/radar_chart/samples/radar_chart_sample1.dart)?

We provided three values. You can provide as many values as you want

https://github.com/imaNNeoFighT/fl_chart/blob/544ad7a91358868e1a0405dfe69099b921941113/example/lib/radar_chart/samples/radar_chart_sample1.dart#L179-L187
