### ISSUE TITLE
paste issue

### ISSUE THREAD

**Issue by song-meng** [imaNNeoFighT/fl_chart#977]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.10.4, on macOS 12.1 21C52 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
local flutter environment
---------------
fl_chart:
    dependency: "direct main"
    description:
      name: fl_chart
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.50.1"
fl_chart version

First of all, it should be noted that the following situation only occurs in IOS simulator.

The second point to note is that I set up a test project locally, just an input box, and then introduce fl_ Chart, which is not used in any way, will still appear.

My fluent project is introducing fl_ Before chart, I could paste the text of my clipboard into the input box in the project, but now I can't paste it into the input box again.

I don't know where to introduce fl_ What happened after chart, so I need your help

**Comment by imaNNeoFighT** [comment]
Sorry I didn't understand the problem.
