### ISSUE TITLE
Tooltip for bars with negative values

### ISSUE THREAD

**Issue by tasaquino** [imaNNeoFighT/fl_chart#98]
Hey, thanks for the library, seems more customisable as the google library for flutter charts :)

I couldn't make the touch on bars with negative values work. Do I need to change something in my code?

My chart is pretty similar to this example, just changed colors to better suit the expected UI:
https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample1.dart

**Comment by imaNNeoFighT** [comment]
Hi, It doesn’t make sense to have negative values in the bar chart.
Because the bars start from the bottom (y = 0) to the tom, they didn't' go to the bottom.

**Comment by imaNNeoFighT** [comment]
I close this issue, and there is a duplicate one [here](https://github.com/imaNNeoFighT/fl_chart/issues/103)
