### ISSUE TITLE
Key/Size of chart area only

### ISSUE THREAD

**Issue by hpiu** [imaNNeoFighT/fl_chart#987]
Hi I am wondering if there is someway to add a key to the chart area only, without the FLTitles. I am wondering this because I want´to access the Size of the chart are only ( I am using the size in a gesture detector so I can draw line on the chart) . 

If I use the FLTitles in the chart the drawing of the chart gets offset by the width and height of the FLTitles and the subsequent calculation gets offset  as well.  This is sub-optimal as i have to kind of eyeball it and the touched area is not updating correctly.

My current workaround would be to put some 'home made' titles in a row and column around the LineChart and GestureDetector stack.

**Comment by imaNNeo** [comment]
We've added `chartRendererKey` property in our BarChart, LineChart, and ScatterChart for this purpos.

Please check it out in [0.50.3](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.50.3)

Check the below sample:

Check [this gist](https://gist.github.com/imaNNeo/678d5bdfb31421f133c404c1d7be60b2).

https://user-images.githubusercontent.com/7009300/168181809-0164b953-9a5e-4208-989c-4a957ff161f4.mov

**Comment by gazialankus** [comment]
@imaNNeo it seems the example gist is removed, could you add it again?

**Comment by imaNNeo** [comment]
Hi, yes, that's true, the link was outdated. Now I just fixed it.
For the other people with the same issue in other places:
The point is that around 2 - 3 years ago, I changed my username from `imaNNeoFighT` to `imaNNeo`
So you just need to change it in the URL,
For example:
`https://gist.github.com/imaNNeoFighT/something` -> `https://gist.github.com/imaNNeo/something`
