### ISSUE TITLE
hi, Is there anyway to let points to be customize widgets?

### ISSUE THREAD

**Issue by lindyer** [imaNNeoFighT/fl_chart#99]
const FlDotData({
    this.show = true,
    this.dotColor = Colors.blue,
    this.dotSize = 4.0,
    this.checkToShowDot = showAllDots,
 });
this is simple and can not to be customizable.but sometimes we need more comflex and customizable.

**Comment by imaNNeoFighT** [comment]
Hi, currently there isn't, but stay tuned.
Thanks!

**Comment by lindyer** [comment]
ok, I will. Nice man, God Bless U.

**Comment by nekoto-kun** [comment]
Hi there, I'm about to post an issue, but this one is kinda similar, which is about customizing dots. It seems until the date that I can't make visual to only show the last dot in a line chart (I couldn't make  the custom function, even it's the same like default function ```showAllDots```).
Looking forward to it^^

**Comment by vinters768** [comment]
@imaNNeoFighT any news on this?

**Comment by imaNNeoFighT** [comment]
It will be in the next version,
I will notify you here.

**Comment by imaNNeoFighT** [comment]
[0.9.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.9.0) -> 
* Added `strokeWidth`, `getStrokeColor`, `getDotColor` in the [FlDotData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#fldotdata), also removed `dotColor` from it (you should use `getDotColor` instead, it gives you more customizability), now we have more customizability on [FlDotData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#fldotdata), check [line_chart_sample3](https://github.com/imaNNeoFighT/fl_chart/blob/dev/repo_files/documentations/line_chart.md#sample-3-source-code), and [line_chart_sample5](https://github.com/imaNNeoFighT/fl_chart/blob/dev/repo_files/documentations/line_chart.md#sample-5-source-code)
