### ISSUE TITLE
折线图显示 Y轴和虚线横轴存在的问题

### ISSUE THREAD

**Issue by kaission** [imaNNeoFighT/fl_chart#996]
**目前找到的规律是，y轴最小值和y轴最大值必须能整除y轴间隔，虚横线才能正常等分和y轴坐标点对应上显示；**

比如，y轴范围为【24，36】或【27，39】，y轴间隔是3，显示效果正常如下：

![2436_3](https://user-images.githubusercontent.com/20827437/167535232-98d20f54-71
![2439_3](https://user-images.githubusercontent.com/20827437/167535247-1ba63922-c0f2-4e26-af02-867ead3c3bdd.png)
33-408b-bf10-1694888413ef.png)

但是，y轴范围为【20，32】或【19，31】，y轴间隔是3，显示效果异常如下：

![2032_3](https://user-images.githubusercontent.com/20827437/167535272-d09e5ada-4512-42fe-ba0e-177f5b9bed78.png)

再比如，y轴范围为【18，26】，y轴间隔是2，显示效果正常如下：

![1826_2](https://user-images.githubusercontent.com/20827437/167535288-15e543d6-4d02-45ef-94d6-db229a505dc0.png)

但是，y轴范围为【19，27】，y轴间隔是2，显示效果异常如下：

![1927_2](https://user-images.githubusercontent.com/20827437/167535300-5c56d9c6-3370-4b48-b935-7b89b5531bd4.png)

**Comment by imaNNeoFighT** [comment]
Please write in English.
